### ISSUE TITLE
Insufficient balance error on first segment

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1001]
**Describe the bug**

When B sends the first segment (with a payment) to O, it receives an error and O logs an insufficient balance error.

**To Reproduce**
1. Run a local on-chain test-harness deployment with 1 O and 1 B
2. Make sure that B has giant deposit & reserve - let's say 1000 ETH 
3. Stream into B
4. Observe insufficient balance error for the first segment in O's logs

**Expected behavior**

B should not encounter an insufficient balance error for the first segment because it should have calculated the necessary payment to top off its balance to meet O's minimum credit requirement.

**Screenshots**

<img width="1675" alt="Screen Shot 2019-07-23 at 5 04 51 PM" src="https://user-images.githubusercontent.com/5933273/61747514-0563a380-ad6c-11e9-9cf4-49dd7d14864f.png">

I added some additional log messages to display B's balance and O's minimum credit requirement when the insufficient balance error is logged.

**Desktop (please complete the following information):**
 - OS: OSX (running test-harness deployment)

**Comment by kyriediculous** [comment]
As you mentioned during the call this is very likely due to a difference in the EV calculation and the big math package. 

```
I0801 01:21:51.187074       1 orchestrator.go:256] Insufficient balance. Balance: 999999999         Orchestrator EV:  1000000000/1
E0801 01:21:51.187137       1 segment_rpc.go:84] Insufficient credit balance for stream with manifestID nico-test123-64622505-1
```

**Comment by kyriediculous** [comment]
Every ticket sent by B has `ev=999999999` instead of 1 gwei if we change the logged message to actually do the division rather than getting a floatstring we can observe this. 

This is also the reason we're immeadiatly sending 2 tickets upon firing a stream as the EV from B directly translates to a manifest Id's balance, so we're 1 wei short of having a sufficient balance. 

I'll have to run an additional experiment with different ticketEV settings for O , but a quick & dirty fix seems to be adding 1 wei

the real EV value is actually a limit approximation of 1 gwei but since we're not having decimals adding 1 wei gives the correct result

```
func ticketEV(faceValue *big.Int, winProb *big.Int) *big.Rat {
    ev := new(big.Rat).Mul(new(big.Rat).SetInt(faceValue), new(big.Rat).SetFrac(winProb, maxWinProb))
    return ev.Add(ev, big.NewRat(1, 1))
}
```

```
I0801 19:23:30.554473       1 orchestrator.go:149] Receiving ticket manifestID=nico-test123-64687398-0 faceValue=200000000000000000 winProb=0.0000000050 ev=999999999
I0801 19:23:30.558976       1 orchestrator.go:149] Receiving ticket manifestID=nico-test123-64687398-0 faceValue=200000000000000000 winProb=0.0000000050 ev=999999999
I0801 19:23:30.562692       1 orchestrator.go:259] Sufficient balance. Balance: 2363999999         Orchestrator EV:  1000000000/1
I0801 19:23:30.566510       1 orchestrator.go:399] Starting to transcode segment manifest=nico-test123-64687398-0 seqNo=3
I0801 19:23:30.566555       1 orchestrator.go:408] Submitted segment to transcode loop manifestID=nico-test123-64687398-0 seqNo=3
I0801 19:23:30.570578       1 orchestrator.go:149] Receiving ticket manifestID=nico-test123-64687398-1 faceValue=200000000000000000 winProb=0.0000000050 ev=999999999
I0801 19:23:30.578272       1 orchestrator.go:149] Receiving ticket manifestID=nico-test123-64687398-1 faceValue=200000000000000000 winProb=0.0000000050 ev=999999999
```

Update
`-ticketEV 999999999
`
`Receiving ticket manifestID=nico-test123-64695984-1 faceValue=2000000000 winProb=0.4999999995 ev=999999998`
