### ISSUE TITLE
Support Config File

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#101]

**Comment by eladmallel** [comment]
@ericxtang what is this issue about? - I was looking for any existing issues that talk about changing the node's setup from CLI params to a config file. Is this issue talking about the same thing?

**Comment by j0sh** [comment]
There's a few issues that indirectly reference using a config file [1][2] but this issue is as good as any for "the" issue tracking config files.

[1] https://github.com/livepeer/go-livepeer/issues/580
[2] https://github.com/livepeer/go-livepeer/issues/203#issuecomment-449102987

**Comment by j0sh** [comment]
To expand slightly on the thinking behind a config file: the CLI options and config file would be complementary to each other. Each CLI option should have a corresponding option in the config file. Typically how precedence works is:

1. CLI Flags
1. Config File
1. Default values

**Comment by leszko** [comment]
related issue #2047

**Comment by darkdarkdragon** [comment]
To support reading from config file and from env vars we could use this lib github.com/peterbourgon/ff
It requires just couple of lines of code to use it, like this:
https://github.com/livepeer/stream-tester/blob/59ae0b396c367b8c602a117e18d90a75f574a44d/cmd/recordtester/recordtester.go#L64-L68

**Comment by leszko** [comment]
Thanks @darkdarkdragon for sharing the library, I checked it and it allows to add a config file with just a few lines of code. Exactly what you mentioned!

Nevertheless, using this library has some limitations and let me write them down here as well as document other alternative solutions we can implement. All depends on how much time we want to invest into the UX of Livepeer configuration. The solutions are in order, starting from the simplest one. I'm not sure about the Livepeer roadmap and the importance of the simple configuration, so the feedback is welcome here. CC: @hthillman @yondonfu

## Solution 1: Use ff library

Using the [ff](https://github.com/peterbourgon/ff) library is a really low hanging fruit (max. 1 day of work), because with just a few lines of code, we can use a configuration file instead of flags!

### Usage

```
$ livepeer -config livepeer.conf
```

Here's a sample `livepeer.conf`.

```
broadcaster
cliAddr :7937
httpAddr :8938
orchAddr 127.0.0.1:8935,127.0.0.1:8936
v 6
```

The file contains key/value pairs which are mapped into flags. Alternatively it's possible to use JSON to specify the key/value pairs.

### Comment

The solution is very simple (almost zero dev effort and zero maintanance effort) and probably scratches the itch. The downsides I see:
- The file format is not flexible
	- We need to use this key/value format or JSON
	- No control which flag is exposed in the config file
- Multi-values are passed as a string
	- i.e. for  `orchAddr` multiple addresses are passed as `127.0.0.1:8935,127.0.0.1:8936`
	- in most configuration files, multi-values are represented as an array (i.e. `["127.0.0.1:8935", "127.0.0.1:8936"]`)
- Using external libs always bring some concerns
	- Potential vulnerabilities
	- Probably minor, since we already use quite a few of libs in Livepeer
	- This lib has `964 stars` in GH and it's quoted in some Red Hat blogs, so looks ok IMO

## Solution 2: YAML/TOML Config File

We can implement Livepeer configuration on our own (~1 week of work):
1. Create a struct `LivepeerConf` with all the configuration fields
2. Parse config file and flags into that struct

Alternatively we can use the [ff](https://github.com/peterbourgon/ff) library and write our own parser.

### Usage

```
$ livepeer -config livepeer.yaml
```

Here's a sample `livepeer.yaml`.

```yaml
broadcaster: true
cliAddr: :7937
httpAddr: :8938
orchAddr:
  - 127.0.0.1:8935
  - 127.0.0.1:8936
```

### Comment

This solution means implementing and maintaining some code. At the same time I see some benefits:
- we're free to choose the configuration file format
	- probably YAML or TOML are the best choices
- we can implement the multi-value parameters as arrays
	- i.e. `orchAddr` is represented as an array
- we can change some parameters
  - i.e. use something like `mode: Broadcaster`, instead of `broadcaster: true`
- we can limit or rename the flags that are available in the config file
	- i.e. I'm not sure if `v` should be available in the config file

## Solution 3: Improve Livepeer UX

My last idea is that if we think the UX of the `livepeer` command is really important, we could redesign how it currently works.

You can run Livepeer in 3 modes (`broadcaster`, `orchestrator`, and `transcoder`) . Currently you can specify any flag to any mode, but some of them are just ignored. E.g. let's type the following command.

```
$ livepeer -transcoder -h
```

In the results you'll see a tons of options, one of them is  `-maxGasPrice` which is not used by the transcoder.

I'd imagine a better UX would be to group the options by the mode in which Livepeer is used and then have contextual flags. For example.
```
$ livepeer transcoder -h
```

This should show only options related to the transcoder.

In other words, we could rethink from scratch how `livepeer` is used using flags and config file.

Saying that, I'm not sure we want to invest into it and if it's the right time to do it. It's just an idea.

**Comment by hthillman** [comment]
If we did Solution 1 now, does that preclude us from doing Solution 3 in the future?

**Comment by leszko** [comment]
> If we did Solution 1 now, does that preclude us from doing Solution 3 in the future?

No, we can proceed with Solution 1 right now and put Solution 3 on the roadmap, and implement it in the future.

**Comment by darkdarkdragon** [comment]
I don't think solution 3 is the scope of that ticket - we can do it any time when we're ready.
I don't see any advantages of YAML/TOML - so that leaves us with solution 1.

**Comment by leszko** [comment]
> I don't think solution 3 is the scope of that ticket - we can do it any time when we're ready.

Yeah, agree.

> I don't see any advantages of YAML/TOML - so that leaves us with solution 1.

I'm fine to proceed with this simplest approach. @yondonfu @hthillman wdyt?

**Comment by hthillman** [comment]
Let's do option 1, agree that #3 is out of scope and yaml doesn't add much value.

**Comment by yondonfu** [comment]
Agreed with everyone else on implementing solution 1 right now and looking into the flag/config UX improvements separately.
