### ISSUE TITLE
Devtool script `ticket faceValue higher than max faceValue` error

### ISSUE THREAD

**Issue by angyangie** [livepeer/go-livepeer#1020]
**Describe the bug**
Devtool script does not provision correct ticketFace value, resulting in a `ticket faceValue higher than max faceValue` error here: https://github.com/livepeer/go-livepeer/blob/master/pm/sender.go#L135

Therefore, no Orchestrator gets appended here because this condition isn't satisfied o.pred == nil || o.pred(info) https://github.com/livepeer/go-livepeer/blob/master/discovery/discovery.go#L113

**To Reproduce**
- Run `docker run -d -p 8545:8545 -p 8546:8546 --name geth-dev livepeer/geth-with-livepeer-protocol:pm`
- Run go run cmd/devtool/devtool.go setup broadcaster
- Run go run cmd/devtool/devtool.go setup transcoder
- Use output of last two steps to run B and O/T
- Observe `Done fetching orch info for orchestrators, numResponses fetched: []` error from  discovery.go:146

**Expected behavior**
Transcoding happens seamlessly

**Desktop (please complete the following information):**
 - OS: mac

**Additional context**
A temporary fix is to comment out these lines in `sender.go`: https://github.com/livepeer/go-livepeer/blob/master/pm/sender.go#L127-L138

**Comment by yondonfu** [comment]
Increasing the default `deposit` [amount](https://github.com/livepeer/go-livepeer/blob/master/cmd/devtool/devtool.go#L176) for broadcasters in the devtool to a larger number like 1000 should fix this.

The reason this error is appearing is because:

- The default `faceValue` for the orchestrator is .2 ETH (based on the default gas price of 20 gwei)
- At the moment, the broadcaster's default `deposit` is 100 ETH
- The broadcaster's default `depositMultiplier` is 1000. Thus, the broadcaster's max acceptable `faceValue` is 100 / 1000 = 0.1 ETH which is less than the orchestrator's `faceValue`

An alternative fix while the devtool is being updated is to start the broadcaster with the `-depositMultiplier` flag set to a small value <= 500 (100 ETH / 500 = .2 ETH - probably want it less than 500 so that even if the broadcaster's deposit decreases it will still find the orchestrator's `faceValue` acceptable).

**Comment by angyangie** [comment]
Thanks Yondon. `-depositMultiplier` of 200 (to be safe) does the trick. I get an `Acceptable error occurred when processing payment: Could not find TicketParams for payment`, but seems like that's okay. Anything you suggest there?

**Comment by kyriediculous** [comment]
Hi Angie! The acceptable error should be fixed when we merge https://github.com/livepeer/go-livepeer/pull/1017

**Comment by angyangie** [comment]
Great, thanks @kyriediculous!
