### ISSUE TITLE
Unacceptable payment error when ticket params change for concurrent streams

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1075]
**Describe the bug**

If a broadcaster sends > 3 concurrent streams to an orchestrator and the ticket params change (i.e. because of a change in the orchestrator's cached gas price, a winning ticket redemption, etc.), the broadcaster will send > 3 tickets with invalid params to the orchestrator which will cause the broadcaster's error count to exceed the current [maximum of 3](https://github.com/livepeer/go-livepeer/blob/master/cmd/livepeer/livepeer.go#L73). The 4th ticket received by the orchestrator before the broadcaster receives updated ticket params will trigger an unacceptable payment error and the orchestrator will not transcode the segment that the ticket came with.

**To Reproduce**
1. Create a network with 1 B and 1 O in on-chain mode
2. Send 4 streams into B
3. Send a few dummy transactions into the ETH node with a random gas price
4. Wait for O to cache the new gas price
5. Observe an unacceptable payment error in O's logs

**Expected behavior**

Ideally, an orchestrator would not skip transcoding a segment just because the broadcaster is sending multiple streams in and the ticket params changed.

**Comment by yondonfu** [comment]
One way to address this could be to track payment errors on a per stream basis for each ETH address. Then, if the ticket params change, the error count for each individual stream will be incremented since a ticket with invalid params will be sent for each stream, but as long as the error count for an individual stream does not exceed the absolute maximum then an unacceptable payment error would not be triggered. If we do this we should address #695 first because we don't want to track error counts per stream using a B provided manifestID. We would likely also want caps on the # of streams/sessions per ETH address to discourage B from creating a new stream for each ticket with invalid params that it wants to send.

**Comment by kyriediculous** [comment]
# Dynamic Acceptable Error Count For Concurrent Streams

Author: Nico Vergauwen

## Overview & Context

An orchestrator's ticket parameters for the PM protocol can change for various reasons: fluctuation in on-chain gas prices, winning ticket redemptions or manual configuration change. When this happens mid-stream, the broadcaster sending the stream will not receive these updates in the HTTP response when requesting to transcode the next segment. The tickets sent with this next segment however, will have old and thus invalid ticket parameters, resulting in a payment error from the orchestrator dropping it from the working set. 

To aleviate this, _acceptable_ and _unacceptable_ payment errors were introduced, as well as a limit for how many acceptable errors a broadcaster is allowed to have before an orchestrator will stop accepting work. This was done in order to give broadcasters a grace period to update the ticket parameters for an orchestrator when those change mid-stream. 

Currently this value is hardcoded to be `3` acceptable errors. This leads to problems when the amount of concurrent streams a broadcaster has with a particular orchestrator exceeds this hardcoded value. As when ticket parameters change, a PM ticket will be sent for every concurrent stream, exceeding the maximum acceptable error count causing the orchestrator to no longer work with that broadcaster. 

## Goals 

Create a mechanism whereby no unacceptable payment errors are encountered due to a high number of concurrent payment tickets having invalid ticket parameters when those parameters have just changed. 

Preferably this mechanism does not cap the amount of concurrent streams a broadcaster is allowed to have with a single orchestrator[1] but neither should it allowing griefing an orchestrator by expending its resources with invalid payment tickets.

_[1] This would have to be a configurable value as it is dependant on an orchestrator's capacity as well as risk apetite, however it would be a hard variable to correctly determine the value of by end-users in accordance to their needs._

## Existing Solution

Currently PM tickets are validated when they are received by the orchestrator. 

`pm.Receipient` injects a `core.ErrorMonitor` dependency which will keep track of the number of acceptable errors encountered for each broadcaster. This number is incremented each time such an error is encountered.

current errors deemed acceptable:
- Invalid `recipientRand` due to recent ticket redemption
- Invalid `faceValue due` to change in gas price
- Invalid `winProb` due to change in gas price

`recipient.ReceiveTicket` will return a type implementing the `core.AcceptableError` interface which exposes an `Acceptable() boolean`  method to the returned error. The returned boolean will be true as long as the maximum error count (currently hardcoded as `3`) isn't exceeded by the latest acceptable error.

This returned error can be handled by the caller, in this case if `err.Acceptable() == false` the caller will not transcode the segment and return an error to the broadcaster. 

The error counts for a broadcaster a reset when the gas price is updated, a winning ticket is redeemed or the node is restarted.

## Proposed Solution

### Overview

Create a dynamic maximum acceptable error limit based on the number of concurrent streams a broadcaster has with an O at any given time. 

```
E = f(N)
 * E is the maximum acceptable error count
 * N is the number of concurrent streams for B with O
```

My proposal is to have `E = N + round(cuberoot(N))`, this reduces the amount of acceptable errors a broadcaster can incur as the amount of requested computational power from O increases. 

```
1 stream -> max 2 errors
2 streams -> max 3 errors
4 streams -> max 6 errors
8 streams -> max 10 errors
16 streams -> max 19 errors
```

### Implementation Details 

1. Remove the current hardcoded `maxErrCount` field from `ErrorMonitor`

2. Change the `ErrorMonitor` to keep track of the total number of concurrent streams for a broadcaster:
        a. Add a new field `streams map[ethcommon.Address]map[ManifestID]bool`) which will be a nested map tracking the ManifestIDs for a sender
        b. Add a method `AddStream(sender, manifestID)` to `ErrorMonitor` that adds a `ManifestID` for a sender to the `streams` map if it not already exists, if already exists we'll update the timestamp for which we received the last segment for that ManifestID. 
        c. Add a method `RemoveStream(sender, manifestID)` that removes a `ManifestID` for a sender from the map if it exists
        d. Add a method `MaxErrCount(sender)` which returns `len(streams[sender])`
        
3. in `Orchestrator.ProcessPayment` [call](https://github.com/livepeer/go-livepeer/blob/f957f046a8949f1e88f26f2183c76547c9e93c9e/core/orchestrator.go#L112) `AddStream(sender, manifestID)`

4. Call `RemoveStream(sender, manifestID)` when the segment loop for that `ManifestID` [times out](https://github.com/livepeer/go-livepeer/blob/f957f046a8949f1e88f26f2183c76547c9e93c9e/core/orchestrator.go#L586). To obtain the sender address we could [add it to](https://github.com/livepeer/go-livepeer/blob/f957f046a8949f1e88f26f2183c76547c9e93c9e/server/segment_rpc.go#L262) `core.SegTranscodingMetaData` when calling `verifySegCreds`
        

Both `pm.Recipient` and `core.LivepeerNode` have access to the same `ErrorMonitor` instance so the only API requiring change would be the `ErrorMonitor`. In addition we would have to change the `core.SegTranscodingMetaData` to have a `sender/broadcaster` field.

### Benefits

- No need for an orchestrator to have a resource allocation cap per broadcaster (max number of concurrent stream)

- Attempt to reduce the exposure to griefing for an orchestrator compared to having an acceptable error count per manifestID, which would make the max acceptable error count scale linearly with the number of concurrent streams. 

- Time/Space complexity for the current ErrorMonitor operations is left unchanged. When tracking error counts per manifestID, clearing the error counts would become `O(n) = n`.

- No need to update the `ErrorMonitor.AcceptErr(ethcommon.Address)` function signature to also take in a `ManifestID` as argument.

### Downsides

- The `ErrorMonitor` will have to keep track of the number of concurrent streams a broadcaster has at a given time by either adding a dependency to a new type or by adding additional logic

- Griefing is still possible but to a lesser extent as the error count isn't "refreshed" for a new `ManifestID`

## Alternative Solutions

#### Maximum Error count per ManifestID

We could track error counts on a per `ManifestID` basis in a map and keep the hardcoded value of `3`. 

This would however require significant API changes as `pm.Receipient` now needs to be aware of `ManifestID` to update the error count for the right stream, in tandem `ErrorMonitor.AcceptErr` would have to take that `ManifestID` as a second argument to be able to update the correct map entry.

## Testability and Monitoring

Follow the reproduction steps outlined in [the original issue](https://github.com/livepeer/go-livepeer/issues/1075) and observe that **no** _unacceptable payment errors_ occur when running N concurrent streams

> 1. Create a network with 1 B and 1 O in on-chain mode
> 2. Send 4 streams into B
> 3. Send a few dummy transactions into the ETH node with a random gas price
> 4. Wait for O to cache the new gas price
> 5. Observe an unacceptable payment error in O's logs

## Milestones

T.B.D.

**Comment by yondonfu** [comment]
Thanks for posting this spec! Need to digest and think about this problem a bit more, but here are some quick high level thoughts:

One problem we have right now is that we increase the acceptable error count for each ticket received with invalid params. This means that an N ticket payment that specified invalid params will increase the acceptable error count by N. Consequently, a single payment could put B over the max error count regardless of how many concurrent streams it is sending to O. It probably makes sense to increase the acceptable error count on a per payment basis as opposed to a per ticket basis given that if a single ticket in the payment would trigger an acceptable error then all tickets in the payment would trigger acceptable errors since they share the same params (besides signatures and sender nonces).

> My proposal is to have E = N + round(cuberoot(N))

I'm not sure that I see the value of using the cube root here as opposed to adding a constant or using any other function applied to N. As long as N is added as a constant factor in this function then the # of acceptable errors allowed for B will scale at least linearly with the # of streams it has. So, the incentive to create a new stream (i.e. generate a new manifestID) will still exist as long as N is added as a constant factor in this function.

**Comment by kyriediculous** [comment]
>  It probably makes sense to increase the acceptable error count on a per payment basis as opposed to a per ticket basis given that if a single ticket in the payment would trigger an acceptable error then all tickets in the payment would trigger acceptable errors since they share the same params (besides signatures and sender nonces).

Great point, had looked over this. 

> I'm not sure that I see the value of using the cube root here as opposed to adding a constant 

Constant would work as well , it's just that if you use a constant the leniency provided by the constant is relatively speaking greater when running a smaller number of concurrent streams. This can be acceptable as it means less resources from a single O are requested and thus the risk involved for O is minimized either way.

**Comment by kyriediculous** [comment]
# Gracefully Handle Stale TicketParams

## Overview & Context

### Existing Solution - Max Acceptable Error Count

Currently PM tickets are validated when they are received by the orchestrator. 

`pm.Receipient` injects a `core.ErrorMonitor` dependency which will keep track of the number of acceptable errors encountered for each broadcaster. This number is incremented each time such an error is encountered.

current errors deemed acceptable:
- Invalid `recipientRand` due to recent ticket redemption
- Invalid `faceValue due` to change in gas price
- Invalid `winProb` due to change in gas price

`recipient.ReceiveTicket` will return a type implementing the `core.AcceptableError` interface which exposes an `Acceptable() boolean`  method to the returned error. The returned boolean will be true as long as the maximum error count (currently hardcoded as `3`) isn't exceeded by the latest acceptable error.

This returned error can be handled by the caller, in this case if `err.Acceptable() == false` the caller will not transcode the segment and return an error to the broadcaster. 

The error counts for a broadcaster a reset when the gas price is updated, a winning ticket is redeemed or the node is restarted.

#### Issue

- Whenever a broadcaster sends more pm tickets than `maxErrCount` that all contain outdated ticket params, the `maxErrCount` will be exceed immeadiatly and the segment not transcoded, even if the broadcaster is acting honest. 

### Proposed Solution 1: Dynamic Max Acceptable Error Count

To prevent unacceptable payment errors due to the number of concurrent streams (or tickets) exceeding the max acceptable error count, it was proposed to make this maximum a dynamicly tracked value based on the number of concurrent streams a broadcaster has with an orchestrator. 

[Dynamic Acceptable Error Count for Concurrent Streams](/U4xaW17nSL-D5EoV385qmg)

#### Issue

- a broadcaster can send in streams with new manifestIDs to circumvent hitting the max acceptable error count if we would make it dynamic or track it on a per manifestID basis 

- When an orchestrator receives a ticket because the ticket params aren't up to date it doesn't want to immeadiatly stop working with B as it might not be acting maliciously, in fact it O might have even just redeemed a winning ticket from B causing the ticket params on B's end to become stale. 

## Goal

Create a mechanism where malicious acting broadcasters can't gain an unfair advantage by sending invalid pm tickets along with the transcode requests. And honest node operators aren't put at a disadvantage when ticket parameters are out of date[1].

Preferably this mechanism does not cap the amount of concurrent streams a broadcaster is allowed to have with a single orchestrator.

Furthermore the solution must make sure to not significantly increase the latency of the E2E trancoding workflow.

[1] Either because of a change in gas price, which causes the `faceValue` and `winProb` to change, or because the `recipientRand` has already been revealed due to winning ticket redemption. 

## Proposed solution 2

### Overview

- Remove error counting from the orchestrator

- Remove the notion of acceptable / unacceptable payment errors

- Always send back updated orchestrator info in the case of a payment error

- Return a payment error to the broadcaster as alongside the updated orchestrator info

- Broadcaster retries `submitSegment` once with updated orchestrator info when a payment error is encountered

### Considerations

Assuming that B behaves honestly it would only require one retry to get updated orchestrator info. Considering that orchestrator info could get updated at a maximum rate equal to the block production rate of the network being used, the added latency due to a retry would be acceptable on mainnet as it would only occur at a maximum of 1/6 segments given an estimated 12 second block production rate.

To further decrease latency impact we could decrease the polling interval for the `gasPriceMonitor`. The queried gas price is calculated a moving average over the last X blocks (5?). Decreasing the polling interval to once every two blocks significantly reduces the latency added by this solution, while having much less impact on gas pricing. 

In this setup case B is disincentivized from sending invalid tickets because the segment won't be transcoded as long as no updated ticket is sent and the computational overhead incurred by O for sending back an error over HTTP is minimal. On the other end, orchestrators will not be doing work for tickets that can never be redeemed. 

This solution also reduces quite a bit of complexity around processing payments when we no longer have to differentiate between acceptable and unacceptable payment errors, which has been a recent topic of confusion in the discord channels.

### Engineering Tasks

- Create a new `paymentError` global `var` in the `server` package that can be used to compare encountered HTTP errors

- When a payment error is encountered send back updated orchestrator info to the broadcaster alongside a payment error and `400 Bad Request` status

```
	if err := orch.ProcessPayment(payment, segData.ManifestID); err != nil {
		glog.Errorf("error processing payment: %v", err)

		oInfo, err := orchestratorInfo(orch, sender, orch.ServiceURI().String())
		if err != nil {
			glog.Errorf("Error getting orchestrator info: %v", err)
			http.Error(w, "Internal Server Error", http.StatusInternalServerError)
			return
		}

		buf, err := proto.Marshal(oInfo)
		if err != nil {
			glog.Errorf("Error getting orchestrator info: %v", err)
			http.Error(w, "Internal Server Error", http.StatusInternalServerError)
			return
		}

		w.Write(buf)
		http.Error(w, paymentError.Error(), http.StatusBadRequest)
		return
	}
```

- When a payment error is encountered , retry the segment once. 

```
retries := 0
maxRetries := 1
for retries <= maxRetries {
	res, err := SubmitSegment(sess, seg, nonce)
	if err != nil || res == nil {
		if err.Error() == paymentError.Error() {
			if retries < maxRetries {
				retries++
				continue
			}
		}
		cxn.sessManager.removeSession(sess)
		if res == nil && err == nil {
			return errors.New("Empty response")
		}
		if shouldStopStream(err) {
			glog.Warningf("Stopping current stream due to: %v", err)
			rtmpStrm.Close()
			return err
		}
		if shouldStopSession(err) {
		}
		return err
	}
}
```

- Since the ticket won't be redeemed and the segment not transcoded, do not update accounting balances on either side.

- Remove `ErrorMonitor` and and its usage

- Remove `pm.receiveError` and `core.AcceptableError`, their stubs and their usages

- Update the `monitor` package to reflect the above updates

- Update grafana dashboard to no longer differentiate between acceptable and unacceptable payment receive errors

**Comment by yondonfu** [comment]
**Re: proposal 2**

I like how the proposal reduces complexity by removing the concept of acceptable vs. unacceptable payment errors and how it eliminates the incentive for B to try to game the max acceptable error count mechanism. However, here are some of my concerns with the proposal:

- Honest Bs upload segments twice whenever retrying an O after receiving a payment error which results in 2x upload cost and increased latency. Given N concurrent streams, the upload cost and increased latency could apply for each segment that is sent with a payment for each of the N streams.
- The proposal mentions that balance accounting would not be updated when a payment error is triggered. This means that honest Bs can end up overpaying whenever a retry occurs. An alternative would be to update balance accounting even when a payment error is triggered such that when a retry occurs B only needs to send a payment that covers the missing value from its first payment.

If O refreshes its gas price view every block, given ~12 second blocks, 1 out of every 6 segments will involve a double upload. O can be discouraged from frequent gas price refreshes that would trigger payment param changes if B counts a retry toward an O's latency score, but an inability to frequently refresh its gas price view hurts Os because their exposure to gas price fluctuations (that affect the tx overhead incurred for ticket redemption) increases

**Other alternatives**

Here are some ideas about alternatives that might address some of the concerns mentioned above.

Note: Since changes to ticket params *and* price can trigger a payment error, I'll just refer to ticket params and price as payment params.

A problem with the current payment error handling scheme seems to be that B has no idea whether it should expect payment params to be honored after it receives them from O. As a result, B does not know if a payment sent with a particular set of payment params should be accepted by O. While O currently offers a grace period using a max acceptable error count, this is an implementation detail of O - the protocol between B & O does not dictate that O has to provide a grace period so B cannot use the expectation of a grace period for stale payment params when handling responses from O.

Another problem with the current payment error handling scheme is that B can send a payment using *any* payment params and the payment would be accepted by O as long as B is below the max acceptable error count. In theory, B could send a payment with value = 0 and O would accept it.

We can address the first problem by having O attach an expiration timestamp [1] to payment params. B can expect O to honor a set of payment params until the expiration. So, if O returns an error despite the payment params being not yet expired, B will know that O deviated from the protocol and can drop O knowing that O misbehaved. We can address the second problem by also having O only accept payment params that it has previously advertised that are not expired. O would also include the most up-to-date payment params with each response to B so that B always has access to a set of payment params that are not yet expired. 

[1] Should probably use the block timestamp so that B & O can have a synchronized view of a global clock

Options for adding an expiration timestamp
1. Add an expiration timestamp field to the `OrchestratorInfo` message
2. Encode the expiration timestamp in the `seed` field of a `TicketParams` message

Option 1 should work here, because un-upgraded Bs will ignore unknown fields. Upgraded Bs would have to accommodate (or reject) Os that haven't upgraded to incorporate the expiration timestamp, regardless of which option is used. Going with Option 1 would make that easier, eg checking for a zero value for a particular field, rather than introducing an additional step of splitting / parsing an existing field.

Options for having O only accept payment params that it has previously advertised that are not expired.
1. Have O send `sign(ticketParams, price, expirationTimestamp)` to B and B is responsible for sending back the signature
2. Have O keep track of the old payment params for each B (might only need to keep track of last advertised set of params)
3. Have O incorporate `faceValue`, `winProb`, `price` and `expirationTimestamp` in the HMAC used to generate `recipientRandHash`.

Option 3 avoids additional bookkeeping for O and can ease the rollout of this change because it does not require a change to network protocol messages.

The `recipientRandHash` could be constructed as:

```
recipientRandHash = keccak256(HMAC(O.secret, recipientRandSeed | B.address | faceValue | winProb | price | expirationTimestamp))
```

This construction of `recipientRandHash` binds `faceValue`, `winProb`, `price` and `expirationTimestamp` to `seed` (recall that `seed` encodes `recipientRandSeed` and `expirationTimestamp`). So, when O receives a `seed` from B with a payment, it can check that it had previously advertised these params.

The update to B would be:
- Check that `expirationTimestamp` is valid

The update to O would be:
- Check if payment params are acceptable given current payment params
- If payment params are not acceptable given current payment params, check if the received params are not expired
- If the received params are not expired, then accept them
- Else, reject them
- Attach up-to-date payment params with each response to B (via `OrchestratorInfo`)

Some benefits of this approach:
- Removes acceptable vs. unacceptable payment errors
- Grace period for a set of payment params is explicitly defined
- O will only accept payment params that it previously advertised and it can bound the time that it will accept them for

Some potential concerns of this approach:
- If O redeems a winning ticket that forces a `recipientRand` change, then B could use old not-yet-expired payment params that include the revealed `recipientRand`. B could try to grind nonces to make sure that it only sends non-winning tickets to O and it would be able to do this until the payment params expire. One way to mitigate this is tweaking the expiration time to limit the # of payments that could be sent with a particular set of params. Another way to mitigate this is to have O generate new payment params with a new `recipientRandHash` after receiving a winning ticket, but waiting until the expiration timestamp to redeem a winning ticket (ex. if each set of params expires in 12 seconds, then after receiving a winning ticket, wait 12 seconds and then redeem). The longer term solution that eliminates this possibility would be to use a non-interactive protocol for selecting winning tickets (i.e. based on [VRFs](https://gist.github.com/yondonfu/352ae689b0d802cc6e3f5403739b4e6a)).

**Comment by j0sh** [comment]
This discussion is great, I haven't read through all this very closely yet, but this comment caught my eye:

> Option 2 can ease the rollout of this change because it does not require a change to network protocol messages

Option 1 would work as well, because un-upgraded Bs will ignore unknown fields. Upgraded Bs would have to accommodate (or reject) Os that haven't upgraded to incorporate the expiration timestamp, regardless of which option is used. Going with Option 1 would make that easier, eg checking for a zero value for a particular field, rather than introducing an additional step of splitting / parsing an existing field.

> Option 3 avoids additional bookkeeping for O and can ease the rollout of this change because it does not require a change to network protocol messages.

This one (incorporating the expiry into HMAC) sounds good to me.

On a somewhat related note, I somewhat recall earlier discussions around incorporating ticket expiration into the protocol to guard against certain types of attacks - B/O collusion in "post-dating" tickets in order to exclude delegators from fees. Is this safeguard already built into the protocol and existing ticket parameters? If so, can we use that data rather than introduce a new field?

**Comment by yondonfu** [comment]
> Option 1 would work as well, because un-upgraded Bs will ignore unknown fields.

Good point! Updated my comment to mention this.

> Is this safeguard already built into the protocol and existing ticket parameters? If so, can we use that data rather than introduce a new field?

Tickets do include a creation round field, but given the current round length of 1 day, I think we'll want to be able to set the expiration to shorter periods of time. Otherwise, payment params would be usable for at least the remainder of a round (day) when Os would be better off if payment params were only usable for seconds/minutes.
