### ISSUE TITLE
Orchestrator should send relative URL to itself to standalone transcoder

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1083]
**Is your feature request related to a problem? Please describe.**
Currently, as part of task, orchestrator sends absolute URL to itself to standalone transcoder.
And it is external host name (or IP address) of the orchestrator. But in most cases transcoders will be connected to orchestrator through another (internal) IP, and on different port. Also transcoders probably will not be able to access external IP of the orchestrator.

**Describe the solution you'd like**
When sending task to transcoder it should send relative URL instead of absolute one - then transcoder will be able to use same host/ip/port by which it was initially connected to orchestrator.

**Describe alternatives you've considered**
1. Send absolute URL but with internal IP. Will require keeping track of that IP inside orchestrator.
2. Push segment data through same connection back and forth between orchestrator and transcoder. Currently not recommended because GRPC doesn't handle well big blobs of data. Maybe worth considering after switching too QUICK.

**Comment by j0sh** [comment]
Sending a relative URL sounds like a sensible solution. We might want to go ahead and remove the use of a base URI altogether within local OS, because that has shown to be brittle in general (eg, https://github.com/livepeer/go-livepeer/pull/1062 ), so we might want to discourage the practice.

Of course this has the tradeoff of requiring additional client-side logic to process any URLs that it receives.  There will still be cases where we need to send full URLs, such as external OS addresses, so clients need be able to handle both cases.

https://github.com/livepeer/go-livepeer/blob/82024b4f902f959f09a625a924046a69dee144aa/drivers/local.go#L143-L144
