### ISSUE TITLE
Remove frozen reserve handling and recalculate reserve alloc at start of round

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1089]
**Is your feature request related to a problem? Please describe.**

Once livepeer/protocol#319 is merged, there will no longer be a concept of a "frozen reserve". The PM client currently has a few pieces of logic that are based off the concept of a "frozen reserve". These areas of the codebase will need to be updated.

**Describe the solution you'd like**

- [ ] `eth.SenderWatcher` should refresh the cached reserve for a sender when a new round is initialized in order to update the total funds available for claiming if the sender's deposit depleted (livepeer/protocol#319 will update the reserve funds to be "reset" at the start of a round - active set members can claim up to the total funds available at the start of the round divided by the size of the active set during the round)
- [ ] Remove pieces of code that depend on a frozen reserve. Examples [here](https://github.com/livepeer/go-livepeer/blob/master/eth/watchers/senderwatcher.go#L211) and [here](https://github.com/livepeer/go-livepeer/blob/master/eth/watchers/senderwatcher.go#L164)

Note: This will require up-to-date contract Go bindings.

**Comment by kyriediculous** [comment]
The way this currently works is that we expose a method on the `SenderMonitor` , `reserveAlloc()` which calculates the reserve allocation for a sender as follows `reserve/poolSize - claimedReserve (by sender)`

`claimedReserve` is either calculated as a cached value based on ticket transfer events that draw from the reserve or fetched through an RPC call if the value is not cached. The value is currently being reset when a frozen reserve that has thawed gets funded (increment senderNonce).

Instead we can reset this value when `RoundsWatcher` receives a new round event. **The main issue** being that the concerns of `ClaimedReserve` and watching for new round events are completely separated.

One possible solution is to track the round number `claimedReserve` belongs to in a wrapper struct. When we then receive events that would alter `claimedReserve` we would check the current round vs the round number on the struct. If both are equal we alter the current value, if currentRound is larger than the round number on the struct we first reset `claimedReserve` to 0 before doing the necessary arithmetics. 

```
type claimedReserve struct {
amount *big.Int
round *big.Int
} 
```


Alternatively, we could start `SenderWatcher` with a dependency on `RoundsWatcher` but ideally these watchers have separated concerns.

Another option is to turn the current `claimedReserve[address]*big.Int` map into a nested map that also takes a round number. However a wrapper struct achieves the same since we don't need historical access and it is a more flat structure that will take up less memory.

**Comment by yondonfu** [comment]
Just noting that the equation for a recipient's reserve allocation can be expanded to:

```
((reserve.fundsRemaining + reserve.claimedInCurrentRound) / poolSize) - reserve.claimedByAddress[currentRound][sender]
```

So, whenever a new round begins we want to make sure to reset the recipient's view of the reserve funds available (i.e. `reserve.fundsRemaining + reserve.claimedInCurrentRound`) and the recipient's view of how much it has claimed (i.e. `reserve.claimedByAddress[currentRound][sender]`).

Here are two additional implementation approaches:

1. Add a `Subscribe()` method to the `RoundsWatcher` that accepts a sink channel that the `RoundsWatcher` uses to send `NewRound` events to listeners. The `SenderWatcher` can subscribe to these `NewRound` events and every time it receives one of these events it can iterate through the keys of its `claimedReserve` map and reset the values to 0. After receiving a `NewRound` event, the `SenderWatcher` would also call `GetSenderInfo()` for all keys in its `senders` map to refresh its view of the available reserve for a sender during the round.

2. 

> One possible solution is to track the round number claimedReserve belongs to in a wrapper struct. When we then receive events that would alter claimedReserve we would check the current round vs the round number on the struct. If both are equal we alter the current value, if currentRound is larger than the round number on the struct we first reset claimedReserve to 0 before doing the necessary arithmetics.

The option below is pretty similar to the above description with some small tweaks in details.

Inject an interface with the `LastInitializedRound()` method into `SenderWatcher`. Add a `lastUpdateRound map[ethcommon.Address]*big.Int` field to the `SenderWatcher`. Every operation in `SenderWatcher` for a sender address, whether it be an RPC call or an event handler, will call `LastInitializedRound()` on the interface passed into `SenderWatcher` and compare it with the the `lastUpdateRound` stored for the sender address. If the value returned by `LastInitializedRound()` is greater than the stored value in `lastUpdateRound`, we call `GetSenderInfo()` for the address to refresh the view of the available reserve and we reset the value for the address in the `claimedReserve` map to 0.

I currently lean toward the first option since it feels simpler: after adding the `Subscribe()` method to `RoundsWatcher`, `SenderWatcher` just needs to set up a goroutine that listens for new round events on the sink channel and all the updates associated with the event can be isolated into a single code path.
