### ISSUE TITLE
Windows CI build stuck on same commit

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1121]
**Describe the bug**
CI always builds same commit for windows:
```
Build succeeded :white_check_mark:
Branch: throughbench
Platform: windows-amd64
Last commit: removing commented out lines by ya7ya
https://build.livepeer.live/0.3.3-adebd820/livepeer-windows-amd64.zip
```

**To Reproduce**
Look into #builds channel

**Comment by iameli** [comment]
Yup. It's because gomodules are broken on Windows but I forgot to put `set -e` on the script, so it looks like it's succeeding even though it's failing. Yahya's commit there happened to be the last build to happen before we merged gomodules into master.

I've "fixed" this in https://github.com/livepeer/go-livepeer/pull/1095, which is to say the Windows build properly throws an error in that branch. I have not yet actually fixed the Windows gomodules build.

**Comment by iameli** [comment]
Update: I fixed this problem but then there was some new problem blocking Windows builds on Azure. So the Windows builds are cauterized for now. Which is okay, nobody was really asking for them.

**Comment by darkdarkdragon** [comment]
@iameli can be closed?

**Comment by yondonfu** [comment]
Closing because we're using GH actions for Windows builds now.
