### ISSUE TITLE
non-integer price for N pixels in Wei throws incorrect error

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1146]
**Describe the bug**

When invoking multi-step "become an orchestrator", I enter a value of `1.23456789` for `Enter the price for 1 pixels in Wei (required) >`.

The process eventually fails with the following error:

`price unit must be greater than 0, provided 0`

`0` was not provided. `1.23456789` was provided.

**To Reproduce**
1. Run `./livepeer -network rinkeby -orchestrator -transcoder -pricePerUnit 1` and log in.
2. In another terminal, run `./livepeer_cli`
3. Make sure the address of the node has ETH and LPT
4. Select the option `Invoke multi-step "become an orchestrator"`
5. Accept all the default settings
6. For `Enter the price for 1 pixels in Wei (required) >` enter `1.23456789`
7. Configure the amount to bond to yourself etc.
8. See the following error in the console for the `./livepeer` process:

`E1030 21:18:50.287955   32557 webserver.go:236] price unit must be greater than 0, provided 0`

**Expected behavior**

I expect to be able to configure non-integer values for the `price for N pixels`.

Failing that, I expect to be shown an error message that I need to provide an integer value for this parameter.

Failing that, I expect to be told that the non-integer value is not acceptable.

Failing that, I expect to be prompted to enter an integer value in the process.

**Screenshots**

**Desktop (please complete the following information):**
 - `OS: Ubuntu 19.04`
```
Livepeer Node Version: 0.5.0
Golang runtime version: gc go1.13
Architecture: amd64
Operating system: linux
```

**Comment by j0sh** [comment]
Thanks for the report. The CLI language probably should be updated to reflect that an integer is expected here.

The pricing is handled internally as a rational number, `wei/pixels`. To achieve the per-pixel price of 1.23456789 wei, you need to scale out the numbers: 123456789 / 100000000.  Note the preceding example in the CLI prompt:

https://github.com/livepeer/go-livepeer/blob/2675094baed9ee45bdf21d72c41d355fe8f5eeca/cmd/livepeer_cli/wizard_transcoder.go#L43-L44

Aside: are we still storing pricing info on-chain? If not, is this pricing information still necessary to collect at registration time without also collecting additional PM parameters such as EV, deposit multiplier, etc? cc @yondonfu

**Comment by yondonfu** [comment]
@j0sh Pricing info is not stored on-chain. The pricing information isn't absolutely necessary at registration time, but IMO it is a good time to ask for pricing information in addition to required PM params at this point (good point about also asking for PM params) since the user is preparing its orchestrator to perform work. Perhaps we can make a clearer distinction between information that is stored on-chain vs. off-chain by keeping the commission rates + serviceURI prompts grouped together in the workflow and then prompt the user for off-chain pricing and PM params after on-chain registration is complete.

On a separate note, it might be useful to store pricing information and PM params in the DB when configured using the CLI wizard so that the values persist across restarts (could be overridden using the node flags) to avoid confusion around having to set these values after every restart...

**Comment by j0sh** [comment]
> Perhaps we can make a clearer distinction between information that is stored on-chain vs. off-chain by keeping the commission rates + serviceURI prompts grouped together in the workflow and then prompt the user for off-chain pricing and PM params after on-chain registration is complete.

Agreed - pricing + PM params should at the very least be a separate API endpoint within the CLI server. The CLI user interface can then wrap that accordingly.

> store pricing information and PM params in the DB when configured using the CLI wizard so that the values persist across restarts (could be overridden using the node flags)

There's a bit of a UX catch-22 regarding having to set the `pricePerUnit` flag at startup time, configuring (perhaps a different) price at registration time, then needing to *remove* the old `pricePerUnit` flag after the node restarts, especially if the new price in the DB is different.

Also this is a bit interesting because that'd give us a fourth way to configure the price:
1. Node flags
2. CLI API
3. CLI user interface
4. Database

**Comment by chrishobcroft** [comment]
> @j0sh Pricing info is not stored on-chain. The pricing information isn't absolutely necessary at registration time, but IMO it is a good time to ask for pricing information in addition to required PM params at this point (good point about also asking for PM params) since the user is preparing its orchestrator to perform work. Perhaps we can make a clearer distinction between information that is stored on-chain vs. off-chain by keeping the commission rates + serviceURI prompts grouped together in the workflow and then prompt the user for off-chain pricing and PM params after on-chain registration is complete.
> 
> On a separate note, it might be useful to store pricing information and PM params in the DB when configured using the CLI wizard so that the values persist across restarts (could be overridden using the node flags) to avoid confusion around having to set these values after every restart...

Can I suggest that there is a different process for setting stuff which *is* stored onchain, vs. stuff which *is not* stored onchain.

The reason is, I expect to be changing my PM parameters a lot more regularly than changing e.g. my Reward Cut / Fee Share / ServiceURI, and it would be tedious to have to make sure I have to enter the same values for these more static parameters each time, otherwise it would end up calling `transcoder` or `setServiceURI`.

Aside: am I right in thinking that in terms of SC function calls, the only change in terms of on-chain setup between the Alpha and Streamflow is that `transcoder` now only takes 2 arguments instead of 3 - given that `pricePerSegment` is no longer required?

**Comment by yondonfu** [comment]
> Aside: am I right in thinking that in terms of SC function calls, the only change in terms of on-chain setup between the Alpha and Streamflow is that transcoder now only takes 2 arguments instead of 3 - given that pricePerSegment is no longer required?

In terms of on-chain parameter setting, yep you're correct that there is now one less parameter (`pricePerSegment`) that needs to be set on-chain since pricing is now advertised off-chain.
