### ISSUE TITLE
Improve logging on "Could not create payment: ticket EV higher than max EV"

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1176]
**Is your feature request related to a problem? Please describe.**

I'm trying to set up the parameters for PM, and I'm hitting an error `Could not create payment: ticket EV higher than max EV`.

I am aware of [the notes in the documentation about how to resolve this issue](https://livepeer.readthedocs.io/en/latest/streamflow-public-testnet.html#broadcasting-video), but it would be really helpful if the error logging could be more informative - in order to help expose some of the inner workings of the PM setup.

**Describe the solution you'd like**

It would really help to log the values of the `ticket EV` and `max EV` that are being compared, so that a user can understand how far off they are.

`Could not create payment: ticket EV = 10000000001, higher than max EV = 10000000000`.

In addition, in general, it would be really useful to expose the parameters being used to "govern" the PM parameters, to help users to know what's going on "under the hood", and thus allow them to understand via their own worked examples.

The `gaspricemonitor.go:134] Cached gas price: 1000000000` is a good start, but I feel like there are other metrics which would be worth logging, to help a user work out what is going on in real time.

**Describe alternatives you've considered**

I've tried to think about alternatives to this - there is perhaps an option to display a section in the `livepeer_cli` to display some kind of `PAYMENT STATS`, displaying some real time metrics about how the nodes are operating in terms of cached gas price, max ticket EV, ticket EV - although some of those things might be per-stream.

**Additional context**

None, thanks! Keep up the good work... this PM stuff is really interesting, but would help to have some more visibility on how it works in practice, and in real time :)

**Comment by yondonfu** [comment]
I agree that actual numbers in the error logs would be helpful.

Under the hood, max EV is being compared against the sum of the EV of each ticket in a batch included for a payment (rather than the EV just a single ticket). I think "required payment value higher than max payment value" might be a clearer way to describe the failed validation. Related - `maxPaymentValue` might be a better name for the current `-maxTicketEV` flag since the value passed to that flag represents the maximum value of a single payment that a broadcaster will send with a segment to an orchestrator.
