### ISSUE TITLE
Support arbitrary fps and transcoding profiles

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#1185]
We should support custom FPS and 3 different types of transcoding profiles (baseline, main, high).

This should be configurable via the webhook.

**Comment by j0sh** [comment]
> We should support custom FPS

Also see https://github.com/livepeer/go-livepeer/issues/874 and https://github.com/livepeer/lpms/issues/120 . In particular, lowpass frame rate filtering seems to be what's needed to satisfy certain ladders, eg [Apple's](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices). Pass through below X fps, otherwise cap the framerate at X, say 30fps or 60fps.

> 3 different types of transcoding profiles (baseline, main, high)

Note that this is codec-specific, so these options will need to be scoped to H.264 since it won't generalize if/when we add other codecs. This is also something that can't really be safely supported in on-chain mode at the moment, because there are knock-on concerns around encoding cost, verification, etc.
