### ISSUE TITLE
Investigate PTS out of sync issue

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#1188]

**Comment by ericxtang** [comment]
@darkdarkdragon reported an issue where the PTS across different media playlists get out of sync over time.

**Comment by darkdarkdragon** [comment]
It turns out that Wowza re-packaging segments it receives from Livepeer.
Problem is that it cuts them differently for different streams (resolutions).
Probably that's why it PTS getting out of sync overtime.
For example, streaming this [video](https://storage.googleapis.com/lp_testharness_assets/bbb_sunflower_1080p_30fps_normal_t02.mp4):
Segment that gets sent by Wowza to Livepeer is `source-171.ts`.
It has start time 262.872 and length `00:00:01.13`.

Segments that are coming out of Wowza:


|name|resolution|start time|length|
|----|----------|----------|------|
|media_b5018866_182.ts|1920x1080|262.893333|00:00:00.27|
|media_b1465800_180.ts|1280x720|262.893000|00:00:00.27|
|media_b567435_180.ts|640x360|262.893000|00:00:00.27|
|media_b202823_180.ts|256x144|262.893000|00:00:01.11|

It happens every time in the same place for that video file.

**Comment by f1l1b0x** [comment]
thats with a variable GOP, right? is this also appearing with steady 2 sec gops?

**Comment by darkdarkdragon** [comment]
@f1l1b0x 
> thats with a variable GOP, right?

Probably.

> is this also appearing with steady 2 sec gops?

Where I can get 1080P test video that surely has 2 sec gops?

**Comment by f1l1b0x** [comment]
encode yourself with ffmpeg add -g 48 since you have a 24 fps source

**Comment by darkdarkdragon** [comment]
@f1l1b0x 
I have 30pfs source.
I've recoded it using
`ffmpeg -i bbb_sunflower_1080p_30fps_normal_t02.mp4 -c:a copy -c:v libx264 -g 60 -profile:v high -preset:v slow bbb_sunflower_1080p_30fps_normal_t03.mp4`
How do I check that it did the trick?

**Comment by darkdarkdragon** [comment]
@ericxtang I've checked segments that was sent by Wowza to Livepeer - almost all of them are 1.62s in length, with small number of slight variations (like 1.17s, 1.3s, 1.43s).
