### ISSUE TITLE
Add profiles for 4K (3840x2160) and Full HD (1920x1080) encoding

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1200]
**Is your feature request related to a problem? Please describe.**

I am streaming in 8K (7680×4320) and I would like to be able to offer viewers streams at 4K (3840x2160) and FullHD (1920x1080).

Currently, the largest profile that is possible to be encoded is Standard HD (1280x720).

**Describe the solution you'd like**

As a Broadcaster, I would like to be able to select options for encoding my stream into more sizes.

**Describe alternatives you've considered**

I could encode these streams myself, but I don't have the GPU capacity to do this reliably and cost-effectively.

**Additional context**

[Apparently, 16K screens are on the way too...](https://robbreport.com/gear/tvs/sony-16k-crystal-led-tv-2869489/)

**Comment by j0sh** [comment]
Since https://github.com/livepeer/go-livepeer/pull/1242 , broadcasters have been able to specify custom transcoding profiles via the authentication webhook. But I just realized we're missing documentation for that. Will leave this issue open until those docs are in. Tracking in https://github.com/livepeer/go-livepeer/issues/1292.
