### ISSUE TITLE
How should we handle authenticated webhook requests?

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1278]
When #1263 lands, the API will be returning object store credentials to the broadcaster at `-authWebhookUrl`. We should be careful about exposing those credentials. Currently, anyone in possession of a stream ID could hit `https://livepeer.live/api/stream/hook` and retrieve the object store credentials. That's bad. Here are four ways to handle that which I posted in chat:

1. Very simple shared secret implementation. Run the API with (perhaps) `--webhook-key=SHARED_SECRE`T and require the broadcasters to hit the webhook at https://livepeer.live/api/stream/hook?key=SHARED_SECRET. We could do that without any changes to go-livepeer. But now SHARED_SECRET is in the URL, and URLs get logged a lot, and SHARED_SECRET plus USER_UUID equals access to ultra sensitive credentials, so that makes me nervous.
2. Maybe a slightly better option: basic auth? So in go-livepeer you'd specify -authWebhookUrl https://broadcaster-abcd:SHARED_SECRET@livepeer.live/api/stream/hook, and then that ends up in the authorization: Basic [basic encoded secrets go here] header, validated by the API. That's kind of neat. I like that it can be easily specified as part of `-authWebhookUrl`.
3. As #1, but use some kind of HMAC of SHARED_SECRET and the stream URL such that we can use a shared secret without ever sending that secret over the wire, which I'd be more comfortable with than option 1.
4. Or most complex/robust would probably be a JWT signed by the Ethereum identity associated with the B node. Which would require offchain B nodes to have an eth identity, but maybe that's a good thing.

**Comment by j0sh** [comment]
> Currently, anyone in possession of a stream ID 

Can the stream ID itself be considered a shared secret? This is how RTMP authentication typically works. The playback URL can still be separate / public since it's returned via the manifestID field in the webhook response.

Given that the auth webhook already gives the keys to the transcoding kingdom - OS credentials are only a small part of it, the O itself processes requests with absolutely no authentication - would keeping our current approach unchanged be OK for now?

>  But now SHARED_SECRET is in the URL, and URLs get logged a lot

That is true. We'd also have to do similar sanitization even with HTTP auth  - IIRC, the node currently logs the entirety of the webhook URL.

> Maybe a slightly better option: basic auth?

We could also look at digest auth (rather than basic) to avoid transmitting the secret in its entirety. If we absolutely must do something about this issue right now, HTTP digest auth gets my vote.

But if the goal is really just to authenticate the node itself (rather than the stream) then there are also a number of other ways to accomplish this. SSL client certificates, local SSH tunnels on both ends (or alternates such as spiped), API proxies, etc.

**Comment by iameli** [comment]
> Given that the auth webhook already gives the keys to the transcoding kingdom - OS credentials are only a small part of it, the O itself processes requests with absolutely no authentication - would keeping our current approach unchanged be OK for now?

Possession of a stream ID allows you to stream video into that stream ID. That's a problem, but it's a much smaller problem than the OS credentials, which give you "root" access to an entire AWS MediaStore account.

> We could also look at digest auth (rather than basic) to avoid transmitting the secret in its entirety. If we absolutely must do something about this issue right now, HTTP digest auth gets my vote.

Cool, I like that idea.

**Comment by j0sh** [comment]
> OS credentials, which give you "root" access to an entire AWS MediaStore account.

I'm really surprised if that's the case. In most cases, creds should be configured for least privilege - at least that's an option for S3. Is there some documentation around this for MediaStore?

**Comment by iameli** [comment]
[It looks like we can issue temporary STS credentials](https://docs.aws.amazon.com/mediastore/latest/apireference/CommonParameters.html), it'd just require a bit more work on the API side to generate the temporary credentials. So that would mitigate the problem down to a single compromised stream instead of the whole account.

**Comment by darkdarkdragon** [comment]
Why not just add simple shared secret, same as used between O and T? Specified through command line for B, sent in headers? Very simple but solves our problem.
Temporary credentials can be added later as additional precautions.

**Comment by victorges** [comment]
Adding my 2 cents to this discussion after it got mentioned in the PR above, since I got pretty surprised when I found out that the auth webhook (which feels like a root access API) has no authorization apart from the ID obscurity.

To share an anecdote of my own experience using the Livepeer API before I joined the team, when I was building that justcast.it app:
We wanted a really minimalistic interaction for the users, so the idea was to open the page and be ready to start streaming already. The current design we came up with was to immediately do a 'handshake' API call with the server which returned the `streamKey`/URL for streaming from the client. That API also adds an http-only cookie so the user gets tied to a specific stream after first use. For simplicity, I opted to make that cookie the stream ID itself, with which the server, that had access to an API token, could grab the stream information including the secret stream key and return to the "authorized" user.

I didn't think it was the best solution but it worked and it was just a hack/athon in the end. With an outsider perspective, all I thought could happen would be the user having access to this internal identifier from one of the app dependencies, but that they wouldn't be able to do anything with it other than grab the stream key from the server, since they don't have any direct access to the livepeer API keys. I think that's a reasonable assumption to make, so that's why I also think that using the ID as a "security through obscurity" parameter is not the ideal solution here. Especially because it is not something that is presented as a "secret" to the user of the API, like the stream key itself is, but also because the general ID concept doesn't seem like something that would give powers over a resource. To make an analogy, I wouldn't expect someone with my user ID in a social network to be able to access any private information I have in there.

I think either the HTTP digest or shared secret auth header would be pretty good. The Ethereum identity signature is pretty awesome too, but then it feels like a lot of work. Maybe another idea would be using the stream key instead of the stream ID? But then I guess it would still allow anyone with the streamKey to access private data from the "account" like the object store credentials mentioned here.

Anyway, is this still a priority/the same way as it was in Dec 2019? If so, it feels like this is an important issue and I would be interesting in helping to fix it.

**Comment by iameli** [comment]
@victorges discussing a little proposal for this that would look like this - add a user param to the webhook URLs, like so: 

```
-authWebhookUrl=http://2778622F-D260-4859-9FF8-1B73A9FF4830@staging-livepeer-api/api/detection/hook
```

That being present would add it as a `Bearer` token in the `Authorization` header for webhook calls:

```
Authorization: Bearer 2778622F-D260-4859-9FF8-1B73A9FF4830
```

That would make it quite easy to implement on the API server while also providing a straightforward API for other integrators.

Alternative, more consistent with the URL spec:

```
-authWebhookUrl=http://user:pass@staging-livepeer-api/api/detection/hook

Authorization: Basic dXNlcjpwYXNz
```

For the API, we could do this and disregard the username, perhaps:
```
-authWebhookUrl=http://livepeer:2778622F-D260-4859-9FF8-1B73A9FF4830@staging-livepeer-api/api/detection/hook
```

Or even:
```
-authWebhookUrl=http://[user id goes here]:[api token goes here]@staging-livepeer-api/api/detection/hook
```

**Comment by iameli** [comment]
Still discussing the specific flavor of that implementation.

**Comment by darkdarkdragon** [comment]
@iameli I like idea with `Authorization: Bearer 2778622F-D260-4859-9FF8-1B73A9FF4830` most - anyway it is our internal API which is not useful to anyone else.

**Comment by iameli** [comment]
@darkdarkdragon That's definitely the easiest but @victorges was kind of bringing me around on the Basic Auth version — it has exactly the same security properties but provides zero surprises to integrators.

We could do both, also? Basic if there's a username and password, Bearer if there's just one string before the `@`. Like:
```
-authWebhookUrl=http://2778622F-D260-4859-9FF8-1B73A9FF4830@staging-livepeer-api/hook

Authorization: Bearer 2778622F-D260-4859-9FF8-1B73A9FF4830

-authWebhookUrl=http://user:pass@example.com/hook

Authorization: Basic dXNlcjpwYXNz
```

**Comment by darkdarkdragon** [comment]
@iameli no need to do both - they are basically the same - both transfer tokens in clear text. We can just go with Basic Auth.

**Comment by victorges** [comment]
Cool, I think the basic auth is a good first start, and I guess later we could add a more sophisticated authentication method like an HTTP digest or a shared secret which may need some changes to `go-livepeer` code. 

Apart from the plain-text credentials, the other thing I'm uncomfortable with is how coarse these credentials are. We will be distributing all-powerful admin credentials to every broadcaster deployment we have. It still seems better than having no authorization at all though, so I think it's a good initial solution and we can later improve/tackle these other problems as well. 

I created a PR for the basic-auth and admin-only authorization part on livepeer-api (https://github.com/livepeer/livepeer-com/pull/472). Will be doing some further testing and explore how to make that work in production tomorrow.
