### ISSUE TITLE
Spec: HTTP segment ingest return transcoded data in the same request

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#1279]
## Abstract

Return transcoded data in same POST request.

## Motivation

Currently, handler for HTTP ingest POST endpoint only returns status code, without returning any data. This forces clients to do another HTTP requests to the Broadcaster to receive transcoded data, one request per transcoding profile. This adds unnecessary latency and complicates client's code.

## Proposed Solution

Return transcoded data using `multipart/mixed` encoding. Return it only if client sends `Accept: multipart/mixed header` header.

## Implementation Tasks and Considerations

Borrow implementation from orchestrator. Also, if transcoded segments stored in external object store, instead of actual data return URLs to segments (distinguished by using `application/vnd+livepeer.uri` mime type).

Thing to consider - maybe we should allow client to force to always return URLs instead of returning actual data?  In case client do not want actual data, but, say, want to construct playlist for himself and pass it somewhere?

**Comment by j0sh** [comment]
> Also, if transcoded segments stored in external object store, instead of actual data return URLs to segments (distinguished by using application/vnd+livepeer.uri mime type).

👍  Note that implementing clients would need to be aware of this distinction, but I agree it's a useful feature to have.

>  maybe we should allow client to force to always return URLs instead of returning actual data? 

Yes - maybe this could be signaled by the client requesting a different (more explicit?) content type in the Accept header:
* Maybe something like `multipart/mixed/livepeer.uri`
* Separate JSON response type if the client requests URL-only, again via content-type, eg `application/json`.

For an external OS, the broadcaster will be able to return a full / absolute URL in the response. However, if an internal OS is being used, along with a URL-only return format, the only a relative URL can be returned (since the B doesn't always know the full URL it's accessible at), and clients again need to be prepared for it.

All being said, this particular bit can probably be saved for later.
