### ISSUE TITLE
Transcoder taking more work than -maxSessions should allow

### ISSUE THREAD

**Issue by criticaltv** [livepeer/go-livepeer#1297]
**Describe the bug**

When using `-maxSessions` to set the maximum capacity, the Transcoder accepts more sessions than configured. For example, I set the Transcoder with `-maxSessions 1`, and it accepted 2 concurrent sessions of Transcoding.

**To Reproduce**

1. Run Livepeer as a Transcoder with `-maxSessions 1` flag
2. Broadcast 2 streams to be transcoded by that Transcoder
3. Observe how both streams are being transcoded by the `-maxSessions 1` Transcoder :|

**Expected behavior**

If a Transcoder is handling maximum number of sessions, specified by `-maxSessions` flag, then I expect any additional requests for Transcoding work to be refused by the Transcoder.

I also expect that the Orchestrator should not send any additional streams to a Transcoder when it reaches maximum capacity.

This functionality is important for new entrants to the Livepeer network, who may wish to limit the amount of work their infrastructure might take on, in the early days at least.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Livepeer Version 0.5.2

**Comment by j0sh** [comment]
There is a distinction here between `maxSessions` on broadcaster and transcoder which probably ought to be documented better:

* MaxSessions in `-transcoder` mode caps the number of *simultaneous* transcodes
* MaxSessions in `-orchestrator` and `-broadcaster` mode caps the number of jobs / incoming streams

Since the transcoder works on segmented videos, and there may be some time in between segments, it is possible for the transcoder to work on multiple jobs in an interleaved fashion, while still only doing one transcode at a time. For example:

1. Transcode job1, seg1
1. Transcode job2, seg1
1. Transcode job1, seg2
1. Transcode job2, seg2

If both the transcoder and orchestrator are under your control, then you can cap the number of *jobs* by setting `-maxSessions 1` on the orchestrator. This will result in the behavior you're looking for.

> the Orchestrator should not send any additional streams to a Transcoder when it reaches maximum capacity.

The orchestrator should not exceed the transcoder's capacity at any given instant, although over time, the transcoder may still be processing a number of streams in excess of its `-maxSessions`, but they will be interleaved (eg, non-simultaneous).

Are you doing GPU transcoding? Since https://github.com/livepeer/go-livepeer/pull/1124 , GPU transcodes run in a persistent session [1] which takes up resources (memory, etc) even if no transcoding is happening, so I can see some users wanting to cap the number of sessions separately from the number of concurrent transcodes. The marginal resource-cost per idle stream should be pretty small, but I haven't really run numbers on it yet. Do you have this concern?

[1] Software transcodes are non-persistent, same as before; each segment is its own "session" and after the segment completes processing, there's no remaining trace of it on the transcoder, freeing up resources for the next segment (whether or not it's the same job). This is why the transcoder counts "sessions" the way it does, based on instantaneous transcode count.
