### ISSUE TITLE
Reduce logging level of recoverable blockwatcher errors

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1306]
**Is your feature request related to a problem? Please describe.**

The block watcher currently logs recoverable errors such as:

```
I0114 08:37:58.449250   27125 block_watcher.go:202] failed to get logs for block nextHeader=&{[160 223 85 27 170 71 99 154 21 126 119 10 114 18 77 82 39 173 66 102 237 26 172 80 141 240 199 106 124 15 32 51] [164 49 109 49 151 50 43 220 247 40 65 199 82 72 177 183 153 134 164 232 190 37 167 239 207 228 44 6 213 175 247 140] 9277579 []}
```

The block watcher will retry and recover from these errors so we should avoid logging all of them by default in order to reduce log clutter.

**Describe the solution you'd like**

Reduce the log level for recoverable errors in the block watcher i.e. `glog.V(common.DEBUG).Errorf(...)`.

Note: That the above example log statement would cause a cyclic import right now since the `common` package currently imports the `blockwatch` package so we would need to figure out a solution here.

Log statements involving recoverable errors include:
- https://github.com/livepeer/go-livepeer/blob/master/eth/blockwatch/block_watcher.go#L230
- https://github.com/livepeer/go-livepeer/blob/master/eth/blockwatch/block_watcher.go#L248

There might be additional recoverable errors being logged so we should take a pass through the code and identify each of them.

**Comment by kyriediculous** [comment]
I would be okay moving `common/log.go` into it's own `logging` package even though it seems ridculous for 3 lines of code, the semantics of it would be nice on the other hand eg. `logging.DEBUG`

**Comment by j0sh** [comment]
> it seems ridculous for 3 lines of code

Agreed, would rather not introduce another package. The options here I see are:

* The reason we're talking about this is because we're getting reports from users that are confused by the "acceptable error" language. What we could do instead is reword the message so they aren't so alarmed. Logging the incident is still informative, otherwise we may end up missing further context from bug reports. I'm of the opinion that significant "state changes" should be logged by default, and this counts among that.

* Use numeric indices rather than names. Not elegant but it does the trick. We do this in LPMS.

https://github.com/livepeer/lpms/blob/6e76b1c43b694088aaa57cd96b9bbf6d5abcdc1a/core/lpms.go#L92 

* Re-define the constants within the blockwatch package. Some duplication is OK.

*  Undo the dependency inversion pattern in the DB. (I will continue to hold out hope for this...)

**Comment by kyriediculous** [comment]
- while (1 )is true for acceptable errors we would also have to change the language here. I think changing the language is kind of avoiding the problem. 

- for numeric indices it might be hard to keep consistency with multiple people working on the same codebase but I would be ok with it

- I think (4) touches the root of the issue but undoing that pattern will require some refactoring and I'm not sure that's worth the engineering effort given the scope of this issue and #1076  .  I'd be more in favor of moving DB into its own package then, rather than having it in common.

**Comment by yondonfu** [comment]
I would be onboard with updating the language for this issue. After some consideration, I believe that not displaying these messages by default only partially addresses the problem which is that the current message "failed to get logs for block..." is scary and does not convey to the user that the failure to fetch logs is expected to happen sometimes, that it is recoverable and that it does not prevent the node from operating. If we change the logging level for these messages, we would probably have to respond to similar inquiries from node operators that turn on verbose logging (perhaps because they want to gather as much information as possible - we also mention in the docs that you should turn on verbose logging if you want to see more detailed information about what your node is doing i.e. transcoding) about whether a failure to fetch logs is preventing the node from functioning.

Maybe something like the following:

```
glog.Infof("missing logs for blockNumber=%v - fetching on next polling interval", nextHeader.Number)
```

Right now the log message includes the full `nextHeader` - I suggest only including the block number for `nextHeader` to make the message more concise.

**Comment by kyriediculous** [comment]
I guess updating the language would work, but I still think we should add logging levels here as it is not critical information for node operation. When connected to infura it would still quite often show the message which with the changed language will likely be perceived as not harmful but it will still be clutter to critical information regarding transcoding and payments. 

So in order to make progress on this I would be okay with just using numeric indices in the `blockwatch` package and shelfing the discussion about (1) a logging package (2) removing the dependency inversion in the DB or (3) extracting DB into its own package to a later time where it is more of a pressing issue. WDYT?
