### ISSUE TITLE
command-line flags should be case-consistent

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#1362]
Currently our flags are inconsistent:

`-orchAddr`: ✅
`-orchaddr`: flag provided but not defined: -orchaddr
`-dataDir`: flag provided but not defined: -dataDir
`-datadir`: ✅

I'd argue there's no value in having these be case-sensitive. But if folks like them being case-sensitive, we should at least go through and make them all consistent (e.g. `-dataDir`)

**Comment by j0sh** [comment]
Good point. CLI flags have historically been case-sensitive; tools with a lot of single-letter flags make use of that feature. While don't *really* need case sensitivity here AFAIK, it feels a wee bit risky given how golang allows other tools / dependencies to pull in their own CLI args (we had flags-related issues in the past with `testing`, although not with case sensitivity).

Note that unconditionally changing to `dataDir` since that would break compatibility. But we could add an "alias" that accepts either variant.

**Comment by iameli** [comment]
Sure, I don't have strong feelings either way. Canonicalizing `-dataDir` with `-datadir` as a deprecated alias seems like a reasonable way to handle this.

**Comment by thomshutt** [comment]
This is now fixed
