### ISSUE TITLE
Flakey Test: TestOrchWatcher_HandleLog_TranscoderActivated

### ISSUE THREAD

**Issue by mk-livepeer** [livepeer/go-livepeer#1370]
This test fails sometimes but usually passes after repeating it.
```
--- FAIL: TestOrchWatcher_HandleLog_TranscoderActivated (0.01s)
    orchestratorwatcher_test.go:79: 
        	Error Trace:	orchestratorwatcher_test.go:79
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestOrchWatcher_HandleLog_TranscoderActivated
```
This can cause CI to become unpredictable. It isn't an urgent problem right now - just creating an issue so that it can be tracked.

**Comment by yondonfu** [comment]
This test fails sometimes because the assertion checks for a statement that is logged in a goroutine, but the statement might not be logged yet after the fixed [sleep](https://github.com/livepeer/go-livepeer/blob/cf3e4e59e67e06c76d3efb54e22e2f6e83e5620d/eth/watchers/orchestratorwatcher_test.go#L77) time. This scenario is possible for all event watcher tests that sleep prior to running an assertion that checks state dependent on code execution in a goroutine.

One way to address this issue is to increase the sleep time in these types of tests. However, the downside is that these tests take longer to run. Furthermore, if we do not increase the sleep time by a sufficient amount then the tests could still fail sometimes.

A more robust approach might involve something like the following:

- Defining a `logHandler` interface with a `HandleLog()` function
- Each event watcher type uses a `logHandler` interface and has an associated type that implements this interface. For example, the `OrchestratorWatcher` would use a `orchestratorLogHandler` type
- We can unit test the log handling behavior for the type that implements the `logHandler` interface
- We can unit test the internal loop started by an event watcher and check that it properly invokes the `HandeLog()` function of the `logHandler` by stubbing the `logHandler` in tests.

**Comment by kyriediculous** [comment]
This problem is however not exclusive to this area of the codebase (eg. `TestSelectSession`), the proposed solution would require us to implement additional logic everywhere we have a test depending on a goroutine to finish, despite that logic not being necessary for normal node operations. 

It also involves additional engineering overhead for anywhere we will be using this pattern in the future. 

Perhaps another less coarse solution is to introduce an environment variable for the sleep duration where the default is something like 2 milliseconds, but for CI we can slightly bump this up due to less available resources. 

e.g. `SLEEP=5ms go test ./...`

As I see it the deterrent of increasing the sleep time across the board is that testing time will increase, but I see this only as problematic when having to do quick test runs locally. For the CI tooling I don't think it really matters whether it takes 30 seconds longer to run the tests.

**Comment by yondonfu** [comment]
Yeah agreed that refactoring based on the suggested solution may be overkill. I think we can just bump up the sleep times (i.e. 100ms instead of 2ms) for now. 

> the proposed solution would require us to implement additional logic everywhere we have a test depending on a goroutine to finish, despite that logic not being necessary for normal node operations.

I do think we should avoid introducing new code that also requires using time.Sleep in goroutine based tests when possible - being able to write straightforward non-flaky tests for a piece of code is an important part of the design of the code even if it results in design decisions that aren't required to realize the desired functionality.
