### ISSUE TITLE
redeemWinningTicket fails if round is not initialized

### ISSUE THREAD

**Issue by criticaltv** [livepeer/go-livepeer#1472]
**Describe the bug**

If the O calls `redeemWinningTicket`, and the transaction is processed between rounds (i.e. before the next round has been initialised), then the transaction fails.

First, this wastes gas :(

Second, it's not clear whether the O automatically retries to redeem, or whether that ticket must be claimed manually.

**To Reproduce**

1. Receive a winning ticket
2. Attempt to redeem it after one round is finished and before the next round is initialized
3. See that the transaction fails with `Fail with error 'current round is not initialized'`

Example: https://rinkeby.etherscan.io/tx/0x963052482da1bb03de1f918926ee5a273a6c2e5227ab8337096aab8e3c8294e9

**Expected behavior**

First, I expect that a winning ticket ought to be redeemable at all time, independent of whether the round has been initialised :)

Second, I expect that the node should check whether the round has been initialised before attempting to redeem a precious winning ticket. It should perhaps check whether the transaction is always failing?

Third, I expect that redemption should be retried at a later stage (note: I am unable to verify if this happened or not)

**Comment by kyriediculous** [comment]
Thanks for the catch! 

Since v0.5.5 tickets will no longer be redeemed instantly upon receiving them (have to wait until O recipient reveals the seed). 

I just checked and it doesn't seem to be the case that transaction failures are being re-added to the queue.
https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/pm/recipient.go#L361

We should definitely re-add those tickets to the queue.

I think we should also avoid submitting transactions when the round isn't initialised but that might require additional engineering work so perhaps let's split this up into two smaller issues. This would be similar to checking the maxFloat. I think we need to add state to the `roundsWatcher` that not only checks the latest round number but whether it has been initialised. 
https://github.com/livepeer/go-livepeer/blob/0ee99d8905d461d734b638b0f5b533caa3e2a016/pm/recipient.go#L334

1. Fix resubmission on tx submission failure
2. Avoid submitting always failing transactions due to round not being initialised (we already do this if a B's max float is insufficient to cover the ticket facevalue)

**Comment by kyriediculous** [comment]
fixed by #1495
