### ISSUE TITLE
Verbose setting for transcoding related activities only

### ISSUE THREAD

**Issue by 0xVires** [livepeer/go-livepeer#1483]
**Is your feature request related to a problem? Please describe.**
While running a transcoder and orchestrator in parallel, -v 99 just spams the log with "Cached gas price" every second. 

**Describe the solution you'd like**
A verbose setting that only displays transcoding related activities would be nice and helpful for debugging any transcoder related problems.

**Comment by j0sh** [comment]
That log line probably should be VERBOSE rather than DEBUG. Then `-v 5` should suppress the message, although a quick grep is telling me that we probably have some more adjustments to do with what's considered debug or verbose.

For now, if you're debugging transcoder issues from logs, then `grep -v "Cached gas price"` will exclude that particular line.

https://github.com/livepeer/go-livepeer/blob/80c59d76e294952c83e4512517ccf24162e5e206/eth/gaspricemonitor.go#L134
