### ISSUE TITLE
H.264 Profiles

### ISSUE THREAD

**Issue by jailuthra** [livepeer/go-livepeer#1531]
## Abstract

This is a proposal to add support for configuring the H.264 profiles (baseline, main, high) of the videos transcoded by go-livepeer.

## Motivation

Some decoders support limited H.264 profiles. For example OpenH264 used for WebRTC only supports the Baseline profile. Similarly [older phones](https://superuser.com/a/489092) can usually playback Main and Baseline but not High H.264 content. Refer to https://github.com/livepeer/lpms/issues/190 for the original discussion on B-frame removal for WebRTC ingest.

Most encoders (like ffmpeg, OBS) allow configuring the H.264 profile - extending similar functionality to go-livepeer users is a good idea in general.

## Proposed Solution

Add a new enum field called `Profile` in the VideoProfile structure, which is used to configure the encoder. The enum will comprise of a limited subset of the profiles that we want to support.

The VideoProfile structure is defined in many places throughout the codebase like - LPMS (Go struct), Protobuf and Auth webhook JSON. We will need to add the new field everywhere and finally pass it off as a `AVDictionary` parameter to FFmpeg, similar to the changes done in [#1474 - non-integer framerate support](https://github.com/livepeer/go-livepeer/issues/1474#issuecomment-630952970).

### LPMS

1. Create an enum for the codec profiles with the values `H264_Baseline, H264_Main, H264_High` for now.
2. Add a new field `Profile` of the enum type in the [ffmpeg.VideoProfile](https://github.com/livepeer/lpms/blob/1613618/ffmpeg/videoprofile.go#L28) struct.
3. Use this field to populate the [AVDictionary](https://github.com/livepeer/lpms/blob/1613618/ffmpeg/lpms_ffmpeg.h#L18) passed to the ffmpeg video encoder in the Cgo module. Both CPU (libx264) and GPU (h264_nvenc) encoders support the ffmpeg AVOption `-profile [main/baseline/high]`. Will need to convert the enum value to a String that is supported by the FFmpeg AVOption.

### Go-Livepeer

1. Add a new field `Profile profile` to the Protobuf [VideoProfile struct](https://github.com/livepeer/go-livepeer/blob/dace5d5/net/lp_rpc.proto#L141-L163), where Profile is a Protobuf enum similar to the one made in Go.
2. Ensure the same field is generated (or add it manually) in the [net.VideoProfile](https://github.com/livepeer/go-livepeer/blob/dace5d5982bafe3bbfdc67b122192f49a23f46e2/net/lp_rpc.pb.go#L553-L568) Go struct mapped to the Protobuf.
3. Serialze & Deserialize between ffmpeg.VideoProfile <-> net.VideoProfile
4. Add a new json field in the [authWebhookResponse.Profiles](https://github.com/livepeer/go-livepeer/blob/dace5d5/server/mediaserver.go#L109-L120) which is used to configure go-livepeer via a webhook.

## Testing Tasks and Considerations

* Extensive unit tests for the new codepaths.
* Test transcoding videos manually with both go-livepeer and lpms and verify that the output has the correct H.264 profile.
* Dedicated unit tests in the CPU & GPU test suites of LPMS to sanity check that all profiles encoded correctly.

## Alternatives

~~1. We could use an **Enum** instead of a String for the H264 profile field in all the structs (similar to how `Format` is defined). This is useful in case we only want to support the three most popular profiles - baseline, main, high and not all the profiles supported by the underlying encoder. The implementation tasks would look very similar, with the added step of converting between String <-> Enum as FFmpeg expects a String.~~

1. We could have used a String directly instead of an enum for the H264 profile field, but we want to limit the surface area we expose to the end user so we've chosen the enum route for now. Look at the [comment below](https://github.com/livepeer/go-livepeer/issues/1531#issuecomment-640949472) for details.
2. The name `Profile` of the new field is in a struct called `VideoProfile`. This might be confusing to the reader. We may alternatively call the new field `H264Profile`.

**Comment by j0sh** [comment]
> configuring the H.264 profiles (baseline, main, high)

Note that one of the use cases prompting this feature is WebRTC. Some implementations are apparently unable to handle B-frames.  The [WebRTC spec](https://tools.ietf.org/id/draft-burman-rtcweb-h264-proposal-01.html#sec-profile-level) recommends "Constrained High" for devices that support it ([most do](https://superuser.com/questions/489087/what-are-the-differences-between-h-264-profiles/489092#comment1112348_489092) nowadays), which is  High Profile, minus B-frames and interlacing. WebRTC MTI also requires "Constrained Baseline" but I'd have to refer back to the spec to determine how that differs from regular Baseline and whether it justifies its own named profile.

That being said, we should also be able to "constrained high" out of the box. Under the hood, this can map down to a few AVOptions to enable the high profile, and disable B-frames/interlacing.

Note that this can also be used to sneak in a few different "nonstandard" types of encoding configurations later on, depending on user needs. Similar to the x264 presets (although I suppose the presets are composable with profiles, whereas this really isn't).

> We could use an Enum instead of a String for the H264 profile field in all the structs

Using an enum is probably better in this case, because it minimizes the surface area of the underlying API that's exposed to arbitrary users. Less things to go wrong if they can only choose from a few configurations that are known to be supported. Enumeration also plays a bit better with capability discovery (eg, maybe an encoder wants to disable High or Extended profile support because those are more expensive to process).

We had a similar issue with MP4 support - do we explicitly enumerate the supported formats, or do we expose the format as an arbitrary string, which would also allow for mkv/webm, flv, nut, basically anything else ffmpeg supports? We opted to be explicit.

Note that users directly using the LPMS API can always set the `TranscodeOptions.VideoEncoder` struct which gets mapped directly to the AVOptions. In that sense, `VideoProfile` is just a "configuration shortcut", so being explicit about the supported subset might be okay.

> The name Profile of the new field is in a struct called VideoProfile. This might be confusing to the reader. We may alternatively call the new field H264Profile.

Yes, the naming collision is a bit unfortunate. I think I am okay with using the name `Profile` though, for the following reason:

Consider is if / when we support additional codecs. Not to get too far ahead of ourselves, but what might that entail? Will we have a separate field for each codec that has profiles, eg "HEVCProfile" or "VP9Profile" ? Along with an error checking step, eg if the user specifies, say, HEVC and H264Profile ? Or if we overloaded the `Profile` field for H264+HEVC but then we wouldn't have to add a new field to support HEVC profiles.

Will signaling a HEVC transcode require specifying a HEVC-compatible profile, or do we keep that optional and use a more generic "Codec" to use the default configuration of a particular encoder? Or is there a compound structure we can grow into, eg `VideoCodec { Name: <default h264, or match based on profile>, Profile: <H264_Baseline, HEVC_Baseline> ... }`

All that might be getting ahead of ourselves though. Unless your thoughts have changed on the matter, keeping the field name as `Profile` is fine.

**Comment by jailuthra** [comment]
>  I'd have to refer back to the spec to determine how that differs from regular Baseline and whether it justifies its own named profile.

When I transcoded some videos to 'baseline' using ffmpeg and later ran `ffprobe`, it referred to them as 'constrained baseline'. So I would wager they are interchangeable.

**Update:** Ok seems like there is a difference in some [features](https://en.wikipedia.org/wiki/Advanced_Video_Coding#Profiles) but the original baseline became less popular since the introduction of 'Constrained Baseline', and ffmpeg seems to use the two interchangeably.

> That being said, we should also be able to "constrained high" out of the box. Under the hood, this can map down to a few AVOptions to enable the high profile, and disable B-frames/interlacing.

Should I add this within the scope of this spec? Or limit on adding pass-through support for all the profiles x264 ∩ nvenc support; keeping support for explicitly disabling B-frames/interlacing as a separate issue?

>Using an enum is probably better in this case, because it minimizes the surface area of the underlying API that's exposed to arbitrary users

Makes sense! I'll go ahead with the enum approach and also update the spec.

> All that might be getting ahead of ourselves though. Unless your thoughts have changed on the matter, keeping the field name as Profile is fine.

Sounds good!

**Comment by j0sh** [comment]
> Should I add this within the scope of this spec?

Let's keep it in scope, because one of the things prompting this feature is actually a specific customer request for WebRTC compatibility.
