### ISSUE TITLE
Add retry logic when Claim throws

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#164]

**Comment by ericxtang** [comment]
We should talk about this.  Should we actually retry when Claim throws?  cc @yondonfu @dob

**Comment by dob** [comment]
I agree it doesn't sound like we should actually retry if we've provided enough gas and the on-chain txn throws. That probably shouldn't happen. I think the bigger scenario to handle is to ensure that claims actually get made for work that may have been done across node process restarts...or across long running jobs...or in the case where the transaction never gets included on chain for some reason like network congestion. Though I think these can probably be tracked separately as special cases rather than being blocking requirements for v1.
