### ISSUE TITLE
Multiple O <-> Single T connections

### ISSUE THREAD

**Issue by jailuthra** [livepeer/go-livepeer#1657]
## Abstract

Currently, a Transcoder node can connect to only a single Orchestrator node. Instead, the T could periodically ping a discovery webhook to get a list of Os, similar to what the Broadcaster node already does.

## Motivation

**Improved UX for T operators**
A T operator would only need to be aware of a single webhook URL. Whoever runs the O webhook can dynamically update the list of available Os. Right now, a T operator would need to run multiple Ts in order to connect to multiple Os using the same set of GPUs on a server.

**Flexible utilization of T capacity**
The current 1O-1T setup makes it hard to dynamically scale the # of O nodes without having to change # of T nodes. This may work out fine when we have both O+T node on the same machine, often under the same process. But it is very hard to dynamically scale O and T nodes in tandem, when those nodes are hosted on separate servers.

**Symmetry**
A B has transcoding jobs it wants done, a T holds the capacity to do those jobs, while O nodes are the facilitator between the two. As we already allow a B to split its jobs between multiple Os, it makes sense to also allow a T to find work from multiple Os as well.

## Proposed Solution

The T could re-use the [discovery webhook](https://github.com/livepeer/go-livepeer/blob/master/doc/orchwebhook.md) mechanism the B already uses to connect to multiple Os as follows:

- The T operator uses the `-orchWebhookURL` cli option that a B operator already uses.
- T periodically fetches the list of available Os from the webhook URL.
- T decides how to to divide up its capacity amongst the returned Os. We can divide it evenly for now, and explore how to make it more flexible if needed later.
- T sends a [RegisterTranscoder](https://github.com/livepeer/go-livepeer/blob/master/net/lp_rpc.proto#L17) request to each returned O, along with capacity it wants to provide to that particular O.
- Each O registers the T and starts a gRPC stream where it periodically sends transcoding work via [NotifySegment](https://github.com/livepeer/go-livepeer/blob/master/net/lp_rpc.proto#L271) message

## Implementation Tasks and Considerations

Whenever the webhook updates the list of available Os, the T would want to update its registered capacity amongst the Os. There are two ways to go about this:

1. T closes all the gRPC streams it has, and sends out fresh `RegisterTranscoder` calls to the new list of Os.
2. T updates capacity for unchanged Os through an `UpdateCapacity` RPC message on the existing O<>T gRPC streams, only calling `RegisterTranscoder` for new Os in the updated list.

If closing & re-registering the T is not a very time consuming operation we can go with (1) as we will retain the simple uni-directional O->T gRPC streams and also won't need to find the diff in the returned list of Os.

But in case the delay between closing and re-registering an unchanged O causes significant # of missed segments for that O, it would make sense to spend some extra effort right now and do (2).

**Comment by darkdarkdragon** [comment]
@yondonfu Do I understand it right that main reason for this proposal to exists is the fact that single O can't handle load reliably? If so, maybe we should focus on solving main problem instead of building more hacks trying to hide hide this problem?

**Comment by jailuthra** [comment]
> Do I understand it right that main reason for this proposal to exists is the fact that single O can't handle load reliably?

@darkdarkdragon This is more aligned with the "increasing public network capacity use" goal rather than "improve reliability" although they are not mutually exclusive. The proposal would make supporting a O-T split transcoder-pool setup very easy, where the T node may be owned and running separately from the Os.

>  building more hacks trying to hide hide this problem?

Increasing capacity and improving reliability can go hand-in-hand, but I agree that we should avoid any short-term hacky fixes that make reliability worse. So I lean towards the 2nd approach mentioned above which would prevent any chance of *lost* streams:
>> 2. T updates capacity for unchanged Os through an `UpdateCapacity` RPC message on the existing O<>T gRPC streams, only calling `RegisterTranscoder` for new Os in the updated list.

**Comment by darkdarkdragon** [comment]
@jailuthra how does this helps with "increasing public network capacity use"? If were 1O was working reliably, would we ever needed this proposal?
> The proposal would make supporting a O-T split transcoder-pool setup very easy,

What could be easier than give one O's address to all the transcoders to connect to?

**Comment by kyriediculous** [comment]
After thinking about this as well as the reverse proxy some more and looking at my own experience with running an O-T split I agree with @darkdarkdragon. Horizontal scaling of O's doesn't lead to an increase of public network capacity, it is only a requirement for reliability. I think it's important to look at a couple of extra things

1. I don't think we have a good understanding of how much capacity a single O in an O-T split setup can handle. The orchestrator node here is only limited by bandwith and available computational resources. 

2. It seems that horizontal scaling by containerising is only beneficial to provide a "fallback" mechanism, to benefit from a scalability increase the nodes will have to exist on separate servers. 

3. To me it seems whether it makes sense to allow a T to find work from multiple O's is a different matter altogether and a webhook is not the only way to do this. Who runs the webhook server in this scenario ? Is it the O , or the T? If it is the O, what is the benefit over a reverse proxy ? What is the solution for having access to the orchestrator secret ? 
______

I propose following solution 

1. A reverse proxy can load balance between O's, the T connects to the reverse proxy 

2. T's are responsible themselves for managing and declaring their capacity rather than just messaging their maximum capacity to O's they connect to. If a T is out of capacity it will return a `TranscoderCapped` error. In a future iteration transcoders that falsely signal they still have capacity available but then time out or run out of memory could get suspended. 

_\* In the private pool setup the Ts are known entities and falsely signalling capacity when none is available could have contractual implications_

3. Orchestrators can dynamically scale their max sessions based on T capacity connected to them without having to split the capacity between Os. 

This requires a small change in go-livepeer but it simplifies the other moving parts.

**Comment by darkdarkdragon** [comment]
@kyriediculous 
> I propose following solution

Solution for what? What is the problem we're trying to solve?

**Comment by kyriediculous** [comment]
@darkdarkdragon An O node can go down due to causes out of our control, e.g. datacenter issues. If that happens there should be a fallback for the capacity connected to the O node.

**Comment by darkdarkdragon** [comment]
@kyriediculous 
> e.g. datacenter issues. 

in that case reverse proxy will go down too, so this will not help?

**Comment by jailuthra** [comment]
@darkdarkdragon 

> Solution for what? What is the problem we're trying to solve?

For a private transcoder pool deployment owned by us, a transcoder node operator might want to connect to multiple Os within the same region (suppose CHI). Right now they'll need to run as many T nodes on their machine as we have O nodes in CHI region. And those O nodes might get re-deployed or the number might change. Which is why having a webhook to list all the O nodes might be nice UX for the private-pool transcoder. (Same UX as a B already has, and we can re-use K8s list of pods like we did for B<->O webhook)

> What could be easier than give one O's address to all the transcoders to connect to?

If we have only a single O that we want to keep for a particular transcoder pool partner, then sure this proposal isn't needed. But I do not see how any of this is 'creating hacks to hide O reliability'. 

@kyriediculous 

> Who runs the webhook server in this scenario ? Is it the O , or the T? If it is the O, what is the benefit over a reverse proxy ? What is the solution for having access to the orchestrator secret ?

The webhook could be run by the O (for example by livepeer.com in our scenario) or by the T if they are an independent transcoder and want to connect to multiple pools like Livepool and livepeer.com pool etc.

We could even support passing a static local file which has a *list* of Os within the same CLI parameter of `-orchWebhookUrl`

Reverse proxy would only solve the problem for the former case. Webhook otoh would make it easy for a T to connect to multiple Os (from *any* webhook) without spawning different nodes for each O address.

**Comment by darkdarkdragon** [comment]
@jailuthra 
> , a transcoder node operator might want to connect to multiple Os

Why?

> If we have only a single O that we want to keep for a particular transcoder pool partner

Why not?

**Comment by jailuthra** [comment]
@darkdarkdragon a T connecting to our pool from somewhere near chicago would want to connect to Os in different datacentres/bandwidth (for example EWR and ORD) so that even if one datacenter has outage or bandwidth issue the T continues to receive work, and doesn't need to manually change how many T nodes processes they run.

it is simpler to give them one command to run to onboard their node, rather than multiple commands and special usecases depending upon region etc.

> in that case reverse proxy will go down too, so this will not help?

which is why I don't like reverse proxy idea as that is an extra service in between for which we need to handle availability and scaling.

webhook is simpler and could be hosted separately as no traffic passes through webhook (where it should be hosted is a good question but not exactly blocking this spec)

**Comment by jailuthra** [comment]
@kyriediculous 

> I don't think we have a good understanding of how much capacity a single O in an O-T split setup can handle. The orchestrator node here is only limited by bandwith and available computational resources.
It seems that horizontal scaling by containerising is only beneficial to provide a "fallback" mechanism, to benefit from a scalability increase the nodes will have to exist on separate servers.

That is a great point, we can't gain much (except CPU/RAM) from scaling # of Os within the same datacenter if we are hitting the datacenter-level bandwidth limit.

> A reverse proxy can load balance between O's, the T connects to the reverse proxy
T's are responsible themselves for managing and declaring their capacity rather than just messaging their maximum capacity to O's they connect to. If a T is out of capacity it will return a TranscoderCapped error. In a future iteration transcoders that falsely signal they still have capacity available but then time out or run out of memory could get suspended.

Here I wonder if we need to build, manage scaling & reliability of a new service or node type called "Reverse Proxy". If the RP is a single point of failure anyway, then we can have a single O node itself do all those things like @darkdarkdragon was probably suggesting (and get "more" work from the B directly rather than fetching work from or load balancing between a # of Os).

**Comment by jailuthra** [comment]
IMO even if we want to go with the 1O for the Transcoder pool approach, and host the O in some region with stable bandwidth and CPU - it would still be a good idea to have a simple webhook in front of that single O.

The webhook would be a lightweight single point-of-contact not consuming much resources, but in case we want to ever add an O for the transcoder-pool-program in a different availability zone or region, we don't need to ask the T operator to restart their nodes or start running two different T nodes etc.

**Comment by kyriediculous** [comment]
> That is a great point, we can't gain much (except CPU/RAM) from scaling # of Os within the same datacenter if we are hitting the datacenter-level bandwidth limit.

Redundancy seems to be the main benefit, but if failover to a different O is required upon failure anyway then doesn't a restart of the single O node result in a similar effect with the additional benefit of not having to keep multiple open listeners to multiple O nodes. 

> Here I wonder if we need to build, manage scaling & reliability of a new service or node type called "Reverse Proxy". If the RP is a single point of failure anyway, then we can have a single O node itself do all those things

Yeah that's true. 

> The webhook would be a lightweight single point-of-contact not consuming much resources, but in case we want to ever add an O for the transcoder-pool-program in a different availability zone or region, we don't need to ask the T operator to restart their nodes or start running two different T nodes etc.

A reverse proxy accomplishes the same without having to add a webhook for orchestrator discovery to go-livepeer, no ? 

________

That being said I think the concept of allowing a transcoder node to connect to multiple orchestrators in order to allow their capacity to get more work is an interesting idea to explore but more in a context of public pools.

**Comment by yondonfu** [comment]
@darkdarkdragon 

> Do I understand it right that main reason for this proposal to exists is the fact that single O can't handle load reliably? If so, maybe we should focus on solving main problem instead of building more hacks trying to hide hide this problem?

This was indeed one of the reasons why I started considering splitting capacity of a single T amongst multiple Os. I was interested in improving the utilization of a single T's capacity since a single O might not effectively use all of T's capacity if it stops receiving segments as a result of some of the considerations around the single segment in flight rule described in #1658. 

I agree with you that working around the potentially poor T capacity utilization problem with a single O with this approach is a bit of a hack and you make a good point that we should see if we can address the root cause instead. With this in mind, I created #1658 to track work on addressing this root cause and if we believe the root cause can be addressed then I don't think improving T capacity utilization should be a large driver in the decision on whether or not to implement O webhook discovery on T as proposed in the OP.

That being said, I do think a few other valid reasons for supporting connections to multiple Os have been brought up in this thread including:
- Allowing a T to receive work from Os in different regions which might make sense if the T is located in between those regions
- Allowing a T to participate in multiple transcoder pools to minimize lock-in following the lead of crypto PoW mining where miners can participate in multiple pools simultaneously. I acknowledge that this is a forward looking benefit though and has less short term relevance due to the limited # of public transcoder pools in production today

So, I do think it is still worthwhile considering supporting multiple O connections on a single T via webhook. But, since the benefits of this support are not as urgent, I think it could make sense to look into #1658 first which might help with T capacity utilization.

**Comment by kyriediculous** [comment]
> - Allowing a T to receive work from Os in different regions which might make sense if the T is located in between those regions

Unless we want to split the `serviceURI` from the orchestrator's HTTP Address the transcoder connects to on the node itself this will still require a reverse proxy to avoid registering multiple O's on-chain, in which case a webhook seems superfluous ?

> - Allowing a T to participate in multiple transcoder pools to minimize lock-in following the lead of crypto PoW mining where miners can participate in multiple pools simultaneously. I acknowledge that this is a forward looking benefit though and has less short term relevance due to the limited # of public transcoder pools in production today

This seems mostly relevant in the case of pools ran by several distinguishable entities and the webhook would have then to be ran by the transcoder itself which degrades UX and requires an additional service. So here the better solution I think, would be to have a comma-separated flag and allow this value to be changed through the livepeer CLI (`-orchAddr`).

 I'd like to assess what our goals are, from my perspective these are:

**GOAL 1**
- Improve utilisation of transcoder capacity within a private transcoder pool operated by Livepeer Inc

**GOAL 2**
- Improve reliability of an O-T split setup in the context of a private pool operated by Livepeer Inc

**EXTRA**
(these goals are only applicable if a multi-O setup is deemed to be the best solution)
- Improve transcoder UX 
   - Avoid restarts to add orchestrators to connect to 
      \*  here the question arises whether this should be for O-nodes or different "service providers" as a broader term, e.g. different pools that could be backed by multiple O nodes behind a reverse proxy each. 
   - Only require transcoder to be aware of a single URI for O's run by the same entity 

Looking at these goals the priority seems to be indeed #1658 and potential other improvements and any form of webhook or reverse proxy only comes way down the line if it is still deemed necessary when Goal 1 & 2 are not met by other solutions in which case "EXTRA" would become a requirement.
