### ISSUE TITLE
Orchestrator ignores -gasPrice flag when calling reward

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1659]
## Describe the bug

When running with `-gasPrice` flag set, the O will ignore the preset `-gasPrice` and use a gas price from gas oracle, in the instance that the transaction doesn't confirm `within defined time window`.

This means that in some circumstances, an O is unable to control the gas price used.

## To Reproduce

Steps to reproduce the behaviour:

1. Run O with `-gasPrice` configured to use a preset gas price of 16 gwei.
2. Observe O calling `rewardWithHint` using gas price of 16 gwei.
3. Observe O reporting `Reward tx did not confirm within defined time window - will try to replace pending tx next time`
4. Observe O reporting `Error trying to call reward: context deadline exceeded`
5. **UNEXPECTED BEHAVIOUR**: Observe O calling `rewardWithHint` using gas price of 45 gwei (the prevailing rate from gas price oracle), and transaction being confirmed.

6. On top of this, the O appeared to also call `reward` as a `Replacement transaction`, using gas price of 45 gwei (which presumably failed due to the transaction in step 5 being successful?).

## Expected behavior

I expect that when the `-gasPrice` flag is used to preset a gas price for the O, that it will use that preset gas price, and will never use an alternative setting from e.g. a gas price Oracle, for calling any transactions.

Further, if a replacement `reward` transaction needs to be sent because `Reward tx did not confirm within defined time window`, it should also be sent with the preset `gasPrice` setting.

## Environment
```
Livepeer Node Version: 0.5.12
Golang runtime version: gc go1.13.4
Architecture: amd64
Operating system: linux
```
## Additional context

I wonder also, whether there are other occasions when the O will ignore the `-gasPrice` flag, and submit transactions with higher settings, such as with registering first time as a T, redeeming winning tickets, and other scenarios.

**Comment by kyriediculous** [comment]
This is actually expected behaviour. The transaction didn't confirm within the required timeout window (10 minutes) so it was resubmitted using a higher gas price to not block the transaction queue for other transactions such as redeeming winning tickets. 

The replacement transaction is essentially similar to what happens when you 'speed up' a transaction in metamask. A transaction with the same calldata and nonce gets submitted, but a higher gasprice which replaces the existing transaction in the mempool. 

https://github.com/livepeer/go-livepeer/blob/e69e95cb11a9d9a334c2d12402e570f91b631e21/cmd/livepeer/livepeer.go#L48

https://github.com/livepeer/go-livepeer/blob/e69e95cb11a9d9a334c2d12402e570f91b631e21/eth/eventservices/rewardservice.go#L132

Calling reward with a very low gas price at the beginning of the round and only bumping it up towards the and of a round is a possible strategy but not one we currently support as it also affects other node operations and will only be a good strategy if calling reward is the only thing the node should do. 

Closing the issue currently as this is intended behaviour, but happy to discuss it further such as making that 10 minute window a configurable parameter rather than a hardcoded one.

**Comment by chrishobcroft** [comment]
This is not the behaviour I would expect when running the node like this, and I think it results in a terrible user experience.

If I set the -gasPrice flag when launching the node, I would personally expect that this is the gas price that gets used throughout, and am baffled as to why any other gas price gets used.

Right now, the logic deceives the Orchestrator operator into thinking that they have control over the gas price used, when this is only true in a limited nner of cases.

We wonder why we aren't successfully building more supply side to our transcoding marketplace, and with UX like this, frankly I'm unsurprised.

The explanation from @kyriediculous essentially says "yes, that's what the code currently does, and that's what we think is the right thing for it to do" and it's what is "intended" by the developers.

I am aware that this is just like a "speed up this transaction" in MetaMask, but the difference is that the process there is manually controlled, not automatically controlled by a piece of software which is essentially out of the control of the operator.

This thing about "but a higher gasprice" goes directly against the instruction that the operator has given the node to set a fixed gasPrice.

My assertion is that what the code currently does is really really illogical, confusing and off-putting and ought to change.

**Comment by kyriediculous** [comment]
I think there's two separate discussions here. To clarify by "intended" I meant the gas price you set manually is not being ignored, the code is working as intended and its first trying to submit a transaction with the gasprice set by the user and only speeding up after that gasprice is deemed too low (no confirmation within a certain timeframe). From that perspective the reported behaviour is not a bug. 

Whether that the current behaviour of the code is right or wrong is a different discussion. 

The strategy implemented currently is one that fits a scenario whereby other crucial ethereum transactions need to take place within an acceptable timeframe such as redeeming winning tickets. If a reward transaction would sit confirming for a lengthy amount of time the node could lose out on both a reward call and a ticket redemption which would be bad. The reward transaction could be pending for days and so will subsequent calls if it wasn't sped up.

Therefore I deem the current implemented strategy to be an acceptable one for nodes that require both reward calls and winning ticket redemptions. It's unlikely however that it fits all use cases or everyones desire. There is no omnipotent strategy here in terms of optimal node operations and perfect UX. Let's assume the `-gasPrice` flag disabled replacement transactions , if the user didn't set a responsible gas price to begin with, transactions have to be manually priced up which would also be poor UX. 

Each strategy will come with its own UX deteriorations and its unlikely we can satisfy everyone. From a perspective of the Livepeer node software however I think we should go with whatever allows the most optimal node operations under all conditions.  

As I mentioned earlier a middle ground here could be to have the transaction timeout be configurable. Alternatively automatic reward calls on the node can be disabled and the user is free to implement his or her own automatic reward service with a different strategy or execute on a manual strategy.  The node software is also open source so one could easily alter the param and build from source.

**Comment by chrishobcroft** [comment]
> From that perspective the reported behaviour is not a bug.

For me (and for Wikipedia), a bug is something which produces "an incorrect or unexpected result, or to behave in unintended ways." For me, this is clearly a bug... as a user, it produced an unexpected result for me... and I also strongly believe that the intended behaviour is symptomatic of a mindset which is detrimental to successfully growing an open and permissionless network.

> Whether that the current behaviour of the code is right or wrong is a different discussion.

I would rather have control over what the software that I'm running does, in ways mentioned in the issue, instead of it automating itself in unexpected ways.

If I _do not choose to preset a gas price_, I am very happy for it to a) use a gas price Oracle, and b) go above the preset to "speed up" the transaction.

But if I _do preset a gas price_, I don't expect a) or b), instead I expect to have to retain some manual oversight, and not for the software to decide to spend more of my money than I'm willing to spend, and in some cases, more than I'm receiving in rewards.

Like, imagine if the software chose to automatically override another setting passed in as a flag... like reducing an O's preset `pricePerUnit` in certain circumstances. It would be mental.

> From a perspective of the Livepeer node software however I think we should go with whatever allows the most optimal node operations under all conditions.

I like how these higher gas prices makes higher-staked Orchestrators feel at least some of the pain that new Orchestrators feel when starting from scratch with small amounts of stake.

Imagine you're a newbie O, and you see a) the estimated number of units of gas to call reward, and b) the LPT the reward will mint... and you do the math's and set `-gasPrice` so that you won't lose money, and then the O ignores you, spends all your ETH, and your initial experience of Livepeer is a bad and costly one. You will shut down your O, destroy the OS and go find another use for your GPU.

I suppose you can argue that a new user can just set reward=false and do the rest manually, but if they ever try to migrate to having the node do it automatically, they're going to want to retain the same control over gas price... and as it stands, they will end up with the same costly experience described in the previous paragraph.

I guess you could argue that they should read the code (or even change it)... but now I think you'd be expecting too much from Operations folks running tin in data centres.

I guess you could also argue that Livepeer needs a more sophisticated Operations person to operate an O, who perhaps _does_ read the code, but I expect they have many many options for what to do with their GPUs, and might even be writing their own protocols.

> As I mentioned earlier a middle ground here could be to have the transaction timeout be configurable.

I would be inclined to say that we should remove the `-gasPrice` flag as an option, as I expect that the software also overrides it for any other transaction-type called (right or wrong?) and therefore **fails to be useful in the only situation it would ever be used.**

**Comment by yondonfu** [comment]
Hey @chrishobcroft thanks for the report. 

I agree that the current behavior where replacement transactions can use a gas price that exceeds the value specified by a user via the `-gasPrice` flag is unexpected and unintuitive for users. I also agree that a user should ideally have control over how much they spend in ETH transaction fees. Re-opening the issue because even if the reported behavior matches the currently implemented `-gasPrice` flag behavior, since this is unexpected behavior for a user I think its worthwhile to understand if there are tweaks that can be made to remedy this.

A few thoughts on how the current behavior could be improved upon:
- Allow the user to specify a *maximum* gas price to use for ETH transactions
- The gas price for all transactions even if they are replacement transactions will never exceed the maximum gas price set by a user
- The `-gasPrice` flag could be aliased to a new `-maxGasPrice` flag
    - Could consider keeping the existing `-gasPrice` flag functionality to set the exact gas price used by transactions, but I'm not sure how useful that would be in practice since gas prices fluctuate so in most cases it feels like setting the maximum gas price is more useful
- The `-maxGasPrice` flag could accept a numerical value. It could also optionally accept a float which indicates the maximum gas price as a percentage of the current gas price oracle estimate. Not sure about the best format to express this yet - if it turns out to be too clunky could consider a separate flag if the maximum gas price should be expressed in terms of the gas price oracle estimate.

**Comment by kyriediculous** [comment]
After reflecting on this some more there are indeed a couple of UX problems with the current working of the `gasPrice` flag not exclusive to the one discussed here. 

I created https://github.com/livepeer/go-livepeer/issues/1671 to track the UX problem of this flag along with @yondonfu 's suggestion of aliasing it to `-maxGasPrice` and altering some of the behaviour where its usage is critical. 

Is everyone okay with continuing the discussion there?

**Comment by chrishobcroft** [comment]
Closing, track progress in https://github.com/livepeer/go-livepeer/issues/1671
