### ISSUE TITLE
Remote Transcoder hangs after EOF

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1762]
**Describe the bug**
When a _remote_ transcoder node runs into an `io.EOF` error it will briefly close its connection to the server after it finishes all running transcodes and reconnect to the server. Usually in a gRPC streaming context this error indicates an issue with sending or receiving messages on the stream. 

Sometimes however the transcoder will be stuck in a normally transient state, waiting for running transcode sessions to complete. This means the node will _not_ automatically reconnect to the orchestrator and has to be manually restarted. 

https://github.com/livepeer/go-livepeer/blob/f47f99ccd799510238966799742dc2c02c2e42f6/server/ot_rpc.go#L120

While originally the idea was that this issue could be related due to stuck transcode sessions, it still persists using the go 0.5.14 release. However if there are other root causes of stuck sessions then this problem might still persist. Alternatively the connection to the server is never closed after an `io.EOF` error , this should perhaps be done as well. 

**To Reproduce**
1. Run an orchestrator on mainnet
2. Run a transcoder in split mode 
3. Wait for EOF errors and observe the node being stuck, the transcoder itself will be responding with `no transcoders available` when this occurs.

**Comment by yondonfu** [comment]
Related: #1750 is a known bug in the LoadBalancingTranscoder (used by default when the `-transcoder` and `-nvidia` flags are used) that can cause stuck transcodes. We can try to reproduce this issue before and after the inclusion of a fix for that bug to confirm that at the very least that this issue does not arise under the circumstances for that bug.

An observation regarding this issue is that the impact of stuck transcodes in a split O/T setup is worse than in a combined OT setup right now because the standalone T that gets stuck will stop receiving all segments from the O. As a result, if the standalone T is the only T used by O, O will have no transcoders available for any additional segments for as long as the T is stuck. Meanwhile, in a combined OT setup, while an individual orchestrator session may get stuck due to a stuck transcode prompting a B to move on from the O, the O still has an opportunity to receive segments from other Bs (or the same previous B if it re-adds the O to its working set) to transcode using other orchestrator sessions.
