### ISSUE TITLE
Build from Source docs failing

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1820]
**Describe the bug**

When following the build from source docs at livepeer.org/docs, the process as published fails to build a binary.

**To Reproduce**

1. Build a clean `Ubuntu 18.04` server and `ssh` into it
2. Run the following commands, per the new ["Build from source" docs](https://livepeer.org/docs/installation/install-livepeer#build-from-source):
```
sudo apt-get update && sudo apt-get -y install build-essential pkg-config autoconf gnutls-dev git curl
sudo apt-get -y install clang-8 clang-tools-8
```
3. Follow the official [Go installation instructions](https://golang.org/doc/install):
```
wget https://golang.org/dl/go1.16.2.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.16.2.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
go version
```
4. Then continue:
```
git clone https://github.com/livepeer/go-livepeer.git
cd go-livepeer
./install_ffmpeg.sh
export PATH=$PATH:/usr/local/go/bin
export PKG_CONFIG_PATH=~/compiled/lib/pkgconfig
export HIGHEST_CHAIN_TAG=mainnet
make
```
5. Observe that the process fails with:
```
go: downloading github.com/jackpal/go-nat-pmp v1.0.1
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.

Makefile:29: recipe for target 'livepeer' failed
make: *** [livepeer] Error 2
```

**Expected behavior**

I expect that the build would not fail.

**Desktop (please complete the following information):**
 - OS: `Ubuntu 18.04`
 - Chipset: `amd64` VPS

**Additional context**

If you downgrade the version of `go` to `1.15.5`, it also fails, but with a different error:
```
GO111MODULE=on CGO_LDFLAGS="" go build -tags "mainnet" -ldflags="-X github.com/livepeer/go-livepeer/core.LivepeerVersion=0.5.16" cmd/livepeer/*.go
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
Makefile:29: recipe for target 'livepeer' failed
make: *** [livepeer] Error 1
```

**Comment by kyriediculous** [comment]
This is apparently caused by memory exhaustion on the machine and is unrelated to go-livepeer 

Code 9 equals SIGKILL (Signal Killed) which happens when not enough RAM + SWAP is available for the process to complete. 

https://blog.inventic.eu/2012/07/linux-c-linker-ld-terminated-with-signal-9/#:~:text=The%20linker%20error%20%E2%80%9Cld%20terminated,by%20increasing%20swap%20file%20size.

Are you trying this on a very resource constrained box ?

**Comment by chrishobcroft** [comment]
I was using a VPS with 512Mb, largely to test whether this would build on something so resource-constrained.

In the end it worked after I added 1G of swap.

Should we add something about minimum resource requirements to the build doc, or close this?

**Comment by kyriediculous** [comment]
There is a section in the docs that talks about minimum hardware requirements to run a node https://livepeer.org/docs/video-miners/reference/hardware

Since compiling takes more resources than running these can also count as the absolute minimum resources to build from source. 

Some things are still left open though. The worst box I run Livepeer on still has 4GB of RAM.

**Comment by kyriediculous** [comment]
Since the issue itself is fixed by adding more swap (a solution is available), there is a section in the docs (that needs to be elaborated on , admittedly) and the fact that I think there's little we can do about it from our end I think we can close the issue unless you have strong objections.

**Comment by chrishobcroft** [comment]
Closing, thanks.
