### ISSUE TITLE
Missing ETH client check for maxGasPrice handler: Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dennisgeerts** [livepeer/go-livepeer#1825]
I just started discovering livepeer and i've received the following error in my terminal.

I'm not really aware of the steps I did to cause this issue, a simple restart of the transcoder also solved this issue. Hoping this to be perhaps useful!

(I did not have the time to copy-paste error since I could not scroll up anymore after I took the picture...)

**Screenshot**
![livepeer error transcoder](https://user-images.githubusercontent.com/16606214/113388820-31cc2180-938f-11eb-8827-617c7ba089fa.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by yondonfu** [comment]
Thanks for the report @dennisgeerts

Looks like the error occurred because there is a [missing check for whether Ethereum related requests are supported](https://github.com/livepeer/go-livepeer/blob/4e24711bfabc873f1be7e98cdd8599f68a6cfedd/server/webserver.go#L1145) for one of the server endpoints that was requested. This check is needed because transcoders don't connect to Ethereum so they do not support Ethereum related requests. This will be fixed.

In the meantime, would recommend not trying to connect to the transcoder with `livepeer_cli` which would try making one of these unsupported requests.

**Comment by kyriediculous** [comment]
I think another question is whether we want to expose the CLI at all when running in `transcoder` only mode. 

None of the CLI options are actually relevant and those that are (as informative endpoints) require an ETH Client. 

Furthermore there's the added UX hurdle of having the assign a separate port for each transcoder on the same machine. 

I think it might be better to keep `transcoder` mode as light-weight as possible and just allow it to transcode without requiring any CLI options.

**Comment by yondonfu** [comment]
The main reason that the CLI webserver was exposed on the transcoder in https://github.com/livepeer/go-livepeer/pull/1650 was to enable metrics reporting. Could consider exposing the `/metrics` endpoint on the existing HTTP/RPC port, but re-using that port for metrics has a bit of a smell to me. Alternatively, the endpoint could be exposed on another port altogether that is separate from the CLI webserver port - the downside there is that its yet another port to manage.

**Comment by yondonfu** [comment]
Fixed in #1930
