### ISSUE TITLE
Improve Livepool (the Livepeer transcoding pool)

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#1831]
**Gitcoin Grant PR**

**Is your feature request related to a problem? Please describe.**
There are many features that [Livepool](https://github.com/mtrivedi) can offer to improve the performance and user experience of the transcoding pool.

**Describe the solution you'd like**
- [ ] Better routing mechanisms between transcoders
- [ ] Better resource allocation algorithms
- [ ] Improved user interface for joining the transcoding pool

Interested developer should have deep experience in golang and distributed systems.

**Comment by yondonfu** [comment]
While the motivation here may be to specifically improve Livepool, since Livepool leverages the split orchestrator and transcoder code in go-livepeer, I think it would be great to focus on the split orchestrator and transcoder code improvements in go-livepeer that would benefit not only Livepool, but anyone using that type of setup.

Some existing issues in this area:

- https://github.com/livepeer/go-livepeer/issues/1762
- https://github.com/livepeer/go-livepeer/issues/1712 and https://github.com/livepeer/go-livepeer/issues/1273 (they are related)

**Comment by yondonfu** [comment]
The issues mentioned in the above comment have all been addressed + closed so closing this issue.
