### ISSUE TITLE
Failed gas estimation with revert for txs when another tx affecting the same state is pending

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1906]
# Background

A few orchestrators have reported gas estimation failing for reward txs with the confusing error message of:

```
failed to estimate gas needed: execution reverted: caller has already called reward for the current round
```

This error message is confusing because in these cases reward txs for these orchestrators had not yet been mined in the current round. This error message was observed when the node tried to automatically submit reward txs and when `livepeer_cli` was used to manually submit a reward tx. 

In one case, the operator was able to solve this problem by restarting the orchestrator with a different ETH provider (i.e. switched from a cluster of geth nodes to Infura). After the reward tx was mined, the operator observed a sequence of failed txs:

1. [Successful reward tx](https://etherscan.io/tx/0xdd9ea3c395af5cc174f2cbf124a66ef7bb00e742f0bdfe5cc638ad2b0193710c)
2. [Reverted reward tx](https://etherscan.io/tx/0xcfbc7664378b5726402944f49283dedabbd6798bbf5ec0fe7d782cbc93e0d83f)

The orchestrator had also previously attempted to submit transcoder txs (omitted from the above list, but can be found on the account's Etherscan page), but the node timed out waiting for each of the txs to be mined. The failed tx sequence and the node timing out waiting for some of the txs in the sequence leads me to the believe that the problem was that a bunch of txs were stuck pending which resulted in a few additional problems one of them being failed gas estimation with a revert. I'll focus on this problem in this issue.

The reward tx submitted by the orchestrator while another reward tx was pending resulted in a failed gas estimation with a revert because the node currently uses [EstimateGas](https://github.com/ethereum/go-ethereum/blob/0e9c7d564d6000a372cd3df914ec6c969aea29f2/ethclient/ethclient.go#L505) which calls the `eth_estimateGas` RPC method under the hood without a specified block number. When `eth_estimateGas` is called without a specific block number, it will by default by run against the current ["pending" block](https://github.com/ethereum/go-ethereum/blob/5cff9754d795971451f2f4e8a2cc0c6f51ce9802/internal/ethapi/api.go#L1040). I believe this means that a pending reward tx from the orchestrator would be applied to state such that when gas estimation is invoked for the new reward tx it will execute against state that was already updated by the pending reward tx. As a result, the new reward tx would revert during gas estimation since the updated state reflects that reward was already called in the current round.

This problem will typically arise if an initial reward tx (or any tx for that matter) is submitted with a low gas price such it gets stuck in the pending state. Previously, this would only happen if the required gas price for a tx to be mined in a timely manner spiked up right after a tx was submitted. However, lately, the `eth_gasPrice` RPC call can return extremely low gas prices (lower than what is actually required) depending on the ETH node/provider as a result of an uptick of 0/1 wei gas price MEV txs being mined. geth updated its gas price oracle implementation to stabilize values returned by `eth_gasPrice` in [v1.10.3](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.3), but orchestrator operators may be slow to upgrade and ETH providers running geth might still be using an older version - for example, [Infura is still on v.1.10.2](https://forkmon.ethdevops.io/). While #1860 improved the stability of the gas price monitor in the livepeer node, it is still possible for an [extremely low gas price to be attached to a tx at submission time](https://github.com/ethereum/go-ethereum/blob/0e9c7d564d6000a372cd3df914ec6c969aea29f2/accounts/abi/bind/base.go#L229).

# Possible Solutions

#1841 could help by giving a livepeer node access to a more robust gas price service.

I think support for tx retries with gas price bumping for all txs (we currently have a more limited version implemented just for reward txs) would also help here assuming that the implementation includes:

- A max # of retries
- A time interval between retries
- A strategy to bump the previous gas price by X% OR use the current fetched gas price if it is higher than the result of the former

The time interval between retries would give the livepeer node an opportunity to get a fresh gas price after a period of time - even if the `eth_gasPrice` RPC call returns extremely low gas prices sometimes it is less likely to consistently return extremely low gas prices. The gas price setting strategy ensures that if the fresh gas price is more reasonable than the previous extremely low gas price then it will be used.

Given that recent versions of geth help with this problem when still using the `eth_gasPrice` RPC call to fetch gas prices (so its a matter of orchestrator operators upgrading their geth or ETH providers upgrading their geth), I'm a bit more interested in exploring the tx retries solution first as that will also be generally useful outside of addressing this problem.

**Comment by yondonfu** [comment]
@kyriediculous also suggested using the gas price monitor as the source of all gas price estimates for transactions instead of relying on the `eth_gasPrice` RPC call at transaction submission time which might help because the gas price monitor can do some additional filtering/calculations based on gas prices fetched from the ETH provider.

**Comment by dpurhar27** [comment]
I second @kyriediculous suggestion. 

Our Orchestrator was running into this issue (below) as well so I dug through the Livepeer client the other day and came to a few conclusions. 
I may have missed something in my trace of the client so please let me know if that's the case. Note, some of my own findings are very redundant to this thread at this point. Including anyway as a third-party's attestation.

```
failed to estimate gas needed: execution reverted: caller has already called reward for the current round
```

## Overview

### Steps

1. The Livepeer client sends a txn (in our case `rewardWithHint()`) with a very low gas price which won't get mined in a reasonable amount of time. This is a different issue in the Livepeer client caused by the dependency on the Ethereum client's response when asked to suggest gas prices, related to the evolving ecosystem of MEV/Flashbots zero gas price txns. Will omit code trace that shows Livepeer client's reliance on the ETH client for gas prices.

2. The Livepeer client detects it hasn't "claimed" rewards for the existing round, and tries to resubmit a `rewardWithHint()` . It tries to estimate the gas limit to use, which will simulate the txn against the state of the chain. It throws this error and kills the flow:

```
Error trying to call reward err=failed to estimate gas needed: execution reverted: caller has already called reward for the current round
```

When using [`estimateGas()`](https://github.com/ethereum/go-ethereum/blob/0e9c7d564d6000a372cd3df914ec6c969aea29f2/accounts/abi/bind/base.go#L245) , the Livepeer client doesn't specify the nonce or block number to use, which is the root of the error.

`estimateGas()` will assume the nonce we want to use is incrementing on existing broadcasted txn's, and therefore will simulate this new txn in the context of execution after the previously broadcasted transaction `rewardWithHint()` - which we wanted to replace since it's too slow.

This is why it throws the error `caller has already called reward for the current round`, since in context of the state execution behind the previously broadcast txn, the Orchestrator has. In reality, that txn will never get mined, and the Livepeer client is stuck in the failing loop.

## Solutions

These solutions are not mutually exclusive. The first two focus on the usage of unrealistic gas prices, the third focuses on the root issue with the simulation error.

### 1. Push Orchestrators to update their ETH clients
---
As previously mentioned, the initial cause of the simulation error is to do with the gas price source, which defaults to what the ETH client suggests [here](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/base.go#L229), as the Livepeer client leaves the relevant value in the `TransactOpts` struct `nil`. 

The Geth client specifically had a [fix](https://github.com/ethereum/go-ethereum/pull/22722) for returning unrealistically low gas prices in it's latest version [Geth 1.10.3](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.3), published May 5th. Note, I haven't looked closely at the implementation of the Geth fix, so I can't speak on how sound of a solution it is. 

This would help avoid broadcasting any txns from the Livepeer client at extremely low gas prices. As @yondonfu mentioned, the business context comes into play here, and not all Orchestrators can be expected to make this upgrade.

_Pros_
- Helps solve the underlying issue of using low gas prices
- Upgrade to the latest (read: better performant) and relatively stable ETH client

_Cons_
- Unlikely all client operators have the resources to ugprade

### 2. Enhance usage of  `GasPriceMonitor`
---
Part of my initial confusion was the Livepeer client version `0.5.18` release notes including the below snippet, which implied a fix for the low gas price issues.

> This release includes an important gas price monitoring fix that addresses cases where Ethereum JSON-RPC providers occasionally return really low gas prices for the `eth_gasPrice` RPC call

An aside, it may make sense to re-word this ^. There's a disconnect between the release notes and the relevant PR #1860 .

The `GasPriceMonitor` module does have a filtered value for `gasPrice` exposed with [`GasPrice()`](https://github.com/livepeer/go-livepeer/blob/48409dfcfe988a02f5166d64db2834b4dea4b6f0/eth/gaspricemonitor.go#L58). However, it's currently only used within context of calculating [`txCost()`](https://github.com/livepeer/go-livepeer/blob/8e5df3b95ffd6e4c63d12b3a0999617395b893d4/pm/recipient.go#L221), which is used in calculating the face value of a ticket. Note, `txCost()` doesn't return the gas price value so where it's used is irrelevant in this context.

This module seems to be created to handle all operations related to gas price and already exposes a filtered version of `gasPrice` so it seems natural to leverage it when forming txn objects within the Livepeer client.

I was originally going to suggest the following change in [`createTransactOpts()`](https://github.com/livepeer/go-livepeer/blob/d3dcd112ad0518fdfe215555fd60850318bc67ff/eth/accountmanager.go#L122):

```
return &bind.TransactOpts{
	From:     am.account.Address,
	GasLimit: gasLimit,
	GasPrice: gasPrice,
	Signer: func(signer types.Signer, address ethcommon.Address, tx *types.Transaction) (*types.Transaction, error) {			
	 	if address != am.account.Address {
	 		return nil, errors.New("not authorized to sign this account")
	 	}
		return am.SignTx(tx)
	},	
}, nil
```

However, realized this is only done once [upon setup](https://github.com/livepeer/go-livepeer/blob/52c797a09ce5a51dce49d1b933b54745713bec10/cmd/livepeer/livepeer.go#L399), and since `gasPrice` is not to hold constant value it can't be done at this point. During my perusal, I didn't spot an existing generic module in the codebase where txns are modified, in which we could easily add `&opts.GasPrice = gpm.GasPrice()`. 
I'll revert to somebody with more knowledge of the codebase to suggest a good location to insert this logic.

In this case, the `gasPrice` used is specifically filtered as such below:

- Throws out values below `minGasPrice` when trying to update `gpm.gasPrice` [here](https://github.com/livepeer/go-livepeer/blob/48409dfcfe988a02f5166d64db2834b4dea4b6f0/eth/gaspricemonitor.go#L134)
- Throws out values above `maxGasPrice` when requesting the `gasPrice` to use from the ETH client [here](https://github.com/livepeer/go-livepeer/blob/4e24711bfabc873f1be7e98cdd8599f68a6cfedd/eth/backend.go#L115)

_Pros_
- Leverages existing architecture in the Livepeer client
- Reduces dependency on third-party sources as a gas oracle
- Leaves the runway open for future gas management enhancements as easy add-ons

_Cons_
- Still uses the ETH client as the root source of gas prices
- Will take simple, but extensive code change to insert new pattern of modifying txn details (beyond the `data` field) in-flight to the ETH client - may be missing an easy way to insert this due to unfamiliarity with codebase so may not be much of a con

### 3. Specify the gas limit to use
---
The initial error is bubbled up by the ETH client (Geth in this case). As mentioned above, it attempts to `estimateGas()` against the incorrect state. 

Unfortunately, Geth doesn't alllow specification of the nonce or block number to use when it attempt to estimate gas in its arguments [here](https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/ethclient/ethclient.go#L511), which are formatted via [`callArg(...)`](https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/ethclient/ethclient.go#L530) which doesn't include either field.

This means the Livepeer client needs to specify the `gasLimit` to use in `TransactOpts` that are passed to the ETH client. This will stop the ETH client from attempting to estimate the gas on it's end, with this [code](https://github.com/ethereum/go-ethereum/blob/0e9c7d564d6000a372cd3df914ec6c969aea29f2/accounts/abi/bind/base.go#L235), which will attempt to simulate the txn if the passed `gasLimit` is zero. 

In the same vein as the above solution, the Livepeer client needs to have a new module which allows modifications to `TransactOpts` dynamically in-flight right before being broadcast. Again, this type of module may already exist in the control flow and I missed it.

This type of module would enable dynamically and accurately estimating and setting the `GasLimit` and `GasPrice` fields.

Note, for a quicker solution, we can simply hardcode or only estimate an appropriate `GasLimit` to use for the `rewardWithHint()`, etc. - functions which are susceptible to failing state if executed with the same arguments one after another. I don't have enough context of Livepeer client functionality to provide an exhaustive list.

_Pros_
- Addresses the specific issue at hand
- Avoids repeating this same error in the future against other functionality - maybe where it's not caused by low gas prices, etc.
- Removes dependency from the ETH client being referenced

_Cons_
- Not a necessary change to address the overall issue causing the error at hand

## Conclusion

Overall, I agree with the assessment from @yondonfu and have a few details to add. There's a couple different inclusive solutions on-hand. I don't have enough familiarity with the codebase to suggest the best place to inject some of these solutions, so will wait for others input. 

I'm going to open a few different issues/features to absolve this one large comment, and organize things a bit better.

**Comment by dpurhar27** [comment]
Note, another gas estimation failure in a false-positive case upon `redeemWinningTicket(...)`. 

```
Error redeeming err=failed to estimate gas needed: execution reverted: ticket is used
```

Same root cause - very low gas price (1 or sub-1 Gwei) causes the first txn to hang, a re-broadcast is attempted but gas estimation is delegated to Geth and it simulates the ticket redemption in the state context behind the existing pending txn which is using the same ticket. Hence the error `ticket is used`.

These issues are a strong voice to move the estimate gas functionality to within the Livepeer client, and have the flexibility around custom blocknumbers for simulations, etc.

I'm not opening a separate issue as the root cause is the same, #1915 should resolve this specific case. It may make sense to rename this ticket to a generic title instead of applying specifically to reward txns.

**Comment by yondonfu** [comment]
@dpurhar27 Thanks for writing up such a thorough breakdown of the possible solutions for this issue!

Re: solution 3 

I suspect that the geth ethclient package (which livepeer uses under the hood to send RPC calls to an ETH node/provider) could be updated to support passing a block number to an eth_estimateGas call since eth_estimateGas accepts the same parameters as an eth_call by adding a block number argument to the [EstimateGas](https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/ethclient/ethclient.go#L509) method similar to what is done for the [CallContract](https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/ethclient/ethclient.go#L475) method. That being said, I think calling eth_estimateGas with the pending block number is *usually* desirable and is only undesirable for this particular issue. So, I'm currently not inclined to rely on this.

The latest thinking for addressing this problem is:

- Implement solution 2 which will use the GasPriceMonitor package to help with gas price filtering. There is a [draft PR](https://github.com/livepeer/go-livepeer/pull/1915) out for this.
- Implement a transaction retry mechanism that can be used for all transactions so pending txs can have their gas prices bumped to more reasonable levels such that they are mined in a timely manner [1].

[1] The node already supports a single retry for reward txs, but this feature would enable N retries for any txs (including redeemWinningTicket txs) where N would default to some reasonable value (i.e. 2-3).

> It may make sense to rename this ticket to a generic title instead of applying specifically to reward txns.

I've updated the title of this issue to reflect that gas estimation can fail for a tx whenever there is another pending tx that affects the same state (i.e. reward and redeemWinningTicket txs).
