### ISSUE TITLE
Design and implement better load balancing for Detection models

### ISSUE THREAD

**Issue by jailuthra** [livepeer/go-livepeer#1981]
**Is your feature request related to a problem? Please describe.**
After #1979:
1. We load a new Detection filter at the start of a new stream - leading to an extra `0.5s` latency for the first segment. This wasn't the case before as we used to share the same TensorFlow model graph across transcode sessions, albeit in a non-thread-safe manner.
2. We use a globally defined scene classification model (for adult+soccer streams) at the node-level, so loading a different classifier model on the same node is not currently supported.
3. We hardcode the Detection filter to always run on GPU device 0 due to https://github.com/livepeer/go-livepeer/issues/1980

**Describe the solution you'd like**

**TODO:** Spec out a load-balancing solution to pre-load a configurable number (`minPreloadedModels`) of models per node, that can be used to fix (1) i.e. cut down the extra latency at the start of a new stream session. Also attempt to fix (2) and (3) with the new design, if feasible.

**Additional context**
The new LPMS API introduced in https://github.com/livepeer/lpms/pull/246#issuecomment-891131495 allows us to pre-load the Detection filters, and then use it when the first-segment of a session comes in, attaching it to the rest of the filtergraph.

It should also theoretically be able to load multiple models on multiple devices under the same process, but that is untested right now.

**Comment by yondonfu** [comment]
Before jumping into this we want to determine if it can be concurrency safe to just use the same model in shared GPU mem which would obviate the need for this load balancing design. See https://github.com/livepeer/lpms/issues/257.

**Comment by cyberj0g** [comment]
Detection model and TF runtime are loaded per-device in the same process with the latest version. Additional "warm up" Transcoder is created before transcoding for each device. The overhead for this warmup is about 150 Mb VRAM. Still, first session on device is ~0.3 sec slower than consequent session. This delay is caused by encoder and present even when detector is disabled. It seems that warm up is not complete without actually transcoding some frames.
On load balancing, I think proper implementation should use inference server, as explored [here](https://github.com/livepeer/FFmpeg/issues/15).

**Comment by yondonfu** [comment]
Thanks for the update @cyberj0g 

> This delay is caused by encoder and present even when detector is disabled. It seems that warm up is not complete without actually transcoding some frames.

Yeah this is known behavior - we've observed additional overhead for creating an NVENC session for the first time.

Agree that if we end up using an inference server, can look into better ways to load balance specifically for detection purposes.

Since we no longer have additional latency as of #2038 as long as we pre-load the model by creating a session for each GPU on startup I don't think the solution suggested in the OP of pre-loading a configurable number of sessions is necessary. I'll close this issue for now, but feel free to re-open if there is anything that needs to be followed up on.
