### ISSUE TITLE
Configure verification-enabled streams

### ISSUE THREAD

**Issue by jailuthra** [livepeer/go-livepeer#1993]
- Read `VerificationFreq` from auth-webhook response for a particular stream
- Read trust score for each orchestrator from orch-webhook response
- Use the capability signalling mechanism between B <> O to make sure we send verification enabled streams to Os that support generating mpeg7 signatures

Refer to steps 1, 2 and 8 in the spec #1991 for details

**Comment by yondonfu** [comment]
Re: step 8 in #1991: 

> Update the list of orchestrator capabilities to include a new Capability_PerceptualSignature capability.

I suggest we name this capability `Capability_MPEG7VideoSignature` to make it clear that this capability is not just any perceptual hash/signature, but specifically the MPEG-7 video signature. I think this is important because there are different perceptual hash algorithms so we should treat the MPEG-7 video signature as just one specific perceptual hash algorithm that can be applied to videos. In the future, we may find that we want to use a different perceptual hash algorithm and then we can add a separate capability for that specific algorithm that can be distinguished from the MPEG-7 video signature capability.

> Use the capability signalling mechanism between B <> O to make sure we send verification enabled streams to Os that support generating mpeg7 signatures

I think this feature can be broken up into the following tasks (could all be worked on by the same person or in parallel by separate people):

- Update the network protobuf messages
- Update O to use the new protobuf message definitions in order to configure MPEG-7 video signature generation during transcoding
- Update B to use the new protobuf message definitions when it is requesting MPEG-7 video signatures

**Comment by jailuthra** [comment]
> In the future, we may find that we want to use a different perceptual hash algorithm and then we can add a separate capability for that specific algorithm that can be distinguished from the MPEG-7 video signature capability

Ah good foresight! I'll make a quick edit to the original spec with this less-generic capability name.

> Update O to use the new protobuf message definitions in order to configure MPEG-7 video signature generation during transcoding

My original intent was to cover the details of B<>O protobuf communication in steps 4, 5 of the original spec, which would be implemented in the PR #1994 

But I don't see anything wrong with implementing it within a PR for this issue. Leaving the final decision on whoever starts working on these two issues (which could also be me).

**Comment by yondonfu** [comment]
Re: step 2 in #1991

> For now this trustScore is either 0 or 1 for an untrusted or trusted O respectively. Parse this trustScore for each O into the orchestratorPool struct:

WDYT about using a more generic "score" instead of "trustScore" so that the field could be used to convey additional information besides just trust? For example, if the score was calculated using a formula similar to the one for the [leaderboard tests](https://livepeer.org/docs/video-miners/reference/leaderboard#how-is-the-total-score-in-the-performance-leaderboard-calculated) then the score would convey historic performance based on external data. Relevant to the response format definition that will be used in https://github.com/livepeer/livepeer-com/issues/576.

**Comment by jailuthra** [comment]
> WDYT about using a more generic "score" instead of "trustScore" so that the field could be used to convey additional information besides just trust?

Sounds good to me :+1:

**Comment by yondonfu** [comment]
Closed by #2045
