### ISSUE TITLE
Generate and save mpeg7 signatures during transcoding

### ISSUE THREAD

**Issue by jailuthra** [livepeer/go-livepeer#1995]
Refer to step 5 in the fast verification spec #1991 for details

**Comment by yondonfu** [comment]
> Upload transcoded segments and their signatures to the object store:

Are the MPEG-7 signatures also included in the protobuf message returned to B?

**Comment by jailuthra** [comment]
> Are the MPEG-7 signatures also included in the protobuf message returned to B?

Ah this was slightly hand-waved in the spec - but after storing the signatures to the object store, the orchestrator will include the signature URLs in the `net.TranscodeResult` protobuf message. The B can download the signature for whichever rendition it chooses to compare, similar to how it downloads encoded segments.

An alternative is to directly include the signature binary data within the protobuf message. This approach would be easier to implement as the O won't need to save signatures to the object store. But a drawback here is that the B will have to download signatures for all renditions during the blocking HTTP response of the `POST /segment` request. The signatures are a few extra KBs and the B doesn't really need to compare all renditions.

I'm leaning towards the former approach - but if the signature data is trivial to download in the blocking HTTP request, then makes sense to go with the latter.

**Comment by yondonfu** [comment]
Good point about the size of sigs when considering whether to include them in a protobuf message since protobuf [does not handle large data sets](https://developers.google.com/protocol-buffers/docs/techniques#large-data) very well. While we'll likely still be in the KB range as opposed to the MB range with the sigs, it does feel like it would be more appropriate to keep them out of the protobuf messages.

**Comment by yondonfu** [comment]
Closed by #2007
