### ISSUE TITLE
Multi GPU support for scene classification

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1997]
**Is your feature request related to a problem? Please describe.**

At the moment, the node only supports scene classification on a single GPU even on a multi GPU machine. This is because we only setup detection on GPU 0:

- We [setup detection on GPU 0 on node startup](https://github.com/livepeer/go-livepeer/blob/67db52b72e8343986fdef0f71c15b8a87a0301ff/cmd/livepeer/livepeer.go#L285) in order to load TF deps into GPU memory to avoid doing so later on
- When create a new transcoder with detection enabled, [detection is setup on GPU 0](https://github.com/livepeer/go-livepeer/commit/c17d16e113775f0957bcaefb41a65b66dd756ea6)

The problems with only setting up detection on GPU 0 are:

- With CPU <> GPU data copying, all decompressed frames go from the CPU to GPU 0 on the same connection which might lead to more congestion on that connection given that it has a limited amount of bandwidth
- Without CPU <> GPU data copying (we eventually want to get here), there will be no way for data to get from another GPU to GPU 0 so we'll need to be able to setup detection on those other GPUs
- We're running inference for all streams on GPU 0 and not using the CUDA cores on the other GPUs for inference

**Describe the solution you'd like**

Add multi GPU support so that the node can run scene classification on any of the GPUs on a machine. Additionally, it would be preferable to have scene classification run on the same GPU that transcodes a segment because eventually when we remove CPU <> GPU data copying we'll want to do this anyway.

**Describe alternatives you've considered**

N/A

**Additional context**

I think we ran into https://github.com/livepeer/go-livepeer/issues/1980 when we tried to use multiple GPUs recently. Unclear why. We should see if that issue is a blocker for multi GPU support.

**Comment by yondonfu** [comment]
For reference:

@oscar-davids shared this [comment](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto#L147) from the TF docs that indicates virtual device configuration is per process and not per session.

**Comment by jailuthra** [comment]
Ah I think I misunderstood why the original TF issue around this was closed earlier. IIUC this means we'd need to spawn separate UNIX processes (i.e. orchestrator nodes) to use different GPUs via the `visible_devices` list.

An alternative is mentioned in this comment, where the user can specify the GPU used while creating the model: https://github.com/tensorflow/tensorflow/issues/18861#issuecomment-385610497

I believe @oscar-davids [did something similar](https://github.com/livepeer/FFmpeg/pull/1/files#diff-765b152e21f0f875b4c8cd98268e7993e53872ca2a7f241a12acc56328055bdeR243) in the original detection PR in our FFmpeg fork, which got subsequently removed in the re-design as I wanted to minimize changes in the TF backend.

Maybe we can explore that solution again, if spawning different O nodes per GPU is not feasible.

**Comment by yondonfu** [comment]
> if spawning different O nodes per GPU is not feasible.

I think we should first see if there is a solution that allows a single O to utilize multiple GPUs as running separate Os for each GPU would be a pain from a UX POV.

**Comment by oscar-davids** [comment]
Given that using different settings in different sessions within same process is not safe, 
I think setting deviceID as session config using protobuf will result in unexpected behavior.
Instead, we can do something similar as suggested [here](https://github.com/tensorflow/tensorflow/issues/18861#issuecomment-385610497) and that's what I did before 4.4 upgrade.
The C API that is equivalent to this with tf.device('/gpu:1') in python is TF_ImportGraphDefOptionsSetDefaultDevice("/gpu:1")

I used this to set deviceID and tested it on VNO machine and coreweave GPU. [Here ](https://github.com/livepeer/FFmpeg/commits/oc/multigpu)is the linked branch.
I tested 12 concurrent streams(6 streams on each GPU) and it worked reliably. However, on Coreweave, it crashed after the number of concurrent streams exceed 3 on each GPU.

The test setup are summarized below:
- VNO Server
GPU: gtx1080 x 2
CUDA version 11.1 + 11.2
driver version 11.2
Tensorflow Version: 2.5
- Coreweave
GPU: gtx 1070 x 6
CUDA version: 10.1
driver version: 11.3
Tensorflow version: 2.3


I beleive the failure on coreweave could be either due to:
- version mismatch (https://www.tensorflow.org/install/gpu)
- docker internal bug

**Comment by cyberj0g** [comment]
I have implemented per-graph GPU selection in DNN filter using suggestions above, and it seem to work fine. Do we want to add a separate set of arguments for controlling detection GPU selection to `livepeer.go`?
I see at least 2 possible modes:
* `shared` - run both transcoding and detection on the same GPU (specific GPU is picked for each Transcoder instance). Downside - it will take 2 Gb VRAM per GPU for TF runtime.
* `dedicated` - run detection on dedicated GPU (GPUs?). It will limit VRAM overhead, but such dedicated GPU may potentially become a bottleneck.

@yondonfu @jailuthra

**Comment by yondonfu** [comment]
Hm having different modes could be interesting. But, for now, I suggest implementing the shared mode first as the default without the ability to switch between modes. Since we're also researching the possibility of using different model backends that have less VRAM overhead as a part of https://github.com/livepeer/FFmpeg/issues/15 I think we can wait to consider a dedicated mode until after completing that research - the rationale being that if we eventually end up using a model backend with much lower VRAM overhead then the value of having a dedicated mode could be diminished.

**Comment by yondonfu** [comment]
Closed by #2038 livepeer/lpms#264 livepeer/ffmpeg#16
