### ISSUE TITLE
Complete first pass prototype of #1994 and #1996 to identify any blockers or design considerations

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2005]

**Comment by jailuthra** [comment]
Some design considerations:

### Populating `BroadcastSession`s with O scores

`BroadcastSessionManager` uses `GetOrchestrators(int, Suspender, CapabilityComparator) ([]*net.OrchestratorInfo, error)` to fetch a list of available orchestrators from the pool:
https://github.com/livepeer/go-livepeer/blob/67db52b72e8343986fdef0f71c15b8a87a0301ff/server/broadcast.go#L315
The data-type returned for each O is `net.OrchestratorInfo`, which is what the O returns during discovery. This info is populated inside each `BroadcastSession`:
https://github.com/livepeer/go-livepeer/blob/67db52b72e8343986fdef0f71c15b8a87a0301ff/server/rpc.go#L102-L105

For enabling verification we also want the `BroadcastSessionManager` to keep track of the `score` for each O, which signifies trust for now, but might become a more generic metric later on to [include performance](https://github.com/livepeer/go-livepeer/issues/1993#issuecomment-902885023).

Given that these `score`s are read via the orch-webhook or a local file - where should we keep the score for each O on the broadcaster? Do we re-use the `net.OrchestratorInfo` structure, or populate it directly inside `BroadcastSession`?
Former would make it easy to fetch, latter would need some changes on the B side to fetch scores separately from the `OrchestratorPool` and match each O score with the info received via `GetOrchestrators`.

cc @darkdarkdragon as this is relevant to #1993 

### Select multiple `BroadcastSession`s for verification with in-flight segment tracking

Currently the `selectSession` logic tracks the in-flight time for each segment sent, and prefers returning the last-used session if the last-segment is still in-flight and under a threshold duration. Otherwise it returns a new session from the discovered list of Os, possibly leading to an expensive swap.

For verification we have new requirements for selecting sessions:
1. Select `verificationOrchCount == 3` sessions, where at least one is trusted i.e. `sess.score == 1`.
2. Keep track of the set of sessions that were selected for last segment.
3. For every new incoming segment, decide if we want to stick to the last-used set of sessions, or re-build our set.

We will need to keep our in-flight segment logic intact along with these new requirements. Also the total number of Os we call discovery on is currently hardcoded to `2 * HTTPTimeout / SegLen == 2 * 8/2 == 8` which may be too less for the new requirement of selecting multiple sessions for each segment.

### Transcoding segments using the selected Os

The `transcodeSegment` method is currently a huge routine that handles a lot of concerns - like refreshing and selecting sessions, submitting each segment to a session, tracking in-flight time, downloading transcoded renditions and inserting renditions into playlist. With verification enabled, many of these steps will need to be run on multiple sessions, possibly via concurrent go-routines.

The `transcodeSegment` method will now also encapsulate the logic for -
1. Deciding if verification should be run on a new segment, and submitting segment to multiple sessions (see step 4 in #1991)
2. Select a rendition at random, download pHashes for the rendition from each O, and match them against the trusted O. (see step 6)
3. Pick a winning session from the verified sessions, and download all the transcoded renditions from this O to insert into the playlist. (see step 7)

IMO we should separate many of these concerns out from this main routine into subroutines, while still keeping `transcodeSegment` as the caller for each subroutine.

**Comment by darkdarkdragon** [comment]
> Do we re-use the net.OrchestratorInfo structure,

Given that `net.OrchestratorInfo` is info that O returns about himself, I don't think it is a good place to keep score. Score is information that B keeps about O, so I've made new structure for that.

> Also the total number of Os we call discovery on is currently hardcoded to 2 * HTTPTimeout / SegLen == 2 * 8/2 == 8 which may be too less for the new requirement of selecting multiple sessions for each segment.

Yes, but given that we have hard requirement of getting session with specific score (`where at least one is trusted`) - I think we should keep two separate pools of sessions. I'm thinking about moving out 'sessions list' functionality out of `BroadcastSessionsManager` to separate struct, and `BroadcastSessionsManager` will keep different pools - one for trusted Os, and one for untrusted.

> The transcodeSegment method is currently a huge routine that handles a lot of concerns -
> IMO we should separate many of these concerns out from this main routine into subroutines, while still keeping transcodeSegment as the caller for each subroutine.

Totally agree.

**Comment by jailuthra** [comment]
> Given that net.OrchestratorInfo is info that O returns about himself, I don't think it is a good place to keep score. Score is information that B keeps about O, so I've made new structure for that.

Sounds good!

> Yes, but given that we have hard requirement of getting session with specific score (where at least one is trusted) - I think we should keep two separate pools of sessions. I'm thinking about moving out 'sessions list' functionality out of BroadcastSessionsManager to separate struct, and BroadcastSessionsManager will keep different pools - one for trusted Os, and one for untrusted.

Thanks a lot for writing and posting the skeleton code around this https://github.com/livepeer/go-livepeer/commit/3cfb348c7b794fbb9b20acf5904c4470f86aea53#

Overall the idea of keeping two separate pools for untrusted/trusted Os sounds good to me.

I do think it would be nice if we restrict the the assumption that `score` is an enum which can only be `Score_Untrusted` or `Score_Trusted` to limited places in the code. This assumption conflicts with the plan of using `score`in future to contain indications of [performance](https://github.com/livepeer/go-livepeer/issues/1993#issuecomment-902885023) that we currently calculate for the public leaderboard. cc-ing @yondonfu who had the original idea.

**Comment by darkdarkdragon** [comment]
>  do think it would be nice if we restrict the the assumption that score is an enum which can only be Score_Untrusted or Score_Trusted to limited places in the code. This assumption conflicts with the plan of using scorein future to contain indications of performance that we currently calculate for the public leaderboard. cc-ing @yondonfu who had the original idea.

Yes, but with current task I need a clear separation of trusted/untrusted orchestrators. I'm trying not to change code much, so I'm just using two sessions pools for trusted/untrusted. I think moving to score as leaderboard is another complex task, so It would be better to do it separately.

**Comment by darkdarkdragon** [comment]
Given that we're moving to using multiple orchestrators for same stream, I think we can use same mechanism to do other (not just perceptual verification) tasks - for example, this could replace whole _secondary_ infrastructure - B can send stream to trusted O and to untrusted, and just discard results from untrusted one. Or use untrusted as always-on backup - send stream to trusted and untrusted, and only use untrusted results if trusted one hasn't responded in time.

**Comment by yondonfu** [comment]
Just caught up on the conversation here.

It appears that the main concern being discussed right now is whether the use of orchestrator scores to create separate trusted & untrusted orchestrator pools will be problematic if we want to use scores for other purposes in the future (i.e. use the score in the selection algorithm). I think the answer is no, but I also think it is worthwhile to clearly define the sub-systems in B that scores can be used for. See below for my attempt at summarizing the current and future sub-systems with scores as an input.

**Trusted vs. Untrusted Orchestrator Pools**

As suggested by @darkdarkdragon.

We can establish a score threshold in order to determine whether an orchestrator should be placed in the trusted or untrusted orchestrator pool. For simplicity, we can start off with a score threshold of 1.0. As a result, an orchestrator with a score of 1.0 would be placed in the trusted pool and an orchestrator with a score < 1.0 would be placed in the untrusted pool. Later on, we can consider making the score threshold a configurable parameter.

**Score Based Selection**

The broadcaster can keep track of the score of each orchestrator. At the moment, the selection algorithm will run a weighted random selection of orchestrators that are "unknown" i.e. that have not been sent a segment yet. The weight of each orchestrator is currently set to the orchestrator's stake. If the broadcaster tracks the score of each orchestrator, the weight of each orchestrator could instead of be set to the score (if the score provided by an external service already incorporates stake in its calculation) or a value computed based on the score and stake. We don't need to implement this now, but it could be useful later to incorporate more externally provided data about orchestrators on the network to allow the broadcaster to more quickly find the best orchestrators to use for each stream.

Implementing trusted vs. untrusted orchestrator pools now shouldn't prevent the possibility of implementing score based selection later and it should allow us to delay tracking scores as state on the broadcaster until we want to implement score based selection. 

WDYT? @darkdarkdragon @jailuthra

**Comment by jailuthra** [comment]
> an orchestrator with a score of 1.0 would be placed in the trusted pool and an orchestrator with a score < 1.0 would be placed in the untrusted pool.

> If the broadcaster tracks the score of each orchestrator, the weight of each orchestrator could instead of be set to the score 

Neat! I like the idea of using score 1.0 as a threshold for splitting the two pools for now, using a different threshold for the untrusted pool later, that would incorporate performance + stake in that score value.

>  I think moving to score as leaderboard is another complex task, so It would be better to do it separately.

>  We don't need to implement this now, but it could be useful later to incorporate more externally provided data about orchestrators on the network to allow the broadcaster to more quickly find the best orchestrators to use for each stream.

Makes sense!

I think this places us in a solid position - design wise speaking - so I'll close this issue and track the actual implementation work around this in #1994 and #1996. Feel free to re-open the issue if something changes and needs discussion!

And I believe @darkdarkdragon is planning to incorporate some of the in-progress changes around this within a PR for #1993.
