### ISSUE TITLE
Increased Gas cost when calling reward via CLI with Master build 0.5.19-e9b81b25

### ISSUE THREAD

**Issue by Franck-UltimaRatio** [livepeer/go-livepeer#2015]
**Describe the bug**
When i call reward with CLI, the max gas price is way over the normal transaction

**To Reproduce**
Call reward with CLI with last master build 0.5.19-e9b81b25/livepeer-windows-amd64

https://etherscan.io/tx/0x4b3b8530564976fe5a6c20aa916a23648d970a0e3431458e7eb6d0972fbe7851

**Expected behavior**
it seems like the fields for previous and next O were not populated correctly (filled with 0 instead of the Orch addresses)
(this is most likely the reason for the increased gas cost - it needs to do additional calculations if you don't specify the position of you O. It's basically the same as calling reward without hint)

For the moment, i have reinstalled the last official Master build, i have no more fund for the moment but i ll try to call reward asap to see if the problem is fixed this way.

Also reported by Papa_Bear

**Comment by Franck-UltimaRatio** [comment]
It's look like the Bug happen only when you call reward via CLI, and when the node create a replacement transaction because the gas price was too low in the first one.
Then , in this replacement transaction, some information are not populated correctly : 

Function: rewardWithHint(address _newPosPrev, address _newPosNext) ***
MethodID: 0x81871056
[0]:  0000000000000000000000000000000000000000000000000000000000000000
[1]:  0000000000000000000000000000000000000000000000000000000000000000

Resulting in a TX cost 2 times more expensive than a normal transaction :
Transaction Fee:
0.033669996830854182 Ether ($111.58)
Gas Price:
0.000000053587594846 Ether (53.587594846 Gwei)

**Comment by papabear99** [comment]
I had the same issue today calling reward with the CLI running 0.5.18 official release.

Gas Limit  651,913 Gas Used 628,317

Transaction can be seen here https://etherscan.io/tx/0x763ea83d3be881493f2d1e7158fa52a2f280b103b5389ecf89862370595ef15e

I have installed 0.5.20-6e0a8fe6 and will try again next round

Edit:  Transaction commented above by Cianha can be seen in full in link to my transaction

**Comment by yondonfu** [comment]
This increased gas usage bug was triggered when an orchestrator calls reward after not receiving any stake updates in the previous round. An orchestrator receives stake updates via reward calls or stake delegation. So, if an orchestrator does not receive any delegation in the previous round *and* it did not call reward in the previous round, the bug was triggered when the orchestrator called reward in the current round causing gas usage to increase due to missing positional hint fields in the transaction.

A fix for this bug is implemented in #2029 and it will be included in the 0.5.20 release.
