### ISSUE TITLE
Support H265/HEVC, VP8, VP9

### ISSUE THREAD

**Issue by cyberj0g** [livepeer/go-livepeer#2123]
## Abstract
Currently, we support only H.264 codec in the transcoding pipeline, while H.265 (HEVC) and VP8/VP9 are very popular and widely supported alternatives. 

## Proposed Solution

As Livepeer focuses on using Nvidia GPUs capabilities, it makes sense to first add support for codecs which has hardware implementations on these devices. As per [support matrix](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new):
* VP8/9: **encoding** is not currently supported
* VP8/9: **decoding** is supported on newer devices
* H.265: both encoding and decoding is supported on most devices starting Maxwell (2nd gen), except some entry-level mobile GPUs

This asks for a way in the protocol to announce which encoders, decoders and capabilities in general T supports hardware-wise or wiling to provide. I'm not very knowledgeable on the protocol, so feel free to add your ideas on how to best implement that, or maybe it's already implemented? Adding H.265 support to transcoder is fairly trivial, but require data structures refactoring and corner case testing.

## Implementation Tasks and Considerations

1. Extend `VideoProfile` structure [here](https://github.com/livepeer/lpms/blob/fe330766146dba62f3e1fccd07a4b96fa1abcf4d/ffmpeg/videoprofile.go#L48) to contain both input and output codec. Treat it as input parameters, and `TranscodeOptions` as runtime parameters with specific codec names, which are created from `VideoProfile` [here](https://github.com/livepeer/go-livepeer/blob/f3a299bb95af04004fd957cdc3b2b4a69c72c90b/core/transcoder.go#L233). The main reason for such separation is a requirement to use different encoder\decoder names for same codec with and without HW acceleration.
2. Add corresponding constants for default types of renditions [here](https://github.com/livepeer/lpms/blob/fe330766146dba62f3e1fccd07a4b96fa1abcf4d/ffmpeg/videoprofile.go#L62), when transcoding H265>H264, H264>H265, H265>H265. 
2. Support configuring specific codec with additional parameters for HW processing [here](https://github.com/livepeer/lpms/blob/fe330766146dba62f3e1fccd07a4b96fa1abcf4d/ffmpeg/ffmpeg.go#L331).
3. Add decoder parameter to `lpms_transcode` and pass it [here](https://github.com/livepeer/lpms/blob/fe330766146dba62f3e1fccd07a4b96fa1abcf4d/ffmpeg/ffmpeg.go#L520), currently, input codec hard coded [here](https://github.com/livepeer/lpms/blob/fe330766146dba62f3e1fccd07a4b96fa1abcf4d/ffmpeg/decoder.c#L231). New parameter should be added to: `open_input`, `open_video_decoder`, `lpms_transcode`, `transcode` of [transcoder.c](https://github.com/livepeer/lpms/blob/master/ffmpeg/transcoder.c) and [decoder.c](https://github.com/livepeer/lpms/blob/master/ffmpeg/decoder.c).
4. Choose right HW decoder [here](https://github.com/livepeer/lpms/blob/fe330766146dba62f3e1fccd07a4b96fa1abcf4d/ffmpeg/decoder.c#L227).

Request comments from @yondonfu @jailuthra @oscar-davids @darkdarkdragon.

**Comment by cyberj0g** [comment]
## Additional note on VP8/9
The most widely used implementation of these codecs is [libvpx](https://github.com/webmproject/libvpx/) from Google. However, it does not seem to support any kind of hardware acceleration, neither CPU nor GPU. There is a [project](https://github.com/Italtel-Unimi/libvpx) which aims to add CUDA support to libvpx, but it's not maintained. In case of Ffmpeg and x86-64 platform specifically, the fastest way to transcode VP8/9 seem to be Nvidia's `vp8_cuvid` decoder combined with Ffmpeg's own VAAPI implementation of VP8/9 encoder, which is accelerated on newer Intel and AMD CPUs. Further research needs to be done into performance of such solution as well as exact dependencies and hardware requirements.

**Comment by jailuthra** [comment]
Thanks @cyberj0g, the spec mostly looks good to me!

> Extend `VideoProfile` structure here to contain both input and output codec. Treat it as input parameters, and `TranscodeOptions` as runtime parameters with specific codec names, which are created from `VideoProfile` here. The main reason for such separation is a requirement to use different encoder\decoder names for same codec with and without HW acceleration.

I think rather than creating an additional field in `TranscodeOptions` for the actual codec names, we can create a lookup table in `video_profile.go`, or maybe re-use [`configAccel`](https://github.com/livepeer/lpms/blob/91b94f852f02525e491a3d2c2918ec3879107199/ffmpeg/ffmpeg.go#L214) which can find the correct decoder/encoder name from `VideoProfile.codec` and `TranscodeOptions.accel`. For example if input codec is H265 and accel is nvidia use `hevc_cuvid` for decoding and `hevc_nvenc` for encoding.

> Add corresponding constants for default types of renditions here, when transcoding H265>H264, H264>H265, H265>H265.

I wonder if we need to create new constants for each codec pair. At many places in code, we instantiate one of the default profiles, and change a parameter in it as needed. We can do something similar wherever we need to use or test non-H264 codecs. For example here is a test with non-default framerate of 100 https://github.com/livepeer/lpms/blob/master/ffmpeg/nvidia_test.go#L477-L478

> Add decoder parameter to lpms_transcode and pass it here, currently, input codec hard coded here. New parameter should be added to: open_input, open_video_decoder, lpms_transcode, transcode of transcoder.c and decoder.c.

Rather than adding an argument to these function signatures, we can re-use `input_params`, `output_params` or `input_ctx`, `output_ctx` structs to pass around the decoder/encoder name to these subroutines wherever we can.

> In case of Ffmpeg and x86-64 platform specifically, the fastest way to transcode VP8/9 seem to be Nvidia's vp8_cuvid decoder combined with Ffmpeg's own VAAPI implementation of VP8/9 encoder, which is accelerated on newer Intel and AMD CPUs. 

Good point on the lack of a good hardware accelerated encoder for VP8/9, other than VAAPI. Makes sense to prioritize H265 support first, as decode-only support for VP8/9 doesn't sound immediately useful.

> This asks for a way in the protocol to announce which encoders, decoders and capabilities in general T supports hardware-wise or wiling to provide. I'm not very knowledgeable on the protocol, so feel free to add your ideas on how to best implement that

One improvement to the capability detection is modifying the [nvidia transcode test](https://github.com/livepeer/go-livepeer/blob/6a72cc3defc486c44ac6c61bb67632b89293dabf/core/transcoder.go#L118) performed during node startup to also check if the underlying hardware can transcode segments from/to different codecs.

Depending upon which codecs are supported, the O/T node can dynamically broadcast [capabilities](https://github.com/livepeer/go-livepeer/blob/master/core/capabilities.go#L45) to the network, similar to how we [handle scene classification capability](https://github.com/livepeer/go-livepeer/blob/6a72cc3defc486c44ac6c61bb67632b89293dabf/cmd/livepeer/livepeer.go#L899) at runtime.

**Comment by yondonfu** [comment]
Agreed that it makes sense to focus on H265 decoding and encoding first. Ideally, implementing H265 support will establish an implementation path for new codecs for encoding/decoding that can be used later on when we look into VP8/VP9 support as well. I've updated the issue title to reflect this.

A few additional thoughts:

Will we also H265 decoding and encoding on CPU? This would follow the example established with H264 where we support decoding and encoding on CPU. I also suspect this will be helpful for testing codec support logic without always having to rely on Nvidia GPUs (although of course if what we care about is the transcoded output then we'll need Nvidia GPUs for that test).

> Makes sense to prioritize H265 support first, as decode-only support for VP8/9 doesn't sound immediately useful.

Let's prioritize H265 support first, but worth noting that decode only support for VP8/9 *could* be useful for VOD transcoding because that would allow the node to at the very least accept/decode VP8/9 encoded VOD files which could then be encoded using a different codec (i.e. H264/H265) and there may be a non-trivial number of such cases that would be worthwhile supporting even before supporting VP8/9 encoding.

Something that has come up in offline conversations is whether we should expose all the different configuration options that are possible with new codecs. While we eventually may want to support these options to allow users to customize them as is needed, for now I think we can just focus on supporting the codec period and then come back to consider configuration options separately.

**Comment by Thulinma** [comment]
> Let's prioritize H265 support first, but worth noting that decode only support for VP8/9 _could_ be useful for VOD transcoding because that would allow the node to at the very least accept/decode VP8/9 encoded VOD files which could then be encoded using a different codec (i.e. H264/H265) and there may be a non-trivial number of such cases that would be worthwhile supporting even before supporting VP8/9 encoding.

A pretty relevant example of such a case is that several models of cellphones support VP8 encoding over WebRTC but not H264. Transcoding the VP8 received from these devices to H264 makes sense for compatibility purposes.

**Comment by cyberj0g** [comment]
While working on this, I found that we will also need to refactor and improve capability detection logic to support H.265 and other potential capabilities, which might not be available or desirable on every T. Currently, there is no way for a standalone T to communicate the capabilities it supports to O. Scene classification capability check is hard-coded for  O+T case. After discussing with @jailuthra, the steps to implement that are:
1. Refactor [TestNvidiaTranscode](https://github.com/livepeer/go-livepeer/blob/d7c75365d87eb11ecebe02c9e058b671aa96904b/core/transcoder.go#L118) to have codec and capability discovery logic, with results stored in Transcoder structure. Move scene classification capability test there, too.
2. Add Capability field to [RegisterRequest](https://github.com/livepeer/go-livepeer/blob/d7c75365d87eb11ecebe02c9e058b671aa96904b/net/lp_rpc.pb.go#L1413) struct
3. Modify [selectTranscoder](https://github.com/livepeer/go-livepeer/blob/d7c75365d87eb11ecebe02c9e058b671aa96904b/core/orchestrator.go#L904) to be aware of capabilities requested through `SegTranscodingMetadata`, which, in turn, should be modified to store capabilities.

Feedback is appreciated.

**Comment by yondonfu** [comment]
> Currently, there is no way for a standalone T to communicate the capabilities it supports to O.

Yeah at the moment only B <> O capability discovery is implemented, but O <> T capability discovery is not yet implemented. We initially implemented B <> O capability discovery because that at the very least covered the case where a B is interacting with a combined OT (i.e. an O that is also running as a T) which was the most common setup at the time (although we're now seeing an increasing number of split O + T setups on the network).

I think we should eventually implement O <> T capability discovery to cover the scenario where a O has a diverse set of Ts that might have different capabilities (in particular different hardware with different codec support). However, I suggest implementing this as a part of a separate task i.e. 1) add h265 support and then 2) add O <> T capability discovery.

**Comment by darkdarkdragon** [comment]
@yondonfu 
>  However, I suggest implementing this as a part of a separate task i.e. 1) add h265 support and then 2) add O <> T capability discovery.

If we're not implementing O <> T discovery, that means that in separate O setup user should specify manually what codec it wants to be advertised?

**Comment by cyberj0g** [comment]
> in separate O setup user should specify manually what codec it wants to be advertised

Can O collect capabilities from Ts upon `RegisterTranscoder` calls and then advertise them?

**Comment by yondonfu** [comment]
> If we're not implementing O <> T discovery, that means that in separate O setup user should specify manually what codec it wants to be advertised?

Ah good point! Working through this for myself below...

At the moment, the caps in the node are all hardcoded so an O will advertise whatever caps are hardcoded for the version of go-livepeer that it is running. As a result, without O <> T cap discovery, O just advertises the caps hardcoded for its version of go-livepeer.

If we're planning on dynamically determining the codecs for a combined OT then it would make sense for the same process to be used to dynamically determine the codecs for a standalone T. And since a standalone O doesn't do any transcoding it wouldn't make sense for it to specify its own codecs. It would make much more sense for the standalone O to advertise its codecs based on whatever codecs are supported by its connected Ts. But, that implies that T needs to have a way to advertise the supported codecs to O. If this is the case, then it does seem reasonable to just implement O <> T cap discovery so that T advertises its codecs as a part of the O <> T cap discovery protocol. At first, I thought we could delay implementing O <> T cap discovery, but given that it would be useful to address this issue and is likely the cleanest way to address this issue I'd be onboard with just implementing it now.

> Can O collect capabilities from Ts upon RegisterTranscoder calls and then advertise them?

This makes sense to me.

We'd likely want to add additional caps for each codec similar to the [H264 cap](https://github.com/livepeer/go-livepeer/blob/970d0aa7892cd9c30aaf069a7ee8e72d8fa64111/core/capabilities.go#L24) and then include a capabilities string in the [RegisterRequest](https://github.com/livepeer/go-livepeer/blob/970d0aa7892cd9c30aaf069a7ee8e72d8fa64111/net/lp_rpc.proto#L322) message sent from T -> O similar to the one in the [OrchestratorInfo](https://github.com/livepeer/go-livepeer/blob/970d0aa7892cd9c30aaf069a7ee8e72d8fa64111/net/lp_rpc.proto#L118) message sent from O -> B.

**Comment by darkdarkdragon** [comment]
@yondonfu @cyberj0g @iameli 
> We'd likely want to add additional caps for each codec similar to the H264 cap and then include a capabilities string in the RegisterRequest message sent from T -> O similar to the one in the OrchestratorInfo message sent from O -> B.

This H264 cap advertises codec without distinguishing software/hardware and encoding/decoding.
I imagine, given that Nvidia hardware only allows to decode VP8/VP9 - most people would like to only advertise decoding of VPX and not encoding.

Also, Nvidia's GPU Support Matrix mentions different level of support of decoding VP9/h265 for 8/10/12bit. Should we advertise VP9_dec_8_bit, VP9_dec_10_bit, H265_dec_8_bit, etc.. - or how we should handle this?

**Comment by cyberj0g** [comment]
If we are not hard coding the matrix, we'll need to include a test video segment for each codec settings combination, so I'd start with base profile of H.265 and 8 bit mode of VP9.

For representing the capability, it will probably take two bit strings, one for base capability, and another one for its options: codec settings, and e.g. specific scene classification model. Potentially, we might even need to have continuous values for options, then bit string won't work well.

**Comment by darkdarkdragon** [comment]
> 
> For representing the capability, it will probably take two bit strings, one for base capability, and another one for its options: codec settings, and e.g. specific scene classification model. Potentially, we might even need to have continuous values for options, then bit string won't work well.

And now we're talking about changing capability detection protocol...

Also, now broadcaster should inspect incoming video segment (or require for relevant information to be presented along with the segment) - because if B is given VP9 segment to transcode - it should know if it is 8 or 12 bit - to find correct orchestrator to send to - or just try every orchestrator that support VP9 blindly knowing it can result in error.

**Comment by cyberj0g** [comment]
Right, exact requested capability should be known to perform the task. Regarding extending the off-chain part of the protocol - why not?

**Comment by darkdarkdragon** [comment]
Just wanted to point out that the task is getting bigger and bigger...

> Regarding extending the off-chain part of the protocol - why not?

I'm not against this - but this is a big task - we need to be extremely careful making changes to protocols - it is very hard to fix them after they was publicly released 😄

**Comment by yondonfu** [comment]
> For representing the capability, it will probably take two bit strings, one for base capability, and another one for its options: codec settings, and e.g. specific scene classification model. Potentially, we might even need to have continuous values for options, then bit string won't work well.

Interesting thought. So, as an example, let's say we define the VP9 decoding capability. If we follow this suggestion a node could advertise support for each bit level in tandem with advertising support for VP9 decoding i.e. node 1 and 2 both advertise VP9 decoding, but node 1 advertises 8 bit as an option and node 2 advertises 8 bit and 10 bit as options.

> This H264 cap advertises codec without distinguishing software/hardware and encoding/decoding.

Distinguishing between encoding and decoding capabilities makes sense to me as they are really different features. I'm not as sure about distinguishing between software and hardware. If the main difference between software and hardware is speed and visual quality/compression then I could see these two factors being considered separately - speed would be factored in in the selection process by B (i.e. biasing towards Os that return results faster) and visual quality/compression may be factored in with a quality and/or bitrate metric (the proper way to advertise this and to be able to trust this metric would need to be an area of research). The main reason I could see for distinguishing between software and hardware is if the supported options are different between the two - @cyberj0g @darkdarkdragon do you know if this is the case? If this is the case, then we may need to actually distinguish between software and hardware vendors if each hardware vendor has different options i.e. software VP9 decoding and Nvidia VP9 decoding.

Good point by @darkdarkdragon on the expanding scope of this issue.

While https://github.com/livepeer/lpms/pull/279 adds support for H265, VP8, VP9 we can also consider introducing support for each codec in go-livepeer more gradually.

Depending on the outcome of the distinguishing between software and hardware discussion above we may need to make that distinction below as well.

We could scope this issue to just H265 encoding for go-livepeer which would include:

- Add encoding capability for H265

Then, follow up tasks would include:

**H265 decoding for go-livepeer**

- Add decoding capability for H265
- Add support for determining codec of input stream in order to request the correct decoding capability

**VP8 + VP9 decoding for go-livepeer**

- Add decoding capabilities for VP8 + VP9

**Future**

- Advertise supported options for each decoding/encoding capability

**Comment by cyberj0g** [comment]
@yondonfu this makes sense. I'm already taking a gradual approach in a sense of just expanding [Capabilities](https://github.com/livepeer/go-livepeer/blob/970d0aa7892cd9c30aaf069a7ee8e72d8fa64111/core/capabilities.go#L21) enum with new values:
```
Capability_HEVC_Decode
Capability_HEVC_Encode
Capability_VP8_Decode
Capability_VP9_Decode
```
Assuming that we only care about hardware support of these codecs, so if Nvidia transcoding test fails, T will not report this capability at all. I think it's a good tradeoff for initial implementation, and we can expand that moving forward.  

> The main reason I could see for distinguishing between software and hardware is if the supported options are different between the two

Different implementations will have different low level options, as well as quirks e.g. `ffmpeg -h encoder=libx264` and `ffmpeg -h encoder=h264_nvenc`. But we probably shouldn't care at capabilities level about options which are not in the codec spec. Options like 'profile' and 'preset` may be named differently, but, ultimately, should be included in capabilities.

> Add support for determining codec of input stream in order to request the correct decoding capability

We [already have that](https://github.com/livepeer/lpms/blob/0999e7e2f16c2065a6f6d2eb5b94411bfe911656/ffmpeg/decoder.c#L221), just need to create a separate function to use in O.

**Comment by Thulinma** [comment]
For reference: most hardware-accelerated encoders do not support my favorite mode, CRF (Constant Rate Factor) - otherwise known as "constant quality" (as opposed to constant bit rate).
There are tons of other small differences between all the various implementations, but generally advertising these differences is probably going a bit too far.
It makes more sense, practically, to give a "quality rating" for the encoder, but there is no good way to advertise that without making it very easy to game... so **simply advertising codec support (decode/encode) and nothing more is probably the wisest choice for now**.

**Comment by cyberj0g** [comment]
Looks like one additional case is not covered by pending and merged PRs: when O starts in standalone mode, and then Ts connect to it, B needs to receive info about new capabilities of that O. Implementation tasks are:
1. Update O capabilities upon new `RegisterTranscoder` call
2. Re-evaluate O capabilities on each [selectOrchestrator](https://github.com/livepeer/go-livepeer/blob/763cc0150ebf47299d32f41cb3103d928c9d771e/server/broadcast.go#L604-L603) call

@darkdarkdragon @yondonfu comments are welcome.

**Comment by darkdarkdragon** [comment]
@cyberj0g 
Also we need update O capabilities when transcoder disconnects

**Comment by darkdarkdragon** [comment]
@cyberj0g can you create tickets for these new tasks?
