### ISSUE TITLE
Receive segment metadata from Mist Server

### ISSUE THREAD

**Issue by cyberj0g** [livepeer/go-livepeer#2159]
## Abstract
At the moment a go-livepeer B is not aware of the codec of a source segment. This information is required:
- for B, to select correct O which (has a T which) supports this decoder
- for O, to send segments to correct Ts

Other capabilities or more advanced session-level scheduling might potentially require more segment stream metadata, such as video stream resolution, audio stream codec etc.

## Motivation

Support new codecs which are not available on all user hardware, and, ultimately, support any other capability non-uniformly present in the network.

## Proposed Solution

1. Add segment metadata available to Mist Server as a separate HTTP request header (e.g. `X-Segment-Metadata`) in JSON format.
2. Update O discovery logic
3. Update T discovery logic

## Implementation Tasks and Considerations

TBD

## Alternatives

Use `lpms` to read segment metadata again on B.

Appreciate input from @darkdarkdragon on go-livepeer side, @Thulinma on Mist side and @yondonfu.

**Comment by darkdarkdragon** [comment]
@cyberj0g 
Problem with that solution is that Mist is not the client to the broadcaster, and that solution will demand more from them. Also, what if client sends wrong information about codecs? It'll make error handling harder.

Broadcaster already [uses](https://github.com/livepeer/go-livepeer/blob/e3cec5a7dc0e341300b77693228ce63c7b28e615/server/broadcast.go#L710) LPMS to check every segment - that function (`HasZeroVideoFrameBytes`) opens segment using `ffmpeg` routines and checks that segment can be open and has valid information about streams - so we can modify this function to also return info about codecs.
I think that will be more robust solution to the problem.

**Comment by yondonfu** [comment]
@darkdarkdragon Good points.

One of the reasons I suggested to @cyberj0g to have Mist send the source segment codec to B is because I am concerned about the B re-doing work that Mist has already done. At the moment, the work that is repeated is parsing the source segment codec, but as indicated in the OP, in the future this could include parsing other source segment metadata as well. I see two possible costs of B re-doing the work - code maintenance cost and computational cost. I'm not sure what the computational cost of parsing metadata from a source segment is. Do you know? And is the bulk of any computational cost just from reading the video and once the video is opened fetching any additional metadata is basically free? 

Another reason for my suggestion is that Mist is currently the best software to use for ingest with Livepeer with Bs serving as a middleware layer connecting Mist with O/Ts for transcoding. So, if that is the direction we're moving in then it could be more reasonable to expect Mist to send this metadata correctly to B. However, this might make the HTTP API on B less attractive/impractical to use for other clients. I think there is a larger discussion to be had around the HTTP API on B as well as how the integration between Mist and B should evolve. I wanted to mention this for context, but I don't think having that discussion should block engineering work to make the source segment codec accessible to B in order to properly discover Os have the decoding capability for that codec. So, my current proposal is:

- Answer the computational cost questions mentioned above about reading metadata from video
- If the computation cost is really low/trivial, then implement @darkdarkdragon's suggestion of adding support in LPMS to read the video and return just the codec [1]. Since we already have to do a [zero video frame check](https://github.com/livepeer/go-livepeer/blob/e3cec5a7dc0e341300b77693228ce63c7b28e615/server/broadcast.go#L710) for each source segment, I suggest looking for a way to read the source segment once and a) detect if it has zero video frames and b) return the codec so that B doesn't need to read the video multiple times.
- Separately, put more thought into the Mist + B integration as well as the HTTP API on B

[1] Even if we can get additional metadata right now, I suggest sticking with just the codec to minimize the scope of the changes so that we don't do too much on B before figuring out the Mist + B integration and whether there is a world where we want to offload as much of the media metadata stuff to Mist as possible.

WDYT @darkdarkdragon @cyberj0g ?

**Comment by yondonfu** [comment]
@cyberj0g 

Assuming that B has access to the source segment codec...

> Update O discovery logic

The capabilities logic is in [this file](https://github.com/livepeer/go-livepeer/blob/master/core/capabilities.go).

At the moment, the capabilities requested for a stream (also referred to as a "job") are set when a stream is first received by B i.e. when the first segment with an unknown manifestID (identifies the stream) is received. The logical flow that results in capabilities being set for the stream when Mist sends a segment to the B's HTTP API is:

- [HandlePush()](https://github.com/livepeer/go-livepeer/blob/3649803de21ef36e1fe814c51ca6b94bef4daed6/server/mediaserver.go#L774) is triggered
- [registerConnection()](https://github.com/livepeer/go-livepeer/blob/3649803de21ef36e1fe814c51ca6b94bef4daed6/server/mediaserver.go#L880) is called if the stream is new
- [core.JobCapabilities()](https://github.com/livepeer/go-livepeer/blob/3649803de21ef36e1fe814c51ca6b94bef4daed6/server/mediaserver.go#L559) is called to generate a list of capabilities that are then set in the [stream params](https://github.com/livepeer/go-livepeer/blob/3649803de21ef36e1fe814c51ca6b94bef4daed6/server/mediaserver.go#L563)
- The [capabilities are accessed from the stream params](https://github.com/livepeer/go-livepeer/blob/3649803de21ef36e1fe814c51ca6b94bef4daed6/server/broadcast.go#L612) when the B runs discovery to get a set of Os to select from to send segments to
- The [discovery code](https://github.com/livepeer/go-livepeer/blob/3649803de21ef36e1fe814c51ca6b94bef4daed6/discovery/discovery.go#L96) runs a capability check to determine whether an O has the required capabilities for the job

If we parse the codec around [this line](https://github.com/livepeer/go-livepeer/blob/3649803de21ef36e1fe814c51ca6b94bef4daed6/server/broadcast.go#L710) then perhaps we can add the capability to the list of job capabilities that were already set in the stream params before passing the final capabilities for discovery.

**Comment by darkdarkdragon** [comment]
@yondonfu 
1. Want to point out that only reason we do parse segment inside B - is because Mist sends us invalid segments. So I would prefer not to rely on information that Mist sends us.
2. We still have HTTP push as public API. Even if we think we can rely on information that Mist sends us - we can't rely as much on the information sent by other clients to public API.
3. `HasZeroVideoFrame` function already has codec information, we just need to return it. For other meta information - it probably depends on type of meta information.

**Comment by cyberj0g** [comment]
I agree with @darkdarkdragon that it's more straightforward to implement this with lpms. The added computational cost is close to zero, at least for codec, because `av_find_best_stream` already reads codec_id internally.

**Comment by Thulinma** [comment]
I agree that trusting _any_ data that is separate from the actual stream contents is not necessarily a good idea.
Going even further beyond that, it's certainly possible (and easy, if you know how) to craft a segment that would make ffmpeg's checks say one thing, while the actual decoder would say another. So, even when using data gathered through that method, it can still be incorrect.

While I'm a big fan of using Mist everywhere we can - using it to parse metadata is probably the most useful when Mist itself acts as a broadcaster node in the network; not so much when it is acting as a client of a broadcaster node. 🤔

**Comment by yondonfu** [comment]
Thanks for all the feedback everyone! Sounds like using a LPMS function to parse the source segment codec on B is the way to go right now then. 

> Going even further beyond that, it's certainly possible (and easy, if you know how) to craft a segment that would make ffmpeg's checks say one thing, while the actual decoder would say another. So, even when using data gathered through that method, it can still be incorrect.

This is a great point. In this case, if the codec is parsed from metadata happens to be different from what the decoder says because someone crafted such a segment then I believe that would only hurt the sender of the segment since the the only thing the source segment codec would be used for right now is for capability discovery on B. But, there are definitely other cases where crafting a segment with incorrect metadata information could be actually harmful - an example, that comes to mind is pixel counts since that information is used for payment accounting so if you just used duration, width, height from segment metadata for determine pixel counts that could lead to a different result than the number of pixels actually processed by an encoder which would affect the payment value that could be received/sent. I think this is generally good to keep in mind!

**Comment by Thulinma** [comment]
Yeah, that's more or less exactly what I wanted to point out.
I can also help craft some "bad" segments like that to test against, at some point in the future, if you're interested. Just poke me. 👍

**Comment by yondonfu** [comment]
Decided to detect source codec and infer capabilities required in https://github.com/livepeer/go-livepeer/pull/2191
