### ISSUE TITLE
Unable to register as an Orchestrator using local geth ("Error getting pending stake: execution reverted")

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#2184]
## Summary

When running livepeer on Rinkeby testnet, _using a local `geth` instance_, it is not possible to view `DELEGATOR STATS`, nor is it possible to `Invoke multi-step "become an orchestrator"` without erroring. When attempting to do either of these actions, `livepeer` process reports `Error getting pending stake: execution reverted`.

Everything works fine when using infura as `-ethUrl`, and everything works fine on local geth after becoming an Orchestrator, but until then, there are issues.

## Observed behaviour

1. Start `geth` with:
```
./geth --networkid=4 --datadir=$HOME/.rinkeby --cache=512 --http
```
2. Wait for `geth` to sync with the head
3. Start `livepeer` with:
```
./livepeer -orchestrator -transcoder -network rinkeby -ethUrl http://localhost:8545 -pricePerUnit 1 -serviceAddr 127.0.0.1:8935 -ethPassword password -v 99
```
4. Run `./livepeer_cli`
5. Observe that `livepeer_cli` does not display `DELEGATOR STATS` underneath `ORCHESTRATOR STATS` and `NODE STATS`
6. Instead observe the following error message reported in the `livepeer_cli`:
```
ERROR: logging before flag.Parse: E0114 21:14:58.837343  230341 wizard_stats.go:245] Error getting delegator info: unexpected end of JSON input
```
7. Observe that `livepeer` process prints the following error to stdout:
```
E0114 21:17:15.812103  230278 client.go:674] Error getting pending stake: execution reverted
E0114 21:17:15.812122  230278 webserver.go:726] execution reverted
```
8. Run `1. Get node status`
9. Observe the same as in steps 5, 6 and 7.
10. Get test ETH and test LPT
11. Run `12. Invoke multi-step "become an orchestrator"`
12. Observe the same as in steps 5, 6 and 7.

Note: when running `12. Invoke multi-step "become an orchestrator"` with livepeer running against _a remote `-ethUrl` provided by infura_, these problems do not occur. It is even possible to become an orchestrator using infura, and then switch back to using local `geth`, and then a) successfully retrieve and display `DELEGATOR STATS`, and b) successfully cash winning tickets. Wonder whether there is some kind of race-condition type thing here, because local geth responds very quickly, but infura takes time to respond. But either way, it's an issue with `livepeer_cli`, and one which I wonder might have hindered some people running local geth from becoming Orchestrators on mainnet :|

## Expected behavior

I expect that when running livepeer against geth running locally, that it is able to complete all functions as expected.

## Environment

 - OS: Ubuntu 20.04.3 LTS
 - livepeer 0.5.25

**Additional context**

Related to #1858

**Comment by yondonfu** [comment]
This should be fixed by an upgrade to a new version of the [BondingManager contract on Rinkeby](https://rinkeby.etherscan.io/address/0xF96D54E490317c557A967ABfA5d6e33006BE69b3). See below for more details on what the problem was.

The BondingManager read-only function that is called to calculate the address' stake can end up being pretty expensive to run if the address has never staked/registered before. That is why you only see the RPC errors if the address has never staked/registered before and why they go away if the address had already staked/registered. And you only see this when using a local geth vs. Infura/Alchemy because local geth has some defaults that cause long running read RPC calls to timeout sooner while Infura/Alchemy likely has a custom configuration that extends the timeout for long running read RPC calls.

Note: This will not impact the protocol contracts deployed to L2 since this logic is removed there. The only reason this logic was in the contracts deployed on L1 on Rinkeby is because we deployed virtually the same exact contracts that are deployed on mainnet today. And those contracts still contain this logic. The way that other applications such as the explorer handle this scenario on mainnet today is that they check if an address has not staked/registered and call a different read-only function (`getDelegator()`) in order to fetch an address' stake and fees in that scenario. In this case, upgrading the BondingManager contract on Rinkeby with a small update to skip the extra computation in the read-only function (`pendingStake()`/`pendingFees()`) if the address has not staked/registered was the easiest way to fix this for all testnet participants quickly.
