### ISSUE TITLE
Livepeer configuration parameters are ignored

### ISSUE THREAD

**Issue by leszko** [livepeer/go-livepeer#2193]
**Describe the bug**
When the Livepeer configuration file contains an unknown parameter, then all the following parameters are ignored.

**To Reproduce**
1. Created the following `livepeer.conf`

```
someMisspelledParameter 1234
reward false
```

2. Run Livepeer

```
$ livepeer -config livepeer.conf
```

3. Check that the `reward` parameter is ignored from `livepeer.conf`.

**Expected behavior**
We should have a fail-fast approach and if there is any unknown parameter, then just fail starting Livepeer.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Related Discord discussion: https://discord.com/channels/423160867534929930/932724294230900776/933199481065840731

**Comment by jvventura** [comment]
If this helps, I think I found the logic where this happens.

(Discord context: https://discord.com/channels/423160867534929930/932724294230900776/933447235029590067)

https://github.com/peterbourgon/ff/blob/67fe9632817c69f1aa51a8ef5bd5f430e4c9a7c5/parse.go#L130

It throws an error. But I think because of the way this code works, this callback func successfully sets the flags up that point as it iterates through each line of the conf file, but then does not proceed after that. Thus every option that comes after the unrecognized flag is ignored. Since this is the logic of the library and can't be changed without forking/PR, the only appropriate thing to do is not treat it as a silent error and terminate the livepeer startup process if an error is caught?
