### ISSUE TITLE
Use GPU for transcoding by default

### ISSUE THREAD

**Issue by cyberj0g** [livepeer/go-livepeer#2201]
It pops up in Discord very frequently: users forget/don't know about `-nvidia` argument and end up running transcoding on CPU, which is not their intention and will produce much lower reward. I think default arguments should reflect how the node is supposed to run. This will require implementing getting Nvidia GPU list on node startup, while `-nvidia` argument could still be used to restrict transcoding to specific GPUs.

**Comment by yondonfu** [comment]
> I think default arguments should reflect how the node is supposed to run.

If the suggestion is to try to use all available Nvidia GPUs by default, then I have a few questions/concerns with that approach:

- How will users disable Nvidia transcoding and enable CPU transcoding? While the latter may not be popular for production usage, it is still useful for testing, development and learning to run the software.
- If the node supports other hardware for transcoding, how will users disable Nvidia transcoding and enable other hardware? Will the node always privilege Nvidia in this scenario and set it as the default?

Something else we can do (that is not mutually exclusive with this suggestion) is to make it clearer in the docs that you can also use `-nvidia all` to use all available devices instead of having to select specific ones.

> This will require implementing getting Nvidia GPU list on node startup, while -nvidia argument could still be used to restrict transcoding to specific GPUs.

The node currently already supports getting all available Nvidia GPUs when the `-nvidia all` flag is set. On startup, the node [parses the -nvidia flag](https://github.com/livepeer/go-livepeer/blob/12bc1f16c79b65329f62eef1208f2c735d0b27d0/cmd/livepeer/livepeer.go#L278) using [common.ParseNvidiaDevices](https://github.com/livepeer/go-livepeer/blob/12bc1f16c79b65329f62eef1208f2c735d0b27d0/common/util.go#L449) which will fetch all available Nvidia devices if the value of the flag is "all".

**Comment by cyberj0g** [comment]
Good point about other hardware support. We can deprecate `-nvidia` flag in favor of something like:
```-accel none|nvidia|netint[=device_id[,device_id]]```
with `-accel nvidia` being default option.

**Comment by hthillman** [comment]
To me it seems like this is part of a larger conversation about how we select GPUs for an orchestrator. IMO this should be a highly configurable process that takes into account job type, hardware, concurrent stream count, etc

see e.g., https://github.com/livepeer/go-livepeer/issues/2034

**Comment by hthillman** [comment]
We'd like to wait on adjusting flag behavior until we have a better understanding of how we want to support additional hardware and how we want to support configuring capabilities for that hardware. we suspect that that information will influence how flags should be defined on the node
