### ISSUE TITLE
Improve Feed PubSub mechanism

### ISSUE THREAD

**Issue by leszko** [livepeer/go-livepeer#2207]
## Abstract

In `go-livepeer` we use the in-process PubSub mechanism, based on the [event.Feed structure](https://pkg.go.dev/github.com/ethereum/go-ethereum/event#Feed), which distribute events between different goroutines. We use it with an assumption that it's async, but in reality, it's a blocking mechanism. This spec describes a set of activities to fix this issue.

## Motivation

There were a number of bugs reported, which most probably are related to this issue:
- https://github.com/livepeer/go-livepeer/issues/2152
- https://github.com/livepeer/go-livepeer/issues/2079

A sample scenario to experience the issue is to start an orchestrator and send a transaction which is not been minted for a long time. Then one of the PubSub subscribers waits on [client.CheckTx](https://github.com/livepeer/go-livepeer/blob/c2c73fa6f24473311766baee83e2762c87ef708d/eth/client.go#L870), which blocks the PubSub sender, which in result makes the orchestrator unable to do anything, even transcoding a segment.

## Proposed Solution

This diagram presents how we use the Feed PubSub mechanism in which each feed is a PubSub topic.

![image](https://user-images.githubusercontent.com/2834997/150986190-78420b43-0ca7-46fb-959a-3bb4e28ee676.png)

If anything blocks in any subscriber, it can block the whole graph. Why is it so?

The [Feed subscription mechanism](https://pkg.go.dev/github.com/ethereum/go-ethereum/event#Feed.Subscribe) works with Go channels and when the channel is full, the sender is blocked. The recommendation from the doc is:

> The channel should have ample buffer space to avoid blocking other subscribers. Slow subscribers are not dropped.

However, we have these 2 issues:

1. Subscribers execute blocking operations
2. Blocking operations don't use any deadline/timeout

As an example, we can see [client.CheckTx() in rewardservice](https://github.com/livepeer/go-livepeer/blob/v0.5.26/eth/rewardservice.go#L94). It's blocking and does not use any timeout.

We should address both of these issues, so make sure that each subscriber does not block and add timeouts for all blocking operations.

## Implementation Tasks and Considerations

1. Execute subscribers' blocking operations in separate goroutines
   - PR: #2208
2. Add timeouts for all blocking operations

## Testing Tasks and Considerations

Testing scenarios:
1. Insert `time.Sleep(1 * time.Hour)` into `CheckTx()` and other operations and check that the transcoding is not blocked
2. Check that no goroutines are blocked forever by inserting `time.Sleep(1 * time.Hour)` and checking `runtime.NumGoroutine()`

## Known Unknowns

Consider checking the following aspects:
1. Check O transcoding stability while executing a transaction:
   - I noticed that B retries a segment when O is in the process of executing a transaction
2. Race condition between executing a transaction and calling `CheckTx()`
   - `CheckTx()` is always executed after the transaction and technically the receipt of a transaction can be published before `CheckTx()` is called
   - it's a very corner case and should not happen in practice
3. Check the scenario in which the transaction is never minted
   - Make sure that the next transactions are not blocked
   - If for some reason a transaction is not minted, then we should probably abort it

## Alternatives

1\. Make `feed.Send()` async

Instead of making the subscribers handle events in the async fashion, we could send events in an async manner.

```golang
go func() {
  feed.Send()
}
```

This would actually be the simplest solution. However, this may not work, since the feed graph will still block, only `send()` does not block. It's also acting against the idea of the `event.Feed` mechanism.

2\. Use a different PubSub solution

We could find another library for the in-process PubSub which is really async. However, I belive it's an overkill at this point.

## Additional Context

Related GH Issues:
- https://github.com/livepeer/go-livepeer/issues/2168
- https://github.com/livepeer/go-livepeer/issues/2152
- https://github.com/livepeer/go-livepeer/issues/2079

**Comment by victorges** [comment]
Current proposed solutions look good to me! Reviewed the one for background event processing.

For timeouts, especially the `checkTx` one should be really simply, since its core implementation is just a loop on top of another subscription right? Just a matter of adding a `time.After(timeout)` or `ctx.Done()` to the select cases and exit with a timeout.

**Comment by leszko** [comment]
> Current proposed solutions look good to me! Reviewed the one for background event processing.

Thanks for the review @victorges !

> For timeouts, especially the `checkTx` one should be really simply, since its core implementation is just a loop on top of another subscription right? Just a matter of adding a `time.After(timeout)` or `ctx.Done()` to the select cases and exit with a timeout.

Yes, it should be simple. Actually for the on-chain transactions, the timeout should also be simple, because you can add `context` to into `TransactOpts` or `CallOpts` (which we don't do atm).

**Comment by yondonfu** [comment]
Proposed solutions look good just a few clarifying comments below:

> As an example, we can see client.CheckTx() in rewardservice. It's blocking and does not use any timeout.

This is technically true since `client.CheckTx()` itself does not implement a timeout despite using an infinite for loop that waits on a select statement, but worth noting that there is some additional nuance under the hood:

- `client.CheckTx()` is typically called using a tx created by [TransactionManager.SendTransaction()](https://github.com/livepeer/go-livepeer/blob/d4c981d5c032aceaa400b3693349f76334ba4bb9/eth/transactionManager.go#L100) which adds the tx to a [queue](https://github.com/livepeer/go-livepeer/blob/d4c981d5c032aceaa400b3693349f76334ba4bb9/eth/transactionManager.go#L115) before returning it
- [TransactionManager.checkTxLoop()](https://github.com/livepeer/go-livepeer/blob/d4c981d5c032aceaa400b3693349f76334ba4bb9/eth/transactionManager.go#L186) then pulls txs from the queue and [waits](https://github.com/livepeer/go-livepeer/blob/d4c981d5c032aceaa400b3693349f76334ba4bb9/eth/transactionManager.go#L208) for each one to be mined
- [TransactionManager.wait()](https://github.com/livepeer/go-livepeer/blob/d4c981d5c032aceaa400b3693349f76334ba4bb9/eth/transactionManager.go#L138) does set a timeout for how long it will block to wait for a tx to be mined
- The `checkTxLoop()` will only try to replace a tx [maxReplacements](https://github.com/livepeer/go-livepeer/blob/d4c981d5c032aceaa400b3693349f76334ba4bb9/eth/transactionManager.go#L212) times before giving up

So, in the typical tx workflow, if a tx is already successfully submitted, `client.CheckTx()` is unlikely to block forever (except in the case where there is mismatch between the tx hash that the method is waiting for and the tx hash returned by the channel) due to the timeout on `wait()` and the `maxReplacements` logic. However, there are definitely missing timeouts in a few other areas:

- Since `client.CheckTx()` has an infinite loop, there should probably still be a timeout set there
- There should probably be a timeout set for submitting txs as well in case there is a problem at tx submission time

> CheckTx() is always executed after the transaction and technically the receipt of a transaction can be published before CheckTx() is called

I *think* [bind.WaitMined](https://github.com/livepeer/go-livepeer/blob/d4c981d5c032aceaa400b3693349f76334ba4bb9/eth/transactionManager.go#L141) should still return the receipt when called as it should call the getTransactionReceipt RPC call under the hood, but I'd double check that.

**Comment by leszko** [comment]
Thanks for the clarification @yondonfu 

> * Since `client.CheckTx()` has an infinite loop, there should probably still be a timeout set there
> * There should probably be a timeout set for submitting txs as well in case there is a problem at tx submission time

Yeah, agree. We should have timeouts for both: checking the tx and submitting the tx.

> 
> > CheckTx() is always executed after the transaction and technically the receipt of a transaction can be published before CheckTx() is called
> 
> I _think_ [bind.WaitMined](https://github.com/livepeer/go-livepeer/blob/d4c981d5c032aceaa400b3693349f76334ba4bb9/eth/transactionManager.go#L141) should still return the receipt when called as it should call the getTransactionReceipt RPC call under the hood, but I'd double check that.

Yes, but since we receive tx receipts in another goroutine, technically it's still possible that we first send the receipt before calling `CheckTx()`. In any case, it's so unlikely, I'd not focus on it at the moment.

**Comment by leszko** [comment]
FYI: The most important fix is merged #2208 .

I plan to send one more PR which adds timeouts and aborting of the transaction. Then, this GH Issue will be closed.
