### ISSUE TITLE
Support -network=arbitrum-one

### ISSUE THREAD

**Issue by leszko** [livepeer/go-livepeer#2242]
Add support for `-network=arbitrum-one`.

Similar to what we did in https://github.com/livepeer/go-livepeer/pull/2202

Activities:
- Add chain support build variables
- Add controller address in `livepeer.go`

**Comment by leszko** [comment]
blocked until contracts are deployed in Arbitrum Mainnet

**Comment by yondonfu** [comment]
Suggested change: I think we should use `arbitrum-one-mainnet` as the name of the network to follow the `arbitrum-one-*` naming convention that we already use for `arbitrum-one-rinkeby` since "Arbitrum One" is the term used to distinguish Arbitrum's flagship rollup chain from other deployments of Arbitrum rollup chains.

**Comment by yondonfu** [comment]
Making a note that we'll want to remember to set redeemGas in the network config for arbitrum-one-mainnet similar to what we do for arbitrum-one-rinkeby in https://github.com/livepeer/go-livepeer/pull/2252
