### ISSUE TITLE
Low latency transcoding

### ISSUE THREAD

**Issue by cyberj0g** [livepeer/go-livepeer#2277]
## Abstract
'Low latency' means sending transcoded packets back T->O->B as they are ready, without accumulating them into segments.

## Motivation
It's a common requirement for live streams to have a low latency, comparable to ping time between producer and consumers. It would be essential, if Livepeer to serve as a backend for Zoom-like service.

## Current implementation
1. Mist server buffers whole segment before sending it to B
2. B-O-T transcode on segment level
3. B-O discovery happens once first segment is received
4. Metadata for capability discovery is read by B once first segment is received

## Points that will need to be addressed in low latency implementation 
1. Payment tickets are per-segment, and with low latency there won't be segments, we need a way to generate and send payment tickets as stream goes. It may be problematic to validate payment ticket hash without segment boundaries. 'Control' protocol needs a way to signal virtual segment boundaries.
2. Running B-O discovery once stream already started introduces additional latency. Possible solution is to pre-discover without input stream. 
3. As we need to send both 'control' messages and stream data both ways at same time, it may make sense to replace gRPC and HTTP with protocol which natively support multiplexing and online two-way communication, like HTTP/3 (QUIC). There's stable Go implementation of it.
4. Video metadata (codec, resolution, pixel format) needs to be received from Mist, which already have it from RTMP stream. It should be passed either as part of the protocol, or through some form of IPC from Mist internal data structures.
5. Right now, stream recording done on the broadcaster (it saves each segment to S3 storage). Before implementing new streaming solution we need to move recording process into Mist itself.

**Comment by AlexKordic** [comment]
## Observations

MPEG-TS is good format for our use case. Allows streaming and processing without downloading entire segment.

Our workflow does not allow for packet loss in the transport layer. If we would switch to UDP-based protocol what are the benefits?

Payments rely on segment boundaries. We don't need to get rid of segment boundaries to acomplish streaming workflow.

Currently payment info is packed in HTTP header field.

grpc is not suited for large file transfer so HTTP is used for segment transfer.

## Proposed protocol

Websocket

We would get statefull, full duplex communication.

We would get ordered, binary messages and text messages, maybe JSON encoded.

Good option if browser needs to send files to our network.

## Proposed custom protocol

BSD socket [TLV](https://en.wikipedia.org/wiki/Type%E2%80%93length%E2%80%93value) over [TCP](https://en.wikipedia.org/wiki/Transmission_Control_Protocol)

**Wire Format:**

Type (`T` in the `TLV`) value represents one custom `struct` on both sender and reciever. 

Length (`L` in the `TLV`) is split into two fields `OwnSize` and `ChildrenSize`, combined define byte-count until next `TLV` entry.

**Interface:**

```go
type DecodeResult struct {
	bytes_consumed int
}

type AtomSize struct {
	OwnSize      int32
	ChildrenSize int32
}

type Atom interface {
	MyTag()             uint16
	Decode(from []byte) DecodeResult
	EncodedSize()       int 
	Encode(to []byte)
}
```

`Atom`s can contain other `Atom`s .

**Backward compatibility:**

Because `T`ag and `L`ength are read first unknown atoms can be skipped. 

New fields are placed last so old version won't read them, effectively just skipping those bytes. 

Unknown child atoms would be skipped.

Because `AtomSize` specifies sizes of fields and contained children, we are free to upgrade protocol with fields and new atoms without need to have version of the protocol.

**Streaming:**

No streaming planned. Moving streaming responsibility into next abstraction layer that uses this wire protocol.

Our **existing non-streaming** code already suffers from HTTP protocol that is handling framing on file boundary and requires `Content-Length` to be known in advance forcing "downstream" code to cache/download files before processing takes place.

Instead of streaming interface we can use convention: Rename your large `Data` Atom into `DataChunk` Atom and adjust code logic to handle data chunks in a streaming pipeline maneer.

**Message priority:**

Can be added if required on sender side.

**Comment by leszko** [comment]
Thanks for the work @AlexKordic @cyberj0g. Good spec! I agree with most ideas! Here are some additional aspects that I think we need to cover.

#### B<>O Failover
Currently, when O stops responding, B retries the given segment with another O. What should we do when there are no segments? How to switch to another O and what should be retried? And should we retry at all?

#### O Zero-Downtime Deployment
One of the requested features by orchestrator operators is restarting an orchestrator without losing streams. I documented some approaches we can take in [Orchestrator Zero-Downtime Deployment Feature Spec](https://github.com/livepeer/go-livepeer/issues/2169). We need to think about how to address this requirement in the context of low latency transcoding.

#### Lossless vs Lossy Transcoding

AFAIU we want to completely replace our current segment-based transcoding with low latency transcoding. Then, I think we should cover how to approach two separate streaming use cases:
- Lossless - when latency does not matter (e.g. VOD or watching streams)
- Lossy - when latency (e.g. online calls)

What we currently have is lossless (TCP-based, segment retries). If we want to focus on low latency, then we may need to think about lossy transcoding (UDP-based, no retries).

**Comment by darkdarkdragon** [comment]
@AlexKordic 

> MPEG-TS is good format for our use case. Allows streaming and processing without downloading entire segment.

It has big overhead (It was designed for very different use case/transport layer, and usage of it over internet just wastes precious bandwidth. @Thulinma can tell more about it 😄 ). Also, `Allows streaming and processing without downloading entire segment.` - not much different from other containers like `mp4`.

> Our workflow does not allow for packet loss in the transport layer. If we would switch to UDP-based protocol what are the benefits?

We're not talking about allowing packet loss. [here](https://www.chromium.org/quic/) good explanation why QUIC is built over UDP. Summary:
```
Because TCP is implemented in operating system kernels and middleboxes, widely deploying significant changes to TCP is next to impossible. However, since QUIC is built on top of UDP and the transport functionality is encrypted, it suffers from no such limitations.

Key features of QUIC and HTTP/3 over TCP+TLS and HTTP/2 include

Reduced connection establishment time - 0 round trips in the common case
Improved congestion control feedback
Multiplexing without head of line blocking
Connection migration
Transport extensibility
```
That's exactly features we're looking for.


> Payments rely on segment boundaries. We don't need to get rid of segment boundaries to acomplish streaming workflow.

We will not get rid of boundaries, but we need to find a way to signal boundaries inside stream and embed payment inside stream.

**Comment by darkdarkdragon** [comment]
@leszko 

> What should we do when there are no segments?

There will be no segments like we have now - separate HTTP requests, but stream will be divided in logical segments anyway (need for payment anyway), so B will keep latest segment in memory so it can send it to another O if needed.
But here is another interesting question we didn't discuss but I think we should keep in mind:
If say, failover took 3 seconds - what should happen with playback? Should source stream wait for transcoded ones? If it will wait - then it will increase overall latency.
Or should transcoded segment be skipped so transcoded streams will be in sync with source with lowest latency? @Thulinma  @iameli what do you think?

> O Zero-Downtime Deployment

Even now it can't be done without help of O node itself. And if O node will be doing it - it can be done same way as in things like Nginx - by handing down connections from old instance to new one.
btw, in QUIC there is something called `Connection Migration` - I haven't looked into it in details, but maybe it could be leveraged for zero-downtime deployment.

> If we want to focus on low latency, then we may need to think about lossy transcoding (UDP-based, no retries).

I believe we haven't (yet) discussed that use case.
