### ISSUE TITLE
Price per pixel is showing 0.00 for every orchestrator

### ISSUE THREAD

**Issue by eliteprox** [livepeer/go-livepeer#2278]
**Describe the bug**
livepeer_cli lists every orchestrator with their price per pixel at 0.000

**To Reproduce**
1. Go to livepeer_cli
2. Enter "3" for List registered orchestrators
3. Reference the price per pixel column, which lists **0.000** for every orchestrator.

**Expected behavior**
livepeer_cli should display the correct price per pixel, and the livepeer_cli must set it properly during orchestrator config setup

**Screenshots**
![image](https://user-images.githubusercontent.com/16746274/154788442-f233283f-5926-4294-bd5c-d2e32661237b.png)

**Desktop (please complete the following information):**
- Windows and Linux
- Version 0.5.28

**Additional context**
This might be related to a bug seen when setting orchestrator config, which I've seen consistently cause "Error applying configuration" on 0.5.28 and arbitrum

**To reproduce error setting orchestrator config (which may be related)
1. Go to livepeer_cli
2. Enter 13 for Set orchestrator config
3. After entering all information, an error occurs "Error applying configuration"

**Comment by leszko** [comment]
@eliteprox Are you connecting with `livepeer_cli` to Orchestrator or Broadcaster?

AFAIU, on the Orchestrator side, you should always see only `0.0`, because price per pixel is not stored on-chain, but rather each Orchestrator sets it on the runtime. Therefore, if you connect `livepeer_cli` this value is not checked at all.

However, on the Broadcaster side, you see some numbers, because Broadcaster fills pixel per price in its internal db for each orchestrator it connected to (even just during the discovery phase).

Saying that I agree this mechanism is very confusing, so there is a place for improvement here.

**Comment by eliteprox** [comment]
Okay, I was using this on the orchestrator side so I think you are correct this is a non-issue.

**Comment by eliteprox** [comment]
I checked this on broadcaster side also just now, and it is also showing 0.00 for all orchestrators
