### ISSUE TITLE
Not possible to redeem tickets with Redeemer on Arbitrum

### ISSUE THREAD

**Issue by leszko** [livepeer/go-livepeer#2283]
It's not possible to redeem tickets with a separate Redeemer, because it returns the following error [reported in Discord](https://discord.com/channels/423160867534929930/943004634262413332/945578692023836712):

```
I0221 23:10:46.788973   20060 queue.go:134] Ticket recipient is not active in this round, cannot redeem ticket recipient=0xBe8770603dAf200b1Fa136aD354BA854928e602B
```

**Problem**

1. Redeemer checks if the ticket recipient is an active orchestrator [in the local SQLite](https://github.com/livepeer/go-livepeer/blob/4a8b8bdf08fbe696885b02d1609bdc6c868700d2/pm/queue.go#L172) (in `orchestrator` table).
2. The `orchestrator` table is a cache of the current on-chain orchestrators, which is refreshed:
    - When on-chain block logs are propagated with [orchestrator registration ](https://github.com/livepeer/go-livepeer/blob/754c1ed203539275332363eb2cd2940a7fa6c72a/eth/watchers/orchestratorwatcher.go#L137)
    - (Broadcaster-only) during the [orchestrator discovery](https://github.com/livepeer/go-livepeer/blob/9ab7a8842f2f4c12a0ca9b88cd8ef9b6a1bc1b73/discovery/db_discovery.go#L192)
    - (Orchestrator-only) during the [orchestrator setup](https://github.com/livepeer/go-livepeer/blob/4fb87465094588bfb75ae52a3933cb9a2f2b7940/cmd/livepeer/livepeer.go#L1198)
3. Redeemer may not have the correct `orchestrator` cache in the following cases
    - It was first started after orchestrators were already registered (we backfill blocks only until last block found in SQLite DB)
    - Logs has crashed (probably because of this bug: https://github.com/livepeer/go-livepeer/issues/2265

**Solution**

The solution is to either just allow redeeming tickets if the given orchestrator is not found in the local SQLite DB or refresh `orchestrator` if the given orchestrator is not found.

**Comment by yondonfu** [comment]
IIUC this problem was introduced with https://github.com/livepeer/go-livepeer/pull/2253 because:

- That PR added a requirement in `pm/queue.go` for the recipient of the ticket to be active and the active check was implemented using a DB query against the `orchestrators` table
- The `orchestrators` table could be missing the recipient of the ticket if the node is running in redeemer mode so the table is empty for the DB query and as a result the active check in `pm/queue.go` fails

Does that sound right to you?

If so, could a solution be to ensure that the address that the node expects to receive tickets for is included in the `orchestrators` table? This is what we do when the node is running in orchestrator mode using the [setupOrchestrator()](https://github.com/livepeer/go-livepeer/blob/d85cb21937a0c302f0929889151ad7b3351994d2/cmd/livepeer/livepeer.go#L641) function. This function will add the [specified address to the orchestrators table](https://github.com/livepeer/go-livepeer/blob/d85cb21937a0c302f0929889151ad7b3351994d2/cmd/livepeer/livepeer.go#L1183) ensuring that it exists in the DB. Could we do something similar when the node is running in redeemer mode i.e. call `setupOrchestrator()` when the node is running in redeemer mode *and* when it is running in orchestrator mode?

**Comment by leszko** [comment]
> IIUC this problem was introduced with #2253 because:
> 
> * That PR added a requirement in `pm/queue.go` for the recipient of the ticket to be active and the active check was implemented using a DB query against the `orchestrators` table
> * The `orchestrators` table could be missing the recipient of the ticket if the node is running in redeemer mode so the table is empty for the DB query and as a result the active check in `pm/queue.go` fails
> 
> Does that sound right to you?

Yes, that is correct.

> If so, could a solution be to ensure that the address that the node expects to receive tickets for is included in the `orchestrators` table? This is what we do when the node is running in orchestrator mode using the [setupOrchestrator()](https://github.com/livepeer/go-livepeer/blob/d85cb21937a0c302f0929889151ad7b3351994d2/cmd/livepeer/livepeer.go#L641) function. This function will add the [specified address to the orchestrators table](https://github.com/livepeer/go-livepeer/blob/d85cb21937a0c302f0929889151ad7b3351994d2/cmd/livepeer/livepeer.go#L1183) ensuring that it exists in the DB. Could we do something similar when the node is running in redeemer mode i.e. call `setupOrchestrator()` when the node is running in redeemer mode _and_ when it is running in orchestrator mode?

Ahh, right, I missed the point that Redeemer is always running for one eth orch address only. I thought that it was possible to run a Redeemer for multiple orchestrators, but that actually not the case.

Updated the related PR: https://github.com/livepeer/go-livepeer/pull/2284/files

PTAL. Note that I kept the change with easing the condition for checking if the orchestrator is active. I think that if the given orchestrator cannot be found in DB, then we should try to redeem the ticket.
