### ISSUE TITLE
go-livepeer build from source not working for nvidia transcoder

### ISSUE THREAD

**Issue by ad-astra-video** [livepeer/go-livepeer#2288]
**Describe the bug**
go-livepeer build is not working when running as `-transcoder` with `-nvidia` flag

**To Reproduce**
1. Create new Ubuntu 18.04 VPS
2. Follow build from source instructions at https://docs.livepeer.org/installation/install-livepeer/installing-for-development
3. Run `livepeer` with `-transcoder -nvidia` flags
4. Get `scale_cuda` error below

```
I0223 12:01:01.666699 2139149 livepeer.go:274] ***Livepeer is running on the offchain network***
I0223 12:01:01.674814 2139149 livepeer.go:319] Transcoding on these Nvidia GPUs: [0]
WARNING: decoder.c:249] Nvidia decoder not found; defaulting to software
No such filter: 'scale_cuda'
ERROR: filter.c:107] Unable to parse video filters desc : Invalid argument
ERROR: encoder.c:220] Unable to open video filter : Invalid argument
ERROR: transcoder.c:203] Unable to open output : Invalid argument
E0223 12:01:01.918758 2139149 ffmpeg.go:609] Transcoder Return : Invalid argument
I0223 12:01:01.970571 2139149 transcoder.go:159] Required capability "H.264" is not supported on device 0, see other error messages for details
WARNING: decoder.c:249] Nvidia decoder not found; defaulting to software
No such filter: 'scale_cuda'
ERROR: filter.c:107] Unable to parse video filters desc : Invalid argument
ERROR: encoder.c:220] Unable to open video filter : Invalid argument
ERROR: transcoder.c:203] Unable to open output : Invalid argument
E0223 12:01:02.217718 2139149 ffmpeg.go:609] Transcoder Return : Invalid argument
F0223 12:01:02.261956 2139149 livepeer.go:324] Required capability "H.264" is not supported on hardware
```

**Expected behavior**
Expecting fail on vp8_cuvid decoder.

**Additional context**
Attached log from initial login to end of build process
[go-livepeer-build.log](https://github.com/livepeer/go-livepeer/files/8124533/go-livepeer-build.log)

**Comment by ad-astra-video** [comment]
I was able to get it to build for `-transcoder` using the linux.yml workflow as a guide on Ubuntu 18.04.

I am not certain what specifically fixes it.

For ubuntu 20.04: I could not get build to work with `-transcoder`. Even with steps below I continued to get the "scale_cuda" error.
```
apt-get update
apt-get upgrade
apt-get -y autoremove
apt-get install -y software-properties-common curl apt-transport-https
apt-key adv --keyserver keyserver.ubuntu.com --recv 15CF4D18AF4F7421
add-apt-repository "deb [arch=amd64] http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
apt-get update
apt-get -y install clang-8 clang-tools-8 build-essential pkg-config autoconf git python
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-8 30
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-8 30
git clone https://github.com/livepeer/go-livepeer.git
snap install go --classic
go mod download
cd go-livepeer
./install_ffmpeg.sh
export PKG_CONFIG_PATH=~/compiled/lib/pkgconfig
export BUILD_TAGS=mainnet
./ci_env.sh make
```

**Comment by MikeIndiaAlpha** [comment]
I was able to reproduce the problem on Ubuntu 20.04 machine. The message here: "WARNING: decoder.c:249] Nvidia decoder not found" basically means that ffmpeg was build without support for Nvidia decoders. Now the question is why. Let's look into "install_ffmpeg.sh". One can find a comment there, saying "If we have clang, we can compile with CUDA support!". And the test for clang is simply issuing the command "which clang".

Now, I tested this command on my machine and sure enough, it returns nothing, meaning that clang is not installed. So I did the following:
apt-get -y install clang clang-tools
Now "which clang" returns "/usr/bin/clang" - try to rebuild ffmpeg:
cd ~/ffmpeg
make clean
cd ~/go-livepeer
./install_ffmpeg.sh
make

After that, when I start the transcoder with -nvidia I get the following:
```
I0325 10:28:56.761610   67150 livepeer.go:274] ***Livepeer is running on the offchain network***
I0325 10:28:56.794542   67150 livepeer.go:319] Transcoding on these Nvidia GPUs: [0]
[h264_cuvid @ 0x7f9274009200] Codec h264_cuvid is not supported.
ERROR: decoder.c:274] Unable to open video decoder : Invalid argument
ERROR: decoder.c:301] Unable to open video decoder : Invalid argument
decoder.c:313] Freeing input based on OPEN INPUT error
E0325 10:28:56.892705   67150 ffmpeg.go:727] Transcoder Return : Invalid argument
I0325 10:28:56.892746   67150 transcoder.go:227] required capability "H.264" is not supported on device 0, see other error messages for details
[h264_cuvid @ 0x7f9274031280] Codec h264_cuvid is not supported.
ERROR: decoder.c:274] Unable to open video decoder : Invalid argument
ERROR: decoder.c:301] Unable to open video decoder : Invalid argument
decoder.c:313] Freeing input based on OPEN INPUT error
E0325 10:28:56.952640   67150 ffmpeg.go:727] Transcoder Return : Invalid argument
F0325 10:28:56.952710   67150 livepeer.go:324] required capability "H.264" is not supported on hardware

```

Now, the original error report by @0xB79 said that it was expecting error with "vp8_cuvid" codec, and I am getting "h264_cuvid" codec error. Can I assume this is a mistake in original bug report? Because h264_cuvid error here makes sense to me.

**Comment by ad-astra-video** [comment]
Below is the expected output when using a 1080 ti that I get when using pre built binaries.

@MikeIndiaAlpha Did this fix the build from source for a transcoder running nivida card? The error makes me think it did not. Or, is the error in your logs posted because your machine not have a nvidia card installed?

When I built from source, I used the docs instructions which included ```apt-get -y install clang-8 clang-tools-8```.  Looks like you removed the ```-8``` on the Ubuntu 20.04 install for ```clang```.

```
./livepeer -config ./livepeer_transcoder.conf
I0325 14:59:04.418706   14813 livepeer.go:274] ***Livepeer is running on the offchain network***
I0325 14:59:04.420638   14813 db.go:377] Initialized DB node
I0325 14:59:04.511541   14813 livepeer.go:319] Transcoding on these Nvidia GPUs: [0]
[vp8_cuvid @ 0x7f6dc0785c00] Codec vp8_cuvid is not supported.
ERROR: decoder.c:274] Unable to open video decoder : Invalid argument
ERROR: decoder.c:301] Unable to open video decoder : Invalid argument
decoder.c:313] Freeing input based on OPEN INPUT error
E0325 14:59:06.642016   14813 ffmpeg.go:609] Transcoder Return : Invalid argument
I0325 14:59:06.642114   14813 transcoder.go:159] Optional capability "VP8 decode" is not supported on device 0, see other error messages for details
I0325 14:59:07.084144   14813 census.go:321] Compiler: gc Arch amd64 OS linux Go version go1.17.6
I0325 14:59:07.084193   14813 census.go:322] Livepeer version: 0.5.29
I0325 14:59:07.084235   14813 census.go:323] Node type trcr node ID s1155
I0325 14:59:07.085320   14813 livepeer.go:397] ***Livepeer is in off-chain mode***
I0325 14:59:07.085742   14813 livepeer.go:1061] **Liveepeer Running in Transcoder Mode***
I0325 14:59:07.085680   14813 mediaserver.go:187] Transcode Job Type: [{P240p30fps4x3 600k 30 0 320x240 4:3 0 0 0s 0} {P360p30fps16x9 1200k 30 0 640x360 16:9 0 0 0s 0}]
I0325 14:59:07.086070   14813 webserver.go:72] CLI server listening on 127.0.0.1:6935
I0325 14:59:07.086237   14813 ot_rpc.go:56] Registering transcoder to 127.0.0.1:8935
```

**Comment by MikeIndiaAlpha** [comment]
@0xB79
Your original logs (from February 23th) contained livepeer SW complaining about lack of H.264. But expected behaviour was "fail on vp8_cuvid decoder". These (h264 and vp8) are two different codecs, so I assume that what you were really after is fail on "h264_cuvid". This is what I got after applying my fix.

I believe that your original problem was due to ffmpeg (and hence livepeer) not seeing CUDA subsystem at all. What you have shown as "good" example above sees CUDA subsystem all right, but fails to initialise vp8_cuvid codec because that codec is not supported on that particular GPU. Same goes on my HW after my fix - h264_cuvid codec is not supported. So I assumed that fixes the problem.

To answer your question directly, I think that my build allows livepeer to see my nVidia card all right (there is no 'scale_cuda' problem anymore) but that card doesn't have support for that particular codec.

Yeah, I removed "-8" suffix from clang version because that command installs all clang family of commands with same suffix. What ffmpeg build script expects is "normal" command names (without suffix) and so won't find these that end with -8.

But please be aware of the fact that I just only started working on livepeer SW, and thus have very little experience so far.

**Comment by ad-astra-video** [comment]
@MikeIndiaAlpha I understand now, I have not seen the h264_cuvid error before but I am using 10 series and newer Nvidia cards.

I will try the build process again on fresh ubuntu VPS without the "-8" on clang.  I also found it was interesting that the github actions workflow used a different install process for clang than listed in the docs.

**Comment by MikeIndiaAlpha** [comment]
@0xB79 Don't get me wrong - I am not saying all is fine, maybe new issue should be opened? All I am saying is we moved a step forward, and ffmpeg (and livepeer) can now "see" CUDA subsystem.
