### ISSUE TITLE
When configuring an O with option 13 in the CLI offer the current registered Service URI as the default for "the public host:port of node"

### ISSUE THREAD

**Issue by papabear99** [livepeer/go-livepeer#2293]
When changing options using the CLI option 13 the last configuration "the public host:port of node" defaults to using the IP address of the node, which requires typing out a domain every time a change is made.  Many orchestrators use a Domain Name instead of their IP address so it would make sense for the default option to use the currently registered Service URI.

**Describe the solution you'd like**
Have the default be the currently registered Service URI

**Comment by kyriediculous** [comment]
I +1 this issue. 

I use Route53 to geo-route traffic between a couple of nodes. The individual nodes use their respective IPs/domains as service URIs on startupt, but the on-chain registered serviceURI is the global domain name. 

Each time I adjust my settings it offers to change it to the local IP or domain rather than sticking with the global one.
