### ISSUE TITLE
Geth Docker image with Livepeer confluence protocol

### ISSUE THREAD

**Issue by leszko** [livepeer/go-livepeer#2315]
We already have a [Docker image with Geth and Livepeer contracts](https://github.com/livepeer/go-livepeer/tree/master/cmd/devtool). The latest tag for this image is, however, `streamflow`. We need to have the `confluence` image in Docker Hub.

The new image is intended for two use cases:
- Local development as described in [devtool](https://github.com/livepeer/go-livepeer/tree/master/cmd/devtool)
- E2E Tests as planned in the [E2E tests](https://github.com/livepeer/go-livepeer/issues/2297)

Therefore, the new image should keep the similar behavior than `livepeer/geth-with-livepeer-protocol:streamflow`, in particular:
- delivered in a form of a single image started with `docker run`
- work with `go run cmd/devtool/devtool.go setup broadcaster/transcoder` scripts

Please check related comments from @yondonfu and @RiccardoBiosas [here](https://github.com/livepeer/go-livepeer/issues/2297), in particular:
1. We need to decide if we want to still use Geth image or move to some different tool, e.g., [Hardhat node](https://hardhat.org/hardhat-network/)
2. Some of the [Docker build scripts](https://github.com/livepeer/docker-livepeer/tree/master/geth-with-protocol) won't work, because of the switch from Truffle to Hardhat
3. Deploying the contracts won't work right out of the box because right now you have to deploy contracts from the protocol repo and the arbitrum-lpt-bridge repo because the protocol contracts depend on a L2LPTDataCache contract that is defined in the arbitrum-lpt-bridge.
4. We need to decide if we should start from scratch and deploy our contracts or if we want to fork the chain

**Comment by yondonfu** [comment]
For now I think it is reasonable to:

- Continue to use geth for the image
- Update the Docker build script to accommodate the switch from Truffle to Hardhat
- Define a way to deploy the full suite of contracts as a part of the Docker build script (in order to address the fact that just using the protocol repo contracts doesn't quite work right now)
- Not supporting forking a live chain for now

I think this will keep the scope of this task smaller and a different ETH client (i.e. Hardhat node, an Arb node setup, etc.) and supporting live forking for development can be looked into separately.

**Comment by RiccardoBiosas** [comment]
Related PRs:
https://github.com/livepeer/docker-livepeer/pull/92
https://github.com/livepeer/docker-livepeer/pull/93
https://github.com/livepeer/protocol/pull/557
https://github.com/livepeer/go-livepeer/pull/2402
