### ISSUE TITLE
Streams drop using low face value

### ISSUE THREAD

**Issue by ad-astra-video** [livepeer/go-livepeer#2473]
**Describe the bug**
Streams can drop due to face value of ticket being low using the `maxFaceValue` flag.  This only happens when gas prices spike.

This has to do with the code in `recipient.go` below where it uses 200 gwei as the `avgGasPrice` to check if ticket `faceValue` is less than current txCost or txCost with `avgGasPrice`.

https://github.com/livepeer/go-livepeer/blob/00a3e6d81edaf76bca19264d65269e4aa5f8c1c5/pm/recipient.go#L29-L31

This 200 gwei `avgGasPrice` is then used to compare `faceValue` to `txCost` with `avgGasPrice` of 200 gwei with the much higher gas used on Arbitrum (1,200,000 hardcoded, was 350,000 before switch to Arbitrum).  This test will always fail because it calculates a 0.24ETH value to compare the `faceValue` to.  

https://github.com/livepeer/go-livepeer/blob/00a3e6d81edaf76bca19264d65269e4aa5f8c1c5/pm/recipient.go#L304-L306

**To Reproduce**
1. Set `maxFaceValue` to really low value of 0.0012 when gas price is above 1 gwei
2. Observe `insufficient sender reserve` error in logs

**Expected behavior**
`faceValue` check to `txCost` should use an `avgGasPrice` that is a reasonable amount for Arbitrum.

**Additional context**
Ticket face value determined in `recipient.go` can return `insufficient sender reserve` error when ticket face value is set really low and gas prices start to spike.  See table below:

![image](https://user-images.githubusercontent.com/99882368/175434087-24acd1e2-f1a9-4654-8787-1263f726a21b.png)

**Comment by leszko** [comment]
I think, in the long run, I'd would be good to use the "real" avg gas price instead of the hardcoded `200 gwei`. However, as a quick fix, I think we could increase this value to `350 gwei`. (and maybe rename this variable `avgGasPrice` => `maxAvgGasPrice`). Wdyt @yondonfu

**Comment by ad-astra-video** [comment]
@leszko My last ticket redemption was https://arbiscan.io/tx/0xac6983f010081dc7c516001f0f753e1f993300991565434e489fe6d7d091850e

Paid 0.586694294 Gwei.

My screenshot is off above i see now.  Gas Price (WEI) should be Gas Price (GWEI)

**Comment by AuthorityNull** [comment]
This happened today as well to multiple orchestrators on different versions of Livepeer. Gas spike and most of us lost all streams. I was on 5.29.

**Comment by Franck-UltimaRatio** [comment]
I have been impacted without maxfacevalue set (linux, livepeer/0.5.32-0216d992). all streams down during a high gas spike.

**Comment by papabear99** [comment]
This appeared to hit all Os today. The exception was  ftk who was using `maxFaceValue` and had his streams spike while everyone else was reporting 0 sessions.  See discussion on Discord https://discord.com/channels/423160867534929930/932724294230900776/991399669609549895

**Comment by leszko** [comment]
The Arbitrum gas prices still seem to be really high. Today in https://cointool.app/gasPrice/arb, I see between `106-213 GWEI`.

The root cause of dropping streams is the combination of two factors:
- too high `avgGasPrice`
- too low B's deposit

Under the default conditions, face value equals to the B reserve allocation [1]. Then, we compare if face value isn't lower than estimated tx cost (calculated as `redeemGas * min(currentGasPrice, avgGasPrice)`) [2]. If that's the case, then O does not accept any streams, which makes sense, because if the tx cost is higher than face value, then transcoding will not bring any profit.

I suggest we decrease `avgGasPrice` from `200` to `120` AND increase B deposit in our Bs.

@yondonfu wdyt?

As a side note, if you use `maxFaceValue`, and it's lower than the B reserve allocation, then it makes the situation even worse, because it stops accepting streams with even lower gas price.

[1] https://github.com/livepeer/go-livepeer/blob/35560adb533e105c4521631580bb32202d82f4c3/pm/recipient.go#L276
[2] https://github.com/livepeer/go-livepeer/blob/35560adb533e105c4521631580bb32202d82f4c3/pm/recipient.go#L305

**Comment by leszko** [comment]
I observed the Arbitrum Gas Price for last 5h and here are the spikes.
<img width="729" alt="image" src="https://user-images.githubusercontent.com/2834997/176443787-c7960624-b0bd-4569-b3e9-880342a495b5.png">

You can see spikes up to almost `230`.

**Comment by ad-astra-video** [comment]
These gas prices are not historically what we have paid for transactions. 

Also the gas limit has reduced substantially on the last two winning ticket
transactions to around 55,000 to 60,000 compared to the 1,200,000 the
calculation in recipient.go uses. Not sure if this is permanent or just a temporary change on the gas limits for these transactions.
