### ISSUE TITLE
Investigate L2 Redeem Ticket Gas Consumption

### ISSUE THREAD

**Issue by leszko** [livepeer/go-livepeer#2483]
Currently we assume that redeeming a ticket always consumes a [constant and hardcoded gas amount](https://github.com/livepeer/go-livepeer/blob/d45fc4e5d9a932ecbb3c4b2bc7edadef8c6a35aa/cmd/livepeer/starter/starter.go#L49) of `1200000`.

According to what Vires [posted in Discord](https://discord.com/channels/423160867534929930/932724294230900776/991805247783706705), the gas consumption is not constant but can vary. We need to investigate how much the gas consumption can vary and decide how to act.

I suggest proceeding with the following steps:
1. Check recent ticket redemption txs and their gas consumption.
2. Check the ticket redemption txs during the last Arbitrum gas price spikes (on June, 28th and 29th)
3. Depending on the results, proceed with with one the following actions:
    - If tx gas consumption is always more or less `1200000` => do nothing
    - If tx gas consumption is more or less stable but different than `1200000` => send PR to update this constant
    - If tx gas consumption varies significantly => consider possibility of either dynamically calculating the current gas consumption or change the logic of how this constant is used.

Note that if we change significantly the value of `redeemGasL2`, then we may also adapt the `avgGasPrice` updated [here](https://github.com/livepeer/go-livepeer/pull/2481).

**Comment by yondonfu** [comment]
> we assume that redeeming a ticket always consumes a constant and hardcoded gas amount of 1200000

Adding some clarification here:

The hardcoded gas amount (both on L1 and L2) is used to estimate the tx cost of redeeming a ticket *before* valid winning ticket is actually received. If O has has access to a winning ticket already, then the node can just run gas estimation for the winning ticket redemption tx (under the hood this uses the `eth_estimateGas` RPC call) in order to calculate a mostly accurate estimate of the gas that the tx will consume if it were submitted. In fact, this is exactly what O does right before it submits any redemption tx in order to determine the value to set for the gasLimit field of the tx. If O does not have access to a winning ticket, then it cannot run gas estimation by simulating a tx. So, instead, O uses a hardcoded gas amount and multiplies it with the current gas price to estimate what the tx cost *might* be.

This method is less accurate especially since a hardcoded gas amount is used and we know that the redemption tx does not always consume a constant amount of gas (the actual gas consumed might be slightly higher/lower based on the ops that get conditionally executed in the contract). However, the original thought was that the hardcoded gas amount was good enough because even if the actual gas consumed fluctuates a bit it wouldn't ever be substantially different from the hardcoded amount.

The point raised in Discord was that the gas consumed could be *significantly* different due to gas price fluctuations. So, if this fact, would make the hardcoded gas amount method even less reliable if the actual gas consumed can be wildly different from the hardcoded amount.

**Comment by red-0ne** [comment]
Here is a [google sheet](https://docs.google.com/spreadsheets/d/15p1cHuBTX5Vfj5THlLByuQeGEKOcjSwhzDEtbw4FpOQ/edit?usp=sharing) listing ticket redemption from 2/15/2022 until 7/2/2022.

The first histogram counts txs by gas used while the others shows redemption gas usage over time. The last one zooms into the 6/28-29/2022 date range.

Min gas used: 30339 (these low usage seem to be special cases)
Max gas used: 1383350
Avg gas used: 1125259.134

**Comment by leszko** [comment]
Thanks for the data @red-0ne . Looking at the data, it seems that the gas amount is more or less stable (and correct with what we have hardcoded). The only exception is when there are gas price spikes. I think we can leave it as it is for now and reopen the topics if there are more gas price spikes in the future.

**Comment by yondonfu** [comment]
@leszko Sounds reasonable. @red-0ne please close this if you believe it is done.
