### ISSUE TITLE
Create dms-uploader project

### ISSUE THREAD

**Issue by thomshutt** [livepeer/go-livepeer#2496]
* Create a new golang project
* Create a dummy CLI - e.g print "OK" when invoked with a certain flag
* Create an integration test for this CLI
* Set up Github Actions to build the project and run this test

**Comment by cyberj0g** [comment]
Project structure, command line handling, basic tests, reference Uploader implementation, workflow - [done](https://github.com/livepeer/dms-uploader/tree/main). Tried to make it a pull request to allow review, but instead messed up the repo, because there wasn't any commits there. Will ask someone with organization permissions to switch default branch back to `main`.

@thomshutt @leszko @RiccardoBiosas - please have a look.

**Comment by leszko** [comment]
Some comments:
- I think you could add a Makefile to simplify the building and testing process
- How do you run `dms-uploader_test.go`? I tried but it failed in my case
- I'm not sure what is the usage of the storage handler descriptions and why do we need it in JSON?

Also nit:
- I think you could stick to the "underscode" naming convention and rename `dms-uploader.go` => `dms_uploader.go`
- Also I guess you could rename `UploadWithContext()` => `Upload()`
- I'd probably not document options in README, because they will most probably change in the future which makes it hard to maintain
- Remove commented-out code, it's always misleading

**Comment by thomshutt** [comment]
Looks great! Agree with what @leszko said plus:

* I think we should split the handlers our from handlers.go into a `handlers` package and then have separate files for e.g `handlers/s3.go`
* Since it's a small standalone binary, let's try getting rid of levelled logging to begin with (can always bring it back in in the future if needed) and try more of the approach described in https://thomshutt.github.io/opinionated-logging-in-go.html
