### ISSUE TITLE
Transaction Gas Adjustment

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#25]
During testing, we'll get this error sometimes: `exceeds block gas limit`, especially when calling `verify()` very rapidly.

How do we adjust the gas per transaction in this case?

**Comment by ericxtang** [comment]
Currently we assign a hard gas limit.  I'm not sure if dynamic gas adjustment is easy to implement (or even that useful...).  Should we close this?  cc @dob @yondonfu

**Comment by yondonfu** [comment]
Ideally we would use the `eth_estimateGas` RPC method + some additional % as a buffer which is the default behavior of the Go contract bindings if you don't manually set the gas limit, but we previously ran into some issues with the gas estimation for function calls that involved internal transactions. I can do some testing to see if that issue is still present and if the gas estimator is a viable option.

**Comment by yondonfu** [comment]
Switched to using `eth_estimateGas` RPC method + some additional % as a buffer to set the gas limit on transactions in #317 - have not observed this issue so closing for now
