### ISSUE TITLE
'Failed: insufficient funds for gas * price + value' - Cannot process transactions after Nitro upgrade 

### ISSUE THREAD

**Issue by AuthorityNull** [livepeer/go-livepeer#2574]
**Describe the bug**
After upgrading to Nitro, some orchestrators including myself cannot execute transactions like calling reward or redeeming a winning ticket. 

Initially, the error looked like this:
```
HTTP Response Error 500: Error calling reward: gas required exceeds allowance (152271)
```
Upon node restart, the error evolved into this:
```
 ******************************Eth Transaction******************************
Aug 31 17:21:42 lpr-Not-Specified livepeer[554821]: Invoking transaction: "rewardWithHint". Inputs: "_newPosPrev: 0xE3a5793d7c1D2a04A903FA1695b3E3555d6084CA  _newPosNext: 0x4a43B1D7e62                   27C8b0512e413F406555647ff7bdB"
Aug 31 17:21:42 lpr-Not-Specified livepeer[554821]: Transaction Failed: insufficient funds for gas * price + value: address 0x9D61ae5875E89036FBf6059f3116d01a22ACe3C8 have 604543848649                   53520 want 266627000000000000
```
Or, on the node trying to redeem a winning ticket, this:

```
Invoking transaction: "redeemWinningTicket". Inputs: "_ticket: { Recipient: 0x9D61ae5875E89036FBf6059f3116d01a22ACe3C8  Sender: 0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E  FaceValue: 12000000000000000  WinProb: 9649340769776349618630915417390658987772498722136713669954799000000000000  SenderNonce: 1  RecipientRandHash: 0x83fe58b22811435b18d0c2b90eba17206f612f1072f2805fa792c808d06a0170  AuxData: 0x0000000000000000000000000000000000000000000000000000000000000a7a613ebf57b80834b99a2ec150ea7b2b0cb97419d0c2d31dfeca4659fc6a92688e }  _sig: 0x1f956188526c89394e467aecd529669c65b5c5a5913079721585486dee654ccc1dd79c631f18385e1aeb079634202328ce3d85345ccc9e22e0b51d8f7694da5c1b  _recipientRand: 55259894694139197534321694537779125253224093903070031163731600211776028401548"
Transaction Failed: insufficient funds for gas * price + value: address 0xcdF93B13EFCf63f84f2afFB01BeC48A5c096C69E have 25795810339399299 want 328761600000000000

***************************************************************************
E0831 22:08:41.746572       1 queue.go:149] Error redeeming err="insufficient funds for gas * price + value: address 0xcdF93B13EFCf63f84f2afFB01BeC48A5c096C69E have 25795810339399299 want 328761600000000000"
```
It looks like it's requesting an absurd amount to redeem a winning ticket or call reward, and the cost seems to get higher over time.
We've tried multiple RPC providers (Alchemy, offchain, full arb node) and restarting our nodes but have not had any success.

We CAN, however, call reward normally via https://arbiscan.io/address/0x35Bcf3c30594191d53231E4FF333E8A770453e40#writeProxyContract

My node setup:
Independent local Ubuntu node for calling reward
7 Dockerized Geolocated O/T's 

Upon talking to other O's using similar setups, this does not seem to be an issue that affects them. 
We also had no issues prior to the upgrade.

**To Reproduce**
1. Call reward or redeem a winning ticket
2. Observe logs
3. If the transaction completes normally, you're not affected by this
4. If you see the error listed above, you're in the same boat as me and some others... sorry

**Expected behavior**
Transactions should process normally after the Nitro upgrade.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04.1

**Additional context**
It's hard to see how this could be a configuration error on the orchestrators side, as this started immediately after the Nitro upgrade and several RPC providers have been tested, none of them resolving the issue, while other orchestrators don't seem to have a problem.

**Comment by Franck-UltimaRatio** [comment]
Got the same error on all our nodes. May be this error affect all orchs, but if you have enough ETH in your orch wallet (over the "want" requirement), i think the transaction could succeed.
We have deploy the fix by Yondon, waiting for the next call reward/ winning ticket to see if it s work.

**Comment by yondonfu** [comment]
Looks like the new Nitro node release https://github.com/OffchainLabs/nitro/releases/tag/v2.0.1 should've resolved the gas over-estimation issues that folks have been encountering

**Comment by AuthorityNull** [comment]
Got the same error today when redeeming a ticket in Singapore, and I'm on the latest nitro release

**Comment by leszko** [comment]
> Got the same error today when redeeming a ticket in Singapore, and I'm on the latest nitro release

Did the fix from Yondon help?

**Comment by Franck-UltimaRatio** [comment]
Same error this morning on a winning ticket. Yondon's fix did not help. we have added some fund to redeem the ticket.

**Comment by red-0ne** [comment]
Need to reproduce the isseue, could we have the txhash of one of these expensive redemptions?

**Comment by Franck-UltimaRatio** [comment]
Sep 02 04:15:59 Los-Angeles livepeer[13265]: Invoking transaction: "redeemWinningTicket". Inputs: "_ticket: { Recipient: 0x2e3a21ae7cDEb48F57fcaD1cE16b258d5502aC05  Sender: 0xc3c7c4C8f7061B7d6A72766Eee5359fE4F36e61E  FaceValue: >
Sep 02 04:15:59 Los-Angeles livepeer[13265]: Transaction Failed: insufficient funds for gas * price + value: address 0xC4ea4fa2c0ebba54c09dddBD4D462FaDA562203E have 16143245283882536 want 85835300000000000

This is the error spamed by our LA node this night until we add some ETH to the wallet.

after that, the TX succeed :
https://arbiscan.io/tx/0x477483b3a62635b1a4cab5894ccff9f6cde1a49c295eb76c9f81074b15d0609a

**Comment by leszko** [comment]
Assigning this task to @yondonfu for now, but Yondon feel free to write any analysis here and I can take it over on Monday morning.

**Comment by yondonfu** [comment]
I have not been able to reproduce this yet. The main question is whether the overestimation is caused by something on the Nitro side vs. something on the go-livepeer side with the suspicion being that it is the former. The original thought was that the https://github.com/OffchainLabs/nitro/releases/tag/v2.0.1 release addressed this, but others reported encountering this issue even after they pointed their orchestrator at a v2.0.1 Nitro node. There was another Nitro release https://github.com/OffchainLabs/nitro/releases/tag/v2.0.2 - I'm not sure if this would have a fix because I commented on https://github.com/OffchainLabs/nitro/pull/1065 and the code change that seemed relevant was fixing a problem with underestimation as opposed to overestimation...But, might be worth trying out that release for orchestrators using a self-hosted RPC as well.

And noting that I believe for those that have encountered this issue recently the problem was that the gas required for the tx was overestimated resulting in the estimated tx cost being quite a bit higher than the actual tx cost. Since the actual tx cost was substantially lower than the estimated tx cost the workaround was to add more ETH to the account balance so the estimated tx cost check would pass. Of course, this is understandably inconvenient as it requires additional ETH to be added to the account balance, but noting this as a workaround if this issue is encountered again prior to having confirmation of a solution.

**Comment by Franck-UltimaRatio** [comment]
for information, i have just checked during the last call reward if an RPC using 2.0.2 fix the problem. It did not.

**Comment by Franck-UltimaRatio** [comment]
so, still the same error during the last call reward, on 2 nodes running linux with V 0.5.34 and around 0.02eth on there wallets. 
On a node running V 0.5.34 on windows, no error. so the bug seems linked only to the linux version, and impact you only if you have a low amount of ETH on your wallet (cause if you have enough, the bug appear but the TX succeed at the normal price)

**Comment by papabear99** [comment]
I just ran into this as well running .34 in docker with an up to date v2.0.2 arb node. I only had  0.012 ETH in my wallet so the ticket failed to redeem.

I didn't see the initial failed transaction but caught this error spamming my log.

```
E0904 16:45:43.099436       1 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
I0904 16:45:52.590379       1 block_watcher.go:567] Polling blocks from=22835923 to=22835945
I0904 16:46:02.591828       1 block_watcher.go:567] Polling blocks from=22835947 to=22835960
E0904 16:46:03.003433       1 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
I0904 16:46:12.591902       1 block_watcher.go:567] Polling blocks from=22835962 to=22835997
E0904 16:46:12.912342       1 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
```
>The main question is whether the overestimation is caused by something on the Nitro side vs. something on the go-livepeer side with the suspicion being that it is the former. 
> 
Since this doesn't appear to be an issue for nodes running Windows I don't think it's on the Nitro side.

**Comment by papabear99** [comment]
>The main question is whether the overestimation is caused by something on the Nitro side vs. something on the go-livepeer side with the suspicion being that it is the former. 
> 
Since this doesn't appear to be an issue for nodes running Windows I don't think it's on the Nitro side.

**Comment by papabear99** [comment]
> On a node running V 0.5.34 on windows, no error. 

I can also confirm that I was able to redeem a winning ticket on a Windows node with just a small amount of ETH in the O's account.

**Comment by leszko** [comment]
I did a little investigation and from my understanding the issue is in Arbitrum or in the `go-ethereum` library, but not in the `go-livepeer` code.

Here are some thoughts:
1. I don't think we use the account ETH balance anywhere while sending the transaction. Since the issue occurs **ONLY** when the ETH balance is low, then I think it can't be related to `go-livepeer`.
2. We do use the ETH balance, but only to decide if to accept a new stream. But from what I see, all issues described above are about executing transactions, not about accepting streams.
3. There is no different logic for Unix/Windows in `go-livepeer` when it comes to executing transactions.

I think what we should do is to:
1. Wait some time for Arbitrum, hopefully they'll address the issue; if not, then
2. Try updating the `go-ethereum` dependency to Arbitrum fork of `go-ethereum` and see if the issue persists. I believe it's possible that the issue is in `go-ethereum` dependency.

**Comment by Franck-UltimaRatio** [comment]
"I don't think we use the account ETH balance anywhere while sending the transaction. Since the issue occurs ONLY when the ETH balance is low, then I think it can't be related to go-livepeer."

to be clear, the error occurs every time a transaction is initiated (estimation gas price), but only appears in the logs if it causes problems because there is not enough funds in the wallet to cover the gas estimation error.

**Comment by yondonfu** [comment]
@Franck-UltimaRatio @papabear99 @AuthorityNull 

Are the nodes that encountered the `failed insufficient for gas * price + value...` error using the `-maxGasPrice` flag? If so, can you:

1. Share the value used for the `-maxGasPrice` flag?
2. Try setting `-maxGasPrice 1000000000` (1 gwei which is still quite a bit higher than the typical gas price on Arbitrum right now) and share back if you still encounter the issue?

**Comment by papabear99** [comment]
I am using the `-maxGasPrice` flag .  

It was/is set to 1500000000 (1.5gwei)

Added:
FWIW
On the node running Windows it was set to 5000000000 (5gwei)

**Comment by Franck-UltimaRatio** [comment]
yes, was set at -maxGasPrice 60000000000

**Comment by AuthorityNull** [comment]
@yondonfu My maxGasPrice was set quite high on my reward calling node. Yesterday, I lowered it to 1 gwei and removed most of the ETH from my wallet to test. Today, I was able to call reward automatically so you may be onto something there.

**Comment by Franck-UltimaRatio** [comment]
and now i can't redeem a ticket on a node with 0.11 ETH on it with this error :
Sep 07 14:45:45 newyorkcity livepeer[201653]: E0907 14:45:45.161247  201653 queue.go:149] Error redeeming err="gas required exceeds allowance (1148514)"
maxGasPrice set to 100000000000
I removed the maxGasPrice flag, restarted the node, and.... redeemed ! so definively onto something here ;)

**Comment by papabear99** [comment]
> 100000000000

That's 100 gwei.  I think it's using the `maxGasPrice` value to estimate the transaction fee.  That's probably why it's working for Authority Null after he lowered his to 1 gwei.  The ticket I won this morning was on my Windows node so I still haven't been able to confirm.

**Comment by yondonfu** [comment]
I think the root issue was that an account needs to have a balance with at least `gas used by tx * gas price bid` during tx processing. At the moment, if you set `-maxGasPrice` then your account will need `gas price bid = maxGasPrice` when the tx is processed. So, if you set `-maxGasPrice` to be really high (i.e. 100 gwei), then your account will need a much higher balance even though the actual gas price paid will be substantially lower. In practice, your account will be refunded once the tx is complete such that the fee charged will be less than `gas used by tx * gas price bid`. However, during tx processing your account will need to have a balance that is at least `gas used by tx * gas price bid`.

I just pushed some code in https://github.com/livepeer/go-livepeer/pull/2583 that should update the node behavior so that you can continue to set `-maxGasPrice` with the expectation that the value will be the absolute maximum max gas price that the node will ever be willing to use *and* the node will try to use a lower gas price bid when possible (it will be lower than `-maxGasPrice`, but enough for the tx to be processed quickly).

Here are some builds from that code for testing:

Linux ARM64: https://build.livepeer.live/go-livepeer/0.5.34-19fdf2e0/livepeer-linux-arm64.tar.gz
Linux AMD64: https://build.livepeer.live/go-livepeer/0.5.34-19fdf2e0/livepeer-linux-amd64.tar.gz
Windows AMD64: https://build.livepeer.live/go-livepeer/0.5.34-19fdf2e0/livepeer-windows-amd64.zip

@Franck-UltimaRatio @papabear99 @AuthorityNull When you get chance could you try this build while using whatever `-maxGasPrice` flag that you were previously using? If this works for you, then we'll aim to get these changes included in the next release.

**Comment by Franck-UltimaRatio** [comment]
i have just deployed this version on our redeemer nodes and reduce the amount of eth on them. waiting for the next call reward. i ll let you know asap in 21 hours. Thanks

**Comment by AuthorityNull** [comment]
> i have just deployed this version on our redeemer nodes and reduce the amount of eth on them. waiting for the next call reward. i ll let you know asap in 21 hours. Thanks

You can skip the wait by processing any transaction (like option 13) from the CLI. If it goes through, we're good.

**Comment by Franck-UltimaRatio** [comment]
I can confirm the fix is working, call reward  was succesfull this morning with -maxGasPrice set at 60000000000 and 0.02 ETH on the wallet

**Comment by yondonfu** [comment]
Thanks for all the reports. This issue has been fixed in https://github.com/livepeer/go-livepeer/pull/2583 and the fix will be included in the next release.
