### ISSUE TITLE
Restream RTMP to Other Destinations

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#270]
Allow the Livepeer node to stream incoming streams to multiple destinations.  This is useful because it allows anyone to stream into Livepeer AND Youtube(or Twitch, etc) at the same time.

**Comment by dob** [comment]
We should definitely have this feature as an option, but curious on @chrishobcroft perspective...I'm not sure you've ever tried multiple destinations concurrently, but do think that bandwidth limitations would be an issue in a practical setup?

**Comment by j0sh** [comment]
Would be a nice feature to have. 

> do think that bandwidth limitations would be an issue in a practical setup?

My suspicion is that broadcasters who are serious about this would (should?) situate their nodes somewhere with good connectivity, even if the source stream originates from, say, a home Internet connection and WiFi.

**Comment by watchcoin** [comment]
I don't know if I would prioritise the development of something that allows people to keep feeding content to a centralised mechanism as well as Livepeer, although there are pros and cons.

Pros: it allows people to easily add us as a broadcast medium (which restream.io enables)

Cons: it doesn't encourage creators to cut the umbilical.

My preference would be to prioritize mechanisms where it would be possible to re-stream a Livepeer channel to other Livepeer channels, enabling things like:

1. Curation - I want to re-stream someone else's content on my channel, so that e.g. livepeer.tv could show a stream from Berlin 6-7, then a stream from Rio 7-8, then a stream from Sydney 8-9. Kinda like a real time retweet.

2. Enabling smart contracts to facilitate this, e.g. if you stream from 8-9pm via node 0x123... then I will pay you / you will pay me tokens to re-stream via node 0x456...

I believe this can open up a whole new world of mechanisms for monetising livestreaming content in real time, which in turn can drive the value of Livepeer token.

But this is probably another protocol, right? :|

**Comment by dob** [comment]
@watchcoin I think the channel curation and splitting of funds are not necessarily another protocol - they're just a great application to be built on top of Livepeer. You can think of the current player at media.livepeer.org as one such application, and the above are just features of it...or another application. 

That application would let the users configure a smart contract that splits the funds, and donations flowing to the smart contract address would be split according to the rules in the smart contract. Similarly, the application would read the curation info from a smart contract, and a curator would be someone authorized within the smart contract to update the curation info. Etc. All good ideas that just need product focus and execution.

**Comment by yondonfu** [comment]
This is currently supported by https://github.com/livepeer/livepeer-com so closing for now and if there is interest in something more tightly integrated into the node a separate issue can be created.
