### ISSUE TITLE
Cannot assign streamID via hlsStrmID parameter 

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#296]
We used to be able to assign the streamID via hlsStrmID in the RTMP, but it's reported that no longer works

**Comment by adamsoffer** [comment]
Steps to reproduce:

![hlsstreambug](https://user-images.githubusercontent.com/555740/36131559-4fca01aa-1040-11e8-960b-f35589b4bee6.gif)

In the end, the stream doesn't play with the `ffplay` command. It just hangs.

Note: this bug was introduced with v0.1.4. Reserving a stream ID worked in previous versions.

**Comment by adamsoffer** [comment]
I just tested this again on Rinkeby and I'm still encountering this issue. The only difference is that now when I attempt to play the stream with ffplay it freezes and force quits. Works fine when I don't pass in the stream ID, however. Let me know if you're also able to reproduce.

**Comment by adamsoffer** [comment]
Ah nevermind. Looks I simply wasn't adding enough random characters to the end of the hlsStrmID. I was only changing the last character which for some reason didn't cut it.
