### ISSUE TITLE
Output / Recording Integration

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#31]
The Livepeer network should be able to output a live stream into a storage solution.

Currently the best way to do it is using the broadcasting software (for example, OBS allows you to broadcast and record at the same time).  

But we should also plan to integrate with cloud solutions like Swarm, IPFS, and S3.

**Comment by chrishobcroft** [comment]
I would like to request that by default, Livepeer does NOT record, due to the value to a broadcaster of being able to retain full ownership / control over their content after they've streamed it (obviously, anyone can "consume the stream into a file").

BUT THEN to offer the option on top to save to a decentralised storage platform.

But the option to not save anywhere (except locally) should be always possible.

**Comment by dob** [comment]
@chrishobcroft Yes, agree 100%. Livepeer will not record by default. It is just an option that a broadcaster can choose/pay for (if there is a cost to using a service like Filecoin or S3).

**Comment by j0sh** [comment]
Agreed that we won't record for broadcasters by default. Note that there are a few caveats to this:

1. Transcoders and broadcasters do record segments to disk and store them until the stream is over, then they're deleted. In the future this will be changed to a rolling cleanup where segments are deleted after verification completes. Right now, we can't really avoid writing to disk for resiliency, even though the intended purpose is not long-term storage. Related: https://github.com/livepeer/lpms/issues/46

2. There's not much preventing an unscrupulous transcoder, verifier, relay, viewer, etc from recording your streams (or saving segments rather than deleting them). Solving this problem is hard.
