### ISSUE TITLE
Proposal: Restartable Broadcasting

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#316]
One of the fundamental bottlenecks of our protocol right now is the initial job creation.  Because of the low transaction throughput of the Ethereum blockchain, it can take up to minutes or even hours for a transaction to go through.  This highly disrupts the live streaming experience.

One way to look at this problem is our assumption of a "job" being a single live video session.  If every new live video session depends on a new job being created, the throughput of the Livepeer network highly depends on the throughput of the Ethereum network.

But another way to look at a "job" is an open channel between a broadcaster and a transcoder.  In this paradigm, a broadcaster can have many consecutive live video sessions on the same "job", before the `endBlock` of the job.  This means a broadcaster can create a job anytime, and stream to the transcoder during the entire duration of a job.

This implementation requires a few changes in the `go-client`.  The broadcaster has to remember the latest segment number from the last stream so the transcoder can use the new segment numbers to make the claims.  The subscribe/broadcast pattern also needs to change to give the broadcaster to initiate a new video stream to the transcoder (currently the transcoder has to first subscribe from the broadcaster, but the transcoder will not know when the new video sessions start).

This proposal is prompted by our Rinkeby testnet experience so far - sometimes the job creation transaction takes minutes, sometimes it simply never gets processed (I'm assuming it's just sitting in to txpool)

**Comment by yondonfu** [comment]
Interesting - so a single on-chain job becomes a "contract for work" of sorts with a transcoder during the time period from the time of job creation until the job's `endBlock` with the possibility of multiple streams being sent to the transcoder for processing by the broadcaster during that time.

Some initial thoughts:

- The broadcaster would have to use the same transcoding options for each stream in a session with a transcoder since verification is currently based on the transcoding options set when the job is first created. Could get around this, but would require a contract change
-  The broadcaster has to start streaming within 256 blocks (around an hour) of the job's creation so that the transcoder can make its first claim within that time
- I think this would break the current player since it uses the on-chain job to retrieve the streamID, but in the case where a broadcaster has started a second stream with the same job, the second streamID (and subsequent ones) is never posted on-chain

**Comment by j0sh** [comment]
Good idea: the job creation transaction is distilled down to depositing ETH for escrow and setting the job parameters.

What if the actual broadcast doesn't begin (or continue) until some time in the future and the transcoder set changes? How do transcoders get assigned work? This magnifies a few different flavors of the transcoder availability issue:

* The currently assigned transcoder may not be in the pool anymore (before endBlock)
* Decoupling workload from assignment: transcoders will be assigned work during various rounds, but have to serve jobs on demand. This demand could come all at once (eg, Tuesdays at 8pm).

Since transcoders would still be limited to making claims within 256 blocks, perhaps we could also allow 'empty claims' (with a segment range of 0-0) so the transcoder can claim the job, then wait indefinitely for segments to start coming in. This relieves a bit of the pressure on the broadcaster so they don't have to start streaming within ~1 hour, while signaling transcoder acceptance.

The drawback is, if the transcoder doesn't pick up the job (because they are offline, busy, etc) then the broadcaster would have lost the gas they burned on the transaction. (We have the same basic availability problem right now though.) Is there some way we can make it so that the transcoder is assignable from the *latest* block if the job is unclaimed after 256 blocks?

**Comment by ericxtang** [comment]
@yondonfu 
* re: transcoding options - it might be ok for now.  One way to get around this is to have multiple jobs open, each with a different transcoding profile.
* re: 256 blocks.  This is an issue... I can see in the long term, we change the contract to have the transcoder do a "confirm" transaction within 256 blocks just so the transcoder field in the job is populated.
* re: stream ID issue - The broadcaster would have to use the same streamID (since it's associated with the job).

**Comment by ericxtang** [comment]
TODOs:

- [ ] 1. Temporarily limit the broadcaster to a single broadcasting stream (the current workflow assumes this anyways)
- [ ] 2. Broadcaster remembers the last job it created.  When it receives an incoming stream, check the end block.  If it's not finished yet, re-use that job.
- [ ] 3. Broadcaster remembers segment numbers, so when re-using a job, it'll start with the segment number that's +1 ending segment from the last stream.
- [ ] 4. Broadcaster can signal a transcoder to do work offchain.  The broadcaster should check and make sure Transcoder is still active.  The transcoder will check that it is indeed the assigned transcoder, and subscribe to the broadcasted video stream.  


I think the implementation of 1 - 3 are fairly straight-forward.  We can leverage the node db code @j0sh has been work on.

for 4, we can either add an HTTP endpoint on the transcoder, or add a `TranscodeReq` to `basicnet`.  I think adding to `basicnet` makes things more consistent for now, and we can think about how to change our networking strategy after more discussion.

**Comment by yondonfu** [comment]
Regarding 4, we should also make sure that the transcoder is still registered and bonded. No work can be claimed unless the transcoder is registered (and registration requires being bonded). Additionally, a broadcaster wouldn't want to interact with an unbonded transcoder anyway due to the nothing at stake problem.

**Comment by j0sh** [comment]
The steps seem reasonable. Regarding step 4, if there's a possibility these changes may be short-lived, I'd rather spend a little more time up-front on the network strategy. Then priorities such as this issue can inform how we approach the implementation.

**Comment by chrishobcroft** [comment]
The other day, I waited for 6 minutes for Rinkeby to confirm a transaction to "start streaming".

It wasn't very satisfying :|

**Comment by j0sh** [comment]
About point 2:

> Broadcaster remembers the last job it created. When it receives an incoming stream, check the end block. If it's not finished yet, re-use that job.

For completeness, we should make sure the transcode options match the broadcaster's current preferences. If there's no match, create a new job. Most likely requires https://github.com/livepeer/go-livepeer/issues/390 . 

Price should probably also be included in this check as well. That would allow broadcasters to create a new job if they are able to get a better deal on transcoding.

This doesn't need to be implemented right now, but will be important once users start adjusting broadcast prefs. By that point, we might also have gas accounting (in which case, how we handle broadcast prefs is likely to look very different).

**Comment by j0sh** [comment]
Implemented in https://github.com/livepeer/go-livepeer/commit/2e9b5dacb961d2027d189c7603bdf07220dce121
