### ISSUE TITLE
Manually start transcode job

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#329]
We currently rely on the transcoder listening to events on the blockchain for starting new jobs.  But any number of things can happen when a transcoder doesn't get the job.
* [The websocket connection was closed right before the job was assigned](https://github.com/livepeer/go-livepeer/issues/315)
* Transcoder needs to be restarted for some reason
* Network connection between the transcoder and the Eth network is somehow flaky
* Other situations that we haven't thought of

It'll be helpful to have a manual option to start a transcoding job given a job ID.  The transcoder can check and see if it's really assigned to it, see if it's already doing the job, and start the job if it has to.  Would be nice to have this feature for the network launch.

**Comment by yondonfu** [comment]
I think the one missing piece is: how does the transcoder know what job ID to pass in?

Perhaps an extension to this proposal that is related to #315 is that a transcoder keeps track of the last block that it was assigned a job and we introduce an option in the CLI, something like "Sync Jobs". When that option is triggered, the transcoder can filter for job events from the last block that it was assigned a job until the current block and check if it was assigned to any of them and start doing work for the job. There could also be an automatic version of this such that every time a transcoder goes offline it stores its sign off block and when the transcoder boots up it scans the blockchain for jobs it was assigned to since its sign off block (if the transcoder crashed instead of gracefully shutting down it would have to scan for events starting from an earlier sign off block).

**Comment by ericxtang** [comment]
I like it!  Marking this a duplicate of #315

**Comment by ericxtang** [comment]
Duplicate of #315

**Comment by j0sh** [comment]
Since the node isn't listening for jobs from the blockchain anymore, should we close this ticket?
