### ISSUE TITLE
Failed to estimate gas needed

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#331]
I am attempting to `unbond` and to claim stake and fees on the leading transcoder node on rinkeby, running 0.1.14-unstable, and the transactions are not getting submitted. Instead I'm getting these console errors:

```
E0314 21:14:50.175921    4353 webserver.go:386] failed to estimate gas needed: gas required exceeds allowance or always failing transaction 
```

I have more than 5 ETH worth of gas available.

**Comment by ericxtang** [comment]
This is due to inaccurate gas estimation.  The short term fix is using `-gasLimit` to manually set a gas limit when starting the node.  The long term solution is to look into why this is happening - since the estimator is a part of `geth`.

**Comment by yondonfu** [comment]
The described error should be returned by the gas estimator if the transaction to be submitted would never be successfully executable - it is likely that this particular issue arose because the `unbond()` transaction was going to fail at the time and not because the gas estimator was giving a bad estimate.

**Comment by ericxtang** [comment]
Closing.
