### ISSUE TITLE
Enforce segment length

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#344]
Right now the transcoder doesn't check for segment length.  We should do that because pricing assumes a fixed segment length.  For now, the transcoder can simply stop doing the transcoding job.

**Comment by j0sh** [comment]
Note there is a way to eke out cheap transcoding if we're simply looking at timestamps: a broadcaster could feed in extremely high fps content, have it transcoded, then re-mux into the correct fps themselves later. This works since transmuxing is cheap but transcoding is not.

As far as I can tell by looking at pricing pages, most of the other encoding services have the same problem.

**Comment by j0sh** [comment]
There's a question of what should we do if a transcoder gets a segment that exceeds the allowable length (4 seconds in this case).

Can transcoders skip a specific claim (or a range of claims), continue listening for new segments, and transcode/claim whenever it gets a valid segment? If that's not possible right now, the sensible thing to do would be to un-subscribe and drop the job. @ericxtang @yondonfu 

Also, a separate issue, but it would be really good to be able to send feedback to the broadcaster about error conditions (eg, segment too long, input format not valid, etc).

**Comment by ericxtang** [comment]
@j0sh currently transcoder can skip any segment it wants.  I think we probably want to accept some delta here - encoders are never 100% accurate, so if we got a segment that's 4.5s or 3.5s, it's probably ok.

Agree the error conditions should be reported back if possible. What do you think about adding a new msg type in basicnet that indicates transcoding error?  Not sure if it's the highest priority for now, but would be good to file an issue so we remember.

**Comment by j0sh** [comment]
>  if we got a segment that's 4.5s or 3.5s, it's probably ok

Yup -- we have a 25% allowance here https://github.com/livepeer/go-livepeer/pull/351 (so in practice, 5 seconds or 300 packets, assuming 60fps)

> What do you think about adding a new msg type in basicnet that indicates transcoding error? Not sure if it's the highest priority for now

Yeah was thinking something like that. https://github.com/livepeer/go-livepeer-basicnet/issues/39

**Comment by j0sh** [comment]
So we've been talking about 4 second segments, but in other places we specify 8 second segments (thanks @yondonfu for finding this in https://github.com/livepeer/go-livepeer/issues/354#issuecomment-378426801).

Which one do we follow?

**Comment by ericxtang** [comment]
Let's do 4s segments.  Maybe we can even go to 1s segments... I know @f1l1b0x was mentioning that.  We only picked 8s segments because the CDNs suggested that.  But I recently realized how "flexible" their suggestions are...

**Comment by j0sh** [comment]
Curious what we'd gain from 1s segments. Lower latency? Here are some thoughts:

I don't know what's typical for VOD [1] but forcing keyframes every 1s would hurt compression for live streams [2][3] which are typically under stricter time/resource constraints. That also gives us less margin to handle fluctuations in throughput, before stuttering/stalls become noticeable, which live streams are again more sensitive to. Not to mention the additional traffic from fetching manifests and segments 4x as often, which is where I suspect the CDN recommendations [4] come from.

[1] Random sampling of two videos I had sitting around: Big Buck Bunny (480p) had keyframes exactly every 1 second, while Sintel (720p) had keyframes approx every 4s.

[2] OBS, with keyframes set to auto, emits keyframes depending on activity in the video but appears to be roughly every 4-8s. We need to update our guidelines to make it clear to users that their segments will be dropped with the default OBS settings.

[3] With CBR (which I believe is the OBS default) we'll get less bursty uploads. I think this alone negates any benefit we get from shorter segments (if short segments are meant as a smoothing mechanism); the overall rate should be roughly the same either way. More frequent keyframes generally impacts overall quality, due to the encoder needing to allocate more bits towards intra frames, but I'm not clear yet how short GOPs interact with CBR.

[4] Apple actually recommends 6s segments (but 2s IDRs, presumably to facilitate seeking, which doesn't really apply to us) https://developer.apple.com/library/content/documentation/General/Reference/HLSAuthoringSpec/Requirements.html

**Comment by f1l1b0x** [comment]
about the keyframe distance, it really should not be something that is fixed. 
Codecs use it to define a timeframe for compression efficiency and it differs from content to content and from situation to situation. Advanced transcodings always have variating GOP and picture profiles to be efficient. So whatever the GOP is it should fit to the content. We should recommend to encode at a maximum of "twice the framerate"  to keep our own end2end latency low. we should allow variating segment length and store absolute length of each segment for calculating the costs.  ha! sounds like we need a layer2! someone wants to spam bch?? ;)

**Comment by j0sh** [comment]
> about the keyframe distance, it really should not be something that is fixed.

Agreed 100%, especially for live streams.

The general consensus in the broadcast streaming community (which is distinct from the real-time streaming that I have more experience with) seems to be in setting CBR with a fixed GOP, and I think some streaming services might even enforce those configurations.

If we can avoid the CBR + GOP requirement, it'd help in many ways. We'd probably need to offer ingest in something other than HLS though, since segments need to begin on a keyframe [1]. Hence, we need a maximum GOP for now... 4 seconds good?

[1] mpegts is actually quite flexible as far as splitting and concatenation goes (due to the lack of global headers) so we could theoretically split segments at any point, including mid-GOP. However, that means keeping the decoder initialized in between segments, which would be a large departure from the current transcoder design. That's certainly something we can discuss, if the benefit seems large enough. Might be moot after gas accounting though, when we should have the ability to support arbitrary length segments.

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/351
