### ISSUE TITLE
Recoverable Error Conditions in Transcoder

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#359]
Which of these should be considered recoverable errors? https://github.com/livepeer/go-livepeer/blob/master/eth/eventservices/jobservice.go#L104-L183

Not that we'll attempt to recover immediately, but we should mark which jobs should not be retried after a restart.

Error | Y / N | Reason
--- | --- | --- 
Error getting broadcaster deposit |  Y | Likely connectivity issues with node
Broadcaster does not have enough funds. | N
Error processing transcoding options | N | Bad options won't change across restarts
Transcode Error | N | Not sure about this one; maybe?
Notify Broadcaster Error | Y | Likely networking related

**Comment by j0sh** [comment]
Implementation following the table above: https://github.com/livepeer/go-livepeer/pull/358/commits/14160667d3fed66a752a82c47b292ea701f8ab32

Can be fixed up as needed to match the conditions we agree on.

**Comment by ericxtang** [comment]
Hmm... Good question... I think the `TranscodeError` here really covers `TranscodeError` and `BroadcastError`.

I'm not sure how we are "recovering" the jobs though.  Should we recover jobs across different restarts?  It feels like for now, we should only recover if we are "in the middle of a job".

**Comment by j0sh** [comment]
Yeah, TranscodeError is the one I haven't quite figured out yet, in particular the part where it gets the broadcaster [1] from Basicnet; is that something a restart could possibly fix? Where does a `BroadcastError` come in?

Some of these errors may be network related, so it might not hurt to have the option to recover from those. We don't have to though, and can mark jobs as skipped if we encounter any form of error during the job setup phase.

> we should only recover if we are "in the middle of a job"

Being in the middle of the job technically means jobs with an `endBlock > currentBlock` . Or we can only try to recover jobs for which we've transcoded at least one segment, but that obviously leaves a (rather critical) window at the beginning where we wouldn't pick up legitimate jobs.

[1] https://github.com/livepeer/go-livepeer/blob/master/core/livepeernode.go#L171-L175

**Comment by ericxtang** [comment]
> in particular the part where it gets the broadcaster [1] from Basicnet

Each stream needs a broadcaster from `Basicnet` in order to be broadcasted to the network.  So each of the transcoded stream will need its own broadcaster.  It's interesting you bring up the concept of "fixing issues via restarts".  I haven't thought about that before.  But in this case, I think if we restart the node and want to continue to transcode a stream, we'll need to re-create new broadcasters for those streams.

I agree that we should restart all the jobs that have `endBlock > currentBlock`.

**Comment by yondonfu** [comment]
Re: TranscodeError and node restarts - I think its quite possible that after a restart a broadcaster for an existing job that you know about is no longer broadcasting via the streamID attached to the job which would lead to the TranscodeError when you try to get the subscriber from basicnet here: https://github.com/livepeer/go-livepeer/blob/master/core/livepeernode.go#L180. Additionally, it doesn't look like the error is handled here and the node will continue to try to use that returned subscription even if basicnet returns an error. Perhaps the error should be handled/passed up and the node can skip the job if it is unable to specifically subscribe to the stream. Alternatively, it could retry a number of times to get the subscriber from basicnet for a given streamID in order to gain additional assurance that is not some networking issue and after those number of retries, give up and skip the job.

**Comment by ericxtang** [comment]
@yondonfu what do you think about changing the broadcaster so that if it has created a job in the past, and the job is still active, and there is currently no active video stream using that ID, the new video will use the old ID to broadcast?  This would be a good step towards [Delayed Broadcasting](https://github.com/livepeer/go-livepeer/issues/316)

**Comment by j0sh** [comment]
Merged https://github.com/livepeer/go-livepeer/pull/358 , so closing this issue.
