### ISSUE TITLE
Policy for Minimum Segment Threshold

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#371]
Continuing the discussion from https://github.com/livepeer/go-livepeer/pull/365 in its own issue.

If we do have a minimum segment threshold, we also need to build in some sort of simple policy for dropping unreliable jobs. Otherwise we open up an easy attack vector: broadcasters can get free transcoding by feeding continuous video, but with the segments numbered discontinuously. From there broadcasters can re-assemble the transcoded segments using the known order.

A policy to start off with could be something like

```
if (totalClaimSegmentCost / estimatedGasCost <= factor) count++
if (count > threshold) dropJob()
```

with `threshold` and `factor` being configurable, say 5 and 2.5.

On Rinkeby, a `claim` transaction took 231280 gas [1]. I haven't checked yet to see if this is consistent across various claims. We could also drop `factor` entirely and use `estimatedGasCost` alone and incorporate an appropriate fudging, if the gas cost is a fixed quantity. The check would become
`if (estimatedFudgedGasCost >= totalClaimSegmentCost) count++`

Is there a way to charge the broadcasters `max(gasCost, totalClaimSegmentCost)` ? I imagine that accurately estimating the transaction gas cost in the middle of the transaction itself might be tricky.

Maybe we could also set a minimum segment cost globally -- a contract parameter that approximately reflects the gas cost of a claim. Transcoders would still need to enforce a policy to be profitable, but at least they would break even on gas costs. Especially since transcoders can't really determine whether to drop a job until *after* they've transcoded a few segments; they should still get paid for those (or rather, the broadcaster should still pay, even if the transcoder only breaks even).

[1] https://rinkeby.etherscan.io/tx/0xd1542d86c02c5cf1a7bced168315d6dfb1e0bbe92d4187ac7f07cd0409c9995b

**Comment by dob** [comment]
This is a great start. I'd suggest not putting anything on chain related to transcoders managing this however, and instead give them configuration options when starting their node to let them customize their own params (with sensible defaults).

For example in ETH mining miners end up writing their own custom logic as to what transactions to include in blocks based upon gas prices, mempool state, etc. I'd imagine it would be similar here. One simple default would be that they set two params: 

* minimum consecutive segments to claim (example: 25)
* segment range length without a claim in order to cut off a job (example: 75)

if they've done 75 segments of work and haven't received 25 consecutive, just drop the job.

it might be gameable at the start to a certain extent, but if these params are configurable via a flag people could adjust accordingly...and hopefully people will fork and implement custom, far more intelligent logic and contribute it back.

**Comment by j0sh** [comment]
That's one way to do it. Without considering in the estimated gas cost (which can be done off-chain), the minimum margin for a claim could fluctuate based on a number of variables: the price per segment, the number of encoded profiles in a segment, the cost of a transaction in g/wei, and the dollar price of eth. Factoring all that in and setting a minimum margin (the `factor` in my pseudocode above) at least makes the parameters a bit more set-and-forget.

Perhaps we don't want to set a minimum segment cost on-chain (but such a minimum would be quite below the expected value of a 'normal' claim transaction), but I do wonder if we should still get the broadcaster to pay for the work, and cover the tx as a disincentive. In the 75/25 example, the transcoder would effectively be doing 5 minutes of work for free, with 4 second segments.

**Comment by ericxtang** [comment]
This is going to be moot with PM.  Should we remove it?

**Comment by j0sh** [comment]
Yup.
