### ISSUE TITLE
Refactor video processing work flow

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#413]
The transcoding workflow is starting to get a little complex.  For example, tracing through "RestartTranscoder" is hard.  It calls `doTranscode` on the `JobService`, which calls TranscodeAndBroadcast and subscribes to the network stream.

A more native golang way to do this is with workers and channels.  The transcoder contains a worker pool and has a channel for incoming transcoding work.  The broadcaster contains a worker pool and a buffered channel for broadcasting transcoded segments.

**Comment by j0sh** [comment]
Agreed that tracing through the code is a bit unwieldy.

Note that without a very thorough refactoring, simply replacing function calls with channel invocations is prone to make things more difficult to follow, since it won't be as straightforward to determine where the next step of the processing takes place.

I'm not sure if there's a code quality metric to determine coupling that'd be applicable here (cyclomatic complexity?), but there are a couple things we can try to consider minimizing when refactoring:

* The depth of the backtrace for a job, including within livpeeernode and TranscodeAndBroadcast
* The breadth of function calls, especially cross-module calls among the job service, ethclient, livepeernode, claimmanager, etc.

Of course, this may be easier said than done, since certain things have to be done in a specific sequence.

**Comment by j0sh** [comment]
The code path as described in the issue doesn't really exist anymore, so closing for now. If there is still a need for refactoring the transcoder workflow, we can discuss it in a new issue.
