### ISSUE TITLE
Eliminating Sequence Numbers from Claims

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#418]
Wild idea: eliminate sequence numbers from claims. Or at the very least, we should leave seqNo generation to the transcoder, not the broadcaster. The latter method should mean that no changes to the smart contract protocol are *required*, as far as I understand it.

This would minimize several classes of of concerns.

* Eliminates any possibility of a broadcaster griefing attack with recycled sequence numbers. This is something the current code handles already, but we have to be careful about the checking, now and forever. [2]
* Completely eliminates any concern about segment numbering thresholds. https://github.com/livepeer/go-livepeer/issues/371
* Simplifies https://github.com/livepeer/go-livepeer/issues/316 a little bit
* Not all segments would necessarily be sequential, eg 3D video (quite speculative, as we don't support this yet)

Manifests can still be constructed from segments in FIFO order as they are now.

This could complicate claims checking -- verification should remain unchanged as long as we keep some semblance of sequence numbering. However, we already depend on external watchers for monitoring double claims. This watcher could fetch the Merkle leaves (or the entire tree) for each claim [0], and ensure that the broadcast-related fields (hash + sig) are valid and unique for the entire job [1]. Merkle proofs from two claims with the same leaf would constitute fraud. That entails more overhead for the monitor to acquire and store the hashes themselves (and perhaps do spot checking of the transcoded segments if it's subscribed to the stream), but overall it seems tractable.

[0] The watcher could also get a reduced version of the tree with just the broadcaster's segment hashes + sig. A reduced version might require a protocol change, to submit a URI/IPFS address somewhere. Since we're already putting a certain amount of faith that the transcoded hashes aren't replayed, maybe the entire receipt would be best.

[1] We'd have a problem with Merkle tree availability, in that we'd need to prove that the Merkle tree was available for checking at the time of claiming. However, the same basic problem exist today with segment availability.

[2] Perhaps not. At least with the current proposal, we could have a different type of broadcaster griefing attack where broadcasters replay identical segments. So the transcoder might have to store and check the segment hash or signature regardless.

**Comment by yondonfu** [comment]
> Or at the very least, we should leave seqNo generation to the transcoder, not the broadcaster. The latter method should mean that no changes to the smart contract protocol are required, as far as I understand it.

Seems like the latter method would require a smart contract change because the broadcaster signs `(streamId, seqNo, dataHash)` and that signature is checked if a particular segment is challenged for verification so this would force the broadcaster to still be the one to generate seqNo and then include it in its signature.

> This watcher could fetch the Merkle leaves (or the entire tree) for each claim [0], and ensure that the broadcast-related fields (hash + sig) are valid and unique for the entire job [1]. Merkle proofs from two claims with the same leaf would constitute fraud.

I'm wary of data availability here - we could make the transcoder publish the leaves (or branches) of the Merkle tree for each claim, but unless all the data is put on-chain the transcoder could withhold it from the watcher such that the watcher would be unable to construct the fraud proof. As you pointed out we do already have the segment availability problem today, but at least for the double segment claim slashing condition, a watcher today doesn't actually need the published segments since it has all the necessary data on-chain to prove a transcoder double claimed a segment (if two claims are for overlapping sequence number ranges). 

I know we currently don't have any protection against a transcoder just publishing a stream with transcoded segments that do not match up with the order of the original segments in the broadcaster's stream, but at least currently, there is some reference for what the original order of segments was since the broadcaster includes the sequence numbers in its signature. It seems like by allowing a transcoder to generate the sequence numbers, we lose this information.

**Comment by j0sh** [comment]
By having broadcasters signing the seqNo+segment is that we're assured the broadcaster has sent at least that many segments at the point of verification. That's a nice property.

Availability is a hard problem. I've been looking into NIZKPs (snarks/starks), but I'm not sure yet if they'd adequately cover the case of ensuring non-duplicates. They do seem appealing for bitexact verification, but we'd probably have to do a lot more research on how to encode more approximate checks. There are also proofs of retrievability, but I haven't read closely enough yet to see if they have a way to address the *absence* of a response, which (for our purposes) is probably the basic property we're interested in proving with an interactive system.

**Comment by dob** [comment]
I'm worried about the consequences of this change (both from a data availability perspective, but also just from a protocol accounting perspective). The seqNo essentially serves as an ID for the segment for things like claiming, verification, and challenging. The fact that a transcoder can concisely claim 1000's of segments in one txn because of seqNo ranges gives the protocol some efficiency now that may be lost by needing to make merkle leaves available for all segments so that watchers could confirm that the committed root when making a claim is accurate. That also introduces a lot of bandwidth and data transfer.

**Comment by j0sh** [comment]
One way to do the Merkle leaf distribution and checking is to incorporate the leaves as metadata: whether in the manifest (custom headers), in mpegts (PMT) or H.264 (SEI). This is still at the whims of data availability -- there is currently no guarantee the transcoder will actually publish a manifest or any segments after doing the work, and no way to 'catch up' on missed segments.

On a side note, any non-deterministic verification scheme would likely exacerbate the data availability problem (due to needing the transcoded segments for checking), but if/when we solve that, we would also solve Merkle leaf distribution.

Anyway, I agree that we'd lose some nice properties of the current scheme, so it might be best to toss this idea into the compost bin. Hopefully it'll fertilize something else interesting.
