### ISSUE TITLE
Call to invoke the reward failed

### ISSUE THREAD

**Issue by ghost** [livepeer/go-livepeer#435]
I ran into this error when trying to invoke the call "Reward" through the CLI, command 12 with software version 0.2.2:
https://etherscan.io/tx/0xbcb8f54b6f68d96a9fd71c24b047bb33c4070ecab7f76a0bd842a6a9484b68ae

**Comment by dob** [comment]
It looks like this failed because the current round was not yet initialized. As soon as the new round starts an `initializeRound()` txn needs to be invoked once by somebody in order to calculate the active set of transcoders for that round. We have been running an initialization daemon that does this within the first couple blocks of the round, however it didn't work yesterday because of a crash. Anyone can invoke the txn, but it's a bit expensive.

In the meantime, I'd suggest that we update the CLI to not actually make the `reward()` call if the round is not initialized, since it will just waste a bit of gas.

**Comment by dob** [comment]
Tracking in #436
