### ISSUE TITLE
using Public IPs is not suitable for home user.

### ISSUE THREAD

**Issue by f1l1b0x** [livepeer/go-livepeer#442]
Unfortunately the new requirement of adding the publicIP during transcoder startup is less than ideal for someone with a DSL connection as he might have a forced disconnect and will get a new IP every day.

Philipp

**Comment by j0sh** [comment]
Curious, do you have a particular use case in mind for transcoders on residential DSL/cable connections?

Right now (with basicnet), subscriptions fall back to the relay network if the broadcaster detects the transcoder isn't publicly available. So you could probably put a bogon IP in there. That said, this fallback is going away with the v2 networking proposal.

There are still ways to make this work, such as a dynamic DNS service + port forwarding, DMZ, etc, but I'd discourage it. Transcoders are expected provide reliable infrastructure, and home environments don't lend themselves to consistent availability, IP renewal being one of many reasons.

**Comment by f1l1b0x** [comment]
I agree it might not be the most reliable node but modern dsl can provide enough bandwidth to participate as orchestrator or transcoder. 

for now could I just enter a hostname (dyndns) instead of a IP?

**Comment by dob** [comment]
I would think that hostname should be a fine solution here in addition to IP. And in the future it seems reasonable that orchestrators would be expected to have a stable endpoint either via hostname or IP, but a transcoder within an orchestrator pool may not have this requirement since they would be interacting with the orchestrator/object store p2p and may not require a direct connection from a broadcaster.

**Comment by j0sh** [comment]
The fallback should work for now without exposing your node to the public. If you still want to use a hostname right now, some tweaking is needed because libp2p can't take both an IP and/or a DNS name without changing the prefix, and the `/ipv4/` prefix is hard-coded in basicnet. So this change needs to be applied (untested):

```diff
diff --git a/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go b/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go
index 6b176e09..c04612fc 100644
--- a/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go
+++ b/vendor/github.com/livepeer/go-livepeer-basicnet/basic_network.go
@@ -96,7 +96,7 @@ func NewBasicVideoNetwork(n *BasicNetworkNode, publicIP string, port int) (*Basi
        var ip ma.Multiaddr
        var err error
        if publicIP != "" {
-               ip, err = ma.NewMultiaddr(fmt.Sprintf("/ip4/%v/tcp/%v", publicIP, port))
+               ip, err = ma.NewMultiaddr(fmt.Sprintf("%v/tcp/%v", publicIP, port))
                if err != nil {
                        return nil, err
                }
```

Then the  flag needs to be set to something like `-publicIP "/dns4/my-home.dyndns.com"` . Note that if you want to go back to an IPv4 address without reverting this patch, then `/ipv4/<ip>` is the format to use. (And yes, and there's no way to allow independent resolution of IPv6 DNS names, either; that'd mean a `/dns6/` prefix.)

Again, in the general case, I really don't recommend running an orchestrator/transcoder at home. Downstream bandwidth might be fine if you're only transcoding one video at a time, but I suspect most users would be at risk of maxing out their upstream,  eg if a job were to specify all 8 of our output profiles, including three in 720p. That's not getting into all the other issues such as: lack of SLA, no backups (internet/power), no access control (common burglaries), etc etc. There are also many operational concerns with running a transcoder. IMO, casual home users really aren't the target for transcoders here; if operators don't already have the ability to manage something like a VPS, they'll get owned trying to run a public transcoder from home.

**Comment by f1l1b0x** [comment]
i created the feature request #470 to deal with this and other problems related to IPs
