### ISSUE TITLE
Tutorial Based on Media Player and Livepeer Node

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#468]
**Is your feature request related to a problem? Please describe.**
We want to create a tutorial to show someone how to start developing using Livepeer. This tutorial is meant to be used as an example hack during hackathons.

**Goal**
Goal is for dapp developers to be able to use livepeer to build video into their app, and increase the amount of live video streamed into network. 

**Describe the solution you'd like**
A tutorial that exists in the [Livepeer docs](http://livepeer.readthedocs.io/en/latest/getting_started.html) to walk through the process of setting up a Livepeer node and setting up the Livepeer Media Player to play a video from the node.

**Additional context**
Create a tutorial in the [docs repo](https://github.com/livepeer/docs). The tutorial should include:
* How to set up a Livepeer node that's connected to Rinkeby
* How to fund the Eth account with test Eth
* How to set up the [media player](https://github.com/livepeer/livepeerjs/tree/master/packages/player) to talk to the node
* How to stream into the node, and watch the video from the media player 

Who it is for:
Engineers interested in using video in what they are building. This will be used at hackathons, and in the read the docs, for when people want to build an app using video.

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Tokens: SNT: 1388.00
Contract address: [0x621511e08f4af0e8bfba180adb69bd43d638fbda](https://etherscan.io/address/0x621511e08f4af0e8bfba180adb69bd43d638fbda)
![QR Code](https://openbounty.status.im/qr/livepeer/go-livepeer/bounty/468/e4ba34a327c23d0e99b45fe5241c24d8e180ddf7439789b578338a27bab31c6b/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by mnmli** [comment]
@ericxtang Is this ticket still open or has there been a tutorial created since?

**Comment by ericxtang** [comment]
A few have started, but no one has finished.

**Comment by aj07** [comment]
@ericxtang if this is still open. I would like to work on
