### ISSUE TITLE
"Nonce too low" error during "reward" call

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#471]
**Describe the bug**
The automatic `reward` call for a transcoder keeps getting `nonce too low` error.

**To Reproduce**
Start the node as a transcoder, and wait for the automatic `reward` call as new rounds are initialized.

**Expected behavior**
The `reward` call to go through.

**Additional context**
Even though the automatic invocation fails, manually invoking `reward` through the CLI seems to work.  Here is the error log: 
```
I0621 15:58:27.807871   31184 base.go:207]
******************************Eth Transaction******************************

Invoking transaction: "reward".  Hash: "0x8d1b440f8bf4c84f3357ddef293db7c49c9c2af4da5fea2f6b35e22b418e35c4".  Params: []

***************************************************************************
I0621 16:08:27.810895   31184 rewardservice.go:128] Reward tx did not confirm within defined time window - will try to replace pending tx next time
E0621 16:08:27.810935   31184 rewardservice.go:49] Error trying to call reward: context deadline exceeded
I0621 16:29:07.718614   31184 client.go:882]
******************************Eth Transaction******************************

Replacement transaction: "reward".  Hash: "0xfcbffa89b7dd2fd44dbaaf5a4393b1707d462614f1ccb65080fc0e6d7ca3e39d".  Gas Price: 3429411824

***************************************************************************
I0621 16:39:07.724907   31184 rewardservice.go:128] Reward tx did not confirm within defined time window - will try to replace pending tx next time
E0621 16:39:07.726327   31184 rewardservice.go:49] Error trying to call reward: context deadline exceeded
I0622 16:28:28.008510   31184 client.go:884]
******************************Eth Transaction******************************

Replacement transaction: "reward".  Gas Price: 3772353016
Transaction Failed: nonce too low

***************************************************************************
E0622 16:28:28.009093   31184 rewardservice.go:49] Error trying to call reward: nonce too low
I0622 16:58:31.472871   31184 client.go:884]
******************************Eth Transaction******************************

Replacement transaction: "reward".  Gas Price: 3772353016
Transaction Failed: nonce too low

***************************************************************************
E0622 16:58:31.472992   31184 rewardservice.go:49] Error trying to call reward: nonce too low
I0622 17:28:27.382547   31184 client.go:884]
******************************Eth Transaction******************************

Replacement transaction: "reward".  Gas Price: 3772353016
Transaction Failed: nonce too low

***************************************************************************
E0622 17:28:27.383460   31184 rewardservice.go:49] Error trying to call reward: nonce too low
I0622 17:59:08.522551   31184 client.go:884]
******************************Eth Transaction******************************

Replacement transaction: "reward".  Gas Price: 3772353016
Transaction Failed: nonce too low

***************************************************************************
I0623 20:28:27.145666   31184 client.go:884]
******************************Eth Transaction******************************

Replacement transaction: "reward".  Gas Price: 3772353016
Transaction Failed: nonce too low

***************************************************************************
E0623 20:28:27.145697   31184 rewardservice.go:49] Error trying to call reward: nonce too low


I0623 20:57:31.628552   31184 webserver.go:1030] Calling reward
I0623 20:57:31.797605   31184 base.go:207]
******************************Eth Transaction******************************

Invoking transaction: "reward".  Hash: "0x7e7768f7a773618d78b83ded83ffabb4024476eeab7e82e8ef8997121ac269a4".  Params: []

***************************************************************************


I0623 20:57:52.805841   31184 webserver.go:1040] Call to reward successful
```

**Comment by yondonfu** [comment]
Hm this is a little weird - I think think this is what might've happened:

The node submitted tx 0x8d1b440f8bf4c84f3357ddef293db7c49c9c2af4da5fea2f6b35e22b418e35c4 with a gas price of 3.117647104 gwei which was in the pending state for a long time so the tx confirmation polling loop timed out. After the 30 minute reward call interval, the node tried replacing tx 0x8d1b440f8bf4c84f3357ddef293db7c49c9c2af4da5fea2f6b35e22b418e35c4 with tx 0xfcbffa89b7dd2fd44dbaaf5a4393b1707d462614f1ccb65080fc0e6d7ca3e39d by bumping the gas price to 3.429411824 gwei which also ended up in the pending state for a long time so the tx confirmation polling loop timed out again. 

At some point during the subsequent 30 minute reward call interval, tx 0x8d1b440f8bf4c84f3357ddef293db7c49c9c2af4da5fea2f6b35e22b418e35c4 was mined https://etherscan.io/tx/0x8d1b440f8bf4c84f3357ddef293db7c49c9c2af4da5fea2f6b35e22b418e35c4. From the node's point of view it is always trying to replace the last submitted tx that timed out which in this case is tx 0xfcbffa89b7dd2fd44dbaaf5a4393b1707d462614f1ccb65080fc0e6d7ca3e39d. As a result, when the node checks if tx 0xfcbffa89b7dd2fd44dbaaf5a4393b1707d462614f1ccb65080fc0e6d7ca3e39d is mined yet, it sees that it is not and tries replacing it. However, since tx 0x8d1b440f8bf4c84f3357ddef293db7c49c9c2af4da5fea2f6b35e22b418e35c4 was mined and uses the same nonce, any further replacement transactions will be invalid because they are trying to use the same nonce when the account's nonce has already been incremented.

In theory, tx 0x8d1b440f8bf4c84f3357ddef293db7c49c9c2af4da5fea2f6b35e22b418e35c4 should be replaced by tx 0xfcbffa89b7dd2fd44dbaaf5a4393b1707d462614f1ccb65080fc0e6d7ca3e39d when miners are considering transactions for inclusion since the latter tx has the same nonce and higher gas price. However, in practice this might not have been the case perhaps because not all miners may have seen the replacement tx - as a result, a miner that happened to still have the original tx, but did not see the replacement tx yet could have included the original tx in a block.

I think quick fix for the node is to treat a nonce too low error the same way that we treat a mined tx err when trying to replace a transaction - in both these cases, the nonce for the stored pending tx has already been used so we should discard it.
