### ISSUE TITLE
Check incoming video streams against a list of restrictions

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#476]
**Is your feature request related to a problem? Please describe.**
Currently any RTMP video stream is allowed.  This means we could potentially allow different codecs and dimensions that transcoders in the network don't necessarily support.

**Describe the solution you'd like**
The node should be able to specify a list of restrictions for the incoming video streams.

The node can load a json file that specifies the restrictions (taken from `videoProfile.go` in lpms):
```
{
  "videoInputRestrictions": [
    "P1080p60fps16x9",
    "P720p30fps4x3",
  ]
}
```
We can implicitly assume h264 and aac for now.

If the input video doesn't conform to the restrictions, we terminate the stream, disconnect, and log `StreamCreateFailed` event.

The code should live in `lpms` so developers who only want to use `lpms` can also benefit from this.  You can either choose to use `ffmpeg` or `joy4` to do the video inspection.  

We can call this `videoInspector`. It should accept a `BasicRTMPVideoStream`, and a list of `VideoProfile` (restrictions) as input, and return an error to indicate whether the video has passed the restriction test. (error should contain reason of failure). The `videoInspector` should also enforce h264 and aac.

**Describe alternatives you've considered**
Don't restrict the input video profiles.  However, this could introduce unforeseen issues.

**Additional context**
This is the first step to implement automated ABR decisions in Livepeer, as per discussed with @f1l1b0x

**Comment by j0sh** [comment]
Can you elaborate on the "automated ABR" as opposed to the plain ABR that we have now, and how restricting the input would help with that?

**Comment by ericxtang** [comment]
The "automated ABR" proposal from @f1l1b0x basically states a developer using Livepeer will have a "default" option to let the node decide on the video profiles for the resolutions and bitrates in the ABR masterPlaylist.  So for example, if they stream in `P1080p30fps16x9`, they expect to have `P720p30fps16x9`, `P576p30fps16x9`, `P360p30fps16x9`, `P288p30fps16x9`, and `P144p30fps16x9` without having to specify it.

Controlling the input video profiles can make this a lot simpler.

**Comment by j0sh** [comment]
The idea of automatically selecting a list of transcoding profiles is a good one. How does constraining the input help? If we're creating a job on the fly, then I understand creating a subset of profiles that match the input stream, but what are the problems aside from a possibly skewed aspect ratio for unusual streams? I'm not sure that's something we should terminate the stream for.

Otherwise, we can terminate the stream for all non-standard aspect ratios (basically just 4:3 and 16:9 now), and submit jobs with profiles that are less than the input resolution. Is the additional configuration still needed? Is it a way to specify the "max allowable resolution"?

I think we are moving towards *not* creating jobs on the fly though; see delayed broadcasting and https://github.com/livepeer/go-livepeer/issues/429 . What should the behavior be in that case? I'm not sure I really like the idea of terminating the stream in those cases, because (especially for delayed broadcasting) that means we need to add a cancellation mechanism.

**Comment by ericxtang** [comment]
Created https://github.com/livepeer/lpms/issues/83 and https://github.com/livepeer/lpms/issues/84, getting rid of this issue.
