### ISSUE TITLE
Object Store Implementation

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#487]
Action plan for https://github.com/livepeer/go-livepeer/issues/483

Work will be built on top of the [restartable broadcasts](https://github.com/livepeer/go-livepeer/pull/428) branch since that contains non-trivial changes on top of the v2 networking flow. Otherwise the merge process will be complicated with two diverging branches touching similar code.

The following tasks can be split into several PRs, and merged incrementally.

- [x] Move transcoder-specific code that is in livepeernode.go and mediaserver.go into its own file
  * Otherwise, it is likely to grow even more with the OS changes
  * Which module subdirectory? `core` or `server` ? Or a new one?
  * Maybe move broadcast-specific code as well.
- [x] Set LPMS HTTP listener to share gRPC port, not CLI (which should remain private)
  * Otherwise, LPMS HTTP is not really useful outside of local testing
  * gRPC HTTP listener is currently not initialized for broadcasters.
  * Could also run LPMS HTTP on a third public port. 
- [ ] Preliminary internal API interface for local HTTP driver
  * OS drivers can live in their own module, `drivers` or some such
- [ ] Add IPFS driver
- [ ] Change `/segment` transcode request to submit URIs (HTTP/IPFS)
  * Serve via broadcaster LPMS at first.
  * Enable IPFS for broadcaster later?
- [ ] Change `/segment` transcode response to return URIs
  * Serve via transcoder LPMS and IPFS at first.
- [ ] Add S3 driver
- [ ] Add `/segment` support for transcoder uploads to broadcaster S3
- [ ] Add TranscoderInfo  support for broadcaster uploads to transcoder S3?
- [ ] Support for transcoder to upload segments to their own S3?
- [ ] Support for broadcaster to upload segments to their own S3?
- [ ] CLI or cmd/livepeer changes
  * How to actually expose these options to the user: TBD

**Comment by ericxtang** [comment]
@j0sh this is a reasonable plan.  What do you think about focusing on merging the rpc branch before starting on this?  Otherwise we'd have to juggle 2 separate branches (especially if we have to make fixes in the rpc branch, could be a pain to merge)

I see the node evolving toward different types (Orchestrator, Broadcaster, Transcoder), so I'm in favor of creating a `transcoder` and a `broadcaster` package that captures the separate logic. I can see a world where we build a very thin `transcoder` node so it can run on a cheap GPU board someday.

For LPMS, are you planning on moving all the endpoints to gRPC? If that's the case, how would it change LPMS as a stand-alone media server?  Would clients have to use gRPC to talk to it?

I like the idea of creating an internal API and writing drivers on top of it.  I think `io.Reader` and `io.Writer` is the recommended golang way of doing this.

I feel like IPFS is not very practical for live - it's very slow, so the transcoders will not be able to rely on it for transcoding a live stream, and the broadcaster will not be able to view the transcoded result.  Maybe we can get S3 working first?

**Comment by j0sh** [comment]
> What do you think about focusing on merging the rpc branch before starting on this?

:+1: Are we OK with merging the rpc (+ service registry + restartable broadcasts) branches, or do those need some more time to bake / test?

> For LPMS, are you planning on moving all the endpoints to gRPC?

I haven't looked approaches too closely yet, but I was planning to use an approach similar to how gRPC and HTTP coexist right now. We could either pass in a HTTP handler to LPMS for sharing, or export a non-default handler from LPMS, and handle routing within the RPC code. Other than that, I expect LPMS to remain standalone.

> I feel like IPFS is not very practical for live

Agreed. We already support for IPFS within the (transcoder) node though, so I expect this to be the easiest driver to add. Right now, I'm mostly curious about supporting IPFS in order to 'prove out' the driver API with a variety of providers. As long as we build the interface correctly, then supporting IPFS shouldn't be more work than writing a (hopefully minimal) driver. If that seems like it'll take more than a hour, then we can leave the effort until VOD.

**Comment by j0sh** [comment]
OS merged in https://github.com/livepeer/go-livepeer/pull/562
