### ISSUE TITLE
Broadcaster Should Stop Streaming When Job Expires

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#498]
**Is your feature request related to a problem? Please describe.**
Currently the broadcaster continues to stream segments after a job has expired.

**Describe the solution you'd like**
The broadcaster should terminate the stream when the job expires, so no more segments will be streamed to a transcoder unnecessarily. 

**Describe alternatives you've considered**
Leave it as it is, since the transcoder doesn't accept the segment anyways.  But it's better to terminate the stream.

**Additional context**
To create the "problem", you should:
1. Change the `DefaultJobLength` in `livepeernode.go` to something like 5 blocks.
2. Run the node with `-rinkeby`.
3. Stream into the node.
4. Wait for the job to expire (the log should change from `Response for segment 11: Successfully transcoded segment 11` to `Response for segment 17: Job out of rang`)

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x2fafa3b3c46e31f2d7710415c3f23cf856f4d2d8](https://etherscan.io/address/0x2fafa3b3c46e31f2d7710415c3f23cf856f4d2d8)
![QR Code](https://openbounty.status.im/qr/livepeer/go-livepeer/bounty/498/302ee82eace9d11eb672c6e8fc421e36f56bbf7f04db11b224f0ceab0b7bb8b9/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by j0sh** [comment]
Note that we already attempt to mitigate this issue somehow in the [restartable broadcasts PR](https://github.com/livepeer/go-livepeer/pull/428) by only reusing a job if there are at least 10 minutes remaining in the job. We can adjust this (or even make it configurable) if another number makes more sense, eg 1h.

In terms of actually implementing this feature: we should avoid making Eth RPC calls every few seconds. The [partial unbonding PR](https://github.com/livepeer/go-livepeer/pull/486) adds a block watcher for the broadcaster, along with a local DB lookup for the most recent block number. This lookup should be reused here.

**Comment by eladmallel** [comment]
Hey @j0sh and @ericxtang, I spent some time reading our code, got a basic understanding of the flow, but would love to get some of your guidance before I can arrive at a good solution. Would love your inputs on my questions below, and of course any inputs you think are important that are not mentioned here yet:

1. How to detect this state?
    1. Is it good enough to rely on T's 403 response?
    2. Or is it important that B to determine this state independently?
        1. If so, why?
        2. Can I assume BlockService is highly reliable?
2. How to stop the stream?
    1. I'm focusing on the code under: `gotRTMPStreamHandler` -> `hlsStrm.SetSubscriber` -> `SubmitSegment`
    2. Do I just call `rtmpStrm.close()`?
        1. I am not sure if this is the right way to stop processing and submitting the stream
        2. Also not sure how this impacts the user?


Thanks!

**Comment by j0sh** [comment]
Great questions.

> How to detect this state?

The transcoder will send a "[Job out of range](https://github.com/livepeer/go-livepeer/blob/5fb9565cee34be0e59b61a6fc761f542276d7d72/server/rpc.go#L98)" error. See how we handle "[MediaStats Failure](https://github.com/livepeer/go-livepeer/blob/5fb9565cee34be0e59b61a6fc761f542276d7d72/server/rpc.go#L484-L485)" within SendSegment; we can detect in a similar fashion, although this particular check probably needs to be done one level up in the mediaserver. The broadcaster can then handle that by terminating the stream.

> Or is it important that B to determine this state independently?

I think it's fine for B to depend on just T's response and react to that.

> Do I just call rtmpStrm.close()?

That should be enough to disconnect the RTMP stream. If there are unexpected interactions with other parts of the code, then it'll probably come up during testing.

> Also not sure how this impacts the user?

OBS will attempt to reconnect from involuntary disconnects, which should eventually create a new job on the node. It might take a few attempts if the broadcaster's view of the blockchain is lagging behind the transcoder's. In any case, from the end user's viewpoint, it should appear to be a brief hiccup in the stream.

**Comment by eladmallel** [comment]
@j0sh thanks!

I also looked inside `SubmitSegment`, and I believe the relevant code that's running is [this one](https://github.com/livepeer/go-livepeer/blob/5fb9565cee34be0e59b61a6fc761f542276d7d72/server/rpc.go#L442), since I think T returns 403 [here](https://github.com/livepeer/go-livepeer/blob/5fb9565cee34be0e59b61a6fc761f542276d7d72/server/rpc.go#L241).

The 403 response leads us to [this line](https://github.com/livepeer/go-livepeer/blob/5fb9565cee34be0e59b61a6fc761f542276d7d72/server/mediaserver.go#L368) that IIUC simply silences the error and lets the stream continue.

So I was thinking that right in the last line I linked to I could check for a specific error type and kill the stream if the error means the job has expired.

Does this make sense?

As for using `rtmpStrm.close()` - just want to be clear - are you saying this is indeed the best way to achieve to goal of this task? No better way I should look into?

As for relying on T's response - thank you! I think that makes my life a bit easier :)

**Comment by j0sh** [comment]
> So I was thinking that right in the last line I linked to I could check for a specific error type and kill the stream if the error means the job has expired.

Yes, that's exactly where the check for "Job out of range" should happen. The error code may be a 403 (we consider all non-200 to be failures), but the body should contain "Job out of range"  -- non-200 response bodies gets wrapped in a golang error and propagated.

> As for using rtmpStrm.close() - just want to be clear - are you saying this is indeed the best way to achieve to goal of this task?

Yes

**Comment by eladmallel** [comment]
@j0sh thanks! 

I'm planning to definitely convert the error response into a meaningful error and make decisions based on that. I want to start with the current structure, but also hoping to squeeze into this PR a small change to move us towards a more strongly-typed error typing system, so we can use something more robust than string comparisons to determine the error type.

I've seen examples online of either using a different struct type per error, OR using one struct with both a string description and an int error code, and relying on the error code to determine the error type. Would love to get your take on all this, either here, or when we have some sync time tomorrow!

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/590
