### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#502]
Two parts: refactoring the broadcaster and transcoder, and removing basicnet.

The term 'transcoder' here can be used interchangeably with 'orchestrator'.

## Broadcaster and Transcoder Refactor

This covers the first item in https://github.com/livepeer/go-livepeer/issues/487, "Move transcoder-specific code that is in livepeernode.go and mediaserver.go into its own file"

This is less about large adjustments to the internal API and more about rearranging code so related functionality is in close proximity, and unrelated functionality is separate. Here is a thought on how we can accomplish this.

We can have the broadcaster and transcoder-specific code live in their own files, `broadcaster.go` and `transcoder.go` . Currently, things are scattered across `livepeernode.go`, `mediaserver.go` and `rpc.go` .

There's a few places where we could put these files.
* `core` My preferred location. Otherwise, the `core` directory seems to have little purpose other than holding some common code (but we already have `common` ... )
* `net` Currently only holds the expected interfaces for basicnet. We could expand this, but not everything will be "networking" related, eg the transcode loop. We could further split up the transcoder up across modules, but I like the immediacy of keeping most related things in the same module.
* `server` Requires the least refactoring. While the transcoder part is indeed a server, the broadcast client isn't. Ignoring the slightly inaccurate folder naming, this would be the simplest approach. However, I can also see the `server` module becoming a bit of a dumping ground for future changes.
* Each role gets its own module, eg `broadcaster/broadcaster.go` or `transcoder/transcoder.go` .  Optionally, we could also split the broadcaster and transcoder further down into additional files from there. However, I'm not sure if we have enough role-specific code to really justify this yet; I prefer to keep logically related code together, even if it makes for a longer file, and single-file dirs seem funny to me.

There is also the question of what to do with the `rpc.go` file and the related protobuf generated code. This handles both the client and server aspects of the wire protocol: implementing the RPC methods along with authentication, serialization, etc. While this code can be logically distinct, I generally like keeping it together because it's so tightly coupled (eg, if we change how we need to create a request on the broadcaster, we have to make the corresponding change to the transcoder-side handler).

Do folks have a preference for splitting up `rpc.go`? Note that if we keep `rpc.go` together as-is, we can't split the broadcaster and transcoder into their own modules, at least not without putting RPC code into some other third module (due to cyclic imports for the transcoder). We could also simply rearrange the code within `rpc.go` to make it a bit better organized. Broadcaster and transcoder related functions are mostly separate already, but there's a small bit of interleaving that could be corrected.

Code organization is largely subjective, and this just reflects my style of thinking / working. Feel free to suggest other approaches.

## Basicnet Cleanup

Additionally, we can remove the basicnet integration, which should really clear up the field. I suspect after doing this, we'll have some more ideas for further internal API simplification, since v2 networking was written to accommodate working alongside the basicnet implementation.

**Comment by yondonfu** [comment]
I agree that `core` seems like the logical place to put `broadcaster.go` and `transcoder.go`

If `server` is a bit misleading as a directory name, what if we renamed the directory `rpc` and split `rpc.go` into `rpc_broadcaster.go` and `rpc_transcoder.go` - the files would make the client/server distinction, but the code would be still kept close together in the same directory to facilitate future changes in one file that necessitate changes in the other file? `rpc_broadcaster.go` would import `core/broadcaster.go` and `rpc_transcoder.go` would import `core/transcoder.go`. A `rpc` directory could then maybe be a dumping ground if the node needs to support alternative connection schemes like IPC/WebSockets for external API consumers.

**Comment by j0sh** [comment]
That's a good idea.

We could also separate it out by functionality. For example, there is a bunch of auth generation and checking code that might be split off without losing too much overall clarity. Another thing we could do is move the struct implementations for the `Orchestrator` and `Transcoder` interfaces outside RPC, but that probably means changes in how those structs are created and how the internal API is built.

That should reduce `rpc.go` down to just constructing and processing RPC requests. We can rename the folder too. `net` actually seems like a good name for it, since things like the RTMP mediaserver aren't strictly RPC.

Speaking of `net` , after we clean up the basicnet code, we should have a better idea of what to do with the existing interfaces in `net` . @ericxtang has expressed an interest in salvaging the behavioral outlines that those interfaces define, if not the code that is built around those interfaces.

**Comment by ericxtang** [comment]
Some thoughts I have - 

**Move broadcaster logic and transcoder logic into `core**
* `core/broadcaster` - responsible for the core logic of a broadcast(or ingest) node.  Invokes `rpc/publisher` to make the original video available to the transcoder.
* `core/transcoder.go` - responsible for the core logic of a transcoding node.  Invokes `rpc/publisher` to make the transcoded video available to the rest of the network, and invokes `net/transcoder` to pass along transcoded stream info.

I think the ingest nodes and transcoding nodes aren't sharing that much code at this point. Since these concepts are close to the "entry point" of the codebase, clearly separating them out can make the things easier to reason about.


**Refactor `net` interface**
* `net` - networking interface that specifies how video is made available to the rest of the network.  It's currently closely coupled with the p2p networking workflow and needs some refactoring. I think we can remove `SendTranscodeResponse`, `ReceiveTranscodeResponse`, and `TranscodeSub`. In the ideal world, `net/interface.go` should be implemented by the `rpc` package and the `basic-net-v2` package.
* `net/publisher` - interface for a network video publisher.  It makes a specific video stream "available" to the network (either through push or through caching locally / waiting for subscriber).
* `net/subscriber` - interface for a network video subscriber.  It subscribes to a video stream from a specific node.

I think the `net` package can be video specific.  It's becoming more and more clear that we need both push and pull.  For example, in the `rpc` protocol, (B->T) is push, but (B<-T) has to be pull since T is well-known and B is not.  So the `net` package can just implement a `publisher` and a `subscriber`, and it's up to the implementation to decide how "publish" and "subscribe" work.

**Refactor `rpc` package to implement `net`**
* `rpc` - package responsible for the networking between the broadcaster and the transcoder.
* `rpc/publisher` - implements `net/publisher` by pushing the video stream (B->T for original stream).  Invoked by `core/broadcaster` and `core/transcoder`.
* `rpc/subscriber` - implements `net/subscriber` by subscribing to video stream from a well-known node
* `rpc/transcoder` - special logic to the rpc protocol that can handle things like transcode response. Invoked by `core/transcoder`.

`rpc` can be the first implementation of the new `net` interface, and we can later extend it to dht style p2p-based delivery.

**Comment by j0sh** [comment]
Some thoughts on the `net` interface.

The v2 networking flow is synchronous request-reply, more than async pub-sub. Once the Tributary release is out, the sequence of events will look like this:

* Broadcaster requests transcode
* Transcoder replies with URLs of transcoded segments
* Broadcaster requests each transcoded segments
* Transcoder replies with each transcoded segment
* Broadcaster generates local playlist(s)
* CDN requests playlist and segments from broadcaster
* Broadcaster replies with playlist and segments

These are distinct actions and distinct roles, and we probably should have separate interfaces for those. Pub-sub doesn't quite fit the flow; if anything, the additional indirection (separating request-reply into publish and subscribe) will make things more difficult to follow.

However, we don't strictly *need* interfaces for the broadcaster/transcoder right now. So perhaps we can leave things interface-less for the time being. We can specify interfaces as needed, eg when mocking tests. This seems preferable to fitting code into anticipated or preexisting interfaces that don't quite match the natural flow.

On the other hand, I've been looking at how playlists are managed. Those could probably benefit from being parameterized by the object store. Still TBD precisely how that would work, but the possibilities are becoming clearer as the cleanup progresses. So far: https://github.com/livepeer/go-livepeer/compare/it/metrics...ja/cleanup
