### ISSUE TITLE
Allow  ENS sub-domain registration for Livepeer nodes from CLI

### ISSUE THREAD

**Issue by hgedia** [livepeer/go-livepeer#510]
**Issue**
The current block explorer for Livepeer supports reverse ENS resolution of trancoders. However it is up to the participating node to go and register a domain via ENS. While registering a domain takes longer (via auction); subdomains can be created immediately. From CLI we can issue subdomains very quickly as outlined below.

**Solution**
This feature would allow all Livepeer nodes to register an ENS sub-domain from the Livepeer CLI. Following changes will be carried out to the processes:

1. Livepeer CLI : New option to "Register Sub-domain"
2. Livepeer Server : Logic to process this call and call a proxy contract which will do the ENS subdomain registration and reverse ENS registration on same call.
3. Proxy contract :A wrapper to ENS API which will be the owner of any domain you wish to register for the user ex : transcoder.eth.The proxy contract will call the ENS registry contract to create and register a subdomain ex : user.transcoder.eth.A reverse resolution entry will also be added by the contract in the ENS reverse registry

**Diagram**

![livepeer](https://user-images.githubusercontent.com/32969555/44052052-7a2b5386-9f33-11e8-9d7f-6ff1cf2b95ca.png)

**Comment by hgedia** [comment]
Note : @JosefJ and I have done some work regarding the above, and are happy to continue. A new issue will be opened to track smart contract related queries if you are happy with the proposed changes.

**Comment by dob** [comment]
Really excited about this. For clarification, is the "Livepeer Server" the existing livepeer binary, which exposes an HTTP interface that the CLI talks to? I assume it is, since it can contain the logic for calling the on chain proxy contract.

**Comment by hgedia** [comment]
@dob  ,yes that is correct. Here is a very rough cut of the changes https://github.com/livepeer/go-livepeer/compare/master...hgedia:master

I do need to clean up the code add error handling etc.

**Comment by JosefJ** [comment]
@hgedia slight change - we will have to split the reverse registration to another call if we want this to work with the already published default Resolver on the mainnet.

**Comment by JosefJ** [comment]
Contract code is here: https://github.com/JosefJ/ens/blob/master/contracts/SubdomainDispensary.sol


Setup: 
1. Publish `SubdomainDispensary` with addresses of following mainnet ENS contracts:
`(ENS.address, DefaultPublicResolver.addres, ReverseRegistrar.address, '.transcoders.eth', 0)` 
the 0 in the end sets the price of the call to 0 wei, otherwise it will require users to pay some fee for the registration.  
2. Move ownership of the `transcoders.eth` domain to the newly published contract

Usage:
From the same account, do the following:
1. Call SubdomainDispensary.subRegister(string 'name') 
2. Call ReverseRegistrar.setName(string 'name.transcoders.eth')

**Comment by dob** [comment]
What does `rootNode` represent?

And...

> From the same account, do the following...

Is it necessary that it is the same account that deployed the contract actually call `subRegister`? Anyone should be able to call it from their transcoder's account on a first-come-first-serve basis for a name, right?

**Comment by JosefJ** [comment]
The rootNode is meant to be the node hash resulting from `keccak256(keccak256("0x0", "eth"),"transcoders")`
- it's written this way, so it's actually reusable for any level of an ENS domain.

Ad the same account) 
Sorry, that's written confusingly. I meant to say the steps 1 & 2 in the usage part should be made from the same account - it doesn't relate to the publishing

**Comment by NathanLewis** [comment]
It is cool to see that you guys are still working on our project. I'll try to catch up when I can.

**Comment by yondonfu** [comment]
Hey @JosefJ I forked the ENS repo here: https://github.com/livepeer/ens Want to create a PR there with your current branch so we can more easily review the contract code? We can continue the discussion on the desired mechanics of the contract there and try to get the contract code merged there and then since the contract could be reusable outside of a Livepeer context you could submit a PR to try to merge it into the main ENS repo afterwords as well.
