### ISSUE TITLE
setTranscoderConfig in webserver should check for config changes

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#526]
**Is your feature request related to a problem? Please describe.**
The `setTranscoderConfig` issues 2 transactions - 1 to update the transcoder config, 2 to update the `ServiceURI`.

Currently, when the transcoder only wants to update its `ServiceURI`, we still issue both the `Transcoder` and `ServiceURI` transaction.

**Describe the solution you'd like**
We should check for the transcoder config before issuing the `Transcoder` transaction.  If the config is exactly the same, skip the `Transcoder` transaction.

**Comment by dob** [comment]
There might be a slight hiccup here, in that we require the transcoder to
submit a transcoder() txn in order to break into the set of the top 20
transcoders. It's a weird UX issue so that we can update the accounting to
break into the active set. So if we don't allow submission of a
transcoder() txn if they don't update their params, we may have trouble
with this.
