### ISSUE TITLE
MediaStats Failure in streams with key frame == 0s

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#538]
**Describe the bug**
We've gotten some bug reports that transcoding consistently fails for certain videos with `MediaStats Failure`.  This is caused by setting keyframe to 0s in OBS.

**To Reproduce**
1. Run a broadcaster on Rinkeby with `-maxPricePerSegment` == 200 (so it can pick one of the LP hosted transcoders)
2. Use OBS to stream, make sure the set your key frame to 0 (auto)

**Expected behavior**
Report a better error.

**Screenshots**
![screen shot 2018-08-23 at 5 42 26 pm](https://user-images.githubusercontent.com/345743/44553595-ef80d500-a6fb-11e8-8b7b-e1d1df2a63ee.png)

**Additional context**
Another bug report I got with the same symptom is when people are streaming a slideshow.

**Comment by j0sh** [comment]
Because the segment length is hard-coded to 4 seconds, we reject segments that are too long. There is [leeway up to 25%](https://github.com/livepeer/go-livepeer/blob/cf67256880bf31bfec8c77bc077557a92503a913/core/orchestrator.go#L217-L222), so technically broadcasters should be OK up to 5 seconds.

In the [goclient README](https://github.com/livepeer/go-livepeer#broadcasting) and [broadcasting guide](https://livepeer.readthedocs.io/en/latest/broadcasting.html) we emphasize setting the keyframe interval to 4 seconds -- not auto.

Since slideshow content is mostly static, the auto keyframe setting will naturally produce longer intervals.

To safely fix this, we need pixel-based pricing, but that requires a protocol change. Disabling the media stats check would allow broadcasters to submit long segments while only being charged the price of a 4-second segment.

**Comment by ericxtang** [comment]
Agree that we shouldn't remove the media stats check.  I think it'll help the experience a lot if we just tried to report an error on the broadcaster side.

**Comment by dob** [comment]
If this is "Finished" should we close the issue?

**Comment by j0sh** [comment]
Yep.
