### ISSUE TITLE
Manually replace transactions from the CLI

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#543]
**Is your feature request related to a problem? Please describe.**

Sometimes a transaction submitted from the node (either automatically by the node or manually via the CLI), will sit in the transaction mempool for awhile due to upward gas price fluctuations. The node contains logic to try to automatically replace pending reward transactions. Users should be able to do this manually for other transactions as well.

**Describe the solution you'd like**

Expose an option in the CLI "Replace transaction". When the user selects this option, the user can provide the transaction hash of a previously submitted transaction which is sitting in the mempool and configure a higher gas price to submit the replace transaction with.

**Comment by dob** [comment]
Just noting that it would be nice to re-use existing code to do this if it exists somewhere already, since it would be a shame to rebuild the same "replace transaction" code that must already exist in every wallet.

If it doesn't happen to exist in go-lang already, perhaps we should develop and open source it as a standalone package, since the idea of replacing a txn with a higher gas price would be so useful to many other apps.

**Comment by yondonfu** [comment]
Yep we already have code for this exact purpose (see: https://github.com/livepeer/go-livepeer/blob/master/eth/client.go#L917) which is currently used only for the automatic reward transaction replacements.
