### ISSUE TITLE
Cannot change the broadcast config in livepeer_cli

### ISSUE THREAD

**Issue by gjgd** [livepeer/go-livepeer#552]
**Describe the bug**
Cannot change the broadcast config in `livepeer_cli`

**To Reproduce**
1. `cd <path_to_livepeer_folder>`
2. `./livepeer -rinkeby -v 6`
3. Open new terminal
4. `./livepeer_cli` in the same folder
5. My Broadcaster stats 
<img width="546" alt="screen shot 2018-09-04 at 21 47 02" src="https://user-images.githubusercontent.com/7913565/45066371-1b9d3e00-b08c-11e8-93a1-022dc61820d4.png">

6. Type `15` for "Set broadcast config"
7. Enter broadcast max price per segment in Wei - > `201`
8. Enter the identifiers of the video profiles you would like to use (use a comma as the delimiter in a list of identifiers) - > `P240p30fps16x9,P360p30fps16x9`
9. Type `1` for "Get node status"
10. Broadcaster stats haven't changed

**Expected behavior**
At step 10, Broadcaster stats should change to 201 WEI / segments

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra V10.13.6
 - ./livepeer --version: `Livepeer Node Version: 0.3.0-unstable`
- ./livepeer_cli --version `livepeer-cli version 0.3.0-unstable`

**Comment by j0sh** [comment]
Note that it is expected to use the *identifier* rather than the full name of the transcoding option (mostly because it's a lot easier to write via CLI). So in this case, step 8 would expect an input of `2,7` to set the options you want. Just tested it here and it works OK, but can you confirm?

We could add the full option parsing easily enough, but that's a separate usability issue. Although in practice, I suspect it'd have limited usage due to its cumbersomeness.

In your case, there should have been an error along the lines of `strconv.Atoi: parsing "P240p30fps16x9": invalid syntax` , for example:

```
> 15
Enter broadcast max price per segment in Wei - > 150
Identifier	Transcoding Options
0		P720p60fps16x9
1		P576p30fps16x9
2		P360p30fps4x3
3		P240p30fps16x9
4		P240p30fps4x3
5		P720p30fps16x9
6		P720p30fps4x3
7		P360p30fps16x9
8		P144p30fps16x9
Enter the identifiers of the video profiles you would like to use (use a comma as the delimiter in a list of identifiers) - > P240p30fps16x9,P360p30fps16x9
ERROR: logging before flag.Parse: E0904 19:12:16.412729   28803 wizard_broadcast.go:67] strconv.Atoi: parsing "P240p30fps16x9": invalid syntax
```

**Comment by gjgd** [comment]
You're right, `2,7` works, that's my bad.

However when I tried `P240p30fps16x9,P360p30fps16x9` I didn't see any parsing error message.

Is there a `-v` flag to add to the `./livepeer_cli` command to enable it?

**Comment by j0sh** [comment]
There's `livepeer_cli -loglevel` but it shouldn't be required to see this error message. Granted, the error message can be hard to spot because the status gets printed immediately afterwards.

**Comment by gjgd** [comment]
Found it, closing the issue
