### ISSUE TITLE
reuse of transcoding job does only work on rinkeby but wont be used on mainnet

### ISSUE THREAD

**Issue by f1l1b0x** [livepeer/go-livepeer#554]
restarting a rtmp source stream to LPMS will result in a new job with a new on chain job message instead of reusing it.

behavior on rinkeby is different than on mainnet!

on rinkeby it works as expected and reuses the jobid and transcoder
on mainnet it starts a new one

to test start a new job on rinkeby and start / stop / start OBS
you will only see 1 on chain tx no matter how often you start which is as it should be

now test on mainnet and do the start / stop / start OBS
you will notice a new tx per start in OBS

**Comment by j0sh** [comment]
We looked at this earlier yesterday. In this particular case, there was no job in the local DB that matched the node's current transcode options, which led to new job(s) being created. The node never received the `JobCreated` events from the blockchain, so it didn't have an opportunity to record the information in the DB. Those missing events are a wider issue that should be remedied by https://github.com/livepeer/go-livepeer/issues/492 . 

In general, I think this illustrates a few good reasons for having a separate job creation step (https://github.com/livepeer/go-livepeer/issues/429) since we could improve the UX around the job-creation transaction, and help the user  avoid submitting unnecessary transactions (especially without their knowledge).

**Comment by j0sh** [comment]
Most of these issues aren't applicable with Streamflow, so closing this ticket.
