### ISSUE TITLE
Transcoder Workload Back Pressure

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#572]
**Is your feature request related to a problem? Please describe.**
This issue is related to https://github.com/livepeer/go-livepeer/issues/571.  Currently the "back pressure" mechanism is simply STOP if the previous segment hasn't finished transcoding.  However, if we kick off new go routines, we'll need more sophisticated mechanisms.

**Describe the solution you'd like**
Since we are already setting a timeout for each transcoding routine, we can keep a count of the number of active routines.  When there are more than N (default at 50) active routines, stop accepting new segments.

**Describe alternatives you've considered**
We can also build some kind of wait queue for the segments, but that feels more complicated, and is an optimization we can explore at a later time when we are focusing on scaling (instead of stability at the moment)

**Comment by j0sh** [comment]
> When there are more than N (default at 50) active routines, stop accepting new segments.

50 in-progress segments is a lot; I'd even say that we should leave it at 1.

The reason is that immediate feedback is useful if the transcoder is unable to keep up with incoming segments, eg if it takes more than 4 seconds to transcode a 4-second segment. Slow transcoding hurts the viewer experience as playback outruns the transcoding process. Adding even more segments to an already-overloaded transcoder will also make things worse.

The broadcaster should know as soon as a transcoder has some indication of being backlogged. Having multiple segments in-flight makes the issue harder to diagnose, since the indications are not as obvious, eg there may not be any error returned. We could approximate the time it takes to transcode on the broadcaster side by looking at request timings, and indicate an error over some threshold, but that's not as accurate since we'd also need to account for time in transit.

What we can do is maintain the idea of "one job, one transcoder" and time out the transcoding goroutine after a certain amount of time (say 8s). If we do get stuck here, it's only for 8 seconds (2 segments worth). A broadcaster who notices a transcoder is persistently "busy" can raise the issue. 

This maintains the immediate feedback we have now while allowing the transcoder to self-heal from sporadically stuck goroutines. Seems like a better tradeoff, rather than making the debugging flow more indirect: we'd be tracking down root causes from reports of poor playback, approximating transcode lengths, or waiting for segments to pile up in memory before taking any action.

**Comment by j0sh** [comment]
I think that the [O capacity cap](https://github.com/livepeer/go-livepeer/pull/729) addresses most of these concerns. Should we close this issue?

**Comment by ericxtang** [comment]
Closing
