### ISSUE TITLE
Clean up Network Config

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#580]
**Is your feature request related to a problem? Please describe.**
The network configuration code is getting unwieldy. There are many hard-coded values and uncertain interactions between the options. For example, offchain mode is mutually exclusive with mainnet and rinkeby, but this is not obvious from reading the code.

https://github.com/livepeer/go-livepeer/blob/bbb568ffdc1c4dfd0f92a4f3c9e31e81aab5c285/cmd/livepeer/livepeer.go#L91-L118

**Describe the solution you'd like**
More structure around our network configuration options. This could even be split out into a separate configuration file, for example:

```ini
  name = mainnet
  datadir = /path/to/custom/datadir # this could be optional; default being ~/.lpData/<network-name>
  controllerAddr = 0xabcdef
  ethUrl = wss://mainnet.infura.io/ws
  metricsUrl = http://mainnet-metrics.livepeer.org
```

**Describe alternatives you've considered**
Keep things hard-coded but use a typed data structure for it, eg
```go
type NetworkConfig struct {
  name string
  datadir string
  controllerAddr string
  ...
}
networkConfigs["mainnet"] = { name: "mainnet", ... }
```

**Comment by eladmallel** [comment]
@j0sh I think we should close this issue and merge its specs into this one: https://github.com/livepeer/go-livepeer/issues/537

wdyt?

**Comment by j0sh** [comment]
These are different issues; #537 is solved by putting all network specific data into its own folder (https://github.com/livepeer/go-livepeer/pull/578), while this one is about cleaning up the code around network configuration.

**Comment by j0sh** [comment]
Before anything is implemented for a config file (if that's the direction we go with), it's probably worth discussing the format that should be used. TOML / ini-style looks good to me, for what it's worth. This library seems nice: https://github.com/BurntSushi/toml

**Comment by angyangie** [comment]
It'd be great to get everyone's thoughts on the following flag clean-up. As suggested, we'll focus on cleaning up the flags before introducing a config file + a new flag parsing library (though this one seems like a great candidate: https://github.com/octago/sflags). To make analysis easier to digest, I've grouped flags by function, and have added notes below, along with questions (forgive my ignorance on some of these):

1. **Testnet/offchain/onchain flags**: `devenv`, `rinkeby`, `offchain`. Seems like we could consolidate into one flag, like "testNet". "testNet" could have a value of: "devenv", rinkeby", "mainnet", or "offchain". Default value could be "offchain". This would allow us to do something like this below. We'd be able to grab values like this: `configOptions[*testNet].ethUrl`, etc.  if the flag was not set/was empty on startup. Comments on this structure welcome, as well as alternate solutions.

```golang
type NetworkConfig struct {
	name string
	ethUrl string
	controllerAddr string
	datadir string
	monhost string
}

configOptions := map[string]*NetworkConfig {
	"rinkeby":  {
		"name": "rinkeby",
		"ethUrl": "wss://rinkeby.infura.io/ws",
		"controllerAddr": RinkebyControllerAddr,
		"datadir": *datadir + "/rinkeby",
		"monhost": "http://metrics-rinkeby.livepeer.org/api/events"
	},
	"devenv": {
		"name": nil,
		"ethUrl": nil,
		"controllerAddr": nil,
		"datadir": *datadir + "/devenv",
		"monhost": nil,
	},
	"mainnet": {
		"name": "mainnet",
		"ethUrl": "wss://mainnet.infura.io/ws",
		"controllerAddr": MainnetControllerAddr,
		"datadir": *datadir + "/mainnet",
		"monhost": "http://metrics-mainnet.livepeer.org/api/events",
	},
	"offchain": {
		"name": "offchain",
		"ethUrl": nil,
		"controllerAddr": nil,
		"datadir": *datadir + "/offchain",
		"monhost": nil,
	}
}
```

2. **Address flags**: `rtmpAddr`, `cliAddr`, `httpAddr`, `serviceAddr`, `orchAddr` - these seem fine.

3. **Transcoding options flags**: `orchAndTrans`, `orchestrator`, `transcoder` (not a flag but a local variable we use to indicate standalone transcoder status), `standaloneTranscoder`, `orchSecret`, `transcodingOptions`. Here, it seems like we can consolidate. A couple of questions:

    - Could we autogenerate an `orchSecret` for a user, instead of having them pass in a random phrase? I might be missing the context on why we did it this way, and would love to learn more. 
   - Could we just check the presence of `transcoder` and `orchestrator` flags set to `true` to determine whether user is running in both transc and orch mode, instead of having `orchAndTrans` flag? If so, we could also get rid of `standaloneTranscoder`.

 4. **Blockchain & pricing flags** : `ethAcctAddr`, `ethPassword`, `ethKeystorePath`, `ethIpcPath`, `ethUrl`, `controllerAddr`, `gasLimit`, `gasPrice`, `initializeRound`, `maxPricePerSegment`, `faceValue`, `winProb`. Could we initialize round based on the presence of a `transcoder` or `orchestrator` flag and a `testNet` flag (see #1 on this list)? If so, we wouldn't need `initializeRound` flag.

5. **Metrics flags**: `monitor`, `monhost`, `version`, `verbosity`, `currentManifest`.

  - I've never used the `version` flag, but wonder if that's necessary. Could we just print out the version by default? 
   - I'm not too familiar with what other values someone could set `monhost` to, but would love to hear if we think that values other than the default values would be used here (defaults are http://metrics-mainnet.livepeer.org/api/events and http://metrics-rinkeby.livepeer.org/api/events depending on testnet). 
   - Is there a downside to not having a `monitor` flag, and just output metrics continuously (I imagine the answer is that this might involve some cost to us or to our users, but again, would love to learn more here). 
   - Could `currentManifest` potentially be renamed? The name could explain function even better if renamed to something like `exposeCurrentManifest`

6. **Storage**: `ipfsPath`, `noIPFSLogFiles`, `s3bucket`, `s3creds`: these flags seem fine.

Any other ideas on how to clean these up?

**Comment by j0sh** [comment]
> Seems like we could consolidate into one flag, like "testNet". "testNet" could have a value of: "devenv", rinkeby", "mainnet", or "offchain".

* That sounds good, perhaps the flag could be `-network` rather than `-testNet` ?
* Do we want to allow custom network names? They wouldn't have any associated default values (other than affecting the folder name in datadir), but this could still be useful for private networks such as the test harness.
* Doesn't hurt to maintain our shorthands, eg `-rinkeby` corresponding to `-network rinkeby`
* Each related option (eg, `controllerAddr`) should still be overridable independently via the config or flag. Suppose I want to run on "devenv" but it's likely that my values are going to be particular to my deployment, so we need the ability to set specific values there.
* Note on `datadir` . One of the (IMHO unintended) side effects of the https://github.com/livepeer/go-livepeer/issues/537 fix was that the datadir is always set to `<datadir>/<networkName>`, regardless of whether `-datadir` has been explicitly supplied via CLI. A more intuitive behavior would be to use the datadir as-is if provided, regardless of the network name. For example:
  * If no `-datadir` set: Use `<default-datadir>/<networkName>`
  * If `-datadir` set: Use `<datadir>`
  * This avoids the situation of manually specifying a `-datadir` only to have it populated with a single folder corresponding to the network.

The rest is addressed in https://github.com/livepeer/go-livepeer/issues/709 related to cleaning up the flags.

**Comment by angyangie** [comment]
> That sounds good, perhaps the flag could be -network rather than -testNet ?

Agreed, `network` sounds better!

> Do we want to allow custom network names? They wouldn't have any associated default values (other than affecting the folder name in datadir), but this could still be useful for private networks such as the test harness.

I thought the test-harness was usable in any environment (I'm looking [here](https://github.com/livepeer/test-harness/blob/master/containers/lpnode/start.sh#L7))? In what situation would one need to set the `-network` flag to `test-harness`?

> Doesn't hurt to maintain our shorthands, eg -rinkeby corresponding to -network rinkeby

If we do this, doesn't that promote ppl not using the flags as we intend them to be used? I can see this adding complexity to our logic once again (though I understand that we could just map `-rinkeby` to the new network flag value, in our code). Is the intention here to not break anyone's current way of interacting with the LP network? I can see the transition being confusing, though we're already making so many changes to the next release, that this would just be one more to embrace.

> Each related option (eg, controllerAddr) should still be overridable independently via the config or flag. Suppose I want to run on "devenv" but it's likely that my values are going to be particular to my deployment, so we need the ability to set specific values there.

Agreed! My thinking was to incorporate a check of "if empty, set to default values. Else, use provided values," for this and for `datadir` (your next point). 

Thanks for your feedback @j0sh !

**Comment by yondonfu** [comment]
> value of: "devenv", rinkeby", "mainnet", or "offchain".

I suggest changing "devenv" to "dev" to eliminate any possible confusion around when that flag should be used - we should be able to use `-network dev` whenever we want to connect the node to any development blockchain network whether it be within the devenv VM or within the test harness. The node is going to just use whatever network that the ETH node that it is connected to is using anyway - "dev" will mainly affect the default data directory naming i.e. `<datadir>/dev`.

An aside: I think it would be helpful if the node checked the network ID used by the ETH node it is connected to to make sure it is actually connected to the correct ETH network. For example, if the LP node is started with the `-rinkeby` flag it should query the ETH node for the network ID and verify that it is 4. If the LP node is started with the `-dev` flag it could just check that the network ID is not 1 or 4 (make sure we're not on mainnet or rinkeby).

> Do we want to allow custom network names?

I could see this being useful in the scenario where the node is a part of multiple long lived development networks that it switches between. I'm not sure that this is a common scenario at the moment though. If this is the case, I suggest just sticking with a "dev" option for now.

> If we do this, doesn't that promote ppl not using the flags as we intend them to be used?

I am on board with exclusively using `-network <network-name>` instead of the shorthands if it means less flag parsing code. The requirement of entering an additional word when passing in the flag doesn't seem that onerous especially if there is also going to be an option to specify all these values in a config file.

**Comment by j0sh** [comment]
> I suggest changing "devenv" to "dev" to eliminate any possible confusion around when that flag should be used

I think the value of a hardcoded value such as "devenv" is in that it explicitly sets a certain configuration, such as a local geth URL, whereas the test harness probably has a different configuration (specific to each test harness instance).

Is the suggestion more that we have `dev` as the "default empty" set of configs that has to be specified elsewhere? In that case, the `-network` name could really be anything; if we're already initializing an empty/default config struct for a nonexistent network, we can just use the name that the user supplies.

> An aside: I think it would be helpful if the node checked the network ID used by the ETH node it is connected to to make sure it is actually connected to the correct ETH network.

Should we also make this available as a flag? If the network ID is specified via flag then the node could exit early if the ID mismatches. If we don't already check the network name somewhere or make it easily accessible, then this feels like a "new feature" on top of the config cleanup. So I'd prefer to handle that separately, but it certainly seems nice to have.

Also just wanted to firm up the consensus around the default, no-`-network`-specified behavior. @angie mentions that offchain would be default which seems reasonable at first glance. We also want to be sure to preserve the current onchain behavior, eg exiting early if a connection to geth can't be established or the controller is not found. Following that, the behavior seems to be thus:

```
if `-network offchain` or not specified:
  onchain = false
else
  onchain = true
```

There are still some combinations of flags that might produce unexpected behaviors. For example, do we still want this combination of options to result in offchain mode?
* No `-network` specified
* Valid and complete set of Eth options specified, eg geth, controller

Here, I like the idea of going onchain just from a usability perspective, but there's the question of what the (default) data folder name should be here -- certainly not `offchain`. Or  should we error out in this case and make `-network` mandatory if the Eth options are set?

What about a combination of both options above, plus a custom `-datadir`? Then the desired datadir is unambiguous, since we won't be putting the network name in as a sub-folder (or at least, that's the behavior I'd like to see).

> I am on board with exclusively using -network <network-name> instead of the shorthands if it means less flag parsing code

Part of me likes the shorthand as a signal that "this magically sets a bunch of other flags under the hood" rather than overloading the network flag with "special values" and multiple meanings (sometimes it sets other flags, depending on the value, and sometimes it only sets the datadir sub-folder name). In effect, I like shorthands for the semantic clarity, even if it makes for additional implementation checks.

But this is an extremely minor point of preference, so I'm OK with whatever people prefer.

**Comment by yondonfu** [comment]
> I think the value of a hardcoded value such as "devenv" is in that it explicitly sets a certain configuration, such as a local geth URL, whereas the test harness probably has a different configuration (specific to each test harness instance).

I don't think we actually have a particular configuration associated with "devenv" - do we? My understanding is that the `-devenv` flag is only meaningful at the moment in that it sets the default data directory as `/datadir/devenv`. We have usually paired the use of the `-devenv` flag with something like `-ethUrl ws://localhost:8936`. The test-harness just passes in the WS URL for the Docker container running the ETH node for `-ethUrl` (https://github.com/livepeer/test-harness/blob/master/src/networkcreator.js#L476). 

> Is the suggestion more that we have dev as the "default empty" set of configs that has to be specified elsewhere?

Yeah basically.

> In that case, the -network name could really be anything; if we're already initializing an empty/default config struct for a nonexistent network, we can just use the name that the user supplies.

👍 Yeah we could do that. I originally thought to use "dev" to signal a development network, but I don't see any harm in allowing the user define the name.

> Should we also make this available as a flag?

I don't think that is necessary since the intent is for the node to confirm with the ETH node that it is actually on the network that the user specified. I was thinking that if the node passes in `rinkeby` or `mainnet` for the `-network` name, then the node queries the ETH node for the network ID and checks if it is equal to 4 if the `-network` name is `rinkeby` and 1 if the `-network` name is `mainnet`.

> If we don't already check the network name somewhere or make it easily accessible, then this feels like a "new feature" on top of the config cleanup. So I'd prefer to handle that separately, but it certainly seems nice to have.

I agree. I added this point as an aside, but it shouldn't be a part of flag clean up. I can create a separate issue for it.

> Or should we error out in this case and make -network mandatory if the Eth options are set?

I like requiring a `-network` name in order to go on-chain for simplicity - feels like the clearest usage IMO. If the user wants to go on-chain he/she would need to explicitly express an intent of what network he/she wants to use.

> Part of me likes the shorthand as a signal that "this magically sets a bunch of other flags under the hood" rather than overloading the network flag with "special values" and multiple meanings (sometimes it sets other flags, depending on the value, and sometimes it only sets the datadir sub-folder name).

Wouldn't we be overloading the network flag either way and the shorthand flags would just be an alternative way to set the network name? i.e. I can use `-network mainnet` or `-mainnet`, but they both do the same thing.

**Comment by angyangie** [comment]
> Here, I like the idea of going onchain just from a usability perspective, but there's the question of what the (default) data folder name should be here -- certainly not offchain. Or should we error out in this case and make -network mandatory if the Eth options are set?

I would vote for erroring out when `-network` isn't set. Making it mandatory would take some of this "magic" out of the system ... there would be no assumptions made about what network you meant to use.

> Part of me likes the shorthand as a signal that "this magically sets a bunch of other flags under the hood" rather than overloading the network flag with "special values" and multiple meanings (sometimes it sets other flags, depending on the value, and sometimes it only sets the datadir sub-folder name). In effect, I like shorthands for the semantic clarity, even if it makes for additional implementation checks.

I agree that having specific flags like `-rinkeby` or `-mainnet` would be good indicators that other flags are being set under the hood, if said flags aren't provided. Would logging out which options were automatically set, be helpful in this respect, to alert the user of the flags set?

> 👍 Yeah we could do that. I originally thought to use "dev" to signal a development network, but I don't see any harm in allowing the user define the name.

Is this a correct summary of this flag specifically @yondonfu and @j0sh? We have abandoned the idea of having a `-network dev` flag, but instead, will allow users to name their own network. Internally, we'd treat anything that isn't `rinkeby` or `mainnet`, as being an offchain "dev" network? If `-network` was anything other than rinkeby or mainnet, we'd have

**Comment by angyangie** [comment]
> Here, I like the idea of going onchain just from a usability perspective, but there's the question of what the (default) data folder name should be here -- certainly not offchain. Or should we error out in this case and make -network mandatory if the Eth options are set?

Sounds like we are all in favor of or okay with erroring out when `-network` isn't set. Is this a fair assumption? Making it mandatory would take some of this "magic" out of the system ... we wouldn't be using a combinations of other flags to guess at what network a user might be trying to use if they didn't set that flag.

> Part of me likes the shorthand as a signal that "this magically sets a bunch of other flags under the hood" rather than overloading the network flag with "special values" and multiple meanings (sometimes it sets other flags, depending on the value, and sometimes it only sets the datadir sub-folder name). In effect, I like shorthands for the semantic clarity, even if it makes for additional implementation checks. But this is an extremely minor point of preference, so I'm OK with whatever people prefer.

Thanks for your opinion here @j0sh ! I hear your concern with "special values" and multiple meanings. However, I do think the convenience of not having additional logic based on  `-rinkeby` or `-mainnet` flags wins for me. If you don't have too much of a preference, would it be okay with you if we went with the `-network <network_name>` approach? 

> 👍 Yeah we could do that. I originally thought to use "dev" to signal a development network, but I don't see any harm in allowing the user define the name.

Is this a correct summary of this flag @yondonfu and @j0sh? : We have abandoned the idea of having a `-network dev` flag, but instead, will allow users to name their own network. Internally, we'd treat anything that isn't `rinkeby` or `mainnet`, as being an "offchain" "dev" network? If `-network` was anything other than rinkeby or mainnet, no options would be auto set for them, other than `*datadir = *datadir + "/<name_of_network_supplied>"`.

 >  I was thinking that if the node passes in rinkeby or mainnet for the -network name, then the node queries the ETH node for the network ID and checks if it is equal to 4 if the -network name is rinkeby and 1 if the -network name is mainnet. I agree. I added this point as an aside, but it shouldn't be a part of flag clean up. I can create a separate issue for it.

Agree this is important and would be great as a separate issue.

**Comment by j0sh** [comment]
Resolved in https://github.com/livepeer/go-livepeer/pull/738
