### ISSUE TITLE
Broadcaster VOD Database Design

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#591]
### Intro

One of the benefits of VOD is that it allows for "fire and forget" jobs, including persistence across node restarts. Ideally, at any (reasonable) point after submitting a VOD job, the broadcaster would be able to:

1. View a list of all historical jobs and their statuses
1. Process transcode results of any pending jobs
1. Play back completed jobs

This describes a DB schema for broadcaster VOD and poses some design decisions for discussion. Note that this applies to the broadcaster only; the orchestrator's schema may look different.

There may be unsaid assumptions here about the VOD workflow; happy to clarify if anything is unclear.

### Table `vod`

After an orchestrator is confirmed and a file segmented, the a row is added to the `vod` table containing information for the VOD job.

Column | Type | Description
---|---|---|
id | INTEGER NOT NULL |
input | STRING | URI / path to the input. Informational.
output | STRING | URI of the primary output file (master playlist). May be a local path.
orchURI | STRING NOT NULL | URI of the orchestrator that performed this job.
transcodeOptions | STRING | [Encoded version of the rendition strings](https://github.com/livepeer/go-livepeer/blob/fac0393950e821f16555a17eb460b8abe74f6ada/common/videoprofile_ids.go#L5-L15) 
segmentStart | INTEGER NOT NULL | Starting segment sequence number for this VOD job. Allows for reuse of on-chain jobs under the v1 smart-contract protocol.
segmentEnd | INTEGER NOT NULL | Ending segment sequence number for this VOD job.
currentSegment | INTEGER NOT NULL | Number within the {segmentStart, segmentEnd}  range that has completed post-transcode local processing for this VOD job, regardless of success or failure. Allows for resumption of the processing if interrupted mid-job.
recordedAt | STRING DEFAULT CURRENT_TIMESTAMP
|| PRIMARY KEY(id)

 The `currentSegment` counter is strictly monotonic for a given job; going backwards means re-processing [1] previously processed segments.

[1] Post-transcode processing of a segment may include downloading the results, verifying the results, updating playlists and the DB, etc.
 
We retain the `orchURI` and `transcodeOptions` to decouple the VOD job from the on-chain broadcast job as indicated by the `broadcasts` table.

:question: Other than the orchestrator URI (which is needed to check the job status) and renditions (which are needed to construct playlists), is there currently a reason for us to store a reference to the on-chain `broadcasts` table? The `broadcast` table's status is still uncertain post-Streamflow.

### Table `vodErrors`

To only record the "interesting" data, we record any  transcode errors in `vodErrors` . This allows us to identify gaps that should not be recorded in the playlist, and to persist errors for later offline analysis. Errors should be much less frequent than successful transcodes, so tracking only errors keeps the bookkeeping to a minimum.

Column | Type | Description
---|---|---
vodId | INTEGER NOT NULL | ID of job in `vod` table
seqNo | INTEGER NOT NULL | Sequence number of this segment
recordedAt | STRING DEFAULT CURRENT_TIMESTAMP
errorMsg | STRING | Errors encountered, if any.
|| PRIMARY KEY(vodId, seqNo)
|| FOREIGN KEY(vodId) REFERENCES vod(id)

### Open Questions

There are a few points with this DB design that are open for discussion:

0. Do we even need `vodErrors` ?
    * Should we make post-transcode processing all-or-nothing, eg non-resumable?
    * We'd still need some indication of which jobs have completed processing. Adding in post-transcode resumption is not an especially large jump from there, other than the inclusion of this additional DB table.
    * Keeping a record allows for appending to previous jobs, which also benefits live streaming.

2. Should we store all segments in the DB rather than just errors? Or only successful segments?
    * If we store all segments, most will be rather uninteresting. **All** successful segments are uninteresting until Streamflow. Errors are much more interesting, not only to identify gaps in the playlist, but also for analytical purposes.
    * Storing all segments offers a more intuitive model of reconstruction: the DB lists exactly what goes in the playlist, rather than gaps
    * Storing only **successful** segments allows for DB handling within the playlist. However, keeping DB handling outside the playlist allows us to incorporate DB-related error handling alongside success handling, without expanding the playlist API in unrelated directions or scattering related code around.

3. If storing each segment, should we also store renditions in a separate rows?
    * A job with N renditions would get N+1 DB rows per segment (source + N renditions)
    * Would lead to even more nearly-identical data throughout the table.
    * Transcodes are currently all-or-nothing; no 'partial transcodes' that would merit separate rows for each rendition.
    * If the source fails (eg, failed upload), we'd still need to write N+1 rows unless we optimize this at the application layer with 'special' logic.

4. Do we need additional metadata related to each segment? Eg, URLs, duration, etc?
    * Requires storing each segment in DB, and possibly each rendition
    * Streamflow will probably require this.
    * I'm inclined to wait until Streamflow is better specified to do this

5. Rather than have a table for individual segments, we can store m3u8 playlists on-disk. However, there are numerous drawbacks to that approach:
    * Introduces a (comparatively expensive and redundant) whole-playlist serialization step, after each rendition of each segment
    * Playlists are likely to take up far more space on-disk than a segment DB table
    * HLS ends up becoming a de facto intermediate format. This may complicate things should we ever want to support eg, DASH or even other non-segmented formats.
   * Introduces additional opportunities for on-disk data inconsistency

**Comment by dob** [comment]
10,000 foot view level response here, without being aware of some of the design or prioritization decisions that may have already been discussed...

The one thing that ticks my antennae a little bit is the adherence to V1 concepts in the design, when we're nearing Streamflow which potentially changes some of these concepts. For example the notion that there's a singular orchestrator for the job, or even that there's the notion of a "job" that extends more than one segment.

I am all for building the p2p and media server portions that support VOD, as it will be a very useful feature for our early case studies and partners. But I don't see usage under V1 due to the high costs of claiming, so I think going all the way with the integrated design and implementation for an attempt at deployment would be a misprioritization relative to getting it working within (or after) our minimum viable streamflow milestone.

I know that you and the eng team have spent quite a bit of time on prioritization, so I'll leave the call to you all, but wanted to share this thought.

**Comment by j0sh** [comment]
Yes, this is a large reason why I'm asking for feedback here, so we can start seeing how VOD should fit into Streamflow, and to make it clear which parts we should build now, and which parts to defer until the Streamflow design is more concrete.

Without some accommodations for v1, we can't really have a usable VOD release until Streamflow. Perhaps that's a discussion to have.

> or even that there's the notion of a "job" that extends more than one segment.

While payments protocol won't necessarily have an idea of a "job", the broadcaster certainly will; it still needs a way to group related segments together for later playback.

**Comment by Randy1Burrell** [comment]
I like the idea of a separate table for errors. The thinking behind this is that if we want to build a fully featured architecture for video transcoding then just being decentralized is not enough. We still need to be able to run data analysis to see what happened and where we can improve. From my stand point all metadata will be useful data at one point or another. Application level logic can be a good suggestion to mitigate against N + 1 DB rows per segment but there should be some way in the back-end to stop that.

As for m3u8 playlists on-disk, I'm not so sure that this would be the best thing to do if it limits our ability to support other video formats. Let me put what I mean it into perspective:

* If this is a faster implementation and can have the effect of us achieving streamflow faster then sure store it on disk.
* If this will hinder us in the future from serving a wider community then I'm against on disk storage.
* If the infrastructure can be updated in the future to give users the choice of storing on disk or otherwise then this would be a lovely option paired with the first point. That way we would be able to support other video formats if they opt for off disk storage.

Maybe there are other solutions that I am missing but I would use 2/3 as the deciding factor for my design decision. Any thoughts about my suggestion?

**Comment by eladmallel** [comment]
@j0sh thanks for sharing this! some thoughts and questions:

1. I could use some additional context on VOD to form intelligent opinions here. Is there a PRD or any additional context I should read to better understand everything VOD means to us?
2. I wanted to share that I think it best for us to focus as much of our brain power as possible on speccing and breaking down Streamflow into actionable work first, and only once that's in a good place spend more time figuring out VOD. Too much of our team's velocity is in this "pending Streamflow" state right now, and I think we need to graduate from this state ASAP.

wdyt?

**Comment by j0sh** [comment]
@Randy1Burrell 
> this would be the best thing to do if it limits our ability to support other video formats

Yes, this is why I'm hesitant to use m3u8 playlists in place of a DB table to store segment information.

@eladmallel
> Too much of our team's velocity is in this "pending Streamflow" state right now

Making VOD a Streamflow dependency is going to reduce velocity even further until we get the Streamflow details worked out. We might decide that's necessary, which is OK. Or we can try to pipeline some of that work in.
