### ISSUE TITLE
Add transcoder address flag to livepeer.go

### ISSUE THREAD

**Issue by angyangie** [livepeer/go-livepeer#605]
**Is your feature request related to a problem? Please describe.**
Standalone transcoders and broadcasters are both specified using the -orchAddr flag in  `livepeer.go`. We'll need a way to distinguish between the two. We currently use a transcoder boolean variable in combination with the offchain flag and an orchestrator flag to determine whether something is running in transcoder or broadcaster mode.

**Describe the solution you'd like**
Add a flag for a standalone transcoder address, to minimize broadcaster changes

**Describe alternatives you've considered**
Split into different binaries, eg one for the broadcaster, orchestrator, etc. This could be useful in the future, but is not necessary at the moment. 

**Additional comments:**
We need a better system for managing our flags in general. In the long run, using a config file for flags could make livepeer.go cleaner. The flag logic is getting gnarly, and will only get worse as we add more flags.

**Comment by j0sh** [comment]
Another option is to also re-purpose the existing `-transcoder` flag to make it additive (rather than exclusive) to the `-orchestrator` flag:

* `-transcoder -orchAddr ...` runs a standalone transcoder
* `-orchestrator` runs a standalone orchestrator
* `-orchestrator -transcoder` runs an orchestrator with a local transcoder

The drawback is that this breaks the existing behavior of the node; it's a question of how much compatibility with existing setups we want to preserve.

Also related is the original discussion on flags for the O/T split, which was done before O Discovery: https://github.com/livepeer/go-livepeer/issues/567

**Comment by j0sh** [comment]
Some more context for the general issue:

After the O/T split, the `-orchAddr` flag was introduced. Standalone transcoders are specified using the `-orchAddr` option.

With O Discovery, the broadcaster will be able to manually select an orchestrator via a CLI flag. For consistency, it seems natural to reuse the `-orchAddr` flag for the broadcaster to specify the orchestrator. However, we need a way to distinguish between "standalone transcoders" and "broadcasters" .

Yet another option is to add a `-broadcaster` flag, but that's also a breaking change.

**Comment by j0sh** [comment]
Resolved by using `-standaloneTranscoder` in https://github.com/livepeer/go-livepeer/pull/604
