### ISSUE TITLE
Let users withdraw deposited ETH via CLI if started with --transcoder flag

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#606]
**Is your feature request related to a problem? Please describe.**
Users who have deposited ETH (as broadcasters) can't withdraw it via the CLI if their node was started with the `--transcoder` flag. The CLI option only shows up when started without that flag.

**Describe the solution you'd like**
Show that option regardless of what mode the node is running in. Is there a good reason not to?

**Describe alternatives you've considered**
If the functionality is very different between `--transcoder` mode and ingest node mode, then perhaps they should be two separate binaries (or scripts that invoke the binary with different options) rather than a single binary, which will confuse users about missing functionality when they move between modes?

**Additional context**
This was reported by @lemiscate in the Discord.

**Comment by j0sh** [comment]
> Show that option regardless of what mode the node is running in. Is there a good reason not to?

The orchestrator mode CLI currently has 18 options -- we filter out broadcaster-specific options to make the list of options a bit less overwhelming.

Note that the orchestrator mode can't make deposits via the CLI either. I'm not sure we should expose withdraws (or deposits), since O doesn't need to manage deposits in the normal case.

> If the functionality is very different between --transcoder mode and ingest node mode, then perhaps they should be two separate binaries (or scripts that invoke the binary with different options)

This is something we've been discussing recently, but no settled consensus yet on what to do. This is a good data point, thanks for the report.

**Comment by j0sh** [comment]
I'll close out this issue soon unless anyone has thoughts otherwise about this ticket; discussion is always welcome.

**Comment by yondonfu** [comment]
I'm ok with closing this issue because my preference would be to keep the broadcaster and orchestrator specific options separate i.e. an orchestrator should not be managing ETH deposits so it should never be exposed to those options. I would be on board with tracking whether we want to have 2 separate binaries in a separate issue dedicated to that topic.

**Comment by ericxtang** [comment]
Closing.
