### ISSUE TITLE
pm: responses to acceptable and unacceptable invalid tickets and 

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#634]
**Is your feature request related to a problem? Please describe.**

There is a distinction between "acceptable invalid tickets" and "unacceptable invalid tickets" using the following criteria: could the invalid data in the ticket be a result of information that B has not yet received?

O needs to be able to differentiate between acceptable and unacceptable invalid tickets using the above criteria. 

O also should provide a grace period for acceptable invalid tickets for the sake of quality of service.

**Describe the solution you'd like**

Acceptable invalid tickets:

- Invalid faceValue and/or winProb since these values might have been acceptable at one point, but perhaps O now no longer accepts these values and B does not know about the new values yet
- Invalid recipientRand + randSeed since B might not have received the new pair after sending out a winning ticket yet due to async messaging

Unacceptable invalid tickets:

- Invalid senderNonce i.e. a replay
- Invalid randSeed s.t. `H(randSeed, O.randSecret) != T.recipientRandHash`
- Other invalid fields in the ticket. Ex. invalid recipient address (i.e. not O's address), invalid timestamp (or whatever time indicator is being used), invalid signature from B, etc.

Furthermore, O should respond different to these two types of invalid tickets.

- When O receives an unacceptable invalid ticket, O should not process the segment from B, respond with `ErrUnacceptableInvalidTicket` and disconnect.
- When O receives an acceptable invalid ticket, O will respond with `ErrAcceptableInvalidTicket`, provide B with a grace period and after this grace period, O will not process the next segment from B and disconnect. See below for grace period details.

We can implement the grace period by having O maintaining a counter `acceptableInvalidTickets` for each B that is incremented every time O receives an acceptable invalid ticket from B. This counter is reset every time O receives a winning ticket from B. O also defines a threshold `maxAcceptableInvalidTickets`. If `acceptableInvalidTickets > maxAcceptableInvalidTickets`, the grace period ends.

**Describe alternatives you've considered**

- O allows B to send invalidTicketsInARowAllowed invalid tickets in a row before disconnecting, to allow B time to receive and use the new recipientRand value (default setting invalidTicketsInARowAllowed=3).
- O maintains (on disk) an ongoing invalid tickets ratio per B as well as a invalidTicketRatioThreshold above which O rejects further video/tickets from B (invalidTicketRatioThreshold should be at least invalidTicketsInARowAllowed/ticketWinningProbability)

Neither of these solutions seems to have an advantage over the absolute counter.

**Comment by j0sh** [comment]
It might help to drill down to specific conditions under which "acceptable invalid" tickets could happen. I think there's an argument to be made that we can disregard these for MVS.

> Invalid faceValue and/or winProb since these values might have been acceptable at one point, but perhaps O now no longer accepts these values and B does not know about the new values yet

The way O selection works, B would always query for updated `orchestratorInfo` values prior to starting the stream. So, B should never start a stream with an invalid `faceValue` or `winProb`. The only time this would happen is if the values changed mid-stream.

> Invalid recipientRand + randSeed since B might not have received the new pair after sending out a winning ticket yet due to async messaging

This can be distinguished further. The ticket should be "unacceptable invalid" if the `recipientRandHash` can not be generated from the given `randSeed`. Because of the just-in-time O selection process, B should never submit an invalid `recipientRandHash`.

The only time a ticket could be "acceptable invalid" is if a winning ticket was submitted to the blockchain. Winning `recipientRand` needs to be a separate check. And this should be a hard fail if it occurs at the beginning of a stream.

Given these scenarios, it seems possible to simplify how we handle invalid tickets for MVS. In particular, we can disregard the notion of "acceptable invalid" tickets in MVS and consider all invalid tickets to be unacceptable.

* We can add tolerance for dynamic faceValue/winProb to an **existing** stream at SS or at some later point. Until then, the faceValue/winProb can be set at the time a `recipientRand`/`randSeed` is generated.
* Since MVS operates in a trusted environment without double spending concerns, we can defer cashing winning tickets until shortly after receiving the last segment. Other than storing a list of winning tickets in the transcode loop (rather than cashing them immediately), this seems a bit simpler overall, as it avoids the trouble of implementing grace periods for MVS and the associated state refresh on B/O.
* Breaking up the work in this way will likely give us a better notion of how the grace period can be layered in during SS or later.

**Comment by yondonfu** [comment]
> So, B should never start a stream with an invalid faceValue or winProb. The only time this would happen is if the values changed mid-stream.

Agreed that invalid `faceValue` and/or `winProb` is not a concern for a MVS so it might be premature to handle this case and may be best to wait until this case is possible i.e. when the acceptable `faceValue` and/or `winProb` might change mid-stream.

> The ticket should be "unacceptable invalid" if the recipientRandHash can not be generated from the given randSeed. Because of the just-in-time O selection process, B should never submit an invalid recipientRandHash

Good point. I will update the OP to include this.

> The only time a ticket could be "acceptable invalid" is if a winning ticket was submitted to the blockchain.

To clarify - if a winning ticket is submitted on-chain with `recipientRand`, any subsequent tickets sent to O with a `randSeed` that generates `recipientRand` will be invalid (this is distinct from sending O the same winning ticket since these subsequent tickets can have unique values for `senderNonce`). These tickets are considered "acceptable invalid" if they are received mid-stream because B might not have received the new `randSeed` value to use from O yet. These tickets are considered "unacceptable invalid" if they are received at the beginning of a stream since B should have the an up to date `randSeed` after its initial query for O.

I would consider adding a grace period in MVS for this if this happens mid-stream as this scenario is likely to happen every time `randSeed` is changed upon receiving a winning ticket.

> Since MVS operates in a trusted environment without double spending concerns, we can defer cashing winning tickets until shortly after receiving the last segment.

While I think that makes sense in a trusted environment, I feel like it might be better to implement immediate redemptions in MVS because that is also appropriate in a an untrusted environment (while redeeming at the end of a stream might not be) which is what we're gradually moving towards anyway. Then, if/when we feel like we have addressed double spend concerns (in SS) we can modify the redemption strategy accordingly.

**Comment by eladmallel** [comment]
I don't understand how deferring ticket redemption relaxes the requirements for the random numbers swap grace period.

If we defer ticket redemption till the end of the stream I can see how it's helpful, because we end up with zero random number changes mid-stream.

However, as long as we redeem mid-stream (which I think is preferable), we will certainly have a random number change mid-stream, which forces us to allow some grace, because it's sufficiently likely that B will have a race condition between new random numbers and outgoing segments and tickets.

Therefore I arrive at the conclusion that deferring ticket redemption doesn't change the random numbers grace requirement.

Am I missing something?

**Comment by j0sh** [comment]
>If we defer ticket redemption till the end of the stream I can see how it's helpful, because we end up with zero random number changes mid-stream.

That's why.

The idea was that immediate redemption isn't a strict requirement for MVS (because double spending isn't a concern), which means we could also defer the work for the grace period and the handling around that. There was a lot of thought around counters, ratios, etc which indicates it's maybe a deeper area. Breaking up the work and letting the initial grace-less implementation breathe for a bit would also likely offer better insights into how this could be handled.

This is just a suggestion though; I understand the consensus is leaning towards a "safer by default" implementation even it means more upfront work. That's fair.

**Comment by eladmallel** [comment]
After considering @j0sh's feedback further, we are going for the idea of redeeming tickets only at end of stream for MVS, thereby punting on this issue till SS.

**Comment by yondonfu** [comment]
A few things have changed since this issue was originally created. Most notably, `faceValue` and `winProb` can now change mid-stream since these values are computed dynamically based on O's current view of the network gas price as well as B's max float. The OP proposes an absolute counter for invalid acceptable tickets with counter resets triggered when O redeems a winning ticket - the original motivation behind using a winning ticket as a counter reset was that redeeming a winning ticket would invalidate the ticket's recipientRand and it would be reasonable to expect a B to send a invalid ticket with the old seed (which maps to the invalidated recipientRand) after this point due to a delay in receiving the new seed. Now, since `faceValue` and `winProb` can change mid-stream, we should take into account how this impacts counter reset triggers.

Below is a summary of acceptable invalid ticket errors and the reason behind those errors:

- `invalid ticket faceValue`
  - If O's view of the network gas price changes. At the moment, the gas price view is [refreshed](https://github.com/livepeer/go-livepeer/blob/master/eth/gaspricemonitor.go#L71) every minute
  - If B's max float changes. At the moment, B's max float changes when O [submits a ticket redemption tx and when the tx confirms on-chain](https://github.com/livepeer/go-livepeer/pull/926/files#diff-3a62c7d0189200e6024095a62a267eaaR323)
- `invalid ticket winProb`
  - Same reasons as `invalid ticket faceValue`
- `invalid already revealed recipientRand`
  - O redeemed a ticket with the recipientRand thereby invalidating the recipientRand

A possible approach is to trigger counter resets whenever:

- O redeems a ticket thereby invalidating the recipientRand
- If O's view of the network gas price changes
- If B's max float changes
