### ISSUE TITLE
pm: failure condition for B when O does not respond

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#636]
**Is your feature request related to a problem? Please describe.**

O might not respond to B's segments/tickets for a number of reasons. Thus, B should implement a failure condition such that if this condition is fulfilled, B will stop sending segments/tickets to O.

**Describe the solution you'd like**

B maintains a counter `missingTranscodedResults` that is incremented each time B submits a segment/ticket and decremented each time B receives a transcoded result. If `missingTranscodedResults > maxMissingTranscodedResults`, B stops sending segments/tickets to O and disconnects.

**Describe alternatives you've considered**

There is probably a better solution especially in the future when we add the notion of value accounting, but this just seeks to be the simplest possible failure condition for MVS to trigger disconnects for B.

**Comment by j0sh** [comment]
The proposed approach of counting missing responses seems good. There are a number of scenarios that should be considered there:

* Availability of O itself
* Timeliness of O responses. We're under tight time constraints for live video.
* O's busy indication
* Errors stemming from B itself (eg, B getting knocked offline) which shouldn't count towards O

Perhaps this can be addressed at a later phase (redundancy / failover) rather than within PM itself.

**Comment by eladmallel** [comment]
> The proposed approach of counting missing responses seems good. There are a number of scenarios that should be considered there

To clarify how we might handle the other use cases you mentioned, taking the first example of O's availability:

What would that look like in practice? (a) B not being able to even open an HTTP connection to send O stuff because O is down (immediate failure) (b) B being able to send stuff over, but O never returning a response (timeout). Am I missing other ways this problem can show itself?

Sounds like we solve for (b) with this counter approach. The counter could probably also work for (a), but perhaps B can decide to stop working with O sooner in the case of (a)? - Curious to hear what alternative approach you had in mind?

**Comment by j0sh** [comment]
That sounds correct -- not receiving a timely response seems to be the place where the counter would be most useful [1]. 

If O is unavailable (eg, sending the segment fails immediately) then B should failover to another O right away. Immediate failover is also probably the polite thing to do if O also indicates that it's busy.

Detecting the case where B is offline is where it's a little tricker. This will be easier to determine via redundancy: if B attempts to connect to some number of O's, but all are "offline" then it's more likely that the issue lies with B itself. We can just keep failing over and going down the list of orchestrators, although maybe only up to a certain number.

[1] The request timeout has been disabled on O side ever since the O/T split -- however I think we're still fine here since it's only the B-side timeout that matters 😅 Related: https://github.com/livepeer/go-livepeer/issues/576

**Comment by yondonfu** [comment]
Closing this because this should be addressed by the failover mechanism B uses when it encounters a non-responsive O.
