### ISSUE TITLE
PM Missing Dependencies

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#683]
**Describe the bug**
When building the code, we get errors because of missing dependencies

**To Reproduce**
1. Do `go build cmd/livepeer_cli/*.go`

**Expected behavior**
Build successful

**Screenshots**
```
[Erics-MBP-2][ericxtang]-> go build cmd/livepeer_cli/*.go
pm/recipient.go:12:2: cannot find package "github.com/pkg/errors" in any of:
	/Users/ericxtang/Code/Livepeer/lpdev-data/go/src/github.com/livepeer/go-livepeer/vendor/github.com/pkg/errors (vendor tree)
	/usr/local/go/src/github.com/pkg/errors (from $GOROOT)
	/Users/ericxtang/Code/Livepeer/lpdev-data/go/src/github.com/pkg/errors (from $GOPATH)
pm/stub.go:12:2: cannot find package "github.com/stretchr/testify/mock" in any of:
	/Users/ericxtang/Code/Livepeer/lpdev-data/go/src/github.com/livepeer/go-livepeer/vendor/github.com/stretchr/testify/mock (vendor tree)
	/usr/local/go/src/github.com/stretchr/testify/mock (from $GOROOT)
	/Users/ericxtang/Code/Livepeer/lpdev-data/go/src/github.com/stretchr/testify/mock (from $GOPATH)
```

**Comment by yondonfu** [comment]
If you're building locally try `go get -d github.com/livepeer/go-livepeer/cmd/...`

The packages mentioned in the error message are not vendored at the moment.

**Comment by j0sh** [comment]
Another option, perhaps easier to remember, is to `go get ./...`  from the goclient root dir.

I guess the question is whether we should vendor these packages?

We haven't been vendoring recent additions (eg, grpc). I'm hesitant to make the git tree even larger than it already is. I'm hoping that the vgo implementation from golang 1.11 will mitigate the need to vendor most modules (so we can slim down the tree), but haven't looked into it too closely.

Note that a user starting fresh (eg, running the readme) won't encounter this issue since `go get` fetches all dependencies automatically, and the use of `go get` is recommended in the readme.

**Comment by eladmallel** [comment]
I think we should not vendor these two packages because one is only used in testing and the other is simple enough such that a breaking change is not very likely.

wdyt?

**Comment by yondonfu** [comment]
I'm on board with not vendoring these packages and taking the time to see if we can use the vgo implementation in go1.11 for any packages used in production that need to be fixed at a specific version.

**Comment by ericxtang** [comment]
Ok.  That's fine with me.  Closing this issue.
