### ISSUE TITLE
Transcoding node starts up slowly from scratch

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#713]
**Is your feature request related to a problem? Please describe.**
During bootup of a new transcoding node, it hangs for 2-3 minutes before the servers start.  I think it's because state loading from the blockchain.

**Comment by ericxtang** [comment]
@yondonfu will do some investigation to figure out whether it's an event subscription issue.

**Comment by yondonfu** [comment]
@ericxtang What release/version of the node were you using when you observed this behavior?

**Comment by yondonfu** [comment]
Additional details:

Node Version: [0.3.1](https://github.com/livepeer/go-livepeer/releases/tag/0.3.1)
ETH Connection: Infura

I suspect the long delay in query response might be related to how Infura handles `eth_getLogs` RPC queries over large ranges of blocks (perhaps some type of rate limiting). I ran an `eth_getLogs` RPC query for the BondingManager contract deployed on mainnet for a range of ~275,000 blocks against both Infura and Alchemy and I received responses for both queries in a reasonable amount of time. It is also possible that something internal to Infura was updated since the time when this issue was first observed.

A first step we can take right now is to make sure to set client side timeouts for these types of `eth_getLogs` requests which are provided via a context in [bind.FilterOpts](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/base.go#L65). At the moment, we are not explicitly passing in a context with `bind.FilterOpts` so a [context.TODO](https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/base.go#L347) is used. If we add a client side timeout, we can at the very least make the node does not hang on these queries for too long.

**Comment by yondonfu** [comment]
#731 should help with this so that at the very least the node does not hang on a `eth_getLogs` request for too long.

I think we can close this for now and if this problem is reported again we can revisit using additional details from the reports.
