### ISSUE TITLE
Split `rpc.go` into client and server parts

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#715]
**Is your feature request related to a problem? Please describe.**
`rpc.go` grown to big and it's hard to understand program flow in it.

**Describe the solution you'd like**
Split `rpc.go` into `rpc_server.go` and `roc_client.go`

**Describe alternatives you've considered**
Do nothing.

**Comment by angyangie** [comment]
Perhaps we can tackle this task along with these two issues, since they're all related:

1. Adding unit tests for ServeSegment and SubmitSegment: https://github.com/livepeer/go-livepeer/issues/675

2. Cleaning up lengthy ServeSegment and SubmitSegment functions: https://github.com/livepeer/go-livepeer/issues/714

**Comment by darkdarkdragon** [comment]
PR #732  is merged
