### ISSUE TITLE
The ultimate dev setup

### ISSUE THREAD

**Issue by eladmallel** [livepeer/go-livepeer#718]
**Is your feature request related to a problem? Please describe.**

In recent months we've created some new tools, such as the test harness, improved docker images, `devtool`, etc. At the same time, we still have the devenv project, with its own helper flows and a vagrant machine setup.

I think it would be great to consolidate everything into the best setup we can offer. I think the result should be:
- Greater clarity on how to set up your dev env
- Less moving parts to maintain
- Possibly an overall more productive setup for us all

**Describe the solution you'd like**
I don't know what the solution should be yet - would love a team discussion on this!

**Describe alternatives you've considered**
Leave things as-is :)

**Additional context**
None.

**Comment by ericxtang** [comment]
Is this addressed by the test harness?

**Comment by darkdarkdragon** [comment]
@ericxtang don't think so, but I don't think this was issue in the first place - we have fairly complex project, and there are no one "right way" to do development - different people work on different parts and thus have different optimal development setup.

**Comment by ericxtang** [comment]
@darkdarkdragon I agree that different people will have different setup, but I think some kind of "canonicalization" can help us make progress faster, and save some efforts in maintaining different toolsets.  This can mean modularizing the tools - for example, the `test-harness` does a pretty good job deploying a vanilla network, and can be helpful to a lot of people.

**Comment by j0sh** [comment]
Our dev story is getting better, but I don't think we're out of the woods yet. Agreed that it helps to have a canonical story to help new *developers* get started [1], but I think we're missing is consensus on what this story should look like, and putting that story up-and-front for devs. The recommended approach used to be devenv, but I'm not sure what it is anymore.

One of the big frustrations with devenv is how touchy the blockchain parts are. The test harness certainly helps with that although we should probably publicize the [documentation](https://github.com/livepeer/test-harness/blob/master/docs/demo.md) more widely.

However, I don't think the test harness alone is suitable for active, iterative *development* of the goclient (which I guess is the subject of this ticket). At the very least, the process of building + deploying a new set of goclient containers for each change is tedious. If this is better now, it needs documentation.

Another option would be to use a protocol deployed via test harness in conjunction with a local development environment. Would love to know if this is possible, and where the documentation for that is.

To work around the protocol related issues, I've been directing folks to build and run the goclient in offchain mode, but that feels incomplete and maybe a bit long-term counterproductive to mainnet adoption.

Then protocol development itself may have its own workflows or considerations, but not sure if that belongs in here. cc @yondonfu 

[1] Emphasis on developers (folks working on the goclient) rather than end users who might just want to test Livepeer by running a prebuilt node on a private network.

**Comment by darkdarkdragon** [comment]
@j0sh 
> At the very least, the process of building + deploying a new set of goclient containers for each change is tedious.

Right now it is matter of
`make localdocker` and
`./test-harness restart`

make takes 30-40s on my MacBook Pro for simple change in `mediaserver.go` and test-harness restart takes 5 sec.

> Another option would be to use a protocol deployed via test harness in conjunction with a local development environment.

Isn't that is the same as just running docker container with Geth (with pre-built protocol) and running go-client on host with config made by `devtool`? What is the need for test harness here?

**Comment by hthillman** [comment]
closing for now as the details are outdated - planning to resurrect as part of OSS pod work
