### ISSUE TITLE
Go on-chain in case no suitable orchestrators found in db

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#728]
**Is your feature request related to a problem? Please describe.**
Right B pull list of Os from chain on start and every hour. So, if B can't find suitable O, but suitable O was registered after B's last check, B won't know about it till next check.

**Describe the solution you'd like**
In case B can't find suitable O in it's cached list, it should go on chain for the new list of Os (probably with some de-bouncing, say, don't go on chain if same check was made less than five minutes ago).

**Describe alternatives you've considered**
Do nothing.

**Comment by yondonfu** [comment]
An alternative is for O to run a background service that watches for transcoder update events (at the moment this would involve subscribing to the [TranscoderUpdate()](https://github.com/livepeer/protocol/blob/master/contracts/bonding/IBondingManager.sol#L9) event and filtering for events where the `registered` field is `true` - this isn't the best contract event interface and could be improved separately). So, on start up, O would refresh its cached list and then start this background service which would update the cached list as on-chain updates happen. This type of more active refreshing process may not be necessary if there ends up being a preference for Os that have been registered for longer (and not Os that have just popped up) in which case refreshing the cached O list every set time period might be fine.

**Comment by j0sh** [comment]
Long-term, listening to transcoder-related events seems like the most robust solution. One other approach we had was to build a local list of active transcoders from `reward` calls rather than initializing and reading an on-chain list every round. B's view of the active transcoders list would remain fairly up-to-date that way.

Right now, new Os can only be added once a round, so every ~24h. Are we planning to change that for Streamflow? B's view of the on-chain Os would only be stale for the period between round initialization and the next cache refresh, so 1 hour at the most. For most normal cases, this seems acceptable, although I understand that the accelerated rounds with devenv or test harness may cause issues beyond what we consider to be a "normal" environment.

I am a little hesitant to add special, blocking cases mid-flow, especially ones that would only occur infrequently and are "heavy", eg requiring many external calls to read from the blockchain. However, it would probably be useful to add a separate CLI endpoint to trigger an async refresh. If the test harness behavior is what prompted this issue, then perhaps a manually triggered refresh would also resolve this, absent blockchain monitoring?

**Comment by darkdarkdragon** [comment]
Ok, I'm closing this one. It indeed was about behavior in test environment, and after more thoughts, it not that big problem and we shouldn't add any code specific to testing.
