### ISSUE TITLE
Integrate OpenCensus client library

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#760]
Make it available at `/metrics` endpoint on CLI port
Send to Prometheus following events (from Broadcaster) as simple counters:
- RTMP stream started
- RTMP stream ended
- Source segment appeared in manifest
- Segment uploaded for transcoding
- Transcoded segment appeared in manifest

Prometheus client library
https://github.com/prometheus/client_golang

**Comment by j0sh** [comment]
Curious: if we're sending to Prometheus, where does the `/metrics` endpoint come in? The former implies push, while the other implies pull.

**Comment by darkdarkdragon** [comment]
I wasn't accurately named it, Prometheus will be pulling metrics

**Comment by j0sh** [comment]
Is pulling the only configuration available on Prometheus? Pushing seems more desirable, since pulling requires exposing that area on the node, with all the associated concerns (security, redundancy of polling, etc). If push frequency is a concern, then perhaps the stats can be aggregated / rolled up and pushed periodically in batches.

**Comment by darkdarkdragon** [comment]
They do have some [solution](https://prometheus.io/docs/instrumenting/pushing/) for pushing, but it is not intended for our use case. 
Security here is no more of concern as for exposing CLI port - anyway it should be accessible only from some internal network.
What is `redundancy of polling`?

**Comment by j0sh** [comment]
>  They do have some solution for pushing, but it is not intended for our use case

That actually sounds quite nice for local log scraping / aggregation, which would allow us to avoid otherwise-invasive changes to the goclient itself.

> anyway it should be accessible only from some internal network

That would work for our current use case (private internal network), but I'd be generally uncomfortable with that type of setup in production/mainnet without more rigorous shielding in front of the CLI endpoint, since we can't assume all elements on a network can be trusted, internal or otherwise. If we do go this route, we need to do further work before we can promote it as a "batteries included" monitoring solution for the community.

> What is `redundancy of polling`?

If we don't have any interesting metrics to report (eg, the node is idle) then we're doing redundant work. With push, we can do exactly as much work as needed and no more.

**Comment by darkdarkdragon** [comment]
> That actually sounds quite nice for local log scraping / aggregation, which would allow us to avoid otherwise-invasive changes to the goclient itself.

I want to do changes in go client - many metrics much simpler to calculate on client itself (say, latency), then try to infer externally. Plus push gateway will not give us any advantage (you need to open port for it anyway), just another moving part need to be taken care of.

> but I'd be generally uncomfortable with that type of setup in production/mainnet without more rigorous shielding

Then we should allow to run metrics on separate port.

> If we don't have any interesting metrics to report (eg, the node is idle) then we're doing redundant work.

Anyway it will be neglectable amount of traffic, especially compared to traffic consumed by video itself. But pull model allow us setup number of pulling servers for different purposes. Say, we can create separate Prometheus server for each deployment and make it accessible to customer and in the same time also have own central server that will be scraping same deployment - just for us, to have overall picture of all deployments.

After some research I found this - https://opencensus.io/ - this is library for capturing metrics that can export them to many different systems (Prometheus, Google's Stackdriver, Datadog and other major vendors). Plus it has ability to trace request across services - which we will not use from start, but maybe it will be useful later. So I think it is way to instead of native Prometheus library.

**Comment by j0sh** [comment]
> I want to do changes in go client - many metrics much simpler to calculate on client itself (say, latency), then try to infer externally. 

It may be "simpler" to implement single metrics but I think it hurts long-term maintainability, and makes it harder to compose metrics to get a larger picture of the system. For example, our approach to measuring latency currently involves explicitly tracking the start/end times for each event we're interested in. This alone is cumbersome. We also can't track what's happening across different modules or within dependencies. With log parsing, we can non-invasively generate metrics based on logged events that may be happening across different parts of the stack. For example, there are many types of latency:

* Upload latency
* Transcode latency
* Download latency (OS)
* Verification latency
* Total latency of all the above
* Upload + download (network) latency, excluding transcoding
* Latency under different types of conditions, such as whether O brings its own object storage.

Measuring any combination of latencies becomes a matter of taking the difference in timestamps between the logged lines. With log parsing, we have the ability to evolve our reporting separately from changes to the goclient itself. We can't always predict the metrics we might be interested in, but we can retrofit new metrics onto old data as long as the appropriate log lines exist. This may be huge for debugging. It's hard to "ship metrics" but it's easy to send logs to someone.

This may mean we need to tighten up our logging and that is totally OK; more robust and informative logs will be an improvement, and tools to analyze these logs would be welcome.

> Then we should allow to run metrics on separate port.

How about a hybrid: a separate process that parses local logs and opens up a port for Prometheus to scrape? It should also be straightforward to extend this to run on a log aggregator if we ever need/want to.

> After some research I found this - https://opencensus.io/ - this is library for capturing metrics that can export them to many different systems

Looks good.

**Comment by darkdarkdragon** [comment]
I agree that parsing logs looks like good idea, but it has too much downsides:
- It adds additional moving parts that should taken care of
- It requires additional infrastructure - logs should be put somewhere, processes, metrics extracted and sent somewhere to be presented 
- Code to extract metrics from logs will be more cumbersome, because it needs to guess what happened from text. Going through text we're loosing type safety, thus making whole system more error-prone and less maintainable

> How about a hybrid: a separate process that parses local logs and opens up a port for Prometheus to scrape?

It doesn't give us any advantage, but adds large amount of work - in writing all that, maintaining and running it all on servers.

In general, this is not our core product, and I want to spend as little resources as possible on that thing. Adding extra layers will increase resources needed to develop/support it.

**Comment by j0sh** [comment]
Agreed that it is additional moving parts. There are tools such as [mtail](https://github.com/google/mtail) that could help with this.

I think this also goes back to what we're trying to accomplish with the metrics system: is it meant to provide an overview the health of the node / network, or is it meant as a tool for drilling down and diagnosing specific problems? We built the old metrics system to try and accomplish both, but it was really more helpful for the former. In theory extracting metrics from logs would give us a better opportunity to accomplish both. Using Prometheus-style metrics is doubling down on the "overview" aspect, which is OK if we acknowledge that we're not really going to be able to use these metrics for anything other than systematic diagnoses, rather than particular incident analyses.

> In general, this is not our core product

Indeed. Part of the reason I'm keen on extracting the information from logs is that it doesn't involve actually touching the core product, which keeps each component lean and focused.

Anyway I'll leave the rest up to you.

**Comment by j0sh** [comment]
> That would work for our current use case (private internal network), but I'd be generally uncomfortable with that type of setup in production/mainnet without more rigorous shielding in front of the CLI endpoint, since we can't assume all elements on a network can be trusted, internal or otherwise. If we do go this route, we need to do further work before we can promote it as a "batteries included" monitoring solution for the community.

Based on our discussions here https://github.com/livepeer/go-livepeer/issues/781 my thinking around this issue has evolved -- whether to expose Prometheus on the CLI port -- and now it feels like the best action would be to have Prometheus share the CLI port as was originally suggested.
