### ISSUE TITLE
Determine optimal multi-O allocation/redundancy strategy

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#770]

**Comment by angyangie** [comment]
The primary concern when talking about B -> O, is resiliency. If a single O stops responding mid-stream, the goal is to have transcoding/streaming continue on seamlessly.

For **receiving transcoded segments**, Broadcasters should select whatever transcoded segment comes back first for that specific initial non-transcoded segment, regardless of what approach is being considered below.

There are several methods being considered for **assigning segments to O's:**
1. Sticky: a Broadcaster would choose an Orchestrator and continue sending segments to it, until the O stopped sending transcoded segments back. We’d select another O in that case (similar to what we have now).

This approach is what we have now. Our current failover code skips the segment that couldn't be transcoded when an O becomes unavailable, selects another available O, and continues transcoding following segments with said transcoder. We could make the failover code more sophisticated, and retry the segment that couldn't be transcoded with another O, rather than dropping it. "Always on" redundancy is not needed in this scenario.

2. Round-robin: a Broadcaster would “take turns” assigning segments to be transcoded to different Orchestators. eg. send seg1 to O1, seg2 to O2, seg3 to O3, seg4 to O1, seg5 to O2, etc. (in the case of three O's selected by the Broadcaster).

Using a round-robin approach, we'd buy ourselves time in the event that a segment fails to be transcoded (if that segments happens to not be the first segment of the stream). Since each individual segment would be sent to just one O (same as in approach # 1), "always on" redundancy would also not be needed. Since O's would have 1/3 of the workload as in the approach above, individual O's would be likely to process the segment more immediately than with a larger load (though this could depend on how many other transcoding jobs that O handles ... I'm not sure about this one, so please correct me if I'm wrong). 

The downside: you still wouldn't get the benefits of having another segment immediately available when one O fails.

3. Races: we submit a segment to several Orchestrators simultaneously.

Here, we'd have the security that even if one O failed, B would see no difference in transcoded segments. This could down the line allow us to include other kinds of filtering for transcoded segments received (quality of segments, trustworthiness of O's, etc.). 

The downside: B would have to pay for 2x, 3x, etc. the transcoding cost, depending on how many O's it chooses to use.

**Remaining questions:**
- How much does the time spent selecting a new O in approaches # 1 and # 2 affect stream playback delays/experience? What kind of latency does it add?
- Will some B's choose to pay 2x or more the cost of transcoding for failover?
- Can we allow users to themselves choose the kind of approach to use? Theoretically, we can make a choice between # 1 and # 2, and allow them to choose # 3 if they wish.

(Note: feel free to add more benefits and drawbacks)

Thoughts?

**Comment by ericxtang** [comment]
I think we should consider the redundancy approach separately from the O selection algo.  The redundancy should be determined by the broadcaster using the B node, and I see a case where the broadcaster will want different level of redundancy for different streams.

In terms of O selection, there has been another proposal being discussed in the research calls - **stake weighted random selection**.  This is similar to how we do onchain job assignment today.  @yondonfu can go into more details around the network-level emergent behavior based on this algorithm.

**Comment by angyangie** [comment]
I see the O selection algo issue now: https://github.com/livepeer/research-internal/issues/3. I missed that when I was gone, thanks for mentioning it! The name of this issue is a misnomer then - the focus is on redundancy, not on an orch selection mechanism (i.e. when or how to choose one particular O over another). I'll change the issue name. 

Regarding the options above, I do think it's worth doing # 1 regardless. The question is which to choose amongst the round-robin approach # 2 (must answer the question: what are the real benefits of doing that over having no redundancy, approach # 1??) and race approach # 3 (or allow user to choose between either one).

**Comment by j0sh** [comment]
There are a two different uses of the term "orchestrator selection" ; we should probably come up with a better term to delineate between the two.

* The process of determining which Os are eligible to work with based on pricing, on-chain information, history, reputation, etc. This is the selection that's discussed here livepeer/research-internal#3 .

* Given a list of eligible orchestrators: which ones are allocated segments to do the work, and how?  Essentially, second-order "selection after selection". That is the type of selection this is exploring.

Perhaps a better term for this type of selection would be "orchestrator allocation".

**Comment by j0sh** [comment]
> How much does the time spent selecting a new O in approaches # 1 and # 2 affect stream playback delays/experience? What kind of latency does it add?

Very good question. There are a couple factors here:

* We can maintain a list of Os that would be good candidates. This list can be a few more than we actually need to use (M-of-N); eg if we only need to use one orchestrator at a time, then perhaps we could maintain a list of three orchestrators and immediately fall back to the next in the list.

In fact, we already have the capability to return multiple Os from selection: https://github.com/livepeer/go-livepeer/blob/f120fb4b4f68e9fc4a937d2a856fc128d1c4c824/net/interface.go#L12

* Currently, we use the first orchestrator to successfully respond. This is actually quite fast, and usually means we only lose that one segment (or two at most, if the segment failed near the 2 second interval and a new segment is emitted during selection.)

* If we do maintain a "M-of-N" list of orchestrators, we'll still need to refresh this list occasionally. How often or under what conditions? Can this be done asynchronously to minimize disruption to the active stream?

> Will some B's choose to pay 2x or more the cost of transcoding for failover?

Perhaps. There are also a few other potential uses for this type of mechanism, that could be fleshed out after this project:

* Temporarily use redundancy as a performance discovery mechanism, eg at the beginning of a stream. The orchestrator(s) that consistently win the most races could eventually become the exclusive provider for a given stream. This doesn't actually address mid-stream failures though.

* Split the transcoding work among several orchestrators (eg, one O per rendition), so each O has less to do, and mitigates the impact of any one O going down. The cost isn't necessarily 2x here.

> Can we allow users to themselves choose the kind of approach to use? Theoretically, we can make a choice between # 1 and # 2, and allow them to choose # 3 if they wish.

Races are a something of a third-order selection mechanism in that races themselves can incorporate sticky selection, round-robin or even randomized selection. In fact, it is possible to model the current behavior as a "race-of-1 with sticky selection." So sticky races would send segments to the same Os each time, and round-robin races would send segments to a rotating set of Os, and so forth.

I don't think there is necessarily an immediately optimal choice for selection here though. We can assume the simplest method will be OK for now (sticky / in-order selection).

**Comment by angyangie** [comment]
> Currently, we use the first orchestrator to successfully respond. This is actually quite fast, and usually means we only lose that one segment (or two at most, if the segment failed near the 2 second interval and a new segment is emitted during selection.)

Are we looking to eliminate the loss of 1 or at most 2 segments, as a requirement to this work? 

> We'll still need to refresh this list occasionally. How often or under what conditions? Can this be done asynchronously to minimize disruption to the active stream?

To confirm - this is not referring to the list stored in the DB, but to the list stored in `OrchestratorInfo` on the `BroadcastSession`? We could need to refresh the list asynchronously after several scenarios (we already refresh the DB list asynchronously):
- Every time a certain percentage of O's from a list have been used. This could be an arbitrary number of say  25% or 50%. Not sure if there are any considerations to keep in mind when thinking about a specific number here. I could see the rate of failure of O's could influence what percentage we choose here.
- If we don't see scenario above happening before x minutes/hours, refresh the list. 

> Temporarily use redundancy as a performance discovery mechanism.

This is a great idea to consider for the future!

> Split the transcoding work among several orchestrators.

Is this different than the "round robin" approach outlined above?

> I don't think there is necessarily an immediately optimal choice for selection here though. We can assume the simplest method will be OK for now (sticky / in-order selection).

So, for now, we can assume we'll use sticky selection. Which means, we'll just focus on refreshing the list stored in `OrchestratorInfo` on the `BroadcastSession`,in a way that will allow for little to no segment loss? 

To confirm, thought we've been talking about redundancy, we will NOT be allowing user to select two or more O's to simultaneously send segments to? If we do, wouldn't we still have the question of whether to employ round-robin redundancy, or, simply sending all segments to each O for parallel transcoding of all segments?

**Comment by j0sh** [comment]
> Are we looking to eliminate the loss of 1 or at most 2 segments, as a requirement to this work?

Yes.

> To confirm - this is not referring to the list stored in the DB, but to the list stored in OrchestratorInfo on the BroadcastSession? 

Correct. 

> Every time a certain percentage of O's from a list have been used. This could be an arbitrary number of say 25% or 50%.

We can refresh when a certain percentage of Os in the list have *failed*. Note that with an "M-of-N" list, we need to be careful about whether to apply that percentage to M or N and the relative scales of each other.

A simple scheme could be:
1. Start with a list of length N
2. Require a minimum length of M (this could also be the redundancy factor)
3. For each orchestrator that fails, remove it from the list, thus decrementing N
3. If N <= M, refresh the list.

>> Split the transcoding work among several orchestrators.
> Is this different than the "round robin" approach outlined above?

It's different. "Splitting work" here means giving each orchestrator a subset of the renditions; eg if you wanted to transcode 720p, 480, and 360p, then you could send each rendition to a different orchestrator (3 Os total, 1 rendition each). Which orchestrator(s) to allocate to that transcoding can be done however. So rather than failing to transcode *all* the renditions, only one might fail.

Splitting the work may make alternate failover strategies more reasonable, such as retrying the submission, since less work needs to be done for each O (although whether this makes a difference in practice might depend on O's own work-allocation strategy).

Note that round-robin alone doesn't prevent loss of a segment if an O fails mid-stream; under most cases, you would be submitting a segment in order to discover the failure. Then that failure needs to be accommodated somehow.

One benefit of round-robin which hasn't been mentioned is that it gives Os some additional time in between segments. This could decrease the prevalence of `OrchestratorBusy` errors, which is the predominant error we've been seeing during testing. This may allow us to have more segments "in flight". Normally this would not be good news for latency, but as long as the variance is low, we can view the additional latency as a constant "offset" as long as it's less than the size of the playlist window.

> To confirm, thought we've been talking about redundancy, we will NOT be allowing user to select two or more O's to simultaneously send segments to? If we do, wouldn't we still have the question of whether to employ round-robin redundancy, or, simply sending all segments to each O for parallel transcoding of all segments?

If we do implement resiliency via redundant encodes, then segments would be simultaneously sent to a set of Os. The allocation method is what determines that set of Os, but as mentioned, which method to use is less critical at this point; we can just assume we stickily use the first few Os in the list.

**Comment by angyangie** [comment]
This is very helpful, thank you @j0sh!

> A simple scheme could be: .... 

For # 4 on that list, `If N <= M, refresh the list`, I assume that means we'd populate the whole list length M again. Seems like we'd have to make sure not to include O's that we've "gray listed", as well as O's that are currently in use (mental note for myself).

> "Splitting work" here means giving each orchestrator a subset of the renditions.... Splitting the work may make alternate failover strategies more reasonable, such as retrying the submission, since less work needs to be done for each O.

I hadn't thought of this one - that makes a lot of sense! If one rendition fails, we wait for that rendition to be retried and transcoded before sending all renditions for that segment back to B (which can be done with a blocking function within a loop, or something of the like)

> If we do implement resiliency via redundant encodes, then segments would be simultaneously sent to a set of Os.

Makes sense. So I guess the question is - send job for different renditions of each stream to different transcoders, or, send all to one, or send all to several.

**Comment by angyangie** [comment]
After chatting with @j0sh, here's a summary of strategies being considered, as well as concerns/benefits of each. Feedback is encouraged, before we move forward with any of these (cc: @darkdarkdragon @ericxtang). From my vantage point, seems like Round-Robin makes the most sense, but would love to hear other opinions.

## Goal: Resiliency in the face of errors or failures

Concerns about strategies below were evaluated with all phases of the transcoding process in mind:
- Generate list of Orchestrators
- Emit segment
- Upload segment
- Transcode segment
- Download segment
- Verify segment

### Strategy 1: Retries

This strategy retries a segment without dropping it. This is similar to what currently exists.

```
func remove_orchestrator(o, orch_list) {
  remove(orch_list, o)
  if len(orch_list) <= minimum {
     go refresh_list(orch_list) //  calls existing getOrchestratorInfo, can optimize later
  }
}

while s = get_segment() {
   o = get_orchestrator(orch_list)
   res, err = transcode(o, s)
   while err != nil {
       remove_from_list(orch_list, o)
        o = get_orchestrator(orch_list)
        res, err = transcode(o, s)
   }
}

```
#### Concerns: 
* Out of order segments, if we fail right at the boundary of segments. 
* Direct uploads have to be done again for each retry.
* Object storage: only need to upload once. But not guaranteed to have OS. (Are we even using it for the test network?)
* Downloads may fail. Do we handle this now? No. Can re-evaluate "hard fail" criteria separately.

### Strategy 2: Round-Robin

In this strategy, a Broadcaster would “take turns” assigning segments to be transcoded to different Orchestators. eg. send seg1 to O1, seg2 to O2, seg3 to O3, seg4 to O1, seg5 to O2, etc. (in the case of three O's selected by the Broadcaster).

Most of the fails currently are because orchestrator is busy. With Round-robin, we can alternate and give O time to process individual segments. Here, we don't allow Os to have more than one segment in flight, which mitigates back logging.

This is optimizing for our benchmark of getting to 99% reliability. With this strategy, we'd be drastically reducing or completely eliminating "ErrOrchBusy", which is estimated to be more than 80% of errors seen. Though other errors wouldn't be covered, and we'd still lose a segment, if our metric is 99% reliability, this could be a feasible strategy (at the moment we're at 94% or 95%).

```

func process_segment(s, orch_list) {
  o = pop_orch_from_list(orch_list)
  res, err = transcode(o, s)
  if err == nil {
      push_orch_to_list(o, orch_list)
  }
}

while s = get_segment() {
    go process_segment(s, orch_list)
}

```

This strategy maintains the behavior profile we have now of a single upload, single download.

#### Concerns:
* Not retrying, so no additional uploads or downloads. Errors other than `ErrOrchBusy` wouldn't be covered, and we'd still lose a segment (though we think this would happen to less than 1% of segments).

### Strategy 3: Races

We submit a segment to several O's simultaneously. This strategy is fully redundant.

```
func process_segment(s, o) {
     res, err = transcode(o, s)
     if err != nil {
         remove_from_list(o, orch_list)
     }
     running = false
     signal(cv)
}

while s = get_segment() {
  running = true
  var cv  // condition variable / semaphore
  for each o in orch_list {
      go process_segment(s, o)
  }
  while running {
      wait(cv)
  }
}
```

#### Concerns:
* Multiple uploads, which is computationally and financially more expensive.
* Since we exit after sig checking, there is a possibility that we are mid-download for several other O, increasing the times we download the same segment from different Os.

#### Concerns, when adding object storage to the equation:
* On a good note, we skip sig checking if results are put into a B-owned OS, which means we can skip the download.
* However, we would need to give a separate manifestID / prefix to each O, since we don't want them to write over one another. This is more effort from an implementation perspective.
* Orchestrators will know the URL structure and can preemptively "send" the resulting URL back before the work is actually done, making it more difficult to accurately evaluate whether they actually did do the work. Plus the "read after write" consistency model for most OS could really inconvenience us if we try to fetch a URL that doesn't exist yet.

### Strategy 4: Round-Robin + Retries

This strategy is round-robin allocation, with retries if an error comes up.

```
func process_segment(s, orch_list) {
  o = pop_orch_from_list(orch_list)
  res, err = transcode(o, s)
  while err != nil {
    o = pop_orch_from_list(orch_list)
    res, err = transcode(o, s)
  }
  push_orch_to_list(o, orch_list)
}

while s = get_segment() {
    go process_segment(s, orch_list)
}

```

#### Concerns (same to strategy 1, retries):
* Out of order segments, if we fail right at the boundary of segments. 
* Direct uploads have to be done again for each retry.
* With object storage, need to upload once. But not guaranteed to have OS (not sure if we're even using OS for the test network)
* Though downloads may fail, we won't handle this now (it's not included in pseudo code above). We can re-evaluate "hard fail" criteria separately.

**Comment by yondonfu** [comment]
Round robin seems like a reasonable initial strategy for O allocation with round robin + splitting renditions across Os as a next step afterwords. When using the round robin strategy, B should also refresh its O list when a certain percentage of Os in that list have failed right?

**Comment by angyangie** [comment]
That's right @yondonfu. We'd want a list length N, with a min length of M (number TBD, will be based on desired redundancy, or # streams being handled). For each O that fails, we remove from the list and decrement N. Once N <= M, refresh the list.

**Comment by iameli** [comment]
On number 2:

> Errors other than ErrOrchBusy wouldn't be covered, and we'd still lose a segment (though we think this would happen to less than 1% of segments).

I get that round-robin will reduce the probability that we'll encounter ErrOrchBusy errors because we'll be more evenly distributing the load. But if we do happen to round-robin hit a busy orchestrator, we'll still get that same error, yeah?

I like the idea of #2, #3, and #4 all of these eventually being implemented and configurable — I can imagine use cases for a broadcaster not caring if the occasional segment gets dropped (#2), wanting a contiguous stream even if it arrives out of order (#4), and wanting everything transcoded in real time, costs be damned (#3). But #2 and #4 both seem like good places to start.

**Comment by angyangie** [comment]
> I get that round-robin will reduce the probability that we'll encounter ErrOrchBusy errors because we'll be more evenly distributing the load. But if we do happen to round-robin hit a busy orchestrator, we'll still get that same error, yeah?

Yes, we will. Along with the work you and @j0sh are doing, our hypothesis is that the error just won't happen enough for us to need to address it every time (we'll still hit the 99% benchmark). Bs will be able to select how many O's to work with (through a new flag on startup). Perhaps initially they could choose to work with a large number of O's (which would allow for more segment processing time per segment), until they've gauged the reliability of those Os, and then switch to working with less. 

However, this is just the MVP version. In the future, it could make sense to allow a B to select which strategy to use. A less price-sensitive B could very well choose #3 for higher reliability. For now, # 2 and # 4 I agree make the most sense.

**Comment by ericxtang** [comment]
Can we close this issue?

**Comment by angyangie** [comment]
We can!
