### ISSUE TITLE
Determine optimal mullti-T allocation/scalability strategy

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#771]

**Comment by angyangie** [comment]
**Multi-T** is about scalability: orchestrators must be able to handle 100 concurrent streams. It is important for us to define how an O will determine how many T's it needs to work with given its current workload. Some initial questions and thinking:

- Is it fair to assume that Orchestrators will send particular segments from a specific Broadcaster to ONE transcoder in their network (they will not yet have the ability to send that same Broadcaster's stream to multiple Transcoders)? e.g. seg1 from B1 will only be sent to T1, etc. 

- Seems like an O should be able to, from startup, to specify transcoders it prefers to work with. B nodes can add `-orchAddr` to select specific orchs to work with. Perhaps a similar approach can be taken here with a `-transAddr` flag.

- Is it important to build the ability for O to have a "trusted" list of T's? This is different than the question above, in that a "trusted list" can have any number of T's on it, not necessarily just T's that O is choosing to work with on node startup. If such list is in scope here, questions then remain: if O is at one point working with 10 T's, but given a reduced workload must reduce the # of T's its working with to 2, but would like to continue working with the same 10 T's if workload rises to previous levels, should it be able to add trusted T's to this list, and continue working with said T's in the future?

- Scenario: O is working with 5 Bs. Each is sending it 3 streams. O is working with only one T for all. When should O decide to start working with another T, when a new stream comes in? Will this happen when T's capacity for transcoding has reached a limit? Or, will O's choose to send different streams to different T's every time? Seems like we should build a way to ping T to ask for its current capacity to take on new streams (not sure if this is in scope here ... thoughts welcome).

The simplest approach here, without the need to ping a T for its current capacity, could be for each O to send to the same transcoder, until a segment fails. Switch that particular stream to another transcoder once that happens. The question, then, is: should T capacity be determined prior to sending a segment to specific T? Or, will we allow natural failover to be our mechanism for choosing another T to send additional streams to?

**Comment by angyangie** [comment]
After discussion on multi-O with @j0sh (https://github.com/livepeer/go-livepeer/issues/770), seems like I can answer some of my own questions here 😆.

> Is it fair to assume that Orchestrators will send particular segments from a specific Broadcaster to ONE transcoder in their network (they will not yet have the ability to send that same Broadcaster's stream to multiple Transcoders)? e.g. seg1 from B1 will only be sent to T1, etc.

Nope, this will depend on which selection strategy we employ. Which B the stream is coming from doesn't matter - what matters is T transcoding capacity and whether that T can handle more segments.

> Seems like an O should be able to, from startup, to specify transcoders it prefers to work with. B nodes can add -orchAddr to select specific orchs to work with. Perhaps a similar approach can be taken here with a -transAddr flag.

Still seems like a reasonable approach.

> Is it important to build the ability for O to have a "trusted" list of T's? This is different than the question above, in that a "trusted list" can have any number of T's on it, not necessarily just T's that O is choosing to work with on node startup. If such list is in scope here, questions then remain: if O is at one point working with 10 T's, but given a reduced workload must reduce the # of T's its working with to 2, but would like to continue working with the same 10 T's if workload rises to previous levels, should it be able to add trusted T's to this list, and continue working with said T's in the future?

If we're going to refresh our `transcoder_list` when transcoders fail, like we do with our `orch_list`, then, it seems like this can be a feature we consider in the future.

We can think about refreshing our transcoder list in the following way (same as multi-O). N will fluctuate based on how many Ts might be necessary at any given time:

1. Start with a list of length N
2. Require a minimum length of M (this could also be the redundancy factor)
3. For each transcoder that fails, remove it from the list, thus decrementing N
4. If N <= M, refresh the list

> Scenario: O is working with 5 Bs. Each is sending it 3 streams. O is working with only one T for all. When should O decide to start working with another T, when a new stream comes in? Will this happen when T's capacity for transcoding has reached a limit? Or, will O's choose to send different streams to different T's every time? Seems like we should build a way to ping T to ask for its current capacity to take on new streams (not sure if this is in scope here ... thoughts welcome).

This is where multi-T differs from multi-O. In multi-T, the number of transcoders an O is working with will depend on how much work it is handling (we're focusing on scalability). The more important question seems to be: how will we determine when more T's are necessary? How can we inform individual O's of T capacity? So, again, the answer here doesn't depend on which B a stream is coming from, but it entirely depends on T capacity. Strategies used for multi-B still apply, once the # of Ts necessary at any given time is determined (how can we calculate this?)

**Comment by j0sh** [comment]
> Seems like an O should be able to, from startup, to specify transcoders it prefers to work with. B nodes can add -orchAddr to select specific orchs to work with. Perhaps a similar approach can be taken here with a -transAddr flag.

Transcoders connect to orchestrators, rather than the other way around. This keeps provisioning and management simpler, since O doesn't need to be informed of new Ts; it only needs to accept new (authenticated) connections.

> Is it important to build the ability for O to have a "trusted" list of T's? 

Currently, all Ts are trusted. Having trustless O/T interaction is a deep rabbit hole that may not even be economical, so for now we can count on Ts being trusted.

> Scenario: O is working with 5 Bs. Each is sending it 3 streams. O is working with only one T for all. 

This should only happen if O knows that T has sufficient capacity to handle transcoding 15 streams. In any case, the question of how to allocate work among Ts for transcoding is the crux of the matter here.

> The more important question seems to be: how will we determine when more T's are necessary?

Since Os won't really have an elastic source of Ts, they would probably have to capacity-plan the old fashioned way.

>  How can we inform individual O's of T capacity? 

One way would be for T to transmit its capacity to O upon connecting. This capacity can be configured at startup, similar to how B and O have a `-maxSessions` flag. Then O tracks utilization among connected Ts when allocating work (we can assume that T only connects to one O).

**Comment by angyangie** [comment]
Summary from our Discord conversations, to keep an online papertrail here ... 

> **Angie**:

>I've been looking through some code, looking at similarities and differences between multi-T and multi-O. I'm seeing there are more similarities than anything. "ErrOrchBusy" error is coming from T, so that error is still applicable. Knowing that all T's are trusted,  that capacity can be calculated based on how many streams/processes a T can handle at a time (and that this is a known number, since the number doesn't really depend on which renditions are being processed for a stream, or how computationally intensive they may be, for now), and that T's can let Os know capacity on startup/connecting to O, is very helpful in narrowing down the scope of scenarios I was thinking we'd have to account for. 

> Do we need to think about a gray list here? I'm thinking that might also be a feature that we leave until next time. 

> Since there is a limited number of T's an O works with at a time, the list part of the algorithm might just be placing any non-responding T at the end of the list, and cycling through.

> **Josh**: 

>> and that this is a known number, since the number doesn't really depend on which renditions are being processed for a stream, or how computationally intensive they may be, for now

> The actual capacity in terms of throughput may indeed be affected by the number of renditions and the resolution, but for now we can assume that the capacity cap coarsely indicates how many concurrent "rendition groups" can be processed. Transcoding being single-threaded for now makes concurrency easier to reason about; a rule of thumb would be one core per segment.

>> Do we need to think about a gray list here? I'm thinking that might also be a feature that we leave until next time. 

>We should only think about gray lists if we're facing an issue that would be solved by gray lists. If not, then we don't need to worry about them. FWIW, I haven't seen anything that would call for gray lists yet.

>> the list part of the algorithm might just be placing any non-responding T at the end of the list, and cycling through

> We probably should disconnect non-responding Ts, although I suspect that it's a rather uncommon case where T is unresponsive but the connection stays alive; usually, the connection would eventually time out and get cleaned up.

> **Angie:**
 
>> The actual capacity in terms of throughput may indeed be affected by the number of renditions and the resolution, but for now we can assume that the capacity cap coarsely indicates how many concurrent "rendition groups" can be processed.

>Ah okay, that makes a lot of sense. I figured that we'd keep this simple for now. Once core per segment it is!

>> ...haven't seen anything that would call for gray lists yet.

>Since we're considering all of our T's "trusted", then we can as assume that the only reason they'd go offline is because of a hardware/capacity/connectivity issue, so this seems fine to me. In which case, we'd be okay reconnecting with at a later time. 

>> We probably should disconnect non-responding Ts

>Sounds good on that. Now, say one O is connected to 4 Ts and sending them all segments in a round-robin strategy. Say one of those Ts is unresponsive. We disconnect from that T. I assume, once it's back online, we'd just continue working with that T?

**Josh:**

>>  I assume, once it's back online, we'd just continue working with that T?

> Yep! The O can just use whatever it has available. We can certainly try and build more sophisticated strategies later, but starting simple for now is OK.

**Comment by angyangie** [comment]
## Goal: Scalability in the face of errors or failures

Concerns about strategies below were evaluated with all phases of the transcoding process in mind:
- Emit segment
- Upload segment
- Transcode segment
- Download segment
- Verify segment

Since each orchestrator has a limited number of T's it works with, we don't need to "refresh" a list as we do with O lists in multi-O. The list of transcoders will be stored in LivepeerNode.Transcoders (that field currently exists as a single transcoder, but can be change to be a list). When each Transcoder registers itself with an O, it is added to the list. 

We could keep in mind self-reported transcoder limits, and include an error when we know a T is at its limit, then select the next transcoder on the list instead. That we can flesh out in the code itself.

### Strategy 1: Retries

This strategy retries a segment without dropping it. This is similar to what currently exists.

```
func (n *LivepeerNode) transcodeSeg(t, s) (tData, error) {
	transcoder = t
    tData, err := transcoder.Transcode(url, md.Profiles)
    if err != nil {
		glog.Errorf("Error transcoding seg...")
        n.remove_from_list(transcoder)
		return nil, err
	}
    return tData, nil
}

n = NewLivepeerNode()

while s = get_segment() {
   t = n.transcoders[0]
   res, err = n.transcodeSeg(t, s)
   while err != nil {
        t = n.transcoders[0]
        res, err = transcodeSeg(t, s)
   }
}

```
#### Concerns: 
* Out of order segments, if we fail right at the boundary of segments. 
* Direct uploads have to be done again for each retry.
* Object storage: only need to upload once. But not guaranteed to have OS. (Are we even using it for the test network?)
* Downloads may fail. Do we handle this now? No. Can re-evaluate "hard fail" criteria separately.

### Strategy 2: Round-Robin

In this strategy, an orchestrator would “take turns” assigning segments to be transcoded to different Transcoders. eg. send seg1 to T1, seg2 to T2, seg3 to T3, seg4 to T1, seg5 to T2, etc. (in the case of three T's selected by the Broadcaster).

Most of the fails currently are because transcoders are busy. With Round-robin, we can alternate and give T time to process individual segments. Here, we don't allow Ts to have more than one segment in flight, which mitigates back logging.

This is optimizing for our benchmark of getting to 99% reliability. With this strategy, we'd be drastically reducing or completely eliminating "ErrOrchBusy", which is estimated to be more than 80% of errors seen. Though other errors wouldn't be covered, and we'd still lose a segment, if our metric is 99% reliability, this could be a feasible strategy (at the moment we're at 94% or 95%).

```
func (n *LivepeerNode) transcodeSeg(s) {
  t = n.pop_trans_from_list()
  res, err = transcode(t, s)
  if err == nil {
      n.push_trans_to_list(t)
  }
}

n = NewLivepeerNode()
while s = get_segment() {
    go n.transcodeSeg(s)
}
```

This strategy maintains the behavior profile we have now of a single upload, single download.

#### Concerns:
* Not retrying, so no additional uploads or downloads. Errors other than `ErrOrchBusy` wouldn't be covered, and we'd still lose a segment (though we think this would happen to less than 1% of segments).

### Strategy 3: Races

We submit a segment to several T's simultaneously. This strategy is fully redundant.

```
func (n *LivepeerNode) transcodeSeg(s, t) {
     res, err = transcode(t, s)
     if err != nil {
         n.remove_from_list(t)
     }
     running = false
     signal(cv)
}

while s = get_segment() {
  running = true
  var cv  // condition variable / semaphore
  for each t in n.Transcoders {
      go transcodeSeg(s, t)
  }
  while running {
      wait(cv)
  }
}
```

#### Concerns:
* Multiple uploads, which is computationally and financially more expensive.
* Since we exit after sig checking, there is a possibility that we are mid-download for several other Ts, increasing the times we download the same segment from different Ts.

#### Concerns, when adding object storage to the equation:
* However, we would need to give a separate manifestID / prefix to each T, since we don't want them to write over one another. This is more effort from an implementation perspective.
* Transcoders will know the URL structure and can preemptively "send" the resulting URL back before the work is actually done, making it more difficult to accurately evaluate whether they actually did do the work. Plus the "read after write" consistency model for most OS could really inconvenience us if we try to fetch a URL that doesn't exist yet.

### Strategy 4: Round-Robin + Retries

This strategy is round-robin allocation, with retries if an error comes up.

```
func (n *LivepeerNode) transcodeSeg(s) {
  t = n.pop_trans_from_list()
  res, err = transcode(t, s)
  
  while err != nil {
    t = n.pop_trans_from_list()
    res, err = transcode(t, s)
  }
  
  n.push_trans_to_list(t)
  }
}

n = NewLivepeerNode()
while s = get_segment() {
    go n.transcodeSeg(s)
}
```

#### Concerns (same to strategy 1, retries):
* Out of order segments, if we fail right at the boundary of segments. 
* Direct uploads have to be done again for each retry.
* With object storage, need to upload once. But not guaranteed to have OS (not sure if we're even using OS for the test network)
* Though downloads may fail, we won't handle this now (it's not included in pseudo code above). We can re-evaluate "hard fail" criteria separately.

**Comment by yondonfu** [comment]
Round robin seems like a reasonable initial strategy for T allocation with round robin + splitting renditions across Ts as a next step afterwords.

> We could keep in mind self-reported transcoder limits, and include an error when we know a T is at its limit, then select the next transcoder on the list instead.

After a T self-reports its transcoding capacity to O, does O keep track of T's transcoding capacity with each segment that O sends to that T? Or does O poll/subscribe to T for its transcoding capacity in order to receive updates? The former seems reasonable as an initial solution. I think the latter would only be necessary if Ts were working for multiple Os, but I believe our initial assumption is that the same operator owns O and T so this wouldn't be a concern in the short term.

**Comment by angyangie** [comment]
Good question. Yes! Since O has the capacity to transcode many numbers of streams at a time, and since a T can only work with one O at a time, we can track total # of segments/streams T is working with at any given time. That'll be an implementation detail to sketch out.

**Comment by angyangie** [comment]
This is done. Closing
