### ISSUE TITLE
Determine any commonalities between multi-T/multi-O

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#772]

**Comment by angyangie** [comment]
Preliminary list of Commonalities and differences, based on: https://github.com/livepeer/go-livepeer/issues/770 and https://github.com/livepeer/go-livepeer/issues/771. More specifics will be added on a later comment.

****Commonalities between multi-O and multi-T:**
- Reducing the number of "ErrOrchBusy", could get us to our benchmark of 99% reliability.
- Out of order segments a concern for Round-robin and race strategies.
- When Object storage is introduced, it adds a level of complexity to both - for a race strategy, a separate manifestID / prefix would have to be given to each O/T. If URL structure is known, O/T could send empty segments and remain undetected until error is noticed in the livestream. 
- It is still an open question how retries might affect latency, in both sticky and round-robin strategies, and how prevalent this latency might be. 

****Differences:**

**Multi-O:**
- List is refreshed when below a certain numerical threshold.
- Since we can't assume O's are necessarily trusted, a gray list might be more urgent here

**Multi-T:**
- Ts are trusted
- No need to refresh the list of Ts - Ts will connect and disconnect at will. They'll be included in LivepeerNode.Transcoders list as they register. We'll need to revamp this mechanism to keep track of all T's being added/removed at any given time.
- Need to keep T capacity in mind - Ts can advertise their capacity through a flag (mental note: must add note somewhere on how T's can calculate such capacity, which for now, we'll keep at "one segment per core"). We'll have to incorporate that into whatever allocation strategy we end up going with.

**Comment by yondonfu** [comment]
The gray list feature seems like it will be helpful for multi-O, but it could also be added on its own after the initial O allocation strategy is implemented since there are other uses for the gray list as well i.e. later on when Bs passively fetch pricing info from Os the gray list could also be used to keep track of Os that previously responded to price requests, but then subsequently stop responding.

**Comment by angyangie** [comment]
Good to think about other uses of the gray list. We can leave it off of this initial MVP, and use later with non-responding O's re: pricing (and any other use case). For now, we can randomize and refresh registered list of O's, without a gray list.

**Comment by j0sh** [comment]
> Reducing the number of "ErrOrchBusy", could get us to our benchmark of 99% reliability.

Note that this is mostly a concern with B->O, but not necessarily O->T.

> Out of order segments a concern for Round-robin and race strategies.

Ditto, out-of-order segments are a concern for playlist insertion, but O->T don't handle playlists, so it's not an issue for O->T.

> When Object storage is introduced, it adds a level of complexity to both - for a race strategy, a separate manifestID / prefix would have to be given to each O/T.

At a first glance, B-provided OS for B->O races or retries is nice because it means uploads only have to be done once. However, there are a few other concerns with B-supplied races if O-T is racing. If each T pulls from B's OS separately, this would incur redundant charges for B (which exposes an 'implementation detail' of O). A well-behaved orchestrator should choose to serve source segments on its own for races. Likewise, multiple Ts cannot store into B's OS directly; O needs to upload once from whoever wins.

> O/T could send empty segments and remain undetected until error is noticed in the livestream

O could send the URL itself without actually uploading anything (T is less of a concern since it's trusted). A somewhat innocent-sounding example would be if O preemptively sends a response with the URL before the upload to OS is complete. This would be disastrous with read-after-write consistency if the object is read before the upload is complete, as an updated object may not be reflected in the bucket for some time (hours) after the first access to the object.

> It is still an open question how retries might affect latency

Latency is one part of the concern; we can technically live with latency as long as it doesn't out-run the playlist. Let's see if we can model this part a little: https://docs.google.com/spreadsheets/d/1teKzXPdAdZlp8K2RhoxPJAfdAJG2NafKT-H8T-IYLyc/edit#gid=0

Of course, the lower we can get the e2e latency, the better.

> must add note somewhere on how T's can calculate such capacity

They could self-declare their own capacity, much as the B and O both self-declare `-maxSessions`.

**Comment by angyangie** [comment]
Thanks for the feedback @j0sh! Based on your comments, I've revised my initial post below:

Preliminary list of Commonalities and differences, based on: https://github.com/livepeer/go-livepeer/issues/770 and https://github.com/livepeer/go-livepeer/issues/771.

****Commonalities between multi-O and multi-T:**
- We technically can live with latency as long as it doesn't out-run the playlist, but, the lower we can get, the better. We could model this: https://docs.google.com/spreadsheets/d/1teKzXPdAdZlp8K2RhoxPJAfdAJG2NafKT-H8T-IYLyc/edit#gid=0

****Differences:**

**Multi-O:**
- Reducing the number of "ErrOrchBusy", could get us to our benchmark of 99% reliability.
- Out of order segments a concern for Round-robin and race strategies.
- List is refreshed when below a certain numerical threshold.
- Since we can't assume O's are necessarily trusted, a gray list might be more urgent here
- For O uploads to B, if URL structure is known, O could send URL itself without actually uploading anything, or, while in the middle of an upload before it's complete. This would be disastrous with read-after-write consistency if the object is read before the upload is complete, as an updated object may not be reflected in the bucket for some time (hours) after the first access to the object.

**Multi-T:**
- When Object storage is introduced, it adds a level of complexity to the race strategy. A separate manifestID / prefix would have to be given to each T, to prevent overwrites on the OS side.
- Ts are trusted
- No need to refresh the list of Ts - Ts will connect and disconnect at will. They'll be included in LivepeerNode.Transcoders list as they register. We'll need to revamp this mechanism to keep track of all T's being added/removed at any given time.
- Need to keep T capacity in mind - Ts can advertise their capacity through a flag. We'll have to incorporate that into whatever allocation strategy we end up going with.

**Comment by angyangie** [comment]
This is done. Closing
