### ISSUE TITLE
Endpoint to List All Streams

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#781]
@f1l1b0x had suggested to create an endpoint to list all active streams.  This is something offered by most transcoding products out there, and we expect customers to demand this feature.  It gives users the ability to manage on-going streams.  

Would love to get feedback from @j0sh and @darkdarkdragon

**Comment by j0sh** [comment]
We already have this in the CLI `/status` endpoint. We really need to document these endpoints because there is a lot of useful information hidden in there. See https://github.com/livepeer/go-livepeer/issues/553

**Comment by darkdarkdragon** [comment]
Yes, I use it all the time. But maybe @f1l1b0x was taking about exposing endpoint to users of our Transcoding API?

**Comment by j0sh** [comment]
Yeah, why not. Although perhaps we should reverse proxy this specifically for the demo network instead of exposing the entirety of the CLI directly or re-implementing this on a separate port.

There is probably a useful conversation to be had on the "surface area" of the node and how much should be exposed. Also related is my earlier comments on exposing the metrics endpoint, https://github.com/livepeer/go-livepeer/issues/760#issuecomment-468833079

**Comment by ericxtang** [comment]
In general, I feel like the "CLI-specific" endpoints should be grouped differently from "user-facing" endpoints.  What do you guys think about having "API grouping", and being able to assign different groups to different ports?  So far we'd have `rtmp`, `stream`(hls, and maybe later dash), `crud`, and `cli`.  The command line would look something like `-rtmpPort`, `-streamPort`, `-crudPort`, `-cliPort`.

Metrics is a little different, in that the data is not logged on the `go-livepeer` node.

**Comment by darkdarkdragon** [comment]
Sounds like a good idea. Probably we should call it something more than `crud`, because we're essentially implementing our transcoding API into node, and probably it will be something more than just `crud`. Maybe just call it `api`?

**Comment by j0sh** [comment]
> I feel like the "CLI-specific" endpoints should be grouped differently from "user-facing" endpoints

It really depends on what what we consider "CLI specific" and what's "user facing". The CLI exposes useful diagnostic and administrative features; surely that can be considered part of the API? Even if not, there are various degrees of being "user facing" ; public or administrative/internal? There are infinite variations to this and we're already starting to see splintering (eg, metrics).

We're now talking about opening five ports, four of which are HTTP-based:

* CLI
* Stream / gRPC
* Metrics
* "CRUD"
* RTMP

In terms of devops and opsec, more ports are more annoying. And I maintain that having "too many choices" is not necessarily a good thing from a developer perspective; it's going to invite bikeshedding and paralysis over what belongs where. I'd like to minimize the variation in "surface area" of the node.

Can we formalize the distinction we've been making informally: if it's public, it goes on 8935. If it's internal, it goes on 7935.

Different users will inevitably need different subsets of the internal functionality available on 7935 (or other ports). Competent operators will implement access protection mechanisms to best suit their own needs, so it seems laborious to anticipate that and (somewhat arbitrarily) split things up.

> Metrics is a little different, in that the data is not logged on the go-livepeer node

Isn't part of the appeal of Prometheus that it allows for local dashboards to see the status of the node? And the pull based model implies local logging.

**Comment by darkdarkdragon** [comment]
I think this question arose because we're creating Transcoding API for ourselves (called "CRUD" here), and for us it would be convenient to have it separated in broadcaster node. So main question is - do we want to have "Transcoding API" as separate entity in broadcaster node, or it will part of general API ("CLI"), and we will be surfacing Transcoding API for our customers by tools external to broadcaster node (proxying only some endpoints by nginx, for example)?

**Comment by j0sh** [comment]
> we're creating Transcoding API for ourselves 

This is the root of the concern -- we're narrowly tailoring this for our own use case.  On mainnet, users would legitimately want the CLI knobs exposed to manage their own node. There doesn't seem to be a strong distinction between "what belongs in the CLI" and "what belongs in the CRUD API" .

> we will be surfacing Transcoding API for our customers by tools external to broadcaster node (proxying only some endpoints by nginx, for example)?

This is what we should do, IMO.

**Comment by darkdarkdragon** [comment]
> There doesn't seem to be a strong distinction between "what belongs in the CLI" and "what belongs in the CRUD API" .

I agree with you, but we will be adding new endpoints needed for us anyway, and we need a way to group/track them. So what do you think about running everything on CLI port by default, but allowing to run subset of endpoints on different one if needed? This shouldn't add too much complexity to the code, but will make our life easier.

**Comment by j0sh** [comment]
> So what do you think about running everything on CLI port by default, but allowing to run subset of endpoints on different one if needed? This shouldn't add too much complexity to the code,

We should be vigilant about feature creep on the node. Non-trivial deployments are going to incorporate additional layers in front of the node (proxying, authentication, API gateways, etc). I think it's safe to classify our test harness as a "non-trivial deployment."

Rather than trying to build support for every possible configuration on the node, let's outsource the work to best-in-class tools where possible. We can offer the community best practices, guidance and examples of using Livepeer in a real-world, non-trivial environment. The node doesn't need to be one-size-fits-all, but folks need to understand how to slot in Livepeer using the tools and infrastructure they might already have. Using the test harness to expose a subset of the API via nginx would be a good example of this.

**Comment by darkdarkdragon** [comment]
OK, sounds reasonable.

**Comment by iameli** [comment]
With the creation of the separate API project, I now think that `GET /status` is a perfectly acceptable way to implement this. Indeed, we already have with https://livepeer.live/api/broadcaster/status
