### ISSUE TITLE
Collect & Show Transcoder Stats

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#81]
We need to show transcoder stats so token holders can decide who to bond to.

**Comment by yondonfu** [comment]
Some changes needed to be made to the contract code to make this easier. Since the active transcoder array is an array of structs and Solidity does not support contracts externally returning structs yet, we need a custom getter function to grab the active transcoder addresses. Then, the active transcoder addresses can be used to retrieve the associated stats.

**Comment by dob** [comment]
If we're iterating towards a solution here, I think here's what would be
helpful to see at the minimum about a transcoder:

Address (could be the name.transcoder.eth ens name when we add that)
Price/segment
Fee Share
Block Reward Cut
Number of passed verifications
Number of failed verifications
Total stake

**Comment by yondonfu** [comment]
We can now list stats of candidate and reserve transcoders. The stats that we are currently missing are number of passed verifications and number of failed verifications, but the protocol contracts currently are not tracking that information. Since we will initially be using the identity verifier for the test net soft launch and transcoders will not be failing verifications so this is ok for now. I'll open an issue to add this information in the protocol though.
