### ISSUE TITLE
Document requirements: Webhooks, Specify Bitrate Ladder

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#811]
Deliverable is final requirements

**Comment by iameli** [comment]
Sure!

Upon a stream starting, Livepeer broadcasts nodes currently perform an authentication webhook. Currently, all it receives back is a stream key. Per the work in https://github.com/livepeer/go-livepeer/issues/793, we'd like to return a variety of other structured data, including the desired bitrate ladder for the broadcast.

Per [discussion here](https://hackmd.io/Rb8Hk-sTThm2eR29DXIjzA), that ladder will look something like this.

```json
[
  {
    "width": 1920,
    "height": 1080,
    "bitrate": 6000000,
    "fps": 30
  },
  {
    "width": 1280,
    "height": 720,
    "bitrate": 6000000,
    "fps": 60
  },
  {
    "width": 853,
    "height": 480,
    "bitrate": 2000000,
    "fps": 30
  },
  {
    "width": 426,
    "height": 240,
    "bitrate": 700000,
    "fps": 30
  }
]
```

Or, expressed more formally as a (first draft) JSON-Schema:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "requiredProperties": ["width", "height", "bitrate", "fps"],
    "properties": {
      "width": {
        "type": "integer",
        "minimum": 128
      },
      "height": {
        "type": "integer",
        "minimum": 128
      },
      "bitrate": {
        "type": "integer",
        "minimum": 400000
      },
      "fps": {
        "type": "integer",
        "minimum": 1
      }
    }
  }
}
```

For now, these fields will be further locked down to just support [our hardcoded options](https://github.com/livepeer/lpms/blob/master/ffmpeg/videoprofile.go) to limit the surface area of the validation project, but this API will work for arbitrary settings when we get to that point.

The broadcaster must then use this data to interface with its orchestrators.

Open question for discussion: what happens if the API node returns illegal data? We can reduce the chances of this by shipping a cross-language JSON-Schema to ensure all the components are on the same page, but given the structure of a webhook there's not an obvious way for the broadcaster client to communicate an error state to the webhook server.

**Comment by j0sh** [comment]
Looks nice. Presumably this list is put into the webhook response, eg

```
{"manifestID": "abc", "transcodingOptions": <list>}
```

>  these fields will be further locked down to just support our hardcoded options

I wonder if having a list with a single field of `presets` would be nicer to think about for the developer. It seems a little strange UX-wise to only accept a very specific set of parameters. Presets are fairly common elsewhere.

Otherwise we have to think about defaults too, or make *all* fields required. For example, if a user passes in just `width` and `height` then what should the bitrate be? Or the fps?

> expressed more formally as a (first draft) JSON-Schema:

Other than possibly using a preset, these fields seem reasonable.

Bitrate: I'm OK with interpreting any number in kb/s. So, "10" would mean 10kb/s or 10,000 bits/sec. The minimum of 400 kb/s seems pretty high though.

FPS: This can actually be fractional. When the fps is a non-integer it's typically expressed in decimal form, eg 29.97 fps. Passing this in as a float is a bit awkward without parsing, as the internal representation of framerate is typically a rational pair of integers. Perhaps we could have an optional `fps_den` field that specifies the denominator. We *could* also allow the FPS to optionally be a rational, eg `fps: { num: <int>, den: <int> }` but not sure how that works with JSON schema.

> what happens if the API node returns illegal data?

I think the easiest thing we can do here is log the error then close the RTMP connection, same as we do if the webhook server is unavailable. Closing the connection gives the developer immediate feedback that something is wrong, and they can investigate the logs from there. The error could also be captured by something like Prometheus and exposed to hosted API users.

Also, this are all video specific options. Although we aren't planning to offer audio options right now, is this something we should take into consideration for the schema? Eg, `[ {video: { ... }, audio: { ... }}, ... ]`. Or we could flatten the audio options into the same structure as the video, but there might need to be some prefixing around areas of overlap (`audio_codec`, `audio_bitrate`, etc).

**Comment by iameli** [comment]
> Looks nice. Presumably this list is put into the webhook response, eg

Yep! I might prefer `outputs` to `transcodingOptions` but that's exactly what I was envisioning.

> I wonder if having a list with a single field of presets would be nicer to think about for the developer. It seems a little strange UX-wise to only accept a very specific set of parameters.

I definitely get the motivation for this, especially when we're going to be locked in to our hardcoded list for the immediate future, but there's tradeoffs — you're making it easier for video developers at the cost of making it harder for folks implementing API tools and front-ends that'll need to interface with this data.

I'm still definitely in favor of presets in general, I'm just not sure this low-level API protocol is the right place for them. A Livepeer SDK could easily translate from a preset to a full API representation on the client-side, for instance, allowing for the developer experience of simple presets without bloating the API definition itself. CLIs and graphical frontends can do the same.

> Presets are fairly common elsewhere.

If you know of other examples, would love to take a look and perhaps incorporate!

> Otherwise we have to think about defaults too, or make all fields required. For example, if a user passes in just width and height then what should the bitrate be? Or the fps?

I think all four fields being required is reasonable, with lots of good documentation/examples/SDK presets to make things as easy as possible for developers. Hopefully it'll just mean copy/pasting once to set up the preferred ladder.

> Bitrate: I'm OK with interpreting any number in kb/s. So, "10" would mean 10kb/s or 10,000 bits/sec. The minimum of 400 kb/s seems pretty high though.

Agreed on both counts, updated the example in my post.

> FPS: This can actually be fractional.

Ah, right! Crap.

> We could also allow the FPS to optionally be a rational, eg fps: { num: <int>, den: <int> } but not sure how that works with JSON schema.

Works fine, if it comes to that:

```json
"fps": {
  "type": "object",
  "requiredProperties": ["num", "den"],
  "properties": {
    "num": {
      "type": "integer",
      "minimum": 1
    },
    "den": {
      "type": "integer",
      "minimum": 1
    }
  }
}
```

Or a more terse way to handle the same thing could be `[2997, 1000]`, which is also possible to express as JSON-Schema... but dang, that does make things trickier. I'll take a look at how some other video APIs handle it but I kinda suspect I'll see a lot of floats, number handling be damned. (Perhaps worth noting that JSON-Schema does have a way to enforce "two decimal places" with `"multipleOf": 0.01`, so that's an option too.)

> I think the easiest thing we can do here is log the error then close the RTMP connection, same as we do if the webhook server is unavailable.

Agreed, that's probably all there is to do here.

> Although we aren't planning to offer audio options right now, is this something we should take into consideration for the schema?

Yeah... definitely should. Will ponder.

**Comment by j0sh** [comment]
> If you know of other examples, would love to take a look and perhaps incorporate!

The ones I've seen are from encoding.com and AWS.

Encoding.com has a number of [output formats](https://api.encoding.com/reference/output-formats) corresponding to certain devices/platforms, each with set of [defaults and acceptable variations](https://api.encoding.com/reference/output-videosettings). This ensures that if you're trying to encode for, say, an iPad, you won't accidentally specify a configuration that doesn't work for iPads.

AWS is a little more specific, both [Elastic Transcoder](https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/system-presets.html) and [Elemental MediaConvert](https://docs.aws.amazon.com/mediaconvert/latest/ug/working-with-presets.html) have a number of "system presets" that can be used.

Generally most SaaS services also allow you to specify custom presets and refer back to those, but that's probably out of scope here.

> Or a more terse way to handle the same thing could be [2997, 1000]

That looks good too. Does JSON schema also constrain the size of the array?

Generally, I do think the majority of users will only need a single integer value for fps, so if there's a way we can make the common case less cumbersome that might be nice, such as accepting multiple formats, eg `fps: 30` or `fps:[30000, 1001]` Although this is mostly a "machine to machine" API so I'm not really sure how much it matters once the code is written.

> I'll take a look at how some other video APIs handle it

For what it's worth, ffmpeg can parse a fps string in three ways: using a lookup table for [common rates](https://github.com/FFmpeg/FFmpeg/blob/0a347ff4222345c88b93d7962a696f0e9aae7ca2/libavutil/parseutils.c#L132-L141), as `num/den` or as a float.

```c
/**
 * Parse str and store the detected values in *rate.
 *
 * @param[in,out] rate pointer to the AVRational which will contain the detected
 * frame rate
 * @param[in] str the string to parse: it has to be a string in the format
 * rate_num / rate_den, a float number or a valid video rate abbreviation
 * @return >= 0 on success, a negative error code otherwise
 */
int av_parse_video_rate(AVRational *rate, const char *str);
```
https://github.com/FFmpeg/FFmpeg/blob/0a347ff4222345c88b93d7962a696f0e9aae7ca2/libavutil/parseutils.h#L68-L77

**Comment by iameli** [comment]
Looking in to those presets now.

> That looks good too. Does JSON schema also constrain the size of the array?

Yeah, JSON-Schema calls this "tuple validation" — it'll require exactly two elements matching the two subschema:

```json
"fps": {
  "type": "array",
  "items": [
    {
      "type": "integer",
      "minimum": 1
    },
    {
      "type": "integer",
      "minimum": 1
    }
  ]
}
```

Or, the version accepting two alternate formats:

```json
"fps": {
  "anyOf": [
    {
      "type": "integer",
      "minimum": 1
    },
    {
      "type": "array",
      "items": [
        {
          "type": "integer",
          "minimum": 1
        },
        {
          "type": "integer",
          "minimum": 1
        }
      ]
    }
  ]
}
```

**Comment by f1l1b0x** [comment]
about the encoding output options. please consider to give each a unique outout-id so that we can identify each individual output encoding and do something additoinal with it. example: you want to have one of your encodings also being sent to your backup storage. you would want to pick a single or all abr encodings then with their unique IDs and apply a setting to it

**Comment by iameli** [comment]
@f1l1b0x Yeh, good consideration... potentially in a full API we'll have things like "Output" and "Destination" as top-level constructs that can be shared across multiple ones too.

**Comment by j0sh** [comment]
If we keep the current notion of a preset, then the destination naming can remain the same, eg

```
<manifest ID>.m3u8
<manifest ID>/<preset name>.m3u8
<manifest ID>/<preset name>/<seqNo>.ts
```

Of course, if we don't support presets, or when we do arbitrary resolutions, we'll need some way to refer to each rendition.

**Comment by iameli** [comment]
Cross-referencing: since https://github.com/livepeer/go-livepeer/pull/879, the incoming webhook can specify a bitrate ladder. We're using this mechanism to pick the closest presets for the Wowza plugin; future development on a custom bitrate ladder can be informed by discovered user needs.

**Comment by iameli** [comment]
Assuming we all came to a consensus on the schema, would anyone object to moving forward with this? It'd be nice to have for the Wowza plugin sooner rather than later.

@yondonfu, any implications for the Streamflow protocol design if we support arbitrary resolution/bitrate/framerate? (I think perhaps that the protocol already does internally, and this is just a broadcaster restriction?)

**Comment by yondonfu** [comment]
@iameli Arbitrary resolution/bitrate/framerate should be ok. Even if we *only* supported presets, a verifier would likely extract the expected resolution/bitrate/framerate specified from the preset to use as input into the verification algorithm. I think the manner in which the verification algorithm uses the expected resolution/bitrate/framerate should be the same regardless of whether the values are included in a preset or whether arbitrary values are directly provided.

**Comment by angyangie** [comment]
Circling back to this after some time, so fully aware things might have shifted here. Want to make sure we have consensus on several points mentioned above. @j0sh @darkdarkdragon @iameli looking for your thoughts especially.

1. Does this work for JSON schema?
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Stream Information",
  "type": "object",
  "properties": {
    "manifestId": {
      "type": "string",
      "description": "the stream manifestId"
    },
   "presets": {},
    "profiles": {
      "type": "array",
      "description": "transcoding outputs list",
      "items": {
        "type": "object",
        "requiredProperties": ["width", "name", "height", "bitrate", "fps"],
        "properties": {
          "width": {
            "type": "integer",
            "minimum": 128
          },
          "name": {
            "type": "string",
            "minimum": 128
          },
          "height": {
            "type": "integer",
            "minimum": 128
          },
          "bitrate": {
            "type": "integer",
            "minimum": 400000
          },
          "fps": {
            "type": "integer",
            "minimum": 1
             }
          }
        }
      }
    }
  }
}
```
2. Where would this JSON schema go on the API side? Are we just returning the new `fullProfiles` in the `renditions` field of this? If renditions is populated, `go-livepeer` would know to use `fullProfiles` (not hardcoded presets) NOT `presets` (video_profiles, hardcoded)
```javascript
const doc = wowzaHydrate({
    ...req.body,
    kind: 'stream',
    userId: req.user.id,
    presets: req.body.presets || [],
    renditions: {FULLPROFILESHERE},
    id,
  })
```

3. To make this happen on the `go-livepeer` side of things, it is my understanding that we'll have to change the following - would love feedback here:

-  Define `net.TranscodingProfile` in `SegData` protobufs  `lp_rpc.proto`.
- Since it sounds like we want to support both standard hard-coded profiles as they work now, and a new field `FullProfiles` (if you have a better name for it, let me know!), `segData` would look like this:
```golang
segData := &net.SegData{
		ManifestId: []byte(md.ManifestID),
		Seq:        md.Seq,
		Hash:       hash,
		Profiles:   common.ProfilesToTranscodeOpts(sess.Profiles),
                 FullProfiles:  (sess.FullProfiles), // I assume they'd be coming in the correct format?
		Sig:        sig,
		Storage:    storage,
	}
```
- We'd also need to add a `fullProfiles` field to `&core.SegTranscodingMetadata{`
- Add `fullProfiles` to `streamParameters` in `createRTMPStreamIDHandler`
```golang
streamParameters{
			mid:      mid,
			rtmpKey:  key,
			profiles: presets,
                          fullProfiles: fullProfiles
		}
```
- Add `fullProfiles` to BroadcastSession:
``` golang
&BroadcastSession{
			Broadcaster:      rpcBcast,
			ManifestID:       params.mid,
			Profiles:         params.profiles,
			fullProfiles:         params.fullProfiles,
			OrchestratorInfo: tinfo,
			OrchestratorOS:   orchOS,
			BroadcasterOS:    bcastOS,
			Sender:           n.Sender,
			PMSessionID:      sessionID,
			Balance:          balance,
		}
```
- We already have a `transcodingOptions` flag ... don't think we need another. We do need to make it clear in documentation somewhere that that flag can take a list of preset objects, with `["width", "height", "bitrate", "fps"]` required. Think this is the right approach here ?
- `verifySegCreds` on the Orchestrator side would have to change, since we're using hardcoded profiles to verify if data coming back is correct. `&core.SegTranscodingMetadata{` would have to have a `fullProfiles` field as well. Perhaps we'd just be addins a similar line like this one, `profiles, err := common.BytesToVideoProfile(segData.Profiles)` in `segment_rpc.go` with a schema verifier for `fullProfiles`, like we talked about above, but on the orch/transcoder side?

**Comment by yondonfu** [comment]
> Since it sounds like we want to support both standard hard-coded profiles as they work now, and a new field FullProfiles (if you have a better name for it, let me know!),

The hard coded profiles are just hardcoded instantiations of a [VideoProfile](https://github.com/livepeer/lpms/blob/master/ffmpeg/videoprofile.go#L20) with a particular bitrate, framerate, resolution and aspect ratio. Based on the JSON schema provided, it seems that we could just reuse the existing `VideoProfile` type to express profiles with custom values.

> verifySegCreds on the Orchestrator side would have to change, since we're using hardcoded profiles to verify if data coming back is correct.

Right now there is a hardcoded 4 byte ID for each hardcoded profile. When we support profiles with arbitrary values, we should standardize how video profiles are incorporated into hashes that signatures are generated over (both when B signs a segment to be sent to O and when O signs a result to be sent to B. For example, we could concatenate the bytes representation of all video profiles and that would get hashed (along with other segment metadata) during signature generation/verification. 

Related: #1091

**Comment by j0sh** [comment]
>  Define net.TranscodingProfile in SegData protobufs  lp_rpc.proto.

Maybe we could call it `VideoProfile` to match the current terminology

> We'd also need to add a fullProfiles field to &core.SegTranscodingMetadata{
> Add fullProfiles to streamParameters in createRTMPStreamIDHandler
> Add fullProfiles to BroadcastSession:

As @yondonfu mentioned, we can just create new `VideoProfile` instances from the webhook when we receive them. From that point, they're the same type (`ffmpeg.VideoProfile`) as our presets, so we can reuse what we have now for our internal data structures - no need for new fields there.

The only things that need to change is what goes over the wire -  the webhook JSON response (user -> B), and `net.SegData` (B->O), and `net.NotifySegment` (O->T).

> We do need to make it clear in documentation somewhere that that flag can take a list of preset objects ["width", "height", "bitrate", "fps"]

I'd maybe leave the `TranscodingOptions` flag alone for now, and just keep the current behavior of taking preset names. Specifying JSON on the command line is unwieldy, so we can hold off on the question of "how to specify arbitrary resolutions on the command line"  because that's really a UI question.

One other thing to consider is that each VideoProfile has a name that's used to identify the rendition for downloads, eg ` <manifestID> / <rendition> / <seq> .ts` . How should this be handled? The broadcaster might want to specify their own rendition names, and it's easy to supply that via webhook, although it's really just a UX novelty more than anything.

I'm nervous about carrying a user-supplied VideoProfile name over to the O side for the same reason we shouldn't be using [B-generated manifest IDs](https://github.com/livepeer/go-livepeer/issues/695) on the orchestrator. Two options here that I can see:

* Allow the B to generate the name, but use a different name on the O-side for downloads

* Don't allow the B to generate the name, and use a mechanically generated name - perhaps the rendition index (in the order the user specified their renditions), or some combination of fields similar to our current naming scheme. Note that a randomized or really obscure name (eg, hex-encoded hash) probably shouldn't be used since it makes it harder for users to correlate output names with the actual profiles.

**Comment by angyangie** [comment]
Thanks for all the comments! To summarize, in speaking to @iameli, @j0sh and @yondonfu, I've gotten more clarity on a couple of points:

1. We will not be getting rid of the hardcoded profiles. `common.ProfilesToTranscodeOpts`, for example, wouldn't need any special logic because serialization would be the same whether it's a hard-coded or custom profile - they'll both be the same type of `ffmpeg.VideoProfile`. That said, we'll still do `VideoProfileLookup` for any presets that are supplied by the user on the command line in `go-livepeer`.

2. At this point, there are 2 ways to supply custom presets to `go-livepeer`. The first, is through `LivepeerWowza` - we have to populate `wowzaHydrate` in the API with the correct info: https://github.com/livepeer/livepeerjs/blob/master/packages/api/src/controllers/stream.js#L50. The second, by hitting the API directly on the command line, with something like this (but would have to specify a full bitrate ladder in this command, presumably using almost exactly the same format as will be returned from the webhook): 
```
curl -X POST --data '{"presets": ["P720p30fps16x9", "P360p30fps16x9", "P144p30fps16x9"], "name": "foo"}' -H 'authorization: Bearer eli4' -H 'content-type: application/json' https://livepeer.live/api/stream
```

- This whole thing would have to change on the API, since we're accepting custom presets: https://github.com/livepeer/livepeerjs/blob/master/packages/api/src/controllers/wowza-hydrate.js#L69-L89. We'll select the fps, bitrate, wowza height & width (and build the resolution field), build the name field, from the wowza presets data blob directly.

3. 4 byte ID for each hardcoded profile is unnecessary - they're artifacts of V1 protocol. 4 byte video profile IDs are defined as the first 4 bytes of the keccak256 hash of the video profile name: https://github.com/livepeer/go-livepeer/issues/1091#issuecomment-532334809. I guess it can just be removed? 

4.  This seems like a good way to serialized and hashed video profiles (required for generating signatures). See Josh's comment: https://github.com/livepeer/go-livepeer/issues/1091#issuecomment-557755325

5. Like @j0sh mentioned,  rendition downloads naming needs to change from this: `<manifestID> / <rendition> / <seq> .ts`. I like the second option you named @j0sh, using some combination of fields similar to our current naming scheme. No need to change for O-side downloads.

Thoughts?

**Comment by j0sh** [comment]
> This seems like a good way to serialized and hashed video profiles (required for generating signatures)

Perhaps until we settle on a way to generate the sigs (which is a protocol-specific detail and mostly unnecessary for private networks), we can just skip this part of sig generation and checking?

> using some combination of fields similar to our current naming scheme

Yes, it would mostly work. The only concern I have is that there's a possibility of collisions based on fields that are not explicitly enumerated. Right now the naming scheme is basically `<resolution><fps><aspect ratio>` . Currently it's possible to keep all 3 parameters the same but vary the bit rate, causing a naming collision across two otherwise different profiles. Or in the future we could add different codecs but keep other parameters the same.

In order to use this approach, I guess the answer would be to encode all the relevant fields, although this could lead to a lengthy name.

I'd actually be OK punting on this issue and just allowing user specified rendition names. (These types of decisions have a tendency to ossify though, so we probably should be careful here.)

Two more questions about the proposed webhook schema.

* Are we keeping the ability to specify presets via the webhook as well, in addition to using custom fields? This is pretty useful for my testing with ad hoc scripts and would be a nice way to preserve developer ergonomics.
* How does the `oneOf` for the `fps` field translate to a golang struct which AFAIK doesn't have union/sum types? Protobufs manages it but it's generated code. Maybe for the current webhooks struct (which is currently not generated) we can just take a single integer for the numerator, and revisit things when we're ready to add the denominator, which doesn't even exist in `ffmpeg.VideoProfile` right now.

**Comment by angyangie** [comment]
> In order to use this approach, I guess the answer would be to encode all the relevant fields, although this could lead to a lengthy name.

Is there a downside to lengthy names? 

> Perhaps until we settle on a way to generate the sigs (which is a protocol-specific detail and mostly unnecessary for private networks), we can just skip this part of sig generation and checking?

I can create an Epic on ZenHub and make that one of the last steps to implement, as a separate PR. Does that work for you @j0sh @yondonfu ?

> I'd actually be OK punting on this issue and just allowing user specified rendition names. (These types of decisions have a tendency to ossify though, so we probably should be careful here.)

Same as above for this one.

> Are we keeping the ability to specify presets via the webhook as well, in addition to using custom fields? This is pretty useful for my testing with ad hoc scripts and would be a nice way to preserve developer ergonomics.

Yes! You can POST to `/api/stream` and send in whatever presets you'd like in that request. Is that what you're talking about @j0sh? You can make an http POST request to that endpoint on our API from a script.

> Maybe for the current webhooks struct (which is currently not generated) we can just take a single integer for the numerator, and revisit things when we're ready to add the denominator, which doesn't even exist in ffmpeg.VideoProfile right now.

Totally fine with this as well. I can make a separate ticket for it and include at the bottom of an Epic.
