### ISSUE TITLE
Remote transcoder can't transcode more than one stream

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#845]
Remote transcoder feeds to `LPMS.Transcode` function URL of source segment (pointing to orchestrator).
This URL looks like this: `https://orchestrator:8936/stream/manifestid/1.ts`
LPMS, calling ffmpeg lib, sets output destination for transcoded data as this:
`fmt.Sprintf("out%v%v", i, filepath.Base(url))`, where `I` is transcoding profile number.
This means that requests to transcoded segments from different streams but with same seqNos will overwrite each other (and transcoding for one of the streams will fail).

Possible solutions:
1. Randomize output name in LPMS itself.
2. In transcoder, for every segment create random dir and pass it too LPMS.

**Comment by darkdarkdragon** [comment]
Suggested [fix](https://github.com/livepeer/lpms/pull/116)

**Comment by j0sh** [comment]
Good catch!

The transcoding API (which is admittedly not great) is getting an overhaul with the GPU support. I've already incorporated the [first suggested fix](https://github.com/livepeer/go-livepeer/compare/master...ja/nvidia#diff-418dc657e12875665c93dffe96a0e464R73) into the goclient's nvidia integration.

Once nvidia integration lands, we can retrofit the software transcoding to use the new API. If the fix for this is more urgent, then the second option would be less invasive - we can put a sub-directory in here (and `defer os.RemoveAll(subdir)`). Not pretty but should do the trick for now.

https://github.com/livepeer/go-livepeer/blob/960084b4864927a61f3dc77fb6d6e0cda29c6e63/core/transcoder.go#L23-L24

**Comment by darkdarkdragon** [comment]
[Here](https://github.com/livepeer/go-livepeer/pull/848/commits/9cdddf8b28d58a5ec7731f319fb70c3cdd0bc880) implementation.

**Comment by j0sh** [comment]
Fixed by https://github.com/livepeer/go-livepeer/pull/848/commits/76a5dd8449094d45b26232ba3b9b02f9b4976512
