### ISSUE TITLE
Transcoder should notify orchestrator on exit

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#847]
We don't have timeout on connection between O and T, so right now O becomes aware that T is no longer working is when it sends request to transcode segment.
Transcoder, upon exit, should sending notification to orchestrator, so it can remove it from list of alive transcoders.

**Comment by j0sh** [comment]
The transcoder can notify the orchestrator in the "happy" case but I suspect most disconnects will be "unhappy" where the T doesn't actually send out anything (eg, network partition, crash, etc).

It's too bad that gRPC makes it difficult to determine the status of a connection or stream, because then we could skip over disconnected transcoders. One thing we can do is to implement ping-pong keepalives which will help maintain the T list over time: https://github.com/livepeer/go-livepeer/issues/576

**Comment by darkdarkdragon** [comment]
> The transcoder can notify the orchestrator in the "happy" case but I suspect most disconnects will be "unhappy" where the T doesn't actually send out anything (eg, network partition, crash, etc).

I agree that most disconnects will be "unhappy", but still think it is good to have graceful shutdown of both transcoder and orchestrator. It will at least help when doing upgrades - transcoders will be able shutdown and get back online without introducing unnecessary errors.

> It's too bad that gRPC makes it difficult to determine the status of a connection or stream,

I've found way: #861
