### ISSUE TITLE
Benchmarking for a SINGLE transcoding node on n1-highcpu-4	

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#855]
Understand performance of a SINGLE transcoding node on n1-highcpu-4. Use recommended HLS bitrate ladder from Apple. 30 fps for all. (Eli works with Angie on laying out the exact steps here)
* Step1: On GCP: run on high CPU machines with 4 cores
* Step 2: Find out upper bound in transcoding node throughput
  * Run one stream
    * If success rate below {}, increase {} or {}
  * Run two streams
    * If success rate below {}, increase {} or {}
* Step 3: Find out “steady state” throughput

**Make sure this automated and repeatable**

**Comment by angyangie** [comment]
Spreadsheet with testing info here: https://docs.google.com/spreadsheets/d/1eChPNzG-VuitEFhK9IiJLc_UTNcY6rYu5oEzTEQ3OLQ/edit#gid=1196904340

Turns out I was doing local testing, not using GC instances. Setting up the instances now with ffmpeg/go/dependencies to continue testing.

**Comment by angyangie** [comment]
When we understand the performance of a single machine, we can get a better sense for how to scale our system. How many renditions can 4 cores handle at a time? How many streams? How many Os/Ts are needed to support transcoding for 100 streams in real-time? We should be able to extrapolate how many cores will be needed for any configuration using single transcoder benchmarking.

**Tests and results live here (ongoing)**: https://docs.google.com/spreadsheets/d/1eChPNzG-VuitEFhK9IiJLc_UTNcY6rYu5oEzTEQ3OLQ/edit#gid=1196904340

**Potential conclusions from this data (ongoing):** 
- We need more than 4 vCPUs to transcode 3 renditions at once in real-time. If we don't necessarily care about real time then we can over-provision additional machines to keep up with the load (eg, if it were 50% slower than realtime, we'd need 2x the machines per stream; if it were 25% faster than realtime, then we should be able to use 3 machines for every 4 segments per stream, etc. Note that our current setup basically doesn't accommodate slowdowns of more than 4x realtime (then we'd time out)

**How to set-up GC environment:**
First tests were run using machine type `n1-highcpu-4`. The second set using `n1-standard-8 (8 vCPUs, 30 GB memory)`.  GC instance was set-up as follows (which should be turned into a script ... and will be in the future): 

1. Make $HOME/go/src/github.com/livepeer/lpms path
2. `sudo apt-get update`
3. `sudo apt-get install git`
4. Install golang: `sudo add-apt-repository ppa:longsleep/golang-backports`, `sudo apt-get update`, `sudo apt-get install golang-go`
5. `sudo apt-get install autoconf autogen`
6. `sudo apt-get install libgnutls-dev` or `sudo apt-get install libgnutls28-dev`
7. set package config variable: `export PKG_CONFIG_PATH=/home/angie/compiled/lib/pkgconfig`
8. git clone lpms and [checkout](https://stackoverflow.com/questions/3489173/how-to-clone-git-repository-with-specific-revision-changeset)  [latest commit](https://github.com/livepeer/lpms/pull/114/commits) on GPU branch.
9. `chmod +x ./install_ffmpeg.go`
10. `./install_ffmpeg.go`
11. git clone [latest lpms benchmarking script](https://gist.github.com/j0sh/640cadfe39b759c38f953baca11e78b0/revisions) into lpms folder
12. Edit `out` variable in `lpms-bench.go` to include all transcoding options:
```
out := []ffmpeg.TranscodeOptions{
	ffmpeg.TranscodeOptions{
		Oname:   fmt.Sprintf("out/%d_240p_%d.ts", i, j),
		Profile: ffmpeg.P240p30fps16x9,
	},
	ffmpeg.TranscodeOptions{
		Oname:   fmt.Sprintf("out/%d_360p_%d.ts", i, j),
		Profile: ffmpeg.P360p30fps16x9,
	},
	ffmpeg.TranscodeOptions{
		Oname:   fmt.Sprintf("out/%d_720p_%d.ts", i, j),
		Profile: ffmpeg.P720p30fps16x9,
	},
}
```
13. Upload BigBuckBunny video to benchmarking gist folder just created
14. `mkdir hls`and `mkdir out` folder and run FFMPEG segmentation command: 
```
ffmpeg -i BigBuckBunny.mp4 -c:a copy -c:v libx264 -keyint_min 30 -g 30 -f hls -hls_time 2 -hls_playlist_type vod hls/bbb.m3u8
```
15. Run `go run lpms-bench.go hls/bbb.m3u8 1 297` to run first test. It is useful to look at https://github.com/livepeer/go-livepeer/issues/788 - the first column ("videos") is the concurrency. To run subsequent tests, run go command with more than 1 video. 


**Nuggets of important knowledge from @j0sh to point out:**

- The encoder uses as many threads as it can get already. Nominally there is an upper limit to how many threads the encoder will use, but it's more than the 4 available on the instance.
- Limiting processing to one thread absolutely isn't as fast  - more threads here generally gives us more parallelism, which means we can get more work done in the same amount of time. The increase isn't linear though - see https://en.wikipedia.org/wiki/Amdahl%27s_law.
- What the one-thread/core per video assumption gives us is a slightly easier way  to estimate resource usage, in addition to the original requirement of determinism for verification. But since we aren't actually running single threaded transcoding anymore, we need to do a little more work to benchmark the throughput of the system to understand how much we can throw at it.
- For benchmarking a single node, earlier attempts point to there being a limit to how much data we can push through the system, regardless of the number of streams. So discovering that bound is useful. See https://github.com/livepeer/go-livepeer/issues/788. In this case, the system could only do ~36 frames of 1080p per second, regardless of the number of streams. So adding one more stream meant a proportionate increase in encoding time for the rest. So determining the throughput in frames (for a given set of resolutions) is a good yardstick.
- One of the things we should standardize on is which resolutions / renditions to benchmark against. Then note that we encode all the renditions at once, so we need to benchmark the throughput of those combined. That's the most important thing to look at right now in terms of single-node benchmarking. We'll get different results if we benchmark each resolution separately when we need to understand how the system behaves as a whole.  But if we did that, we could probably determine a relationship between throughput, resolution, and the combinations thereof (my guess is that throughput basically comes down to the number of pixels, modulo some per-frame overhead)

**Comment by j0sh** [comment]
Is this issue done?

**Comment by angyangie** [comment]
Yes! Closing it now
