### ISSUE TITLE
O processes payment from B and checks that minimum credit requirement is met

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#895]
**ProcessPayment(payment, transOpts, manifestID)**

Should check that a broadcaster meets the minimum credit requirement.

Note: In practice, `ProcessPayment` will include additional logic. That logic is ommitted in favor of focusing exclusively on payment accounting related logic.

```
currCredit = CurrCredit(payment.sender)
updatedCredit = currCredit + payment.value
UpdateCredit(payment.sender, updatedCredit)

if updatedCredit < MinCredit() {
    return ERROR_INSUFFICIENT_CREDIT
}

...

```

**Comment by yondonfu** [comment]
We're currently planning on tracking credit balances locally on a per stream basis with relevant state flushed when the session with a stream times out (at the moment, approximately [1 minute](https://github.com/livepeer/go-livepeer/blob/master/core/orchestrator.go#L32) without receiving a segment). Orchestrators are already tracking session state using the [SegmentChans](https://github.com/livepeer/go-livepeer/blob/master/core/livepeernode.go#L61) map. We could make some modifications to this map and the [transcode segment loop](https://github.com/livepeer/go-livepeer/blob/master/core/orchestrator.go#L422) associated with each stream tracked by the map to support credit balance maintenance.

At the moment, `(*LivepeerNode).SegmentChans` maps the manifestID for a stream to a `SegmentChan` which is a type alias for a channel accepting [SegChanData](https://github.com/livepeer/go-livepeer/blob/master/core/orchestrator.go#L200) that holds input segment data as well as an output channel for sending transcoded results. Each `SegmentChan` can already be considered a "session" since an orchestrator maintains a single `SegmentChan` per manifestID (in fact, the code already checks the size of the `SegmentChans` map to [enforce an orchestrator session cap](https://github.com/livepeer/go-livepeer/blob/master/core/orchestrator.go#L80)).

In order to hold additional credit balance state per session, we can introduce a `SegSess` struct:

```
type SegSess struct {
    segChan SegmentChan
    credit *big.Rat
}
```

`SegSess` just wraps `SegmentChan` and also includes the `credit` field which is used to keep track of the broadcaster's current credit balance for the stream. We can maintain a `SegSess` per manifestID which still results in a `SegmentChan` per manifestID as well as a credit balance counter.

Whenever the orchestrator [receives a new input segment](https://github.com/livepeer/go-livepeer/blob/master/core/orchestrator.go#L451) via the `SegmentChan` for a transcode segment loop, it can update the credit balance stored in the `SegSess` for the transcode segment loop and then check if the broadcaster's current credit balance meets the minimum credit requirement (which is just the orchestrator's desired fixed ticket EV). The additional credit amount can be included in `SegChanData` when it is sent into `SegmentChan`. If the broadcaster does not meet the minimum credit requirement, the orchestrator can pass an error into the `TranscodeResult` channel of `SegChanData`.

**Comment by j0sh** [comment]
> Each SegmentChan can already be considered a "session" 

The SegmentChan table is what keys into active transcode loops.

Within the transcode loop we already maintain some per-session state within the `transcodeConfig` struct. Should we try maintaining the balance within that, rather than introduce another level of data encapsulation?

On a per-segment basis, any new credit can be carried within the `SegTranscodingMetadata`. Within the transcode loop, that credit can be applied to the balance, and then the balance debited at the end of the loop.

Aside, but I would also love if this was also done for the older PM ticket stuff which kind lives in its own world; eg `getAndClearPMSessionIDsByManifestID` is entirely unnecessary if it's attached to the transcode loop.

**Comment by yondonfu** [comment]
> The SegmentChan table is what keys into active transcode loops.

Yep I just meant that each `SegmentChan` corresponds to a session (since a `SegmentChan` keys to an active transcode loop for the session).

> Within the transcode loop we already maintain some per-session state within the transcodeConfig struct. Should we try maintaining the balance within that, rather than introduce another level of data encapsulation?

Good point! I'd prefer to avoid defining another wrapper struct as well. Technically, I don't think we even need to include the credit balance in the `transcodeConfig` struct since none of the functions that accept a `transcodeConfig` param need the credit balance (yet?) and we could instead just have the goroutine in `transcodeSegmentLoop` close over a `credit` variable. That being said, I do like holding the `credit` variable in the `transcodeConfig` struct just to keep per-session state in one location.

> On a per-segment basis, any new credit can be carried within the SegTranscodingMetadata.

👍 

> Aside, but I would also love if this was also done for the older PM ticket stuff which kind lives in its own world; eg getAndClearPMSessionIDsByManifestID is entirely unnecessary if it's attached to the transcode loop

Yeah agreed. Though, we might be able to get rid of stuff like `getAndClearPMSessionIDsByManifestID` altogether once #829 is completed since O will no longer be holding winning tickets for the duration of a stream (and thus will not need to save PM session IDs to be used later).

**Comment by j0sh** [comment]
> we could instead just have the goroutine in transcodeSegmentLoop close over a credit variable

Yeah, I like that too. I've been trying to keep such config structs immutable to make things easier to deal with across multiple goroutines. If we can avoid stuffing mutable state into long-lived structs, that's a win. Otherwise, we have to tread carefully and either add locking everywhere mutable fields are used, or ensure that the struct is never shared across goroutines (and golang cannot give us this type of assurance statically).

> close over a `credit` variable.

Can we maybe make the naming little more specific? Something like `ethBalance` on which we can apply credits and debits?

**Comment by yondonfu** [comment]
> If we can avoid stuffing mutable state into long-lived structs, that's a win.

Good point. With that in mind, I now favor having the goroutine in `(*LivepeerNode).transcodeSegmentLoop()` close over a local variable which not only avoids adding mutable state to the `transcodeConfig` struct, but also keeps the credit balance state isolated in the single area of the codebase that it is needed.

> Can we maybe make the naming little more specific? Something like ethBalance on which we can apply credits and debits?

Definitely. My suggestion is `balance` for brevity.

**Comment by yondonfu** [comment]
Just wanted to note that one downside of applying credits/debits and maintaining the broadcaster's balance within the goroutine associated with `(*LivepeerNode).transcodeSegmentLoop()` is that the orchestrator will still download the input segment even if the broadcaster's balance ends up being insufficient for the orchestrator to proceed with transcoding.

**Comment by kyriediculous** [comment]
> we could instead just have the goroutine in transcodeSegmentLoop close over a credit variable

After going through the current code, I agree with this.
_______

Shouldn't we represent `credit` hereafter `balance`  as a `big.Int` rather than a `big.Rat` ?

**Comment by yondonfu** [comment]
> Shouldn't we represent credit hereafter balance as a big.Int rather than a big.Rat ?

Since we're representing the price per pixel as a `big.Rat` the debit amount (calculated as `pricePerPIxel * numPixels`) will also be a `big.Rat`. The debit amount will need to be subtracted from `balance` so I think it makes sense for `balance` to also be a `big.Rat`.

**Comment by kyriediculous** [comment]
Now that I'm actually trying to map how to implement this I'm wondering if there aren't better tradeoffs to make rather than keeping track over a local `balance` variable in the transcoding loop. 

Wouldn't it be simpler to track this in a seperate mapping `(*LivepeerNode).Balances - map[manifestID]*big.Rat` and flush that state where we flush the SegmentChans? https://github.com/livepeer/go-livepeer/blob/8fa167da89657bdc9a973212c181baacd4d816e8/core/orchestrator.go#L447

I know this introduces yet another field on the node and doesn't isolate credit to the part of the codebase where it's needed. But there's benefits to it as well.

1. We don't have to wrap `SegmentChan` in another struct (if going that route)
2. A transcoder doesn't have to download the file if balance isn't sufficient
3. Credit checking business logic doesn't really belong in the transcoding loop, does it? imo it belongs in logic that processes incoming payments but closing over a local variable forces us to take care of that logic in the transcoding loop (or do I see that wrong?)
4. We don't have to return the payment value (credit) from `ProcessPayment` to include it in the `SegTranscodingMetadata`

I'm likely forgetting something here because I can't imagine that this is something that hasn't crossed your minds already, so I'd love if someone could make me wiser as to why that wouldn't be a good decision because to me it sounds reasonable. 

Some of the downsides I'm guessing:
1. balances aren't isolated to that part of the codebase 
2. we'll have to make it safe for concurrent access? 
3. Yet another field on the node

Thanks !

**Comment by yondonfu** [comment]
> Wouldn't it be simpler to track this in a seperate mapping (*LivepeerNode).Balances - map[manifestID]*big.Rat and flush that state where we flush the SegmentChans?

I actually think closing over a balance variable with the transcode loop is the simplest approach since state flushing is automatically handled when the loop times out without any additional changes. Placing the credit balance maintenance logic in the transcode loop has the nice property of tying the balance with the lifecycle of the loop (i.e. the balance only exists for as long as the loop), but that being said, after some more thinking, I do think it would be nice to skip file downloads if B's balance is insufficient which doesn't seem feasible given the current architecture of the transcode loop since program execution wouldn't enter the loop until after the file is downloaded.

> We don't have to wrap SegmentChan in another struct (if going that route)

On second thought, using a wrapper struct feels a bit weird because we'll need to create the struct in the mapping before a transcode loop is actually created. So, there will be three states for an entry in the mapping: nil, initialized struct without an active transcode loop, initialized struct with an active transcode loop. This is in contrast to the current `SegmentChans` mapping which has the nice property of only having two states for an entry in the mapping: nil without an active transcode loop and non-nil with an active transcode loop.

> A transcoder doesn't have to download the file if balance isn't sufficient

Yeah I think this is a nice property to shoot for as its a defensive practice that protects O's bandwidth.

I'm not a big fan of adding yet another field to `LivepeerNode` which represented shared global state, but that seems like the simplest path forward at the moment. As you described, we can add:

```
type LivepeerNode struct {
    balMtx sync.RWMutex
    balances map[ManifestID]*big.Rat
}
```

Then we can lock/unlock `balMtx` in `ProcessPayment()` and perform the balance update [here](https://github.com/livepeer/go-livepeer/pull/937/files#diff-b76fbd82bbf5b7a4d2fdf59ecd8d4ca6R148). Finally, at the end of `ProcessPayment()` we can do the credit requirement check and return an error if it fails.

**Comment by kyriediculous** [comment]
After the design discussion on this issue we will be going for another approach than initially discussed. 

The approach we want has following properties: 
1. Prevents O from downloading the segment if balance is insufficient, protecting O's bandwith
2. Credit is on a per stream basis rather than a per sender basis
3. Reduces amount of possible developer error and increases code maintainability down the line
4. Is seperate from the `pm` package

To achieve this goal we will define a new type alias, one caveat is that it requires a bit of juggling with naming to avoid name repetition (`Balances.balances`). I suggest using the naming as defined below. 

We can run `Accounts.Cleanup()` on a ticker similar to how we refresh the cache. All balances that weren't updated since the last time cleanup ran, will be deleted (duration of `transcodeLoopTimeout`). The method itself is run on a seperate goroutine, we can implement this where we start/stop most other related orchestrator services and set the priceInfo; [line 322-393 in cmd/livepeer.go
](https://github.com/livepeer/go-livepeer/blob/0dcd9bd30b377159801e4be4c6358c1812d1cccc/cmd/livepeer/livepeer.go#L392)

The high-level logic in `ProcessPayment` will now look as follows: 
```
for _, tsp := range payment.TicketSenderParams {
 // If there is no error in receiving the ticket
 // Or the ticket params have acceptable errors
 // Credit the amount to the balance
orch.node.Accounts.Credit(manifestID, new(big.Rat).Mul(new(big.Rat).SetFrac(ticket.FaceValue, big.NewInt(1)), ticket.WinProbRat()))
}
// Check if credit requirements are met
if orch.node.accounts.Balance(manifestID) < MinCredit() {
    return ERROR_INSUFFICIENT_CREDIT
}
```

The Accounts will be defined in `core/accounting.go` rather than a separate package

```
// Use transcodeLoopTimeout as TTL for a ManifestID's credit balance
// We should prevent the use of global state if they are not constants

type Accounts struct {
	Balances map[ManifestID]*Balance
	Mtx      sync.RWMutex
}

type Balance struct {
	LastUpdate time.Time // time since last update
	Amount     *big.Rat  // Balance represented as a big.Rat
}

func (a *Accounts) Credit(id ManifestID, amount *big.Rat) {
	a.Mtx.Lock()
	defer a.Mtx.Unlock()
	a.Balances[id] = &Balance{
		LastUpdate: time.Now(),
		Amount:     new(big.Rat).Add(a.Balances[id].Amount, amount),
	}
}

func (a *Accounts) Debit(id ManifestID, amount *big.Rat) {
	a.Mtx.Lock()
	defer a.Mtx.Unlock()
	a.Balances[id] = &Balance{
		LastUpdate: time.Now(),
		Amount:     new(big.Rat).Sub(a.Balances[id].Amount, amount),
	}
}

func (a *Accounts) Balance(id ManifestID) *big.Rat {
	a.Mtx.RLock()
	defer a.Mtx.RUnlock()
	return a.Balances[id].Amount
}

// Cleanup is a state flushing method
func (a *Accounts) Cleanup() {
	clean := func() {
		for id, balance := range a.Balances {
            a.Mtx.Lock()
			if int64(time.Since(balance.LastUpdate)) > int64(transcodeLoopTimeout)*60 {
				delete(a.Balances, id)
			}
            a.Mtx.Unlock()
		}
	}

	ticker := time.NewTicker(transcodeLoopTimeout)
	for range ticker.C {
		clean()
	}
}
```
