### ISSUE TITLE
O processes transcoded result and debits from B's credit balance

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#896]
**TranscodeSeg(segTranscodingMetadata, seg)**

Should return the transcoded results for `seg` based on the requested renditions included in `segTranscodingMetadata` and additional metadata for each of the transcoded results. The transcoded results will be returned as an array `transRes` and the associated metadata will be returned as an array `transResMetadata` such that `transResMetadata[i]` is the metadata associated with `transRes[i]`. In the context of payment accounting, the particular field in the metadata that we care about is the output pixel count for a particular transcoded result.

The number of output pixels processed should be included in a `TranscodeReceipt` message that is returned to the broadcaster.

**ProcessTranscodedResults(addr, transResMetadata)**

Should debit a broadcaster's credit balance based on the number of output pixels included in the transcoded results. 

This will be called after `TranscodeSeg` and before the results are sent to the broadcaster.

```
priceInfo = PriceInfo(addr)
pricePerPixel = priceInfo.pricePerUnit / priceInfo.pixelsPerUnit

debit = 0

for meta in transResMetadata {
    debit += pricePerPixel * meta.outPixels
}

currCredit = CurrCredit(payment.sender)
updatedCredit = currCredit - debit
UpdateCredit(addr, updatedCredit)
```

In the future, if transcoding is short-circuited due to insufficient broadcaster credit balance, the orchestrator would likely need to withhold the result because the produced result would considered an invalid output. However, in the short term without short-circuiting, it might be fine to return the result even if the broadcaster credit balance drops below 0 to give the broadcaster an opportunity to make up for the amount owed with a subsequent payment. If the next segment the broadcaster sends doesn't include a payment that brings the broadcaster's credit balance back up to the minimum credit requirement then the orchestrator will return an error.

**Comment by yondonfu** [comment]
While the completion of this feature is blocked by livepeer/lpms#124, we can still implement the debit logic described in the OP by temporarily hardcoding the number of pixels that should be used as an input (as well as the orchestrator's current price) in calculating the amount to debit from the broadcaster's credit balance. This approach would allow us to focus on completing an e2e payment accounting workflow with credit maintenance logic implemented for both orchestrators and broadcasters first and then coming back to implement pixel counting logic afterwords (gives us a bit more time to figure out how we want to implement pixel counting).

The debit logic could be executed after the orchestrator transcodes a segment and before it passes the transcoded result into the `TranscodeResult` channel for `SegmentChan`.

**Comment by kyriediculous** [comment]
`TranscodeSeg(SegTranscodingMetadata, HLSSegment) TranscodeResult, error`

returns the transcoded results for a segment based on the requested conditions included in `SegTranscodingMetadata`. Transcoded results will be returned as `TranscodeResult` containing a slice of `TranscodeData`which includes the transcoded segment and pixel count. 

```
type TranscodeResult struct {
	Err  error
	Sig  []byte
	TranscodeData []*TranscodeData
	OS   drivers.OSSession
}

type TranscodeData struct {
   Data []byte // Transcoded segment
   PixelCount int64 // Pixels processed * 
}
```

    * Could potentially be wrapped in a separate TranscodeMetaData struct, but for one field it seems unnecessary for now. 

Processing Segments: 

When looping over the transcoded segments we should debit the balance for `SegTranscodingMetadata.ManifestID`according to the amount pixels processed as defined in `TranscodeData` for each segment rendition and the price as set by the orchestrator.
`orch.node.Balances.Debit(manifestID, pixelCount*price)`  

After debiting the amount of pixels processed should be added to the `TranscodedSegmentData` message for each segment.

Lastly after all segments are transcoded we'll query the remaining balance for the `ManifestID` and let the broadcaster know his provisional remaining balance in the `TranscodeResult` message. 

Since `Balances` isn't part of the `Orchestrator` interface we might want to add an interface method `ProcessSegments(ManifestID, TranscodeResult) net.TranscodeResult, error`

**Comment by yondonfu** [comment]
How about `Pixels` instead of `PixelCount` in the `TranscodeData` struct for brevity?

> Since Balances isn't part of the Orchestrator interface we might want to add an interface method ProcessSegments(ManifestID, TranscodeResult) net.TranscodeResult, error

We could also add a slimmer interface method that is *only* concerned with debiting fees:

Ex.

```
type Orchestrator interface {
    func DebitFees(manifestID ManifestID, pixels int64, priceInfo *net.PriceInfo) error
}

func (o *orchestrator) DebitFees(manifestID ManifestID, pixels int64, priceInfo *net.PriceInfo) error {
    // Compute fee based on pixels and priceInfo
    // Debit fee from the balance for manifestID
}
```

Then, in `ServeSegment()`, we could debit the fees for a transcoded segment after it has been uploaded (so we would have its URI):

```
for i := 0; err == nil && i < len(res.Data); i++ {
    // Upload
    
    // Note: The price used to compute the fee is the price provided by B in the Payment message
    if err := orch.DebitFees(segData.ManifestID, res.TranscodeData[i].Pixels, payment.PriceInfo); err != nil {
        // Log error
    }
}
```

**Comment by kyriediculous** [comment]
> How about Pixels instead of PixelCount in the TranscodeData struct for brevity?

Adjusted names in the types in core as well as the proto messages for brevity

_____ 

> We could also add a slimmer interface method that is only concerned with debiting fees:

That had crossed my mind as well, but when implementing #892 we'll need to add a call to `Balances.Balance(segData.ManifestID)` in `serveSegment` as well , implying to have to add yet another method to the interface (eg. `RetrieveBalance`) .
```
	tr := &net.TranscodeResult{
		Seq:     segData.Seq,
		Result:  result.Result,
		Balance: orch.node.Balances.Balance(segData.ManifestID), // Can't access this
		Info:    oInfo, 
	}
```

Defining an interface method that handles a little more allows us to move all of this logic in one method and only requires us to add a single interface method to the `Orchestrator`interface without having to expose specific methods for accounting (which I don't think should be part of that interface anyway). The current use of the accounting logic is abstracted away behind `ProcessPayment` and `SufficientBalance` as well, and I already find the latter one a means of last resort. If I remember correctly one of the concerns you voiced was adding too much to this interface. 

For the record, I would be moving the already existing logic into `ProcessSegments` (or perhaps `ProcessTranscodedResults`is better but  longer) as well.  So the underlying implementation would be the same as we discussed (debiting in the existing for loop) and as you describe in your comment.

We could also still make smaller unexported methods on the orchestrator that are then bundled in `ProcessSegments / ProcessTranscodedResults`. Furthermore I think it will make `ServeSegment` more readable as well through method names (GetPayment -> VerifySegCreds -> ProcessPayment -> SufficientBalance -> Download body -> TranscodeSeg -> ProcessResults -> Marshal & Return response) because currently it's a little "chewy". 

The major drawback of this approach is that `ProcessTranscodedResults` has quite a body and we'll have to pass the sender as an argument as well (to get the PriceInfo). Additionally we'll still have to construct the `net.TranscodeResult `with an error if `TranscodeSeg` errored, inside of `serveSegment` meaning balance will be returned nil on error. And add orchestratorInfo to the `TranscodeResult` before marshalling.

So I'm not sure what the best tradeoff to make is here, add multiple smaller methods to the `Orchestrator` interface or have a little bit of duplication in constructing the response and not being able to return the balance when `TranscodeSeg` errors. (Or we could pass the error as a fourth argument but that seems weird, alternatively we could check if `TranscodeResult` is nil inside `ProcessTranscodedResult` which would mean there was an error but then we still can't retrieve the error to pass into the response?).

**Comment by yondonfu** [comment]
If we omit `balance` from the `TranscodeResult` message as described in [this comment](https://github.com/livepeer/go-livepeer/issues/892#issuecomment-509758375), then we can simplify the workflow to something like this:

```
totalPixels := 0

for i := 0; err == nil && i < len(res.TranscodeData); i++ {
    // Upload
    
    pixels += res.TranscodeData[i].Pixels
}

orch.DebitFees(segData.ManifestID, totalPixels, payment.PriceInfo)
```

**Comment by kyriediculous** [comment]
It does indeed simplify quite a lot if we don't need to include the balance. In light of my previous comments though, would you be against doing something like what's underneath. I know it doesn't make much difference anymore between doing what's below and `orch.DebitFees`, just makes `ServeSegment` a little more readable. But I still dislike (personal preference I guess) just having an interface method for debiting (which just involves calling Balances.Debit with a multiplication now). 

I'd have a preference for not keeping a pixel count and just debiting per segment though since we do not need to return the balance. 

**orchestrator.go**
```
// ProcessTranscodedResults processes transcoded results, debits the balance for the stream
// uploads to OS and constructs the segment set for the response
func (orch *orchestrator) ProcessTranscodedResults(segData *SegTranscodingMetadata, tres *TranscodeResult, price *net.PriceInfo) []*net.TranscodedSegmentData {
	var segments []*net.TranscodedSegmentData
	for i := 0; tres != nil && i < len(tres.TranscodeData); i++ {
		// Debit balance for each segment
		orch.node.Balances.Debit(segData.ManifestID, orch.transcodePrice(price, tres.TranscodeData[i].Pixels))
		// upload to OS
		name := fmt.Sprintf("%s/%d.ts", segData.Profiles[i].Name, segData.Seq)
		uri, err := tres.OS.SaveData(name, tres.TranscodeData[i].Data)
		if err != nil {
			glog.Error("Error saving to OS")
			break
		}
		// Construct segment result set
		segments = append(segments, &net.TranscodedSegmentData{
			Url:    uri,
			Pixels: tres.TranscodeData[i].Pixels,
		})
	}
	return segments
}

func (orch *orchestrator) transcodePrice(price *net.PriceInfo, pixels int64) *big.Rat {
	return new(big.Rat).Mul(big.NewRat(price.GetPricePerUnit(), price.GetPixelsPerUnit()), big.NewRat(pixels, 1))
}
```

**segment_rpc.go**
usage in `ServeSegment`

...
```
	res, err := orch.TranscodeSeg(segData, &hlsStream) // ANGIE - NEED TO CHANGE ALL JOBIDS IN TRANSCODING LOOP INTO STRINGS

	segments := orch.ProcessTranscodedResults(segData, res, payment.ExpectedPrice)

	var result net.TranscodeResult
	if err != nil {
		glog.Error("Could not transcode ", err)
		result = net.TranscodeResult{Result: &net.TranscodeResult_Error{Error: err.Error()}}
	} else {
		result = net.TranscodeResult{Result: &net.TranscodeResult_Data{
			Data: &net.TranscodeData{
				Segments: segments,
				Sig:      res.Sig,
			}},
		}
	}

	tr := &net.TranscodeResult{
		Seq:    segData.Seq,
		Result: result.Result,
		Info:   oInfo, // oInfo will be non-nil if we need to send an update to the broadcaster
	}

	buf, err := proto.Marshal(tr)
```
...

**Comment by yondonfu** [comment]
> In light of my previous comments though, would you be against doing something like what's underneath.

The choice of what logic to stuff into `ProcessTranscodedResults()` feels a bit arbitrary - why not also just include the construction of the `*net.TranscodeResult` struct? We could also skip defining an additional interface method altogether and stuff all this logic in `TranscodeSeg()`. Furthermore, besides the debit logic, none of the referenced code needs to depend on state maintained by a struct that implements the `Orchestrator` interface since all the relevant state is already held within `ServeSegment()` so it does feel like we're adding another extra level of indirection by moving the code into another method.

> I'd have a preference for not keeping a pixel count and just debiting per segment though since we do not need to return the balance.

I suggested to sum together the pixels and debiting based on the total sum because this would avoid multiple map writes and associated locking/unlocking.

**Comment by kyriediculous** [comment]
> We could also skip defining an additional interface method altogether and stuff all this logic in TranscodeSeg()

I'm fine with this

**Comment by j0sh** [comment]
> skip defining an additional interface method altogether and stuff all this logic in TranscodeSeg()

It's important to exit from the transcode loop early in order to free up the loop for the next segments. Things like `os.SaveData`  can potentially take a long time (eg, if uploading to S3 or GCS), and we don't want to be blocking the transcode loop.

Anything especially heavy that needs to be done after the transcode would probably best belong outside TranscodeSeg. (This isn't currently followed for things like signing the results; feel free to move that around as well.) If updating the balance is quick enough, then it's probably OK to keep that part specifically within TranscodeSeg, but keep the current operations outside.

**Comment by kyriediculous** [comment]
On second thought, we didn't want to add crediting balance in the transcodeloop either, so adding debiting wouldn't be in line with our approach for crediting and checking balance. 

I don't think updating the balance is a slow operation but it is an extra one nontheless. 

Let's keep the logic out of transcodeLoop and go with `orch.DebitFees` inside of `ServeSegment` imo.
