### ISSUE TITLE
B asynchronously verifies its current credit balance using transcode receipts from O

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#899]
**CheckTranscodeReceiptsInBackground(sess, seg, transRes)**

Should check that the information in receipts for transcoded results (i.e. pixels processed) is valid. A broadcaster will call this function *asynchronously* after receiving the transcoded results for a segment. This function should be called asynchronously because we want to avoid as much computation as possible on the critical path for streaming and reduce timing pressure. The broadcaster can provisionally use the receipt information returned by an orchestrator in order to update its credit balance in order to send a subsequent payment and the actual verification of the receipt information can occur in the background.

```
for res in transRes {
    // Check that the pixels processed in the receipt matches
    // the number of output pixels in the result
    // In the future, we can take into account input pixels as well
    if res.receipt.pixelsProcessed != outPixels(res) {
        // Send an error to disconnect from the orchestrator
    }
    
    receiptPricePerPixel = res.receipt.priceInfo.pricePerUnit / res.receipt.priceInfo.pixelsPerUnit
    pricePerPixel = sess.priceInfo.pricePerUnit / sess.priceInfo.pixelsPerUnit
    
    // EPISLON is some constant which is used to determine
    // if the price indicated in the receipt is too far off
    // of the latest price that the broadcaster is aware of
    if abs(receiptPricePerPixel - pricePerPixel) > EPISLON {
        // Send an error to disconnect from the orchestrator
    }
}
```

**Comment by kyriediculous** [comment]
Considering that we are not returning either a provisional balance or a pixelPrice used in the transcode results we limit the scope of this issue to verifying the pixelCount only (as discussed prior in #892). 

I was thinking of completing this check in server/transcodeSegment() which is called from `processSegment`, more specifically in the [download function for each segment](https://github.com/livepeer/go-livepeer/blob/50b15070c7486f24f0f377553c3a8e694e8d92c8/server/broadcast.go#L369), after we download the raw bytes from the transcoder but before we save it to B's OS. 

```
for i, v := range res.Segments {
	go dlFunc(v.Url, i)
}
```

Even though this doesn't isolate this specific logic we could still create a helper method 
`checkOutputPixels(data, res.Segments[i].Pixels, sess.Profiles[i], seg.Duration, seg.SeqNo) error` *

* _I'm not sure what exact arguments are needed here, I assume at least the job profile to pass into the method we use to calculate output pixels on `data`_ 

When checkOutputPIxels returns an error we can disconnect from O. 

**dlFunc(url string, i int)**
```
data, err := drivers.GetSegmentData(url)
if err != nil {
	...
	cxn.sessManager.removeSession(sess)
	return
}
err = checkOutputPixels(data, res.Segments[i].Pixels, seg.Duration, seg.SeqNo)
if err != nil {
	...
	cxn.sessManager.removeSession(sess)
        // Don't return because we still want to use the segment, just disconnect from O
}
name := fmt.Sprintf("%s/%d.ts", sess.Profiles[i].Name, seg.SeqNo)
newURL, err := bos.SaveData(name, data)
```

The major downside of this approach seems to be that we need to calculate the output pixels BEFORE we are insert the HLS segment into the playlist manager. Therefore I have also considered an alternative.

**Alternative Approach**
Do the check [after we insert the transcoded segment into the playlist manager](https://github.com/livepeer/go-livepeer/blob/50b15070c7486f24f0f377553c3a8e694e8d92c8/server/broadcast.go#L399), 
But rather than passing in the raw bytes for the segment we pass in the URL where B has saved it along with probably the job profile. 

`checkOutputPixels(url, res.Segments[i].Pixels, sess.Profiles[i], seg.Duration, seg.SeqNo) error` 

```
err = cpl.InsertHLSSegment(&sess.Profiles[i], seg.SeqNo, url, seg.Duration)
if err != nil {
    ...
}
err = checkOutputPixels(data, res.Segments[i].Pixels, seg.Duration, seg.SeqNo)
if err != nil {
	...
	cxn.sessManager.removeSession(sess)
        return
}
...
```

The downside of this approach is that the mediaserver calculating the output pixels would have to refetch the segment from the OS? I'm not sure what the implications are here as I'm not familiar with this piece of the codebase. 

It does reduce the time it takes for the rendition to be inserted into the playlist so **from that perspective I might even like the alternative better** if my concern about the mediaserver having to refetch is not an issue.

**Comment by j0sh** [comment]
> The major downside of this approach seems to be that we need to calculate the output pixels BEFORE we are insert the HLS segment into the playlist manager. 

This would make it still technically synchronous (since it's not yet available to the user).

The best place seems to be to do the check in its own goroutine after sig checking. Otherwise, it should be considered synchronous.

(I wonder if we really should make the sig check async as well, but failing it would mean we don't retry the segment. But there's a couple issues here with the sig check anyway: 1. not sure how effective this actually is in practice as an 'error check', and the final structure of the sig check is still TBD based on the validation protocol, so it's kind of vestigial right now.)

**Comment by kyriediculous** [comment]
@j0sh  After our design session earlier today we are considering firing a goroutine from the `dlFunc` after inserting the segment into the playlist manager. 

But we've also moved this issued to the _Pixel count integration project_ as function signatures for the actual functions that return the pixel count are still a bit unclear.
