### ISSUE TITLE
MVP B price per pixel preference setting

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#906]
B should be able to set a maximum price per pixel so that it will refuse to work with Os that advertise a higher price per pixel. The node already defines a [BroadcastPrice](https://github.com/livepeer/go-livepeer/blob/master/server/mediaserver.go#L57) which is configurable via the CLI wizard. For this MVP price preference setting we can just update that variable to indicate a price per pixel in same format as described in #891.

Then, when [creating broadcast sessions](https://github.com/livepeer/go-livepeer/blob/master/server/broadcast.go#L176) for a list of orchestrators, we can exclude orchestrators that advertise an unacceptable price per pixel.

**Comment by yondonfu** [comment]
The second part of this issue will require a broadcaster to filter out orchestrators that advertise a price higher than the broadcaster's max price.

We can introduce a predicate function to the orchestrator pool struct defined in the [discovery](https://github.com/livepeer/go-livepeer/blob/master/discovery/discovery.go#L24) package:

```
type orchestratorPool struct {
    uris []*url.URL
    bcast server.Broadcaster
    // This predicate function should be executed for each OrchestratorInfo response
    // If the function returns true, we will accept the orchestrator
    // Else, the orchestrator will be dropped
    pred func (*net.OrchestratorInfo) bool
}
```

An additional constructor `NewOrchestratorPoolWithPredicate()` could be used to initialized an orchestrator pool with a predicate function.

The `GetOrchestrators()` method would be updated to apply the predicate function (if it is defined) for each OrchestratorInfo response:

```
func (o *orchestratorPool) GetOrchestrators(numOrchestrators int) ([]*net.OrchestratorInfo, error) {
    ...
    
    getOrchInfo := func(uri *url.URL) {
        ...
        if err == nil && (o.pred != nil && o.pred(info)) {
            orchInfos = append(orchInfos, info)
            ...
        }
    }
}
```

At the moment, if the node is running in on-chain mode, it will use [discovery.DBOrchestratorPoolCache](https://github.com/livepeer/go-livepeer/blob/master/cmd/livepeer/livepeer.go#L389), an implementation of the OrchestratorPool interface that caches orchestrator URIs in the node's DB. We can update the `GetOrchestrators()` implementation for `discovery.DBOrchestratorPoolCache` to use a max price based predicate:

```
func (dbo *DBOrchestratorPoolCache) GetOrchestrators(numOrchestrators int) ([]*net.OrchestratorInfo, error) {
    ...
    
    // Note: Representing prices as big.Rat values here
    pred := func (info *net.OrchestratorInfo) bool {
        oPrice := big.NewRat(info.PriceInfo.PricePerUnit, info.PriceInfo.PixelsPerUnit)
        return oPrice.Cmp(server.BroadcastPrice) <= 0
    }

    orchPool := NewOrchestratorPoolWithPred(dbo.node, uris, pred)

    orchInfos, err := orchPool.GetOrchestrators(numOrchestrators)
    
    ...
}
```

One not so great aspect of the above sketch is that the `discovery` package will end up importing the `server` package in order to access the exported `BroadcastPrice` variable which is how the broadcaster currently [sets its max price](https://github.com/livepeer/go-livepeer/blob/master/server/webserver.go#L108). While this does not result in an import cycle, it does feel weird to be importing the `server` package for a single variable since the `discovery` package does not care about any other details of the `server` package (and this might lead to dependency weirdness/issues in the future).

An alternative is to replace `server.BroadcastPrice` with a `MaxBroadcastPrice` defined on `core.LivepeerNode` - `discovery.DBOrchestratorPoolCache` already contains `core.LivepeerNode`, so it could directly access `MaxBroadcastPrice`.

**Comment by kyriediculous** [comment]
> An alternative is to replace server.BroadcastPrice with a MaxBroadcastPrice defined on core.LivepeerNode - discovery.DBOrchestratorPoolCache already contains core.LivepeerNode, so it could directly access MaxBroadcastPrice.

I like the alternative better, since we're also defining `PriceInfo` on `core.LivepeerNode`. This gives a more consistent approach. The `LivepeerNode` struct is being shared and not copied everywhere that I see it anyway so adding some extra fields to this for the sake of code sanity shouldn't be that worrysome either I think.

Which one has your preference @yondonfu ?

**Comment by yondonfu** [comment]
Defining `MaxBroadcastPrice` on `core.LivepeerNode` sounds reasonable to me!

**Comment by j0sh** [comment]
> Defining MaxBroadcastPrice on core.LivepeerNode sounds reasonable to me!

Sure, that works. We could also make `MaxBroadcastPrice` global to `core`, but I suspect we'll need to be read-locking this for true thread safety since the value is modifiable via CLI.

While we're on the topic of how to integrate this, may I ask to also update the DB cache implementation to store pricing information as well. The intent has been to use the DB as a quick first pass over the candidate set of orchestrators, and sending OrchestratorInfo requests only to Os that pass the criteria.

This should help minimize the number of requests we're sending out when there are hundreds of Os on the network. (We should still check pricing info based on the OrchestratorInfo response in case that has changed in the interim since the last cache refresh.)

The flow would look something like:

0. Refresh DB cache, insert O pricing info
1. Stream comes in
2. Filter eligible Os from DB cache (update `db.SelectOrchs`)
3. Send OrchestratorInfo request to eligible Os
4. Filter out eligible Os from response
4. Use top-N eligible responses for O selection

**Comment by kyriediculous** [comment]
While I agree that we should reduce the time to transcoding as much as possible, I also think we should enable broadcasters (and all participants on the network, for that matter) to be able to make optimal economic decisions. 

That means if we implement such a design that we should also enable broadcasters to determine the rate at which they want to refresh the entire pool rather than hard-coding it to an hour. This would allow broadcasters to find a balance between optimal economic decisions and time to transcoding based upon their bandwidth capabilities. Although I do not see such a feature as an immediate necessity or priority. 

----- 

Regarding `MaxBroadCastPrice`, I found out we're already importing `server`into `discovery` for access to `server.getOrchestratorInfo` and `server.Broadcaster` though @yondonfu. So I have mixed feelings regarding my earlier statement now, if we're going to implement the `MaxBroadcastPrice` on the `LivepeerNode` we should rework those two as well. 

For the broadcaster interface we're importing it's fairly simple. We can make a seperate package called `roles` or something which would contain both the `Broadcaster interface` and `Orchestrator interface`. For the `server.getOrchestratorInfo` we could make a seperate package `client`. 
Although I'm not entirely sure if that would lead to cyclical imports down the line. Having the packages seperated might also lead to confusion down the line as a node consists of both a server and a client, so I get why those aren't separated now either.

**Comment by yondonfu** [comment]
> We could also make MaxBroadcastPrice global to core, but I suspect we'll need to be read-locking this for true thread safety since the value is modifiable via CLI.

Yeah - regardless of where we put it, I think we'll need to lock it with a `sync.RWMutex`.

> 1. Refresh DB cache, insert O pricing info
> 2. Stream comes in
> 3. Filter eligible Os from DB cache (update db.SelectOrchs)
> 4. Send OrchestratorInfo request to eligible Os
> 5. Filter out eligible Os from response
> 6. Use top-N eligible responses for O selection

This flow looks right to me.

> This would allow broadcasters to find a balance between optimal economic decisions and time to transcoding based upon their bandwidth capabilities. Although I do not see such a feature as an immediate necessity or priority.

@kyriediculous I've created #925 to track this. I think we can proceed with implementing this issue and address adjustable refresh intervals later on.

> I found out we're already importing server into discovery for access to server.getOrchestratorInfo and server.Broadcaster

Ah I missed this when I was skimming the file - good catch. If we're already importing `server` in the `discovery` package, I'm fine with leaving `BroadcastPrice` in the `server` package for now then.

**Comment by kyriediculous** [comment]
> Ah I missed this when I was skimming the file - good catch. If we're already importing server in the discovery package, I'm fine with leaving BroadcastPrice in the server package for now then.

While it still doesn't seem optimal to me to import the` server` package solely for an interface, variable and a single client-side method I think we can move on for now. But it might be worthwhile revisiting this structure in the future.
