### ISSUE TITLE
go-livepeer should use https rather than http for data sharing between nodes

### ISSUE THREAD

**Issue by mkrufky** [livepeer/go-livepeer#913]
as long as http is used to pass segments between nodes (rather than https), we risk that a bad transcoder actor may try to inject bad video data into the pipeline

***if https is served directly from the node, then the node *must* be built using latest stable golang.   If we wrap the endpoints in question with nginx+tls, this becomes a non-issue, but still, all services should communicate via https and not http

**Comment by darkdarkdragon** [comment]
https is being used to pass data between Livepeer nodes. Only broadcaster serves data using http.

**Comment by mkrufky** [comment]
nothing should use http or else we risk false data injection.   @angyangie is showing me here how the transcoder is pulling from the orchestrator via HTTP and not HTTPS.   Additionally, the output m3u8 is available over HTTP, not HTTPS, and so are the segments within

**Comment by darkdarkdragon** [comment]
> showing me here how the transcoder is pulling from the orchestrator via HTTP and not HTTPS.

Can you please show me too?  It can be configured to use http, but by default it is uses HTTPS.

> nothing should use http or else we risk false data injection.

It's really not Livepeer Broadcaster's job to properly serve HTTPS. It should be done by external tooling.
P.S. btw, even HTTPS is used to communicate between Livepeer nodes, it doesn't saves us from anything - we don't have (yet) proper checking of certificates in place.

**Comment by mkrufky** [comment]
....yondon just explained to me that the verifier is set as to InsecureSkipVerify .....

Clearly I need to grok thru this a bit more .....   If the reasoning behind this is to ease in testing, then it makes good sense, but it should be an option.  HTTPS should be required by default STRICTLY, and we should make the appropriate arrangements to disable this esily for testing's sake

**Comment by j0sh** [comment]
> we don't have (yet) proper checking of certificates in place

Yup, this is the reason we don't have HTTPS enabled on the broadcaster (which is what serves the m3u8 and segments for playback). There's some minor TODOs there related to passing in certs via CLI flags (easy to do but just something that needs to be done), but the real problem is the UX around tooling and testing. Generating and installing self-signed certs adds another step to what is already an involved set-up process.

Also, the certs we do generate on the node itself are basically ignored. For O certificates, it would also be nice to have some tie-in with the Ethereum address to ensure identity, eg perhaps via a cert attribute [1], but that need a lot more thought around revocation, etc. There's also some earlier (outdated?) discussion on the topic [2].

[1] https://github.com/ChristopherA/revocable-self-signed-tls-certificates-hack
[2] https://github.com/livepeer/go-livepeer/issues/437

**Comment by mkrufky** [comment]
There are better more idiomatic ways to achieve this now in golang.  I implemented it in my own pool stratums, but then disabled it when it failed due to the miner stratums not passing the hostname in the http request.  Now, instead, i do the certbot txt record registration "dance" , but that's for a much different use case.

For on-the-fly node-to-node https, we can use the method described here:
https://blog.kowalczyk.info/article/Jl3G/https-for-free-in-go-with-little-help-of-lets-encrypt.html

I admit, I havent read through the links you posted yet - I will read up on those and get back to you ... but, i do feel like tying in the ethereum address may be overkill.

Golang provides on-the-fly TLS, and we should take advantage of it and not reinvent the wheel.

I know i don't have the full story yet, so as I said, I'll come back with more comments after catching up on the resources you just linked.
