### ISSUE TITLE
B should be able to react to PriceInfo updates from O mid-stream and adjust according to its MaxBroadcastPrice

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#929]
**Is your feature request related to a problem? Please describe.**
#924 would allow an O to adjust the `PriceInfo` he sends along with `OrchestratorInfo` mid-stream through the CLI. A B would be notified of such an update when a transcoded segment is returned along with `OrchestratorInfo`

B should then be able to check that the updated `PriceInfo` from O, it is still below B's `MaxBroadcastPrice`. 

If the updated price from O exceeds B's preferrence, B should be able to fluently switch to a new O with a time to transcode for the next segment as little as possible. 

**Describe the solution you'd like**
Since `PriceInfo` is part of `OrchestratorInfo` which is sent along with `TranscodeResult` we can check for updated pricing upon receiving a transcoded segment.

If `OrchestratorInfo && Orchestrator.PriceInfo` is not `nil` we should update the `PriceInfo` for O in `func updateOrchestratorInfo(sess *BroadcastSession, oInfo *net.OrchestratorInfo)` (`segment_rpc.go`)

If the NEW price exceeds B's `MaxBroadcastPrice` a new O with acceptable pricing should be selected. 

Selection of a new O should be fluent to reduce latency. Therefore we could go through the previously selected O's for B in the `DBCache` rather than using `orchestratorPool.GetOrchestrators` to refresh `OrchestratorInfo` for the entire active transcoder pool as described by Josh's comment in #906. 

**Describe alternatives you've considered**
Refresh the entire orchestratorPool to get the absolute best price. 

**Additional context**
This issue depends on/is blocked by the completion of #906 and #924

**Comment by yondonfu** [comment]
> Selection of a new O should be fluent to reduce latency. Therefore we could go through the previously selected O's for B in the DBCache rather than using orchestratorPool.GetOrchestrators to refresh OrchestratorInfo for the entire active transcoder pool

Prior to selecting Os from its DB cache, B should iterate through its current in-memory O list (represented by a set of [broadcast sessions](https://github.com/livepeer/go-livepeer/blob/master/server/broadcast.go#L30) each with its own O. I believe the flow would look something like the following:

1. O sends an OrchestratorInfo update to B
2. B checks the price included in the OrchestratorInfo update and an error is returned because the price exceeds B's max broadcast price
3. B removes the broadcast session associated with O
4. B retries the current segment using the next broadcast session in its session list

B would only select Os from its DB cache when the size of its current in-memory session list falls below half of its desired # of Os ([relevant code](https://github.com/livepeer/go-livepeer/blob/master/server/broadcast.go#L46)).

**Comment by kyriediculous** [comment]
After the design discussion we have settled on following workflow:

1. Upon receiving updated pricing info we will store the new price info on the broadcast session, which is already being done by `updateOrchestratorInfo` in `server/segment_rpc.go` 

2. The next time `BroadcastSession.OrchestratorInfo.PriceInfo` is being used, when generating a payment in `genPayment`, we will check it against the `MaxBroadcastPrice` set by B which is contained in the `BroadcastCfg` variable in the same package. 

3. If the price is not acceptable we will return an error from `genPayment` which we'll then subsequently return immeadiatly from `submitSegment`

4. Receiving an error from `submitSegment` will cause the session for that O to be removed from the session list. B will retry the current segment using the next broadcast session in the list.
