### ISSUE TITLE
nodes should use an external queue to manage work

### ISSUE THREAD

**Issue by mk-livepeer** [livepeer/go-livepeer#941]
Broadcasters should make work available to orchestrators via an external queue, and orchestrators should make work available to transcoders via external queue.

An example of an external queue is [RabbitMQ](https://www.rabbitmq.com) or [SQS](https://aws.amazon.com/sqs/features/), although we may decide to use another solution.  SQS itself is available to run standalone without amazon, and is also included in the amazon elastic search docker container for testing.

Using an external queue allows for a semi-persistent idea of state to be shared between the nodes, and exists outside of each process in case the nodes themselves should crash.

The queue will manage the order of work to be processed in a first in first out basis.  If we use SQS, it will allow us to tag each queue item by the stream it belongs to.  RabbiqMQ allows creating and destroying queues on-the-fly if need be.

These queues provide throttling options if we should choose to use them.  For instance, we might decide to only allow X streams to run through an orchestrator at a given moment.   Within those X streams, we may decide to allow Y simultaneous transcoding jobs to run on each stream (each working on different chunks, perhaps some working on redundant chunks if we should so choose)

This will help to improve reliability of the current pipeline, but also paves the way to the idea of redundancy further down the line.

**Comment by j0sh** [comment]
We should make a distinction between queues for broadcasters, and queues for orchestrators. They have very different implications, so should be looked at separately in order to keep the discussion focused.

But some general notes along the idea of using an external queue rather than the notion of queuing itself:

> Using an external queue allows for a semi-persistent idea of state to be shared between the nodes

Curious, which nodes are these? Specifically, what's the topology you have in mind? There's a few possibilities in my mind, each with different implications:
* A queue shared among several orchestrators (under the same Eth address)
* A queue shared among one orchestrator and several transcoders
* A queue shared among several broadcasters (under the same Eth address)
* A queue shared among one broadcaster and several orchestrators

> and exists outside of each process in case the nodes themselves should crash

In our live streaming context, if a broadcaster crashes, then the RTMP stream goes down too. Otherwise, the broadcaster and already has mechanisms to retry for orchestrators that go down mid-stream. The same is true for orchestrators + transcoders. Segments will be retried as long as there is capacity somewhere to absorb the work.

Fully recovering from a broadcaster crash would involve a lot of other considerations right now, and the role of a persistent transcode queue in that scheme is unclear. Not to say we shouldn't discuss broadcaster crash recovery, but it's a larger topic than the queue itself.

Since we currently drop segments if there's no capacity to absorb the work, we could talk about queuing until there's more capacity online. But that doesn't seem to require an external queue; a simple internal one should do given the behaviors described above. There's a lot more to unpack here for B and O respectively, so we should probably discuss those separately and not overwhelm a single thread.

> first in first out basis

I would actually suggest LIFO for any queues we do. Two reasons: more recent segments are more "important" in a live streaming context (especially as the queue grows), and apparently LIFO also really shortens the median wait time [1].

[1] https://news.ycombinator.com/item?id=20291942

> These queues provide throttling options if we should choose to use them

This is nice because we don't have to re-invent those knobs. As we explore this approach, let's keep in mind:

* More infrastructure to run, more knobs to manage, and more things to go wrong. Basically, it doubles the operational surface area for a node operator. This feels like a pretty big obligation for our downstream users, and I'm concerned the additional complexity will hurt adoption.
* Another hop in the time-sensitive live transcoding workflow.
* How much control can we maintain over work allocation? Eg, routing work via some combination of latency / price / features / errors and dynamically responding to changes in those parameters?
* There are certain things where it's helpful for B to know in advance which O is being used, such as uploading segments to an O-supplied object store, or signing PM tickets for the protocol. I'm still unclear on the topology here, but it seems like delegating the work allocation to a queue would require close integration.

> paves the way to the idea of redundancy further down the line.

FWIW, the goclient's plumbing is ready for per-segment redundancy ever since @angyangie added support for multiple orchestrators per stream. The actual redundancy just has to be implemented  - select several O, send work to them asynchronously, use the first successful result. I'm just not sure how much it'd help right now. At the very least, we should improve O utilization first (otherwise we'll probably have worse issues with over-provisioning).

**Comment by angyangie** [comment]
> allows creating and destroying queues on-the-fly if need be

What would we use that for @mk-livepeer? When stream starts/end?

**Comment by angyangie** [comment]
Great discussion and thought exercise! I have some questions:

> allows creating and destroying queues on-the-fly if need be

Would that only be useful when stream starts/end @mk-livepeer?

> At the very least, we should improve O utilization first

By that, do you mean, making sure we fully utilize O capacity as measured by single O testing @j0sh?

**Comment by j0sh** [comment]
> By that, do you mean, making sure we fully utilize O capacity as measured by single O testing @j0sh?

That is one aspect; another is in being a little more [intelligent](https://github.com/livepeer/go-livepeer/issues/938) about B's selection of O in order to shift traffic to under-utilized Os. At this point, introducing redundancy is just going to mean provisioning even more nodes. 3x redundancy == 3x the cost, etc. Without doing so, we'd likely see network throughput get *worse* with redundancy, because 3x redundancy means we're pushing 3x more work through the network without a corresponding increase in the capacity to absorb that work. (Although whether we should actually implement redundancy is another discussion, because I think the we can still gain most of its perceived benefits without the corresponding increase in costs.)
