### ISSUE TITLE
Implement HTTP POST/PUT ingest of video segments

### ISSUE THREAD

**Issue by iameli** [livepeer/go-livepeer#953]
This is designed to be a simple API for backing external API services such as the Wowza plugin.

### Request: `POST /:streamKey/:segment.ts`
Required Headers: 
* `Content-Type: video/MP2T`
* `Accept: multipart/form-data`

Example: `POST /stream/eli/1.ts`

This posts in an MPEG-TS video segment to a go-livepeer broadcaster. The URL structure uses the same patterns we use for RTMP URLs — the "stream key" would be the same and the webhook can be triggered in the same way to access the bitrate ladder and whatnot.

Behind the scenes, go-livepeer should begin its main transcoding loop. It should send the segment off to an orchestrator and be ready to await new sequential video requests following the same URL pattern.

### Response:

Server sends a `200 OK` response with a multipart/form-data blob containing all of the transcoded outputs.

**Comment by mkrufky** [comment]
I was under an impression that the `m3u8` playlist (or a url pointing to one) is what we'd POST to the endpoint.  This would be enough info for the process to pull down segments on its own.

Is POST'ing segments directly to the endpoint a requirement?  If so, can you explain why?  Might it make sense to support both playlist POST and ts direct POST?

**Comment by iameli** [comment]
Interesting — that could certainly work also, direct POST isn't a requirement. I might upload the segments to GCP buckets or something to allow us to handle the case where the Wowza server isn't on the public internet but that's workable. I suppose I'd POST the manifest every time a new segment is available? The only downside off the top of my head would be that in a failover/deployment case we'd do a bit of unnecessary transcoding:

Wowza:
```
POST /stream/eli.m3u8

https://example.com/1.ts
https://example.com/2.ts
https://example.com/3.ts
```

Livepeer Broadcaster A: Okay, I'll transcode 1.ts, 2.ts, and 3.ts

Wowza:
```
POST /stream/eli.m3u8

https://example.com/1.ts
https://example.com/2.ts
https://example.com/3.ts
https://example.com/4.ts
```

Livepeer Broadcaster A: Cool, already did most of those, but I'll transcode 4.ts.

Livepeer Broadcaster A: Oh no, I'm dead! 💀

Livepeer Broadcaster B: I'll take over.

Wowza:
```
POST /stream/eli.m3u8

https://example.com/2.ts
https://example.com/3.ts
https://example.com/4.ts
https://example.com/5.ts
```

Livepeer Broadcaster B: Okay, I'll transcode 2.ts, 3.ts, 4.ts, and 5.ts.

Not a huge deal, just the only downside that comes to mind.

**Comment by j0sh** [comment]
Still need to review the proposal more closely, but just wanted to respond about POSTing manifests rather than segments. There's a few reasons segments would be preferable:

* Regardless of whether B pulls or W pushes manifests, it's an additional step in the workflow. This increases latency.
* B needs to be more stateful: after parsing the manifest, needs to check which segments it has processed, and only fetch ones that are new on the list
* The transcoding becomes asynchronous. This means tracking even more state on Wowza itself to pull down segments that have completed.
* "Pulling down segments that have completed" implies we fetch the HLS playlist (or some other "completed list") for each rendition on B. Which is yet another step in the workflow.
* Error propagation and handling becomes harder because of the asynchronicity, especially if B is pulling manifests from W. How can W be notified or respond to issues? (If the answer is, "it doesn't" then this implies we need *some other system* for handling problems that come up, which is yet another moving-part in the mix; I'll elaborate below.)
* We cannot put manifests for live streams into object storage (OS) such as S3 or Google due to read-after-write consistency. Whether manifests are communicated via push or pull, it needs to be done directly between W and B. (Segments are fine for OS, although OS writes aren't really that fast nor do they typically represent the shortest path between W/B.)

With that, POSTing manifests doesn't seem to bring any great advantages, but am curious if there is anything I'm overlooking.

On the other hand, pushing segments directly offers some nice benefits:

* The workflow is strictly request-reply. Request a segment be transcoded, receive the results (or an error).
* Error handling becomes immediate, localized to Wowza and a lot easier to respond to. If a push fails, try another B. This is really easy to implement and very robust. Not dependent on external services to monitor for errors and handle the error for us (and who monitors the monitor...?)

Some further notes from the above that I think were implicit in the write-up, but I'll make explicit. We should be directing traffic from Wowza directly to B. We need some sort of discovery service to return a B for each job, or a list of candidate Bs.  The discovery service can go down between requests without affecting running streams, which gives us a nice way to handle transient issues and things like upgrades / restarts.

If a single B goes down mid-stream, then Wowza has others to work with. This is the same basic principle we use for B/O and O/T reliability: maintain a local pool of available workers, and retry on failures.

Without a discovery service, I think we would have to proxy traffic through a separate service that fronts the Bs, and that becomes a SPOF, which also brings up a ton of annoying issues (compounded on top of the drawbacks of using manifests). Just to highlight @iameli example where broadcaster A dies, and broadcaster B takes over:

* Broadcaster A needs to be closely monitored by some external service. Usually it's not going to say "I'm dead!" [1]
* The state of broadcaster A needs to be maintained somewhere for fail over purposes. Mostly segments in-flight, but this also includes completed segments if we're using manifests as Eli mentioned.
* There needs to be glue between the monitoring, the state storage and the notification/failover. There needs to be a transition to allow the new B needs to take over the work and the segments need to flow back from new B to Wowza (whether via API node proxy, or notifying Wowza who's currently responsible for the work).

Using a discovery service and doing the transcode via direct request-reply posting of segments mitigates all of these issues.

[1] We should certainly still monitor service status, but it's better if our failover strategy isn't intrinsically dependent on that monitoring.

**Comment by iameli** [comment]
Thanks for the thorough write-up! Almost all of this mirrors my thinking so far, let me go into some more detail on what I'm envisioning for a few points:

> Segments > Manifests

Agreed with all of this.

> The workflow is strictly request-reply. Request a segment be transcoded, receive the results (or an error).

So this would put you in favor of option #2 above? My biggest ambivalence is that I wish we could interleave the output somehow for latency-reduction reasons — receive each transcoded stream in parallel rather than one `multipart/form-data` blob in series. This is compounded by the fact an external service is handling segmentation, so these might be 30 second segments. HTTP/2 Push seems like a great candidate but I'm also not terribly excited about implementing that in Wowza, which appears to be locked to Java 8.

> We should be directing traffic from Wowza directly to B.

Sure. "Directly" in this case may involve a Google load balancer doing SSL termination and a bit of intra-cluster routing, but I take your point that we shouldn't try and maintain a stateful connection between the W and the B. It'll be a connection to something like `https://broadcaster-8291.livepeer.org` that routes directly to a go-livepeer instance rather than `https://api.livepeer.org/stream/asdf` that we try and route with a reverse proxy. The only thing in the middle will be some Google infrastructure.

> We need some sort of discovery service to return a B for each job, or a list of candidate Bs. The discovery service can go down between requests without affecting running streams, which gives us a nice way to handle transient issues and things like upgrades / restarts.

Yep, I'm envisioning that this will be one role of the API node's "Broadcaster" object. `GET https://api.livepeer.org/broadcasters/available`, perhaps, will give you a JSON response with the necessary endpoints. As we get more sophisticated we can keep track of which broadcasters are handling the most traffic and return a filtered list accordingly. Additionally, this endpoint can be statically cached by something in front of the API node.

> Without a discovery service, I think we would have to proxy traffic through a separate service that fronts the Bs, and that becomes a SPOF, which also brings up a ton of annoying issues (compounded on top of the drawbacks of using manifests).

To be clear, I think I may still do this — it'll be nice to be able to look at one URL for the HLS output for demonstration purposes and such. It's easy to implement given that the API is keeping track of all broadcasters and broadcasts already. But it won't be part of the critical transcoding paths.

**Comment by j0sh** [comment]
> My biggest ambivalence is that I wish we could interleave the output somehow for latency-reduction reasons

We currently process renditions all-at-once then return them all-at-once. We could improve this someday, but I wouldn't base the design around that possibility right now. I'm in favor of the simplest approach that we know will work. That also makes it more friendly to tools such as curl and wget (if that is a goal at all, which seems like a nice bonus but also something we should be prepared to drop if necessary since this is ultimately a machine-to-machine API).

That being said, I see a few possible approaches for supporting this type of streaming response. "Chunked multipart" seems to actually be a thing. The output also doesn't strictly need to be interleaved, but we can build the client to support that if needed (if it isn't already the default). Or we can have a custom Content-Type using chunked encoding - the `Accept` header gives us some semblance of upgradeability/versioning there. Or we could just have a new API for streaming responses when we're ready.

> it'll be nice to be able to look at one URL for the HLS output for demonstration purposes and such

Can you elaborate on this?

**Comment by iameli** [comment]
> "Chunked multipart" seems to actually be a thing.

Oh, nice! Cool, I'm totally in favor then.

> Can you elaborate on this?

Full workflow looks something like this:

1. Wowza plugin (or whoever) requests a list of broadcasters from `api.livepeer.org`.
2. Wowza plugin selects `broadcaster-5181.livepeer.org` from that list.
3. Wowza uploads segments to `https://broadcaster-5181.livepeer.org/streamKey/1.ts` and so forth.
4. broadcaster-5181 fires off a `POST https://api.livepeer.org/stream/hook` to authenticate the upload. Receives back the bitrate ladder and streamName/manifestID.
5. broadcaster-5181 gets the segments transcoded and passes them back to Wowza.

Presumably, in addition to this workflow, there's now an HLS stream available at `https://broadcaster-5181.livepeer.org/manifestId.m3u8`? It seems like that'd happen by default, given that's the current behavior?

Assuming I'm correct in that, all I meant was that I may have the API act as a proxy for that stream, such that it can be viewed at `https://api.livepeer.org/manifestId.m3u8`. The API already has all the information it needs to make that connection, and I think it'd be useful for debugging and demonstration purposes.

EDIT: But if it's extra work to implement then NBD, not essential for this feature.

**Comment by iameli** [comment]
Updated the original post to specify that we're going with the `multipart/form-data` response and clarify a few things.

**Comment by iameli** [comment]
Cross-referencing: the aforementioned service discovery interface will be an enumeration of Broadcaster objects as discussed in livepeer/livepeerjs#385

Request:
```
GET /broadcaster
```

Response:
```
[ ... {"address":"https://broadcaster-17863.livepeer.live"} ... ]
```
