### ISSUE TITLE
all tests must pass (`go test ./...`)

### ISSUE THREAD

**Issue by mk-livepeer** [livepeer/go-livepeer#973]
In an effort to move towards portability and continuous integration, we must make sure that all tests pass.

Developers should run:
```
go test ./...
```
before every check-in to ensure that all existing tests pass before proposing any pull requests.  Developers are encouraged to include tests to cover every testable change made to the repository.

For now, let's just make sure that the existing tests all pass.

Once this is done, we should add `go test ./...` to CI.

**Comment by kyriediculous** [comment]
We already run a batch script in CircleCI `./test.sh` though which runs both go tests as well as flag tests in `./test_args.sh`

"./test.sh passes" is also listed as a checkbox  when submitting a PR. 

I'm not sure if the extra redundancy is necessary as long as `./test.sh` is adjusted when new packages are introduced? This can of course be forgotten due to human error.

**Comment by mkrufky** [comment]
As I explained in the OP, any tests present should be fixed.  If they can't be fixed, they should be removed.

I have seen the test scripts and they are great, but we shouldn't allow the standard `go test ./...` command to break - this is what is used by most golang developers, and is extremely useful in build sanity tests for cross-platform portability testing.
