### ISSUE TITLE
Wowza Plugin V1 Features

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#990]
As we discussed, here are a list of things we would like to accomplish before saying the plugin is "good enough".
- [x] Transcoding result consumption in Wowza plugin
- [ ] Understand whether some kind of error status is possible, so the user can tell when transcoding is not happening
- [ ] On / off switch for the plugin
- [ ] Fallback solution for the user if Livepeer goes down completely
- [ ] Consider when transcoding result comes back very slowly
- [x] Versioning of Livepeer plugin

**Comment by dob** [comment]
How are you thinking about "fallback solution for the user if Livepeer goes down completely"? One option would be that the Wowza engine does the transcoding, except it seems a little bit like a non-starter since the purpose of the plugin is that you can ingest many streams on the single engine instance (more than could be transcoded).

I have an initial reaction that this particular feature may require a lot of work to actually be done right, and may not be a blocker for "good enough". But perhaps you have a good idea that would suffice here.

**Comment by j0sh** [comment]
> "fallback solution for the user if Livepeer goes down completely"? One option would be that the Wowza engine does the transcoding

To the extent that we spend time on this issue to make it "good enough", my feeling is that our effort should be going towards making the Livepeer service itself as resilient as possible.

Given the broad outlines of our current design (as I understand it), this seems achievable by ensuring we don't build any single-points-of-failure into the Livepeer portion of the system, and operational planning to mitigate risks around availability. We may still go down sometimes, especially at the beginning. But that's a golden opportunity to further improve our processes and resiliency.

Happy to elaborate on the technical aspects further; I think we have a pretty good chance delivering a highly available system to our users.

**Comment by ericxtang** [comment]
> How are you thinking about "fallback solution for the user if Livepeer goes down completely"? One option would be that the Wowza engine does the transcoding, except it seems a little bit like a non-starter since the purpose of the plugin is that you can ingest many streams on the single engine instance (more than could be transcoded).
> 
> I have an initial reaction that this particular feature may require a lot of work to actually be done right, and may not be a blocker for "good enough". But perhaps you have a good idea that would suffice here.

I agree with you and @j0sh here.  The "good enough" solution here might be just to "turn off transcoding" when Livepeer is down.

**Comment by iameli** [comment]
Going through the remaining points on this list, incorporating our learnings in the last few weeks:

> Understand whether some kind of error status is possible, so the user can tell when transcoding is not happening
This is a good idea but it should/needs to be an external client that connects to the API server and the video stream. We don't have the ability to customize the Wowza management interface, so that's kinda all there is.

This can grow out of the existing "demo experience" feature in @livepeer/player but it's a totally separate application that doesn't exist yet, so we're a little ways out. For now we can accomplish a basic version of this by pointing the Livepeer player at the video stream and seeing if things are working.

In the meantime, we can 

> On / off switch for the plugin
> Fallback solution for the user if Livepeer goes down completely

These two are both accomplished by https://github.com/livepeer/livepeer-wowza/issues/12.

> Consider when transcoding result comes back very slowly

I will consider it by testing it, but I think the default behavior will be reasonable.
